### ISSUE TITLE
Can't run f.inputWrangling()

### ISSUE THREAD

**Issue by jorjon88** [facebookexperimental/Robyn#10]
# Issue
Im trying to Run fb_nextgen_mmm_v20.0.exec.R and get this error Message: 

Error in value[[3L]](cond) : unused argument (cond) 

When showing the  Traceback I get:

4. tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
3. tryCatchList(expr, classes, parentenv, handlers) 
2. tryCatch({
    dateCheck <- as.matrix(dt_transform[, set_dateVarName, with = F])
    dateCheck <- as.Date(dateCheck)
}, error = function() { ... 
1. f.inputWrangling() 

# Environment
R version (R --version)

**Comment by jorjon88** [comment]
Im using Rstudio for MAC

**Comment by Leonelsentana** [comment]
Hola @jorjon88! Thanks for using our code :) could you try to retain the call-stack from the original error but have a more informative error message? just edit the error and re-raise it?

  tryCatch({
    # some other code
  }, warning = function(war){
    logwarn(war, logger = "MyLogger")
  }, error = function(err){
    # edit the error message
    err$message <- paste("While training model", err, sep = " ")
    # and re-raise
    stop(err)
  })

Can you let us know what the error says? Thanks a ton
