### ISSUE TITLE
dt_mod <- f.inputWrangling() in fb_robyn.exec.R not working

### ISSUE THREAD

**Issue by rsoranzo** [facebookexperimental/Robyn#100]
# Contributing to FB NextGen MMM R script

dt_mod <- f.inputWrangling()   in fb_robyn.exec.R 

Error message and block of the execution of the following codes.

# Steps to Reproduce

Proceeding step by step in the execution of the R code of fb_robyn.exec.R on RStudio - without modifying the original code e database de_simulated_datacsv and keeping open the other two files b_robyn.func.R and b_robyn.optm.R - I arrived at line 170  dt_mod <- f.inputWrangling() 

# Expected Behavior

dt_mod <- f.inputWrangling() should recognize the date from dt_input as Monday and proceed without error.

# Actual Results

"Error during wrapup: week start has to be Monday or Sunday".

# Environment

R version 4.0.4 (2021-02-15)
R Studio Version 1.4.1717

**Comment by gufengzhou** [comment]
hello, can you share the first couple of values of your date variable with me?

**Comment by rsoranzo** [comment]
Hi
I used the attached file.
SO the first two value of date variable are

2015-11-23
2015-11-30

Both are Monday
Hope you can solve my problem.

Thank you!
Best regards
Ramon

Da: gufengzhou ***@***.***>
Inviato: giovedì 1 luglio 2021 19:15
A: facebookexperimental/Robyn ***@***.***>
Cc: Ramon Soranzo ***@***.***>; Author ***@***.***>
Oggetto: Re: [facebookexperimental/Robyn] dt_mod <- f.inputWrangling() in fb_robyn.exec.R not working (#100)


hello, can you share the first couple of values of your date variable with me?

**Comment by rsoranzo** [comment]
[de_simulated_data.zip](https://github.com/facebookexperimental/Robyn/files/6749859/de_simulated_data.zip)

Here the file I used. Best regards

**Comment by gufengzhou** [comment]
oh you're using our simulated data? this is strange. can I ask where you're from? Or to be precise, what is your output of Sys.getlocale()? I got a feeling that it's because of your locale setting. Maybe try do this? Sys.setlocale("LC_ALL", Sys.getenv("LANG"))

**Comment by rsoranzo** [comment]
I am working from Italy and this is the output from Sys.setlocale("LC_ALL", Sys.getenv("LANG"))

"LC_COLLATE=Italian_Italy.1252;LC_CTYPE=Italian_Italy.1252;LC_MONETARY=Italian_Italy.1252;LC_NUMERIC=C;LC_TIME=Italian_Italy.1252"

**Comment by gufengzhou** [comment]
after the above it still doesnt work? if no, can you try setting locale to english Sys.setlocale("LC_ALL", 'en_US.UTF-8') and retry?

**Comment by rsoranzo** [comment]
Hi I'm not very expert in informatics.
This is the message I get after Sys.setlocale("LC_ALL", 'en_US.UTF-8')
[1] ""
Warning message:
In Sys.setlocale("LC_ALL", "en_US.UTF-8") :
  OS reports request to set locale to "en_US.UTF-8" cannot be honore

Let me know, how to overcome this problem. Thank you!

**Comment by gufengzhou** [comment]
hm ok. if you go to .func script line 463, you will see how this warning is created:
weekStartInput <- weekdays(dt_transform[1, ds])
weekStartMonday <- if(weekStartInput=="Monday") {TRUE} else if (weekStartInput=="Sunday") {FALSE} else {stop("week start has to be Monday or Sunday")}
I recommend you to manually debug the f.inputWrangling function by going line by line from 236 to 463 and see why this is happening. Let me know what you got

**Comment by rsoranzo** [comment]
Dear gufengzhou actually I manually debug the f.inputWrangling function - No problem . All codes from 236 to 463  are correctly executed.

Then I run 
dt_mod <- f.inputWrangling()   

Then run 
model_output_collect <- f.robyn(set_hyperBoundLocal
                                ,optimizer_name = set_hyperOptimAlgo
                                ,set_trial = set_trial
                                ,set_cores = set_cores
                                ,plot_folder = "S:/3. Tools/0 Formazione R - Tibco/1. RStudio/6. FB Robyn") # please set your folder path to save plots. It ends without "/".

where  S:/3. Tools/0 Formazione R - Tibco/1. RStudio/6. FB Robyn   is my working directory.
And finally model_output_collect$allSolutions

But nothing. It doesn't appear the output. 

Actually I feel lost...

**Comment by gufengzhou** [comment]
so the monday/sunday error is gone now? this is strange. what do you mean by nothing? do you get some printed outputs like this when running f.robyn? if not, what error/warning do you get? I need bit more info to debug
![image](https://user-images.githubusercontent.com/14415136/124183543-aad73400-dab8-11eb-8d33-ca93b0eb7cdf.png)

**Comment by rsoranzo** [comment]
Hi I solved the problem thank a collegue of mine that analyzed the code.
At line 462 and 463 you must replace Monday with "lunedì" (which is the italian name of monday) and same for Sunday with "domenica". This is for Windows, don't know if this is necessary also for Mac.

weekStartInput <- weekdays(dt_transform[1, ds])
       weekStartMonday <- if(weekStartInput=="lunedì") {TRUE} else if (weekStartInput=="domenica") {FALSE} else {stop("week start has to be Monday or Sunday")}

**Comment by gufengzhou** [comment]
Thank you very much for this input! It used to work by just setting the system locale to english, but not anymore apparently. I'll adapt the code to be insensitive to language.
