### ISSUE TITLE
Nevergrad error in robyn_run()

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#1004]
## Describe issue
Robyn tells me Nevergrad is not installed, even though it should be as I've run the code before without issues (see screenshot).
![image](https://github.com/facebookexperimental/Robyn/assets/118725564/52896723-9436-4be1-99d3-7d2e199535eb)

I see that Robyn runs reticulate's py_module_available() under the hood to produce this error, which is basically reticulate's import() function with an error handler, so I ran this code manually which produced the following error:
![image](https://github.com/facebookexperimental/Robyn/assets/118725564/576cf122-cabb-4595-96ed-6c4e76eabda8)
Is it possible that this error is then caused by the use of a deprecated NumPy feature?

## Environment & Robyn version
Robyn version: 3.11.0
R version: 4.4.0

**Comment by TJh0110** [comment]
I got the same issue as well, but 2 weeks back it was working fine for me as well. Any luck solving it ?

**Comment by gufengzhou** [comment]
This error needs an update from the Nevergrad's side. I'll ping them and keep you updated. 

cc @igorskokan

**Comment by NataliaVConnolly** [comment]
Seeing the same error.  Tried to install an older version of nevergrad, still no luck.

**Comment by gufengzhou** [comment]
Until the Nevergrad fix, see a workaround here

https://github.com/facebookexperimental/Robyn/issues/998

**Comment by igorskokan** [comment]
Nevergrad landed the fix yesterday

The Nevergrad code should work with both numpy1 (at least reasonably
recent) and numpy2.0.

Check it out and let us know.

**Comment by bart-vanvlerken** [comment]
@gufengzhou I'm no longer getting the same error, but a new one:
![image](https://github.com/facebookexperimental/Robyn/assets/118725564/cbe0ef41-4b44-4bc4-8a0a-b418b3fd92ef)

Will this require an update on Robyn's end?

**Comment by gufengzhou** [comment]
Have you updated /reinstalled nevergrad? If yes please also restart R and try. 

After the above, If this still occurs, an user here has solved it by updating the R version. See https://github.com/facebookexperimental/Robyn/issues/1006

**Comment by bart-vanvlerken** [comment]
Thanks Gufeng, that worked!

**Comment by gufengzhou** [comment]
Would you please let me know if you needed to update R or not?
If yes, which R versions did you have before/after?

**Comment by bart-vanvlerken** [comment]
I did need to update, yes. I updated from 4.4.0 to 4.4.1
