### ISSUE TITLE
Error in signif(nevergrad_hp_val[[co]][index], 10) :    non-numeric argument to mathematical function

### ISSUE THREAD

**Issue by TJh0110** [facebookexperimental/Robyn#1006]
## Describe issue
after the nevergrad compatibility issue, I am getting this error while trying to run robynoutput function
{
Error in signif(nevergrad_hp_val[[co]][index], 10) : 
  non-numeric argument to mathematical function
}
## Environment & Robyn version

Make sure you're using the latest Robyn version before you post an issue.

> packageVersion("Robyn")
[1] ‘3.11.0’

Input data has 208 weeks in total: 2015-11-23 to 2019-11-11
Initial model is built on rolling window of 157 week: 2016-01-04 to 2018-12-31
Time-series validation with train_size range of 50%-80% of the data...
Using geometric adstocking with 20 hyperparameters (20 to iterate + 0 fixed) on 11 cores
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
  |                                                                                                                      |   0%Timing stopped at: 0 0 0
Error in signif(nevergrad_hp_val[[co]][index], 10) : 
  non-numeric argument to mathematical function

**Comment by JayLiangMKT** [comment]
same issue when checking the py_config()

> python:         /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate/bin/python
> libpython:      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin/libpython3.10.dylib
> pythonhome:     /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate:/Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate
> version:        3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
> numpy:          /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate/lib/python3.10/site-packages/numpy
> numpy_version:  2.0.0
> nevergrad:      /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate/lib/python3.10/site-packages/nevergrad

**Comment by JayLiangMKT** [comment]
> same issue when checking the py_config()
> 
> > python:         /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate/bin/python
> > libpython:      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin/libpython3.10.dylib
> > pythonhome:     /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate:/Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate
> > version:        3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
> > numpy:          /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate/lib/python3.10/site-packages/numpy
> > numpy_version:  2.0.0
> > nevergrad:      /Users/jian_liang/Desktop/mamon_projects/local_dev/r-reticulate/lib/python3.10/site-packages/nevergrad

After taking "update.packages(checkBuilt=TRUE, ask=FALSE)" from [the ](https://github.com/facebookexperimental/Robyn/issues/750)

**Comment by gufengzhou** [comment]
The Nevergrad numpy2 update is shipped. Have you guys re-installed the package and restarted R? This error usually occurs when the R session is not restarted.

**Comment by JayLiangMKT** [comment]
> The Nevergrad numpy2 update is shipped. Have you guys re-installed the package and restarted R? This error usually occurs when the R session is not restarted.

I fixed my issues by reinstalled latest R when I detected that the "reticulate" package was built on a later R version. Works for me. Thank you!
