### ISSUE TITLE
Waterfall chart without labels after upgrading to v3.11

### ISSUE THREAD

**Issue by leokm-cw** [facebookexperimental/Robyn#1008]
Hello! 
I'm facing some issues with the onepagers after I upgraded my Robyn to v3.11.

I'm using exactly the same plot commands as before (pretty much like the default from demo), but now my waterfall plot is returning empty labels, as the pic below.

![image](https://github.com/facebookexperimental/Robyn/assets/170359883/550581df-43dc-44ab-a67c-17a4ca2b9b56)

I already had some warnings during the plots before the update, such as the one below, so I believe it's not the cause for it.

![image](https://github.com/facebookexperimental/Robyn/assets/170359883/a9ff6f43-fd41-4445-84cf-c778a5a38f00)

The only new error is this one:

![image](https://github.com/facebookexperimental/Robyn/assets/170359883/5591ca5c-3742-4c02-a7c5-2c0a3b7e5bd4)

Any ideas on what could be causing this error? Thanks in advance.

**Comment by laresbernardo** [comment]
Hi @leokm-cw Expect a fix later today in v3.11.1. Ref: #1011

**Comment by laresbernardo** [comment]
Fixed in CRAN and Github. Closing this thread.

**Comment by vlulla** [comment]
When is the CRAN version for macos (arm64) expected to be updated to this latest version (3.11.1)?

**Comment by laresbernardo** [comment]
> When is the CRAN version for macos (arm64) expected to be updated to this latest version (3.11.1)?

May take a day or two tops, but the update has already landed in CRAN.

**Comment by vlulla** [comment]
It's up there now, thank you!
