### ISSUE TITLE
Michaelis-Menten model in Robyn func code：Vmax * spend/(Km + spend)

### ISSUE THREAD

**Issue by wenyanyy** [facebookexperimental/Robyn#102]
# Michaelis-Menten model in Robyn func code：Vmax * spend/(Km + spend)
# Issue
Question about define Vmax and Km

# Steps to Reproduce
<img width="385" alt="捕获" src="https://user-images.githubusercontent.com/82489568/124211717-2e783b80-db20-11eb-86fc-4f61307940c5.PNG">

I searched Michaelis-Menten model in Google, Vmax **represents the maximum rate(Impression)** achieved by the media channel, happening at saturating spending. Km is numerically equal to the **spending** at which the impression reaction rate is 1/2 of Vmax.
Please see the attached picture.  However, In the Robyn function code. 

**“nlsStartVal <- list(Vmax = dt_spendModInput[, max(exposure)/2], Km = dt_spendModInput[, max(exposure)])”**

In the code ,Vmax is numerically equal to the impression at which the 1/2 of max impression(Vmax) instead of the Max impression . 
Km also  is numerically equal to the Max impression(Vmax) rather than spending at which the 1/2 of max impression(Vmax) . 

So i'm a little bit confusing how to define Vmax and Km.

Please let me know if I misunderstand. 

Thanks 

# Expected Behavior

Vmax = Max exposure
Km= spending at 1/2 max exposure

# Actual Results

Code in Robyn 
**“nlsStartVal <- list(Vmax = dt_spendModInput[, max(exposure)/2], Km = dt_spendModInput[, max(exposure)])”**

# Environment

R version (R --version)

**Comment by gufengzhou** [comment]
Hey, you're right about this :) Another user has noticed it as well and raised [the issue here](https://github.com/facebookexperimental/Robyn/issues/77), which I've answered thoroughly. Let me know if you have more questions.

**Comment by gufengzhou** [comment]
let me know if you have more issues
