### ISSUE TITLE
Error in model_output_collect

### ISSUE THREAD

**Issue by amirjz** [facebookexperimental/Robyn#103]
# Contributing to FB NextGen MMM R script

# Issue

Hi there,

Running the below part of the code in fb_robyn.exec.R threw an error.

model_output_collect <- f.robyn(set_hyperBoundLocal
                                ,optimizer_name = set_hyperOptimAlgo
                                ,set_trial = set_trial
                                ,set_cores = set_cores
                                ,plot_folder = "~/Documents/GitHub/plots") # please set your folder path to save plots. It ends without "/".

# Steps to Reproduce
I am not using my own data. I was just curious to see how it performs on the sample data that has been provided. I tried to run it without changing anything in the code and data.

# Expected Behavior

Expected to see the model is run successfully.

# Actual Results

In fb_robyn.exec.R resulted in the below error:

Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'nevergrad.parametrization.parameter' has no attribute 'MultiobjectiveReference' 

**Traceback:**
11.
stop(structure(list(message = "AttributeError: module 'nevergrad.parametrization.parameter' has no attribute 'MultiobjectiveReference'", 
    call = py_get_attr_impl(x, name, silent), cppstack = NULL), class = c("Rcpp::exception", 
"C++Error", "error", "condition"))) 
10.
py_get_attr_impl(x, name, silent) 
9.
py_get_attr(x, name) 
8.
py_get_attr_or_item(x, name, TRUE) 
7.
`$.python.builtin.object`(x, name) 
6.
`$.python.builtin.module`(ng$p, "MultiobjectiveReference") at fb_robyn.func.R#962
5.
ng$p$MultiobjectiveReference at fb_robyn.func.R#962
4.
py_resolve_dots(list(...)) 
3.
optimizer$tell(ng$p$MultiobjectiveReference(), tuple(1, 1)) at fb_robyn.func.R#962
2.
f.mmm(set_hyperBoundLocal, set_iter = set_iter, set_cores = set_cores, 
    optimizer_name = optmz) at fb_robyn.func.R#1433
1.
f.robyn(set_hyperBoundLocal, optimizer_name = set_hyperOptimAlgo, 
    set_trial = set_trial, set_cores = set_cores, plot_folder = "~/Documents/GitHub/plots") 

# Environment

R x64 4.1.0
RStudio 1.4.1717
<img width="725" alt="Robyn" src="https://user-images.githubusercontent.com/11503208/124228054-f5a38b00-db4e-11eb-830b-90249c081bcf.PNG">

**Comment by gufengzhou** [comment]
In your screenshot I am seeing the yellow warning bar above that you haven't installed all libraries yet. Please do so, restart RStudio and try again

**Comment by Leonelsentana** [comment]
Please also check you run this once after installing all libraries:
conda_create("r-reticulate") # must run this line once
conda_install("r-reticulate", "nevergrad", pip=TRUE)  #  must install nevergrad in conda before running Robyn
use_condaenv("r-reticulate")

**Comment by gufengzhou** [comment]
let me know if you have more issues
