### ISSUE TITLE
Plotting response curves for the allocation period

### ISSUE THREAD

**Issue by apoorvabc** [facebookexperimental/Robyn#1042]
I need help in Plotting the simulated response curve for the entire budget allocation period

I managed to extract the values and plot the response curves and mean spend per channel by fetching the adstocked_media and decomp_media from the pareto_media_transform_matrix.csv.

However, I would like to plot the **simulated response curve** for the **entire budget allocation** period. Can you please point me towards how this can be achieved.

**Comment by AdimDrewnik** [comment]
I have spent few weeks researching this topic and searching for help with zero results. From what I understand it is unclear how Robyn accounts for delayed and adstock effect when using longer time periods for simulation.

**Comment by apoorvabc** [comment]
I am sure there must be a way since these plots are available in the output. But I am unsure how I can extract the discrete values to be able to replicate it.
![image](https://github.com/user-attachments/assets/c70b5d71-a741-4c67-a7b4-8e36c44d724e)

**Comment by louisjanin** [comment]
You have everything in the object returned by robyn_allocator function:
I managed to recreate the plot from this data
```
#assuming you ran robyn_allocator function and saved the result in an 'AllocatorCollect' object
scurve = list()
scurve[['data']]  <- AllocatorCollect$plots$p3$data
scurve[['main']]  <- AllocatorCollect$mainPoints
```

Is this what you were after?

**Comment by apoorvabc** [comment]
Thank you very much! This is what I was looking for
