### ISSUE TITLE
Quantify the conversion in absence of any additional marketing spend

### ISSUE THREAD

**Issue by sujithnair2021** [facebookexperimental/Robyn#105]
# Question

Is there a way to quantify the conversion in absence of any additional marketing spend? 

I suppose the way to do that would be figuring out intercept values in the actual vs predicted response plot. Is it possible to get those values?

**Comment by gufengzhou** [comment]
Hey, not sure what you mean. If you're referring to non-paid/organic activities like CRM, the current way to include CRM is just use it as baseline variable in set_baseVarName. Or what do you mean by figuring out intercept?

**Comment by sujithnair2021** [comment]
Hi,
Thanks for the response.
Let me try this way. In a typical regression equation, 
y = Intercept + Ax
The predicted vs actual graph shows y but not the intercept. I know what the effect share of a channel is and that gives an idea on what A is but I don't know anything about the predicted intercept(constant). 
In marketing terms, I am considering Y Intercept as the baseline sales that we will make without any marketing spend (in theory). So, it would be useful to get some direction on it. Is there any way to get that?

**Comment by gufengzhou** [comment]
Got it. Yes, in the folder where the whole plots are saved, you can find couple of CSVs. There you'll find what you need, esp in the _aggregated csv.

**Comment by Leonelsentana** [comment]
You should be able to find the intercept in the pareto_aggregated results within the plots folder as Gufeng said. E.g.:
![image](https://user-images.githubusercontent.com/70534991/124886441-86a5b680-dfd4-11eb-95db-86c5e1c36169.png)

**Comment by sujithnair2021** [comment]
Thank you!
