### ISSUE TITLE
Error when running pareto calculations

### ISSUE THREAD

**Issue by malaman5** [facebookexperimental/Robyn#1099]
## Describe issue
When running a model using a calibration, Robyn throws an error when running the pareto computations:

`>>> Running Pareto calculations for 10000 models on 3 fronts..
Error in `mutate()`:
ℹ In argument: `mape_n = .min_max_norm(.data$mape)`.
Caused by error:
! `mape_n` must be size 10000 or 1, not 22.`

## Provide reproducible example
The parameters file used are attached:
[parameters.json](https://github.com/user-attachments/files/17568722/parameters.json)
[dataset.csv](https://github.com/user-attachments/files/17568723/dataset.csv)

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn version: 3.11.1.9003
- R version: 4.3.3

**Comment by laresbernardo** [comment]
Hi @malaman5 

For reproducibility, I'm sharing the code I've tested and I don't encounter the error.

```
json_file <- ".../parameters.json"
dt_input_csv <- ".../dataset.csv"
json_data <- robyn_read(json_file)
dt_input <- read.csv(dt_input_csv)

InputCollect <- robyn_inputs(
  dt_input = dt_input, 
  json_file = json_file)
OutputModels  <- robyn_run(
  InputCollect = InputCollect,
  iterations = 1000,
  trials = 1)
OutputCollect <- robyn_outputs(
  InputCollect, OutputModels,
  pareto_fronts = 2, 
  export = FALSE)
```

Can you please check what's the difference between your code and the reproducible example? If you run this example do you get the error? I'm currently on version 3.11.1.9004 but there hasn't been any changes on the calibration code for a while. Feel free to reach back.

For reference, [this](https://github.com/facebookexperimental/Robyn/blob/c8bb458ae00b47924101d54415926b78efd8de9b/R/R/clusters.R#L297) is where the code is triggering your error.

**Comment by malaman5** [comment]
When running with the provided code, at first attempt I got the following error:
`Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns`

I increased the number of iterations to 2000 and the error was as follows, and looks to be related to the mutate function, but most likely because it didn't converge:
`Couldn't automatically create clusters: Error in sample.int(m, k): cannot take a sample larger than the population when 'replace = FALSE'

Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "NULL"`

**Comment by malaman5** [comment]
Apparently this issue appears when the model does not have enough iterations to converge. Increasing the number of iterations and making sure that the calibration provided is feasible solved the issue.
