### ISSUE TITLE
decomp.rssd utility

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookexperimental/Robyn#110]
Hi,

I’m raising this issue to ask for clarification about the `decomp.rssd` optimization metric.

According to the documentation, the aim of this loss function is to “steer the model towards more realistic decomposition results”.

**Question:** Isn’t this optimization metric mitigating one of the benefits of MMM, the possibility to spot channels where we are overspending and channels where we are underspending?

**Comment by gufengzhou** [comment]
Hi, good question. I think of it this way: When you talk about "the possibility to spot channels where we are overspending ...", you're assuming that MMM can produce the truth. This is unfortunately too good to be true... Users are deciding which "truth" they choose, no matter with Robyn or other MMM solutions. Therefore, the premise of MMM's reality is rather "all models are wrong, but some are useful". In this case, decom.rssd helps us getting rid of the "wronger"/ extreme results. In practise, running experiments and then calibrate MMM is the best thing you can do to get as close as possible to truth.

**Comment by LeoUbbiali** [comment]
Hi Gufeng,
thanks for the prompt reply - it makes totally sense 👍
