### ISSUE TITLE
Calculation speed

### ISSUE THREAD

**Issue by kpizon** [facebookexperimental/Robyn#118]
# Contributing to FB NextGen MMM R script

# Issue

Calculations are way slower than expected. Runs on included simulated data with recommended settings are taking usually ~3-5 minutes per trial (which is 2-3 hours depending on the machine used). I tried running it on google cloud (24 vCPUs, 64GB RAM) and calculation time totaled 114 min. I also monitored CPU usage on the machine and depending on its type it was ~30-40%, never exceeded 50%. Should I change anything except set_cores variable? 

# Steps to Reproduce

Run example data.

# Expected Behavior

Time estimation: with geometric adstock, 500 iterations * 40 trials and 6 cores, it takes less than 1 hour.

# Actual Results

It takes 3 hours instead of less than 1.

# Environment

R version 4.0.5 (2021-03-31) / 4.1.0 on other machine

**Comment by gufengzhou** [comment]
Hi, this might be caused due to the last commit that was aiming to fix the connection error. I've just reversed it and please see if the performance increases.  #123

**Comment by kpizon** [comment]
Hi, thank you for the reply. I tried once again and it occurred that total time decreased to 33 minutes now (14 cores out of 16 used during that test, but still CPU usage is ~36%). Nevertheless now the times are acceptable, thank you!
