### ISSUE TITLE
set_depVarType conversion

### ISSUE THREAD

**Issue by kpizon** [facebookexperimental/Robyn#119]
# Contributing to FB NextGen MMM R script

# Issue

When using conversion as dependent variable type I can't see any options to add costs. I am modelling units sold and all plots have incorrect ROI (not multiplied by unit costs). Is there an easy option to add it?

# Steps to Reproduce

-

# Expected Behavior

Part of code where I can add costs.

# Actual Results

Incorrect ROI

# Environment

R version (R --version) 4.1.0

**Comment by gufengzhou** [comment]
Hey, you're right that when using conversions as type, the ROI is incorrect (it's just conversions/spend, so the flipped CPA). I'll fix this in the next update in ETA August
