### ISSUE TITLE
How to resume learning?

### ISSUE THREAD

**Issue by watanta** [facebookexperimental/Robyn#12]
# Issue
I accidentally stopped running in the middle of learning.　Is there a way to resume learning?

# Steps to Reproduce

I kept learning for about 16 hours and accidentally stopped it ;(
![image](https://user-images.githubusercontent.com/20069196/105816884-345d7400-5ff8-11eb-88ea-d4809439eae0.png)

# Expected Behavior
I don't want to waste these 16 hours. Is there a way to resume learning?

In other words, is there a way to restart learning from parameters that have been learned to some extent?
It is like resuming learning of a neural network from the middle.

**Comment by Leonelsentana** [comment]
Hi @watanta,
Thanks for your recommendation about adding a feature to save somewhere partial results. I will add it to our backlog. We currently do not offer this feature. However, to speed up things, you may increase the number of cores in the set_cores variable to N-1 total cores (N) your computer or server may have. This should speed up things. Another thing you may do is to reduce iterations a bit (set_iter) also you may reduce the epochN to a smaller number than 16, you can see that based on epoch.optim parameter you just have 3 variables (those with 0) where an optimum has not been found, which is not necessarily a bad thing, coefficients will still be calculated for those parameters. Hope it helps and thanks so much again for testing our code :)
