### ISSUE TITLE
modelling period

### ISSUE THREAD

**Issue by kpizon** [facebookexperimental/Robyn#120]
# Contributing to FB NextGen MMM R script

# Issue

It would be nice to add an option to change modelling period. 

In my last model, there were huge TV spends from Christmas to New Year's Eve of year x and my modelling period started on 1st January year x+1, so I wanted to include its adstock in my model by loading more data and setting that the modelling period starts on 1st January.

# Steps to Reproduce
-
# Expected Behavior

Variable responsible for setting the custom modeling period.

# Actual Results
-
# Environment

R version (R --version) 4.1.0

**Comment by gufengzhou** [comment]
Hi, yes this one is already implemented in the next update that will be released ETA August. You can input all data and select any period to build the model, while the adstocking will always be applied on the entire dataset so that any previous adstock is included.

**Comment by kpizon** [comment]
Thank you!
