### ISSUE TITLE
Delayed adstock affect?

### ISSUE THREAD

**Issue by Ocean199** [facebookexperimental/Robyn#121]
Hello,
What is your opinion about modeling more down funnel metrics?  For instance modeling Website Visits vs Sales?  Website Visits is fairly straight forward and doesn't involve much adstock or delay, However Sales often have much longer adstocks and can peak weeks later.  It seems neither the Geometric nor Weibull functions have a variable for delay and might only be intended for upper funnel metrics?

Thanks 

![image](https://user-images.githubusercontent.com/87148058/126832511-0ce21bb5-3886-49e8-875f-762e7c84c951.png)

**Comment by gufengzhou** [comment]
Hi you're right about this. Both geometric and weibull transformations always peak at period 1. We do consider adding one more adstocking option in the future. It's just so far there's not much request on this feature and therefore we've deprioritised it. In the practise, we see this challenge rather in high-value products like cars, which are not yet the primary users for Robyn. But yes we do have this on the wishlist.
