### ISSUE TITLE
AttributeError: module 'nevergrad.parametrization.parameter' has no attribute 'MultiobjectiveReference' 

### ISSUE THREAD

**Issue by RoseBarzilai10** [facebookexperimental/Robyn#124]
I get the following error:

Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'nevergrad.parametrization.parameter' has no attribute 'MultiobjectiveReference' 

Any clue how this can be solved?

**Comment by gufengzhou** [comment]
hi, this is a rare error. Another reported this, please have a look at it first. https://github.com/facebookexperimental/Robyn/issues/103
