### ISSUE TITLE
KPI simulation with predefined baseVar value over time

### ISSUE THREAD

**Issue by not4fame** [facebookexperimental/Robyn#125]
Will it be possible to simulate the behavior of the measured KPI for the model using baseVar variables?
(e.g. How much more would I earn if my competitor's sales were always X)

**Comment by gufengzhou** [comment]
So far Robyn doesn't directly offer a function to output that. However, because baseVars don't have any transformation,  beta coefficient of competitor is just the slope --> when competitor sales changes x, depVar changes beta

**Comment by gufengzhou** [comment]
please re-open if necessary
