### ISSUE TITLE
Building a what-if scenarios using Robyn

### ISSUE THREAD

**Issue by learningml07** [facebookexperimental/Robyn#130]
# Contributing to FB NextGen MMM R script

# Issue

A summary of what the issue is about.

# Steps to Reproduce

Please provide instructions that can be used to reproduce your issue. Usually this will include a test case that produces the wrong output.

# Expected Behavior

What you expected to happen. For example the error message you expected to see.

# Actual Results

What actually happened. For example, an error message you did not expect to see.

# Environment

R version (R --version)

**Comment by learningml07** [comment]
Hi, I came across Robyn and the approach used amazed me. Can we create a what-if scenario. For example, if I increase the investment on medium-a by 5%, what will impact sales?

**Comment by gufengzhou** [comment]
Hey thanks for trying this out! So far we only simulate the response for media variables within the budget allocator. However you could do your own simulation by using the beta coefficients of your selected model. This is saved in the list of model output as well as the pareto_aggregated.csv on your machine. The equation is simply linear: y = intercept + beta1 * x1 + beta2 * x2...

**Comment by learningml07** [comment]
Thanks for the input. I am playing around the 'pareto_aggregated.csv' file only. So if let's say my 'spend_share' of medium(Facebook) is 0.18 and ROI is '0.69'[given in the above file], how do I compute the relation between these two variables.?

**Comment by gufengzhou** [comment]
For that, you might want to attend the "3.0 beta" where there is a new function that gives you the response for any given channel on any spend level. [Check it out](https://github.com/facebookexperimental/Robyn/issues/132)

**Comment by learningml07** [comment]
Cool, thanks :)

I have applied for the beta release.
