### ISSUE TITLE
Alternative approach to confidence interval and p-values for  glmnet models

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookexperimental/Robyn#131]
Hi,

I see that `glmnet` does not provide CI and PValues for regressors coefficient.

**Question:** what alternative approach would you suggest to gauge if a regressor coefficient is "significant" or not? (and eventually base backward elimination/forward selection decisions on that)

**Further context**
I get the intuition behind thy CIs and P-values are not meaningful for Ridge Reggression from these CrossValidated Question:

- [Why are confidence intervals and p-values not reported as default for penalized regression coefficients](https://stats.stackexchange.com/questions/224796/why-are-confidence-intervals-and-p-values-not-reported-as-default-for-penalized)
- [When using glmnet how to report p-value significance to claim significance of predictors?](https://stats.stackexchange.com/questions/45449/when-using-glmnet-how-to-report-p-value-significance-to-claim-significance-of-pr)

**Comment by gufengzhou** [comment]
Hey, as you've noticed that it's uncommon to obtain CI and p for regularised regression. There's research on how to do it best, for example [here](https://stats.stackexchange.com/questions/291409/inference-after-using-lasso-for-variable-selection). We've decided to not dig into this area for now. We believe that calibrating MMM with experimental result is rather the best practise to obtain "true value", while the uncertainty on point estimate still can't really help users to decide which result is the truth. Hope it helps.

**Comment by LeoUbbiali** [comment]
Hey Gufeng,

thanks for the quick reply.
It helps. It's paramount to have experimental results to obtain the true value of the regressors coefficients
