### ISSUE TITLE
Support For Multiple Variables in set_factorVarName

### ISSUE THREAD

**Issue by mbyim** [facebookexperimental/Robyn#133]
# Issue

When I tried to set multiple factor variables in the line

`set_factorVarName <- c("covid_began", "gift") `

I got this error referencing a line in fb_robyn.func.R

`Error in get(set_factorVarName) : first argument has length > 1`.

# Expected Behavior

Expected it to be possible to add several factor variables here.

# Actual Results

The code worked when I had a single factor variable set, but multiple broke the code. It seems possible that the input manipulations in the fb_robyn.func.R script don't currently support more than one factor variable? If this is true, is this on any roadmap?

# Environment

R version 4.1, macOS Big Sur.

**Comment by laresbernardo** [comment]
Hi @mbyim 
Thanks for reporting this issue on factor inputs. We have actually [already detected and fixed this problem in the 2.1 version](https://github.com/facebookexperimental/Robyn/blob/gufeng-2.1/source/fb_robyn.func.R#L673-L677) (try it out - not yet on master branch). We are constantly working on improvements and fixes and will merge them all into a single `Robyn` package quite soon as well.

**Comment by mbyim** [comment]
Oh good to know! I may give that branch a try. Thanks for the quick reply and vigilance on the issue!

**Comment by laresbernardo** [comment]
Hi @mbyim 
Thanks for reporting this issue on factor inputs. We have actually already detected and fixed this problem in the 2.1 version, which is currently on beta phase. If you'd like to try it out, please do and register [here](https://github.com/facebookexperimental/Robyn/issues/132). We are constantly working on improvements and fixes and will merge them all into a single `Robyn` package quite soon as well.

**Comment by gufengzhou** [comment]
> Oh good to know! I may give that branch a try. Thanks for the quick reply and vigilance on the issue!

Hey @mbyim, as you can see in the register link above shared by bernardo, we're actually recruiting for beta test through a registration:) The branch you just saw is a working branch and thus might break sometimes. also we're trying to have better overview with who's participating in the beta. Therefore please register for the beta to get the new testing code. Apology for the confusion!
