### ISSUE TITLE
Budget allocation

### ISSUE THREAD

**Issue by wenyanyy** [facebookexperimental/Robyn#134]
# Contributing to FB NextGen MMM R script

# Issue
Hi,

Hope you are doing well. I have a question about budget allocation part. 

# Steps to Reproduce

model_output_collect$allSolutions
optim_result <- f.budgetAllocator(modID = "1_1_1"
                                  ,scenario = "max_historical_response"
                                  ,channel_constr_low = c(rep(1.0,14)) 
                                  ,channel_constr_up = c(rep(1.0,14))

I input 1 on channel_constr_low and channel_constr_up for each channels. I thought spending allocation may not be changed. However, I saw the optimize results. the spending shares changed a little bit. So I want to ask the reasons. 

Another case I tried, I input 0.7 in channel_constr_low for one channel. however the results of that spending channel decrease 0.75 times. Could you please kindly explain it?

sometimes I tried different channels bounds which is 0.7-1.5. I found the response increase is negative sometimes. it makes me surprised.

Looking forward to your reply.

Thanks

# Actual Results

<img width="499" alt="捕获" src="https://user-images.githubusercontent.com/82489568/129137986-bee6f06c-9ff2-4acf-b3e4-13016b33754b.PNG">

# Environment

R version (R --version)

**Comment by gufengzhou** [comment]
Hey, I believe you should try out the beta version of our next release [here](https://github.com/facebookexperimental/Robyn/issues/132) :) The allocator is also adapted a bit and I'm curious if that works better. I've changed the default algo from MMA to SLSQP there and it seems to be more reliable so far.

**Comment by wenyanyy** [comment]
Thanks a lot. I sent the email to robyn team and apply for trying the new version. Looking forward to onboard it.  ：）
