### ISSUE TITLE
set_mediaSpendName when having multiple features for one channel but only one spend

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#137]
# Expected Behavior

Say I have records for `Facebook_clicks`,`Facebook_impresisons`,`google_clicks` and `google_impressions` i.e

`set_mediaVarName <- c("facebook_clicks","facebook_impressions","google_clicks","google_impressions")`.

As far as I understand, `set_mediaSpendName` is the spend for each record in `mediaVarName`, but since we get only one bill for each channel i.e one for Facebook and one for Google, we cannot divide our spend for `facebook` into spend for clicks and spend for impressions. Do we then just set
`set_mediaSpendName <- c("facebook_spend", "facebook_spend", "google_spend","google_spend")`

or how is this issue handled?

**Comment by gufengzhou** [comment]
Hi, you should pick either imps or clicks, not both. They're both caused by the same spend, thus there's probably impossible or makes no sense to split the spend towards imps and clicks. 

Regarding how to choose between imps and clicks, a simple matrix against your dependant variable helps

**Comment by Jakobhenningjensen** [comment]
Thanks a bunch
