### ISSUE TITLE
Issue with NEVERGRAD

### ISSUE THREAD

**Issue by KaisGarci** [facebookexperimental/Robyn#140]
Hello, 
At first I would like to thank you for this code.
I am trying to run this code:
conda_install("r-reticulate", "nevergrad", pip=TRUE) #must install nevergrad in conda before running Robyn
But this error occurs: 
Error: Error installing package(s): "nevergrad"

Can anyone help me please ? 
Thank you

**Comment by gufengzhou** [comment]
Hi, thanks for trying out! This is the installation guide. You can choose either conda or PIP environment to install the python package nevergrad. Hope it helps.

## install the python library Nevergrad
## please see here for more info about installing Python packages via reticulate - https://rstudio.github.io/reticulate/articles/python_packages.html

## option 1 nevergrad installation via conda
# conda_create("r-reticulate") # must run this line once
# conda_install("r-reticulate", "nevergrad", pip=TRUE)
# use_condaenv("r-reticulate")

## option 2 nevergrad installation via PIP
# virtualenv_create("r-reticulate")
# py_install("nevergrad", pip = TRUE)
# use_virtualenv("r-reticulate", required = TRUE)

## in case nevergrad still can't be imported after installation, please locate your python file and run this line
# use_python("/Users/gufengzhou/Library/r-miniconda/envs/r-reticulate/bin/python3.9")

**Comment by KaisGarci** [comment]
Thank you for your response 
Is it enough to do "pip install nevergrad" ? Even if conda_install("r-reticulate", "nevergrad", pip=TRUE) is getting error ? 
Thanks

**Comment by gufengzhou** [comment]
We're importing python package into R using reticulate. That's why you need to install Nevergrad into the reticulate environment. Also you have to specify the right python path for reticulate. Hope you made it.

**Comment by KaisGarci** [comment]
Yes it worked fine
Thank you for your help :D
