### ISSUE TITLE
Specify Adstock-function for each channel?

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#141]
# Contributing to FB NextGen MMM R script

# Issue
Say I have 4 media channels where for two of them the geometric adstock would assumed to be appropriate and for the other two, weibull.

Is there a way to include that in ROBYN? As far as I understand the code, we apply the same adstock-function to all media-channels (with media dependent hyperparameters)

**Comment by gufengzhou** [comment]
Hi, please run f.plotAdstockCurves(T) for weibull to see the shape transformation. Weibull can take on both S and L shape. The larger the "shape" parameter, the more S-shape. The smaller, the more L-shape.

**Comment by Jakobhenningjensen** [comment]
My question is more if we can have specific adstock for specific channels i.e using Geometric for e.g Google and FB and Weibull for e.g TV?

Med venlig hilsen

Jakob Henning Jensen
+45 26200713
________________________________

**Comment by gufengzhou** [comment]
Then no you can't. But weibull is intended to also cover the geometric like shapes and thus takes longer to run too.

**Comment by Jakobhenningjensen** [comment]
Exactly - thus I hoped to save some computation time by specifying Geometric for the ones.

Thanks for the swift replies!
