### ISSUE TITLE
Clarification on Average adstock decay rate graph

### ISSUE THREAD

**Issue by el-wrk** [facebookexperimental/Robyn#142]
Hi, just a quick question, in the documentation the Average adstock decay rate chart is described as:

"This chart represents, on average, what is the percentage decay rate each channel had. **The higher the decay rate, the longer the effect in time for that specific channel media exposure.**"

Which to me reads that the higher the % average adstock decay rate (the longer the bar on the chart), the longer the channel exposure effect (i.e. a good thing - front of mind for longer). Is this correct? It being called a higher decay rate is confusing me a bit.

**Comment by gufengzhou** [comment]
Yes, 70% decay means 70% of the effect today will carry over to tomorrow (or next week depend on your data).

**Comment by el-wrk** [comment]
Great, thank you for your prompt response.
