### ISSUE TITLE
Cross Validation?

### ISSUE THREAD

**Issue by Ocean199** [facebookexperimental/Robyn#143]
Hello,
I noticed in the code you are not providing a nfold or foldid, then isn't it by default 10 fold cross validation, not 100?

![image](https://user-images.githubusercontent.com/87148058/130656095-32d3793a-4178-4afc-b28c-b0f1d94ab6f8.png)

**Comment by gufengzhou** [comment]
You're right indeed! It's default 10 not 100. I'll correct the message. Thanks! Btw not sure if you have seen that there'll be a new release end of September. Registration for the event here https://www.alpha.facebook.com/groups/robynmmm/permalink/1023786281722838/
