### ISSUE TITLE
Data inputs with multiple simultaneous sections

### ISSUE THREAD

**Issue by KaisGarci** [facebookexperimental/Robyn#145]
Hello community, 

When I run this code: dt_mod <- f.inputWrangling()

I get this error :  Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates 

I didn't succeed to solve it. 
Can Anyone please help me ? 

Thank you

**Comment by gufengzhou** [comment]
You have panel data, which Robyn doesn't support at the moment. It's time series only. We'll consider supporting panel data in the future. For now, you can split your data into one dataset per region and fit individually.

**Comment by gufengzhou** [comment]
please re-open if necessary
