### ISSUE TITLE
Error in nlsModel(formula, mf, start, wts) :    singular gradient matrix at initial parameter estimates 

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#146]
# Contributing to FB NextGen MMM R script

# Issue
When calling `f.inputWrangling()` I get the following error: `Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates `

# Steps to Reproduce

I can unfortunately not share the dataset here. I thought it maybe was because the spend/var-names where not correctly aligned/sorted but they should indeed be

![image](https://user-images.githubusercontent.com/37367467/131264158-bf543482-b4e0-4c4b-bfe3-16f417b42dbb.png)

Note, I have made sure that we only have each day once i.e no duplicates. I have 21 variabels and use 1 year of data (which will be extended, but this is just to understand ROBYN and "play" around with it) - could that in any weird way introduce that error?
# Expected Behavior

An expected reason to why that is such.

# Actual Results

See the error above

# Environment

R version: 4.1.1

**Comment by laresbernardo** [comment]
Hi @Jakobhenningjensen Would you please check [this ticket](https://github.com/facebookexperimental/Robyn/issues/145) and check if it's the same case?

**Comment by Jakobhenningjensen** [comment]
I have identified two channels `bing` and `pinterest`. If I include either of them, the error raises, removing them makes the model run.

I do not have any NaNs nor duplictates (according to your questions regarding the other ticket).

**Comment by gufengzhou** [comment]
This is caused by the initial value issue of the spend exposure fitting. This issue should get better in the new release (Sep.29th). For now you can use spend instead. Sorry for the inconvenience

**Comment by gufengzhou** [comment]
please re-open if necessary
