### ISSUE TITLE
Add test sets

### ISSUE THREAD

**Issue by anorakj** [facebookexperimental/Robyn#148]
Hello community,
Would it be possible to add test sets to MMM? Specifically, test for dep_var. In our case, the dep_var = gross transaction value (GTV). We hope that the MMM model can help predict GTV. Currently Robyn provides us with training, validation and model renewal.

**Comment by gufengzhou** [comment]
Hi, you're testing the 3.0 beta right? At the moment Robyn 3.0 also hasn't provided a forecast function. We'll consider adding this in the future. You could also try customizing yourselves by using the beta coefficients for predictors from a given model. The hacky part would be how to create the "future data frame" of the predictors.

**Comment by gufengzhou** [comment]
please re-open if necessary
