### ISSUE TITLE
Model output collect problem

### ISSUE THREAD

**Issue by KaisGarci** [facebookexperimental/Robyn#149]

**Comment by gufengzhou** [comment]
This still looks like Nevergrad installation issue. Are you using the sample data and getting this error? Try reinstalling Nevergrad following the guide closely.

**Comment by KaisGarci** [comment]
I uninstalled R and installed it again and it worked. 
Thank you :D

**Comment by KaisGarci** [comment]
> Hello community,
> 
> When I run the model through this code:
> 
> model_output_collect <- f.robyn(set_hyperBoundLocal
> ,optimizer_name = set_hyperOptimAlgo
> ,set_trial = set_trial
> ,set_cores = set_cores
> 
> # please set your folder path to save plots. It ends without "/".
> I got this error: Error in py_get_attr_impl(x, name, silent) :
> AttributeError: module 'nevergrad' has no attribute 'p
> 
> Any help please ?
> 
> Thank you
