### ISSUE TITLE
'f.mmmCollect' error

### ISSUE THREAD

**Issue by victorlee29** [facebookexperimental/Robyn#15]
Hi, 

Hope you're well. 

# Issue
I'm running Robyn with my own data. This is the 'same' as example data, aka, a CSV with date, revenue and data from 3 digital channels (with spend/imp numbers,) plus a variable column for unemployment rates. Unfortunately I am getting this error message after no further hyperparameter optimisations can be found;

Error in f.mmmCollect(set_hyperBoundLocal) : object 'epochN' not found

# Steps to Reproduce
To confirm, I have not altered he code in ay way, but the below is turned on (though I get the same error regardless):

- activate_hyperBoundLocalTuning <- T # change setChannelBounds = T when setting bounds for each media individually

However, the below is turned off for now, as a single epoch was taking 3 hours. With the example data, this can be turned on and all the graphs and workings were plotted, after multiple epochs, after a few hours:

- activate_calibration <- F # Switch to TRUE to calibrate model. This takes longer as extra validation is required

# Expected Behavior
I expected it to plot all the chosen graphs, as well as the optimiser, like when I tested the example data.

# Environment
RStudio

Hope you can help!

Tanks,
Lee

**Comment by gufengzhou** [comment]
Hello Lee, sorry for the late reply! There's a major update of Robyn since yesterday, where we've deprecated the whole "epoch" setting and embraced the evolutionary algorithm for hyperparameter optimisation. Please just pull the new code and try it out! If you have more issue, please just open a new issue. Thank you!
