### ISSUE TITLE
Minimum recommended 

### ISSUE THREAD

**Issue by el-wrk** [facebookexperimental/Robyn#151]
Hi,

Is there a minimum recommended level of sales for the model? At the moment I'm running it on daily sales data where there's a thin spread of about 500 sales a year, which isn't providing as good of a model as running it on another markets data which has around 1900 sales a year. Would you recommend I aggregate the sales data?

Thanks for your help.

**Comment by gufengzhou** [comment]
No the magnitude of dependent variable doesn't matter. If a model is good or not is rather depending on how good the predictors can explain the variation of the sales. If you see low fit, recommendation would be looking for extra predictors and considering splitting media vars.
