### ISSUE TITLE
Lambda is not properly used when a fixed set of set_hyperBoundLocal are passed through f.robyn

### ISSUE THREAD

**Issue by jlmorrissette-cbi** [facebookexperimental/Robyn#152]
# Contributing to FB NextGen MMM R script

# Issue

When providing a set of fixed set_hyperBoundLocal, the model is not properly fit.  It appears that the following sequence happens:
`num_hyppar_ng` is calculated as 0
`if (num_hyppar_ng == 0) {fixed.out <- T}` evaluates as TRUE and sets fixed.out to TRUE
During the initial stages of f.mmm, fixed.lambda is never assigned a value (see line 887 of the current fb_robyn.func.R file)
The following section is then run
```
          ## if no lift calibration, refit using best lambda
          if (fixed.out == F) {
            mod_out <- f.refit(x_train, y_train, lambda=cvmod$lambda.1se, lower.limits, upper.limits)
            lambda <- cvmod$lambda.1se
          } else {
            mod_out <- f.refit(x_train, y_train, lambda=fixed.lambda[i], lower.limits, upper.limits)
            lambda <- fixed.lambda[i]
          }
```
Here, fixed.out has been set to TRUE but fixed.lambda is still the default NULL (having not been assigned a value on line 887), so it is passed through to f.refit as NULL.
The decomp now has unexpected values for `mod_out` and throws an error message.

# Steps to Reproduce

Provide a list of single values to set_hyperBoundLocal (not ranges) and run f.robyn using that set list. 

# Expected Behavior

Expect lambda to get calculated and a reasonable estimate to be returned.

# Actual Results

Multiple error messages are produced:
"### attention for loop 1 : manual decomp is not matching linear model prediction. Deviation is 406285.4 % ###"
"Warning message:
In mapply(function(regressor, coeff) { :
  longer argument not a multiple of length of shorter" 

Model is not fit properly when passed back to f.refit. 
Model results are not fitting as well as they should.
Model decomp produces an error.

# Environment

R version 4.1.0

**Comment by gufengzhou** [comment]
hi, you're touching a very rare use case that is actually not supported anymore. please check out the f.robyn.fixed() function in the .exec script and follow that use case

**Comment by gufengzhou** [comment]
Robyn is just updated to 3.0. Please let me know if this is working now
