### ISSUE TITLE
Retrieving Projected Responses

### ISSUE THREAD

**Issue by maisiemoore** [facebookexperimental/Robyn#158]
Hi Robyn team, thank you again for making this an open source project. Its been really helpful to quickly build up an MMM for my business context!

In a couple of the tickets (#65 and #148 ), you all did not intend for this tool to be used for projections. However, in my business context we do need the projected `response` from the `max_response_expected_spend`.
Is there anyway I can back into the projected `response` with the generated outputs from `optim_result`?

**Comment by Leonelsentana** [comment]
Hey, thanks for your interest in Robyn. Exactly as you said. Robyn, and MMMs in general, are designed to explain past behavior and recommend budget allocation based on past data history. The new 3.0 version will allow to run recent windows and window refreshes which will also allow better representation of the latest investment behavior. We will consider the forecasting mechanism for future releases. At the moment the budget allocator is purely based on response curves from this past behavior. At some point, what you could do with what we have as a hack, is to forecast separately (Through prophet or any other time series forecasting tool) how the predicted sales and the expected investment and/or impressions in channels should look like for the upcoming period of time in question. Then input that as if it were "Real" data in a new window and analyze how Robyn actually assigns budget given the new forecasted window. 

Hope I could explain myself. Please let us know if you try it!

**Comment by maisiemoore** [comment]
Thanks Leo! This is helpful! I will probably try it (maybe _have to_ try it!)
I'll let y'all know how it goes!

**Comment by Leonelsentana** [comment]
Awesome! If you do need access to 3.0 let me know we will happy to grant it to you

**Comment by maisiemoore** [comment]
Actually @Leonelsentana , if you don't mind, I'd like to try 3.0! (Eager to get my hands dirty!)

**Comment by PetricaR** [comment]
@Leonelsentana how can I have access to  3.0?

**Comment by Leonelsentana** [comment]
Hey PetricaR! The official launch is Sep 29th during the summit: https://projectrobynmmmsummit2021.splashthat.com/
Do you have any use case on 3.0 vs. 2.0 like Maisie's where you would like to provide feedback as a beta tester? Thanks

**Comment by Leonelsentana** [comment]
@maisiemoore please share your email with me? Please have in mind we will need feedback as a beta tester on this. Thanks!

**Comment by PetricaR** [comment]
@Leonelsentana  

Yes, I have a use case. I would like to test the model on carrefour media data. Also, i could provide some feedback, i think It would be great if i can do that.

**Comment by maisiemoore** [comment]
@Leonelsentana -- just updated my user profile with my email address. thanks! looking forward v3.0!

**Comment by Leonelsentana** [comment]
> Yes, I have a use case. I would like to test the model on carrefour media data. Also, i could provide some feedback, i think It would be great if i can do that.

Would you be able to provide feedback regarding the specific features below? If so please let us know what that would be :) 
If not, on the 29th we will be releasing the final version and you will be able to use it.

- Rolling windows and Model refresh & reporting(Higher frequency of update for reporting)
- Marginal response function. Get total and marginal response for any given spend level from chosen channel and model version.
- Organic variables

Thanks for your feedback and understanding!

**Comment by PetricaR** [comment]
@Leonelsentana 
I am a beginner in DS, my feedback of course you will received, but I am not sure how much value will be added. 

Thanks
PS: Anyway, after I finish the simulation, i will provide feedback, in general.

**Comment by Leonelsentana** [comment]
@PetricaR thanks so much for be willing to test Robyn current version. We will love to receive your feedback. Please stay tuned for the official release during our summit https://projectrobynmmmsummit2021.splashthat.com/ Sep 29th :) Looking forward to having you with us that day!
