### ISSUE TITLE
Link to demo.R does not work

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#166]
# Contributing to FB NextGen MMM R script

# Issue

The link in `README.md` to `demo.R` throws an 404:

# Steps to Reproduce

Click the link on `demo.R`, which forwards to https://github.com/facebookexperimental/Robyn/blob/package/inst/demo.R

# Expected outcome
Assuming it should link to https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R

**Comment by gufengzhou** [comment]
thanks for raising this! it's fixed
