### ISSUE TITLE
Error in message("Input data has ", nrow(dt_mod), " ", InputCollect$intervalType,  :    object 'ds' not found

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#167]
# Contributing to FB NextGen MMM R script

Note, the dataset has been running/working with Robyn 2.0

# Issue
When calling 
```R
OutputCollect <- robyn_run(
  InputCollect = InputCollect # feed in all model specification
  , plot_folder = "./Plots/" # plots will be saved in the same folder as robyn_object
  , pareto_fronts = 3
  , plot_pareto = TRUE
)
```

I get the error: `Error in message("Input data has ", nrow(dt_mod), " ", InputCollect$intervalType,  : 
  object 'ds' not found`

The column `ds` does exist in the holidays data: 
![image](https://user-images.githubusercontent.com/37367467/135261258-2d607e8b-ee4a-4529-8bfa-5a196a013895.png)

It seems like you are trying to access `ds` in  `dt_mod[, min(ds)]` [model.R](https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R) line 61, but my `InputCollect$dt_mod` is empty/NULL. 

All code uptil has been run w/o any errors/warnings

# Steps to Reproduce

Unfortunately I'm not able to share the data - but more than happy to print out any inputs you would like

# Actual Results

See above

# Environment

R version: 4.1.1

**Comment by gufengzhou** [comment]
You're trying out the new package right? Have you tried restarting R session? The demo data is running without issue?

**Comment by Jakobhenningjensen** [comment]
That is correct (sorry) - it s 3.0,yes.

Yes, the demo-data works fine, and after the first `InputCollect` the attribute `dt_mod` is non-empty with the demo-data, although for our data, it is NULL:
![image](https://user-images.githubusercontent.com/37367467/135270852-eabe36ad-7d5c-4853-9ab2-884128ff8a11.png)

bu `dt_input` and `dt_holiday` are populated
![image](https://user-images.githubusercontent.com/37367467/135271395-e0c9703c-8e0e-4399-80fe-a69209f92a93.png)

**Comment by gufengzhou** [comment]
not sure if relevant but how come your screenshot shows InputCollect&dt_inpu ? the "t" is missing?

**Comment by Jakobhenningjensen** [comment]
Yeah, I think R-studio finds the attribute closest to the one written. I tried with `dt_inp` as well and that gave same result:
![image](https://user-images.githubusercontent.com/37367467/135275476-87a03156-3384-40ea-b73c-420448925199.png)

**Comment by gufengzhou** [comment]
no, dt_mod is created in the robyn_engineering function within the robyn_inputs function. the above is super strange. can you check again if all variable specification is right? are there any missing dates in your dataframe? or missing values?

**Comment by Jakobhenningjensen** [comment]
That's what I thought aswell.

I ran into that problem in Robyn 2.0 (with some missing variables), and fixed that afterwards. The dataset has been working with 2.0.

Just for being sure, I checked again for missing values an there's none (python)
![image](https://user-images.githubusercontent.com/37367467/135276970-3e5d9550-b872-4f61-bfab-a24273f5d54f.png)

**Comment by gufengzhou** [comment]
in demo.R row 207, have you run that too? https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R

**Comment by Jakobhenningjensen** [comment]
I have just tried to wipe the workspace, close it all down, re-open and create a new file and run it from there.
Now I get an error in the `check_hyperparameters` function, which might also have been in the previous one but for some odd-reason havent been shown.

My apologies!

**Comment by Jakobhenningjensen** [comment]
As per my comment above - it works like a charm now. The variables from `set_baseVar` in 2.0 hadn't been added to the `hyperparameters`, which caused the issue.
Why I didn't get the error message after tried to clean the workspace several times, I have no clue.

Thanks for the support!
