### ISSUE TITLE
Potential error in the check for set_holidays

### ISSUE THREAD

**Issue by amogh-nalwaya** [facebookexperimental/Robyn#168]
There seems to be an error within the check for if the week start is Sunday or Monday when the interval type is Week. I know this issue has happened before and potentially could be related to locale. Here's what getlocale() returns for me.

```
> Sys.getlocale()
[1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"

```

```
> lubridate::wday("2017-01-22", week_start = 1)  
[1] 7
```

Just checking for start date "2017-01-22" which is a Sunday would return 7 for the check and fail the check below.

```
if (intervalType == "week") {
    weekStartInput <- lubridate::wday(dt_transform$ds[1], week_start = 1)
    if (!weekStartInput %in% c(1, 2)) stop("Week start has to be Monday or Sunday")
    dt_holidays$dsWeekStart <- floor_date(dt_holidays$ds, unit = "week", week_start = 1)
    holidays <- dt_holidays[, .(ds = dsWeekStart, holiday, country, year)]
    holidays <- holidays[, lapply(.SD, paste0, collapse = "#"), by = c("ds", "country", "year"), .SDcols = "holiday"]
  }
```

What am I doing wrong?

**Comment by xlim7** [comment]
I'm facing the same issue as well

**Comment by PetricaR** [comment]
same issue as well

**Comment by gufengzhou** [comment]
hi, thanks for reporting it. i just fixed it by changing to %in% c(1, 7) instead of c(1,2). let me know if it works.

**Comment by xlim7** [comment]
It works for me now, thanks!

**Comment by gufengzhou** [comment]
I assume this is solved. Please reopen if not

**Comment by amogh-nalwaya** [comment]
@gufengzhou you probably also need to fix this line based on what the week start date in your input data is

`dt_holidays$dsWeekStart <- floor_date(dt_holidays$ds, unit = "week", week_start = 1)`

**week_start** should be flexible based on the start date.
