### ISSUE TITLE
Robyn refresh rolling window issue

### ISSUE THREAD

**Issue by madnoodles** [facebookexperimental/Robyn#169]
# Issue

Robyn refresh rolling window start and end dates does not work as expected

![image](https://user-images.githubusercontent.com/4481967/135363243-68ab0ba7-d2cd-4a8a-9f8f-39eacac76e06.png)

# Expected Behavior

I'm expecting the refresh model to be build on from 1-11 to 9-25.

# Actual Results

From the screenshot you can see it's actually from 1-11 to 9-6.

# Environment

R version (R --version 4.1.1)

**Comment by gufengzhou** [comment]
Hi, this is a little strange. I've just manually changed our dummy data to daily and tried it out, it looks normal to me on my end. Could you check if there's any missing dates in your data? Any chance you can share a reproducible data example with me? It's difficult for me to debug without the data.

![image](https://user-images.githubusercontent.com/14415136/135427672-287aab58-dceb-4f1d-92fe-8ab45bfbd2d3.png)
![image](https://user-images.githubusercontent.com/14415136/135427762-ed67d948-0eb5-4f64-bc37-3bbba8945938.png)

**Comment by madnoodles** [comment]
[MMM_demo.csv](https://github.com/facebookexperimental/Robyn/files/7261471/MMM_demo.csv)
Yes, you can find it here.

**Comment by gufengzhou** [comment]
Thanks for sharing the data. I've tried it out using V1 as dep.var and all 25 indep.var, it works ok on my side see screenshot. can you also share your demo.R script so that i can see your setting?
![image](https://user-images.githubusercontent.com/14415136/135598996-085d83e6-bbcc-47f0-b866-544ad9a94b43.png)

**Comment by madnoodles** [comment]
[sample.R.zip](https://github.com/facebookexperimental/Robyn/files/7269232/sample.R.zip)
Sure, you can find it here, could you post your script by any chance as well? just want to compare it. thx!

**Comment by gufengzhou** [comment]
hey, after testing your demo script, i still get normal outcome as in screenshot. I've attached my demo version for you to compare. maybe reinstall the Robyn lib and restart R session before running it? let me know

![image](https://user-images.githubusercontent.com/14415136/135902858-b156f3a3-2d4b-448f-99ce-51d4f64f60e8.png)
![image](https://user-images.githubusercontent.com/14415136/135902819-4d5b9ba6-f51c-4a3d-9943-765eec17c048.png

[sample_gufeng.R.zip](https://github.com/facebookexperimental/Robyn/files/7280350/sample_gufeng.R.zip)
)
