### ISSUE TITLE
Ratio between independent data points and what, in the rolling window?

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#170]
# Contributing to FB NextGen MMM R script

# Issue

In the [docs](https://facebookexperimental.github.io/Robyn/docs/demo-R-script#step-2a-4-model-calibration-optional) it's written under `window_end`:

> Recommended to have ratio of independent variable data points of 1:10

And I don't think I quite understand the phrasing. What is the ratio of independent variable data points to? Is it atleast 1/10 of the total number of data points (i.e the window should contains atleast 10% of the datapoints of the dataset), is it a ratio to the hyper parameters (the window should contain atleast 10x the number of hyperparameters of datapoints)?

Do you prefer having such "clarifying questions" here as "issues" or in the FB group?

R version (R --version)

**Comment by gufengzhou** [comment]
hey, you could post anywhere you prefer. this one is regarding documentation fix, so it's totally ok here too. 
It just means the dimensions of input table, rows - columns ratio ideally > 10:1, or 1 indep.var to 10 data points. I'll change to clearer wording. thanks for raising this issue

**Comment by Jakobhenningjensen** [comment]
Thanks a lot for the swift answer

**Comment by Jakobhenningjensen** [comment]
Just to reopen this for a quick question - is the 1:10 between our channels/datapoints or the channels-hyperparameters ? Say we have 4 channels and using geometric, we'll have 4*3 = 12 hyperparameters to be tuned. I would assume we would require 30 datapoints (i.e a window of a 1.5 month when using daily data) and not 120 (a window of 4 months when using daily data).

**Comment by gufengzhou** [comment]
Sure. It's 1:10 as columns to rows of the input data

**Comment by Jakobhenningjensen** [comment]
Great - just had to be sure. Thanks
