### ISSUE TITLE
Plotting takes really long time (3 hours<)

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#172]
# Contributing to FB NextGen MMM R script

# Issue

Having a dataset with 1 year of data and 12 channels, using weibull as adstock and 5 trials with 2000 iterations it takes around 15 min/trial.
Afterwards nothing is printed. The program is running but nothing is printed nor plotted (have been waiting for around 3 hours now, after the last iteration).

Note, I'm running with 20 cores, and I have tested with `geometric`, 3 `trials` with `500` iterations that it all runs and plots are created. Furthermore I have added `message("Training done!")` after `robyn_run()` which haven't been printed yet.

1) Is it normal that it takes that long time?
2) In robyn 2.0 there was a plotting-time-bar. Do you plan adding that aswell to Robyn 3.0?

# Expected Behavior
A time-bar of the plotting as in Robyn 2.0 would be great

# Actual Results

Have been running for ~3 hours after last iteration.

# Environment

R version: 4.1.1

**Comment by gufengzhou** [comment]
the plotting time bar is still there actually. you're not seeing this? not even with geometric?

regarding weibull, true that it takes longer because weibull has 2 parameters compared to geometrics with only 1. But still weibull is often too slow. we'll look into how to do better there

**Comment by Jakobhenningjensen** [comment]
It came ~5 hours after the last iteration was finished. 
We might stick to geometric then untill we are confident with the new version, then switch to weibull. 

Thanks
