### ISSUE TITLE
relative plot-path seems to not be working

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#175]
# Contributing to FB NextGen MMM R script

# Issue
I have the following folder-structure

```
Robyn_3_0/
├─ Data/
├─ Model/
├─ Plots/
├─ main_robyn.R
```
where `main_robyn.R` runs the fitting. 

In `main_robyn` the following is set:

```R
setwd("~/Documents/robyn_3_0/")
.
.
robyn_object <- "Model/MyRobyn.RDS"
.
.
OutputCollect <- robyn_run(
  InputCollect = InputCollect # feed in all model specification
  , plot_folder = "Plots/" # plots will be saved in the same folder as robyn_object
  , pareto_fronts = 3
  , plot_pareto = TRUE
)
```
and that raises an issue

1)  The plots are placed in `Robyn/` and not in `Robyn/Plots/`

Note, I have tried following plot-path's : `./Plots`,`.Plots/`,`./Plots/`,`Plots/` and neither of them works
# Expected Behavior
The plots to be placed in `Robyn/Plots/` 

# Actual Results
Plots are placed in the same folder as `main_robyn.R` (`setwd`)

# Environment

R version (4.1.1)

**Comment by gufengzhou** [comment]
Can you try using the full path, namely "~/Documents/Robyn/Model/MyRobyn.RDS" as robyn_object instead of separated? same as for plot_folder?

**Comment by Jakobhenningjensen** [comment]
I have tried setting the following
![image](https://user-images.githubusercontent.com/37367467/135616102-eaf37ef2-4495-4fc6-926b-cc9bcdf579ea.png)

but the plots are still being placed in the root-folder

![image](https://user-images.githubusercontent.com/37367467/135616176-66d1dcc5-ee6f-4c17-9faa-c88767ae5157.png)


I noticed that if I add an additional folder-layer e.g `plot_folder = "/home/u27428/Documents/projects/robyn_3_0/Plots/something"` then it actually works. Do you by any chance assume that the input to `plot_folder` is the path-name to the `robyn_object` (which is a file) thus to get the folder, you go one level up from the provded path i.e `/home/u27428/Documents/projects/robyn_3_0/Plots  ->  /home/u27428/Documents/projects/robyn_3_0` ?

**Comment by Jakobhenningjensen** [comment]
I have tried setting the following
![image](https://user-images.githubusercontent.com/37367467/135616102-eaf37ef2-4495-4fc6-926b-cc9bcdf579ea.png)

but the plots are still being placed in the root-folder

![image](https://user-images.githubusercontent.com/37367467/135616176-66d1dcc5-ee6f-4c17-9faa-c88767ae5157.png)


I noticed that if I add an additional folder-layer e.g `plot_folder = "/home/user/Documents/projects/robyn_3_0/Plots/something"` then it actually works. Do you by any chance assume that the input to `plot_folder` is the path-name to the `robyn_object` (which is a file) thus to get the folder, you go one level up from the provided path (remove everything after the last `/`) thus

`/home/user/Documents/projects/robyn_3_0/Plots` is being trimmed to `/home/user/Documents/projects/robyn_3_0` whereas adding a "dummy" folder then fixes it since

`/home/user/Documents/projects/robyn_3_0/Plots/something` is being trimmed to `/home/user/Documents/projects/robyn_3_0/Plots` which then works

**Comment by gufengzhou** [comment]
I've just pushed a fix for this. Please let me know if it works now.

**Comment by Jakobhenningjensen** [comment]
Yes, that seems to've done the trick! Thanks
