### ISSUE TITLE
Recommended trials and iterations inconsistent between docs and demo.R

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#176]
# Contributing to FB NextGen MMM R script

# Issue
In the [demo.R](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R) you recommend `trials=5` and `iterations=2000`.

In the [docs](https://facebookexperimental.github.io/Robyn/docs/automated-hyperparameter-selection-optimization) you recommend `trials=40` and `iterations=500`.

I assume the docs is a typo from robyn 2.0 (where you had those recommendations, if I'm not wrong).

**Comment by gufengzhou** [comment]
Thanks for raising this! You're right that 500x40 is old. Apology that the website is not fully updated to 3.0 yet. We're working on this asap! @Leonelsentana for visibility.

**Comment by Leonelsentana** [comment]
Just fixed it! Thanks so much for the help @Jakobhenningjensen :) really appreciated
