### ISSUE TITLE
Differences between Robyn 2.0 and 3.0 in R scripts

### ISSUE THREAD

**Issue by el-wrk** [facebookexperimental/Robyn#179]
Hi,

I'm updating my code from 2.0 to 3.0 and comparing code from the exec, func and optm files in GitHub noticed there's not very many differences between the two (a few lines of code). Are the 3.0 changes available using the original three files or are they only available using Robyn as a package?

Apologies if I'm missing something!
Thanks

**Comment by gufengzhou** [comment]
No worries. Please check the readme in the Robyn repo. The func/exec scripts are deprecated. You only need to install the Robyn library and run the demo.R script that is the new guide. All in readme.

**Comment by el-wrk** [comment]
Great, thanks.
