### ISSUE TITLE
 Error in get(date_var) : object 'DATE' not found 

### ISSUE THREAD

**Issue by michellegrushko-glossier** [facebookexperimental/Robyn#182]
# Contributing to FB NextGen MMM R script

# Issue
I am getting this error when I attempt to run the InputCollect <- robyn_inputs(... 

The date variable in our data is named "DATE" and I'm using dt_input as the name of our dataframe. The date variable is also in the format of yyy-mm-dd and is a date object using lubridate, so I'm not sure why I am seeing this error. I noticed that in the dt_input example the DATE variable is an IDate object so I tried to convert it too but it still came back with the same error. I attempted to convert to character string but still had the same issue. Lastly, I attempted to redownload the newest 3.0 code and rerun but experienced the same issue. 

# Steps to Reproduce

Please provide instructions that can be used to reproduce your issue. Usually this will include a test case that produces the wrong output.

# Expected Behavior

What you expected to happen. For example the error message you expected to see.

# Actual Results

What actually happened. For example, an error message you did not expect to see.

# Environment

R version (R --version)
"R version 4.0.4 (2021-02-15)"

**Comment by gufengzhou** [comment]
I usually use data.table::fread() to read csv. Could you try? Otherwise, please share your error message and provide your model configuration script (the demo.R script) and a dataset to reproduce the error for debugging, with your real data value masked of course.
