### ISSUE TITLE
Weibull probs error

### ISSUE THREAD

**Issue by tamarDSG** [facebookexperimental/Robyn#185]
## Describe issue
Hi, 
Thank you for your incredible work!

I run Robyn 3.0 model on custom data  includes 5 spend channels and it worked

However, once I change the "adstock" parameter from "geometric" to "weibull" I received the following error:

>'Error in { : task 1 failed - "'probs' outside [0,1]'

Please assist

## Provide dummy data & model configuration

InputCollect <- robyn_inputs(
  dt_input = df
  ,dt_holidays = dt_prophet_holidays
  ,date_var = "day" 
  ,dep_var = "revenue" 
  ,dep_var_type = "revenue" 
  ,prophet_vars = c("trend", "season", "holiday", 'weekday') 
  ,prophet_signs = c("default","default", "default",'default') 
  ,prophet_country = "DE"
  ,context_vars = c() 
  ,context_signs = c() 
  ,paid_media_vars = c("a", "b","c","d" ,"e", "f")
  ,paid_media_signs = c("default", "default","default", "default", "default","default")
  ,paid_media_spends = c("a", "b","c","d" ,"e", "f")
  ,organic_vars = c()
  ,organic_signs = c()
  ,factor_vars = c() 
  ,cores = future::availableCores() 
  ,window_start = "**"
  ,window_end = "**"
  ,adstock = "weibull" 
  ,iterations = 2000 
  ,nevergrad_algo = "TwoPointsDE" 
  ,trials = 5 
 )
  

InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)

OutputCollect <- robyn_run(InputCollect = InputCollect , plot_folder = robyn_object , pareto_fronts = 3, plot_pareto = TRUE)

**Comment by gufengzhou** [comment]
In order to debug, I'd need your dataset and your demo.R script. Could you please modify your dataset to mask the real values and share a reproducible case with the error with me?

FYI, I've just commited a fix that should improve weibull's performance. 619b2ca86b2f50c17acadd067023f747d2ee8351
