### ISSUE TITLE
Check variable significance

### ISSUE THREAD

**Issue by VO-FS** [facebookexperimental/Robyn#188]
## Describe issue
Is it necessary to first run a Time Series regression to check whether the variables you want to include are having a significant effect on the dependent variable? For example first check if the Time Series of Temperature is significant before including it as a variable in Robyn. 

I am wondering if someone has a thought about this or already implemented a regression model to check for significance? 
I like hearing from you. 

Thank you in advance!

**Comment by gufengzhou** [comment]
please reopen if necessary.
