### ISSUE TITLE
Fail to install nevergrad following `demo`

### ISSUE THREAD

**Issue by kennychen83** [facebookexperimental/Robyn#189]
## Describe issue

I tried to copy-paste `demo` locally to my Rstudio. However, I haven't been able to get pass the stage of installing nevergrad. Any help is appreciated.

1. USE `pip`
```
remotes::install_github("facebookexperimental/Robyn/R")
library(Robyn)
library(reticulate)
set.seed(123)

Sys.setenv(R_FUTURE_FORK_ENABLE="true")
options(future.fork.enable = TRUE)

## Option 1: nevergrad installation via PIP
virtualenv_create("r-reticulate")
use_virtualenv("r-reticulate", required = TRUE)
py_install("nevergrad", pip = TRUE)

Using virtual environment '/Users/kennychen/.virtualenvs/r-reticulate' ...
Requirement already satisfied: nevergrad in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (0.4.3.post8)
Requirement already satisfied: cma>=2.6.0 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from nevergrad) (3.1.0)
Requirement already satisfied: numpy>=1.15.0 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from nevergrad) (1.21.2)
Requirement already satisfied: typing-extensions>=3.6.6 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from nevergrad) (3.10.0.2)
Requirement already satisfied: bayesian-optimization>=1.2.0 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from nevergrad) (1.2.0)
Requirement already satisfied: scikit-learn>=0.18.0 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from bayesian-optimization>=1.2.0->nevergrad) (1.0)
Requirement already satisfied: scipy>=0.14.0 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from bayesian-optimization>=1.2.0->nevergrad) (1.7.1)
Requirement already satisfied: joblib>=0.11 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.virtualenvs/r-reticulate/lib/python3.8/site-packages (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad) (3.0.0)
```
But it fails during Step 3 (run `robyn_run`):
```
Using robyn object location: /Users/kennychen/Desktop
Input data has 208 weeks in total: 2015-11-23 to 2019-11-11
Initial model is built on rolling window of 92 weeks: 2016-11-21 to 2018-08-20
Using geometric adstocking with 18 hyperparameters & 10-fold ridge x-validation on 6 cores
>>> Start running 5 trials with 2000 iterations per trial each with TwoPointsDE nevergrad algorithm...
 Running trial nr. 1 

Error in robyn_mmm(hyper_collect = InputCollect$hyperparameters, InputCollect = InputCollect,  : 
  You must have nevergrad python library installed.
```

2. USE `conda`
```
remotes::install_github("facebookexperimental/Robyn/R")
library(Robyn)
library(reticulate)
set.seed(123)

Sys.setenv(R_FUTURE_FORK_ENABLE="true")
options(future.fork.enable = TRUE)

## Option 2: nevergrad installation via conda
conda_create("r-reticulate") # must run this line once
use_condaenv("r-reticulate")
conda_install("r-reticulate", "nevergrad", pip=TRUE)
```
and this takes forever with some following messages:
```
ERROR: Command errored out with exit status 1: /Users/kennychen/Library/r-miniconda/envs/r-reticulate/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cl/dh6ng9n54497kq338mr97xv40000gp/T/pip-install-2cnal0_e/scipy_89b10482d6b64757a968ef573987162c/setup.py'"'"'; __file__='"'"'/private/var/folders/cl/dh6ng9n54497kq338mr97xv40000gp/T/pip-install-2cnal0_e/scipy_89b10482d6b64757a968ef573987162c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cl/dh6ng9n54497kq338mr97xv40000gp/T/pip-record-5w5zk2sn/install-record.txt --single-version-externally-managed --prefix /private/var/folders/cl/dh6ng9n54497kq338mr97xv40000gp/T/pip-build-env-i6uajlu6/overlay --compile --install-headers /private/var/folders/cl/dh6ng9n54497kq338mr97xv40000gp/T/pip-build-env-i6uajlu6/overlay/include/python3.10/scipy Check the logs for full command output.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e1/4d/15c3542a17eebf61e48bd71dc55b5f3b5031f1cd0dc4aad1ff9ac9651e49/scikit-learn-1.0.tar.gz#sha256=776800194e757cd212b47cd05907e0eb67a554ad333fe76776060dbb729e3427 (from https://pypi.org/simple/scikit-learn/) (requires-python:>=3.7). Command errored out with exit status 1: /Users/kennychen/Library/r-miniconda/envs/r-reticulate/bin/python /private/var/folders/cl/dh6ng9n54497kq338mr97xv40000gp/T/pip-standalone-pip-5z4uruie/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/cl/dh6ng9n54497kq338mr97xv40000gp/T/pip-build-env-i6uajlu6/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'oldest-supported-numpy; python_version!='"'"'3.7'"'"' or platform_machine=='"'"'aarch64'"'"' or platform_system=='"'"'AIX'"'"' or platform_python_implementation == '"'"'PyPy'"'"'' 'numpy==1.14.6; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'scipy>=1.1.0' Check the logs for full command output.

 Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
```

3. USE `use_python` with `pip`
```
## In case nevergrad still can't be imported after installation,
## please locate your python file and run this line with your path:
use_python("~/Library/Frameworks/Python.framework/Versions/3.10/bin/python3")
virtualenv_create("r-reticulate")
use_virtualenv("r-reticulate", required = TRUE)
py_install("nevergrad", pip = TRUE)
```
still can't run `robyn_run`:
```
Using robyn object location: /Users/kennychen/Desktop
Input data has 208 weeks in total: 2015-11-23 to 2019-11-11
Initial model is built on rolling window of 92 weeks: 2016-11-21 to 2018-08-20
Using geometric adstocking with 18 hyperparameters & 10-fold ridge x-validation on 6 cores
>>> Start running 5 trials with 2000 iterations per trial each with TwoPointsDE nevergrad algorithm...
 Running trial nr. 1 

Error in robyn_mmm(hyper_collect = InputCollect$hyperparameters, InputCollect = InputCollect,  : 
  You must have nevergrad python library installed.
```

4. USE `use_python` with `conda`
Same message with 2.

5. Force Python path for reticulate:
Not working either.

## Environment & Robyn version
R version 4.1.1 
Please make sure you're using the latest Robyn version -- YES

**Comment by Tsurty** [comment]
Yes this still works like before.

**Comment by Tsurty** [comment]
This may be helpful somehow for you guys.
The `Sys.setenv(RETICULATE_PYTHON = "/path/to/python")` after restarting R Session and reloading everything now seems to "work". This because now I'm not getting the error on the shared Python library but it says that the file doesn't even exist.

![image](https://user-images.githubusercontent.com/43139944/138288886-0c42407a-cb0a-420c-ae28-a5629fef5a3f.png)

I'm still trying to figure this out.

**Comment by Met0o** [comment]
> Hey guys, I was also experiencing an error message when trying to install nevergrad with conda.
> 
> Problem was coming from Python 3.10 package in my r-reticulate env.
> 
> I have just run:
> 
> conda_create("r-reticulate","Python 3.8")
> 
> to change the version of the Python package, and all is working now. Seems you can use all previous version up to 3.9
> 
> Hope it helps.

Thank you. This fix helped me resolve the following error:

"Error in py_module_import(module, convert = convert) : ImportError: DLL load failed while importing _ctypes: The specified module could not be found."

Recreating the r-reticulate environment with python version 3.8 resolved the problem.

**Comment by andrey-legayev** [comment]
Win10:
I've tried many ways and found that the most easy one is to use Nevergrad via system Python. 
Without venv / conda / miniconda / anaconda.
There is no special code required for making it work after proper installation - it just works in R Console, R Studio and in PyCharm with R plugin.

I hope it will help someone -

**Win10 Instructions**

1. Cleanup: 
    * uninstall all Python installations
    * uninstall Miniconda
    * remove folders:
%HOMEPATH%\\.miniconda (path is not precise)
%HOMEPATH%\\Documents\\.virtualenv (path is not precise)
any other folders related to venv / miniconda
1. Install latest Python 3.9.* from here: https://www.python.org/downloads/windows/ 
1. Run powershell as admin: Win+X -> Windows PowerShell (Admin)
1. Install pip: `py -m ensurepip --upgrade`
1. Upgrade pip: `py -m pip install --upgrade pip`
1. Install nevergrad: `pip install nevergrad`
1. Test Nevergrad availability in R console:
    * Run R console
    * Run code:
```
install.packages('reticulate')
library(reticulate)
if (!reticulate::py_module_available("nevergrad")) {
  cat("This is yout current python config:\n")
  print(reticulate::py_config())
  stop("Nevergrad is not available. Python config has been printed above.")
} else {
  cat("You have nevergrad and it is available to R!\n")
}
```

**Comment by tgtod002** [comment]
1. HI Guys,  

I have an HP Windows laptop.  Running Anaconda 2.1.1
I was finally able to install Nevergrad using the following method:
1.  Create a new environment ( i named mine RStudio)
2. Install RStudio
3. Install Powershell Prompt
4. Environments -->  RStudio(name of your environment) -->  Not installed (searched for reticulate)  --  shows up r-reticulate , choose and then apply)
5. Switch to Powershell:  in command prompt:  pip install nevergrad
<img width="471" alt="pipinsallnevergrad" src="https://user-images.githubusercontent.com/69650410/141837113-0087b61f-cc60-4da6-98b5-322ea8bcbb2c.png">

**Comment by amysheep** [comment]
I had similar issue. After I pointed use_python to the right python version and restart a new R session. py_config was able to pick up the correct version and everything worked.

**Comment by wamm0909** [comment]
> 

my issue display like you:"there's "nevergrad" right after "numpy" which is missing on mine. "do you solve this?ths!

**Comment by wamm0909** [comment]
> After many testes I'm still stuck here on my M1 Macbook. I'm now on Python3.8 which shouldn't be a problem, Nevergrad seems installed correctly but yet Robyn won't run.
> 
> ![image](https://user-images.githubusercontent.com/43139944/138470988-de14d472-da2f-4c56-8636-a94d0b294d4a.png)
> 
> This is what happens when I try to `py_config`
> 
> ![image](https://user-images.githubusercontent.com/43139944/138471807-550ec355-44b8-446b-8b3a-93793339437a.png)
> 
> Besides the fact that I don't get why `py_config` itself is not working, I noticed that on @laresbernardo's output there's "nevergrad" right after "numpy" which is missing on mine.
> 
> P.S.In the meantime I borrowed an older 2016 Macbook Pro (with Intel CPU ofc) on which I managed to make Robyn run smoothly with one little trick: I was still having troubles with the missing "shared Python library" error. Simply installing Xcode (without even running it once) fixed it and now it works fine.

my issue display like you:"there's "nevergrad" right after "numpy" which is missing on mine. "do you solve this?ths!

**Comment by Tsurty** [comment]
> > After many testes I'm still stuck here on my M1 Macbook. I'm now on Python3.8 which shouldn't be a problem, Nevergrad seems installed correctly but yet Robyn won't run.
> > ![image](https://user-images.githubusercontent.com/43139944/138470988-de14d472-da2f-4c56-8636-a94d0b294d4a.png)
> > This is what happens when I try to `py_config`
> > ![image](https://user-images.githubusercontent.com/43139944/138471807-550ec355-44b8-446b-8b3a-93793339437a.png)
> > Besides the fact that I don't get why `py_config` itself is not working, I noticed that on @laresbernardo's output there's "nevergrad" right after "numpy" which is missing on mine.
> > P.S.In the meantime I borrowed an older 2016 Macbook Pro (with Intel CPU ofc) on which I managed to make Robyn run smoothly with one little trick: I was still having troubles with the missing "shared Python library" error. Simply installing Xcode (without even running it once) fixed it and now it works fine.
> 
> my issue display like you:"there's "nevergrad" right after "numpy" which is missing on mine. "do you solve this?ths!

Nope, I've done some other tries over time with no luck (tried uninstalling and re-installing everything aswell) but I now had the chance to switch to an older intel-based mackbook which worked just fine right from the beginning using conda.

I haven't completely given up on my M1 tho, so I'll be glad to share once everything is fixed.

**Comment by wamm0909** [comment]
> > > After many testes I'm still stuck here on my M1 Macbook. I'm now on Python3.8 which shouldn't be a problem, Nevergrad seems installed correctly but yet Robyn won't run.
> > > ![image](https://user-images.githubusercontent.com/43139944/138470988-de14d472-da2f-4c56-8636-a94d0b294d4a.png)
> > > This is what happens when I try to `py_config`
> > > ![image](https://user-images.githubusercontent.com/43139944/138471807-550ec355-44b8-446b-8b3a-93793339437a.png)
> > > Besides the fact that I don't get why `py_config` itself is not working, I noticed that on @laresbernardo's output there's "nevergrad" right after "numpy" which is missing on mine.
> > > P.S.In the meantime I borrowed an older 2016 Macbook Pro (with Intel CPU ofc) on which I managed to make Robyn run smoothly with one little trick: I was still having troubles with the missing "shared Python library" error. Simply installing Xcode (without even running it once) fixed it and now it works fine.
> > 
> > 
> > my issue display like you:"there's "nevergrad" right after "numpy" which is missing on mine. "do you solve this?ths!
> 
> Nope, I've done some other tries over time with no luck (tried uninstalling and re-installing everything aswell) but I now had the chance to switch to an older intel-based mackbook which worked just fine right from the beginning using conda.
> 
> I haven't completely given up on my M1 tho, so I'll be glad to share once everything is fixed.

thanks buddy，Looking forward to your good news

**Comment by fee1985** [comment]
I tried to install nevergrad with Option 1: nevergrad installation via PIP of the demo.R

reticulate is installed and loaded

virtualenv_create("r-reticulate") worked an I have this folder:
C:\Users\name\Documents\.virtualenvs\r-reticulate

I also have the pip.exe here
C:\Users\\name\Documents\.virtualenvs\r-reticulate\Scripts

But when I try py_install("nevergrad", pip = TRUE) I get the following error
C:\Users\SD89F~1.LES\DOCUME~1\VIRTUA~1\R-RETI~1\python.exe: No module named pip
Error: Error installing package(s): "nevergrad"

py_config() brings this output
python:         C:/Users/s.leschke/Documents/.virtualenvs/r-reticulate/Scripts/python.exe
libpython:      C:/Users/s.leschke/Anaconda3/python39.dll
pythonhome:     C:/Users/s.leschke/Documents/.virtualenvs/r-reticulate
version:        3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function


Installing via Anaconda Prompt with pip install works well.

Would be grateful if someone has an idea how I can install nevergrad.

**Comment by Robin-Lord** [comment]
Hiya, first off - great project, I'm really impressed.

Second - I'm one of the people who hit a bit of a wall with this and really struggled to get further. I was working on Macbook Pro did find that downgrading to a laptop with a non-Apple chipset meant it breezed through the start phase (but then struggled a bit with the model build, understandably).

Most effective solution I found was creating a [cloud-hosted notebook with Google's Vertex AI](https://cloud.google.com/vertex-ai/docs/workbench/user-managed/create-new). Unfortunately Colab (even Colab Pro) crashed when I got to the model building stage, but the Vertex Jupyter notebook seems to have coped with it all really well. Tried Azure's equivalent but that struggled a bit.

Not to advertise the service but it's roughly 35p per hour for the core-number needed, so could be worth people giving it a try if you're stuck.

**Comment by wamm0909** [comment]
> > > After many testes I'm still stuck here on my M1 Macbook. I'm now on Python3.8 which shouldn't be a problem, Nevergrad seems installed correctly but yet Robyn won't run.
> > > ![image](https://user-images.githubusercontent.com/43139944/138470988-de14d472-da2f-4c56-8636-a94d0b294d4a.png)
> > > This is what happens when I try to `py_config`
> > > ![image](https://user-images.githubusercontent.com/43139944/138471807-550ec355-44b8-446b-8b3a-93793339437a.png)
> > > Besides the fact that I don't get why `py_config` itself is not working, I noticed that on @laresbernardo's output there's "nevergrad" right after "numpy" which is missing on mine.
> > > P.S.In the meantime I borrowed an older 2016 Macbook Pro (with Intel CPU ofc) on which I managed to make Robyn run smoothly with one little trick: I was still having troubles with the missing "shared Python library" error. Simply installing Xcode (without even running it once) fixed it and now it works fine.
> > 
> > 
> > my issue display like you:"there's "nevergrad" right after "numpy" which is missing on mine. "do you solve this?ths!
> 
> Nope, I've done some other tries over time with no luck (tried uninstalling and re-installing everything aswell) but I now had the chance to switch to an older intel-based mackbook which worked just fine right from the beginning using conda.
> 
> I haven't completely given up on my M1 tho, so I'll be glad to share once everything is fixed.

hi,buddy, I have successfully installed it on the m1 chip, macos big sur 11.6.1; the r version of rstudio is 4.1.2, the python is 3.8 or 3.9, and the method of “use conda” is used【at the top of this page】, but the last step command cannot use pip, it needs to be changed become：conda_install("r-reticulate", "nevergrad")；hope you can get it！and you can use 

> > > After many testes I'm still stuck here on my M1 Macbook. I'm now on Python3.8 which shouldn't be a problem, Nevergrad seems installed correctly but yet Robyn won't run.
> > > ![image](https://user-images.githubusercontent.com/43139944/138470988-de14d472-da2f-4c56-8636-a94d0b294d4a.png)
> > > This is what happens when I try to `py_config`
> > > ![image](https://user-images.githubusercontent.com/43139944/138471807-550ec355-44b8-446b-8b3a-93793339437a.png)
> > > Besides the fact that I don't get why `py_config` itself is not working, I noticed that on @laresbernardo's output there's "nevergrad" right after "numpy" which is missing on mine.
> > > P.S.In the meantime I borrowed an older 2016 Macbook Pro (with Intel CPU ofc) on which I managed to make Robyn run smoothly with one little trick: I was still having troubles with the missing "shared Python library" error. Simply installing Xcode (without even running it once) fixed it and now it works fine.
> > 
> > 
> > my issue display like you:"there's "nevergrad" right after "numpy" which is missing on mine. "do you solve this?ths!
> 
> Nope, I've done some other tries over time with no luck (tried uninstalling and re-installing everything aswell) but I now had the chance to switch to an older intel-based mackbook which worked just fine right from the beginning using conda.
> 
> I haven't completely given up on my M1 tho, so I'll be glad to share once everything is fixed.

hi,buddy, I have successfully installed it on the m1 chip, macos big sur 11.6.1; the r version of rstudio is 4.1.2, the python is 3.8 or 3.9, and the method of “use conda” is used【at the top of this page】, but the last step command cannot use pip, it needs to be changed become：conda_install("r-reticulate", "nevergrad")；hope you can get it！and you can use command "reticulate::py_module_available("nevergrad")" to find whether the installation was successful, this is more efficient than py_config; remember "library (reticulate)"

**Comment by Tsurty** [comment]
> 

Hey there, thanks for the suggestion.

I tried it but surprisingly enough I get stuck here:
`Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... `

It just stands there and doesn't progress.
I've done a bunch of other tests with no luck.

The thing is if I open a terminal via Anaconda and I do "pip install nevergrad" in there, it actually works and tells me that Nevergrad is installed.
Then, I can use either `use_virtualenv("r-reticulate", required = TRUE)` or `use_condaenv("r-reticulate")` but non of those seem to pickup Nevergrad.

At this point I believe there's just something screwed up somewhere between all the tests I've done.

**Comment by wamm0909** [comment]
> > 
> 
> 你好，谢谢你的建议。
> 
> 我试过了，但令人惊讶的是我被困在这里： `Collecting package metadata (current_repodata.json): ...working... done Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve. Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source. Collecting package metadata (repodata.json): ...working... done Solving environment: ...working... `
> 
> 它只是站在那里，没有进展。 我做了很多其他的测试都没有运气。
> 
> 问题是，如果我通过 Anaconda 打开一个终端并在其中执行“pip install nevergrad”，它实际上可以工作并告诉我已安装 Nevergrad。 然后，我可以使用其中任何一种`use_virtualenv("r-reticulate", required = TRUE)`，`use_condaenv("r-reticulate")`但似乎都不能使用 Nevergrad。
> 
> 在这一点上，我相信在我所做的所有测试之间存在一些问题。

yes, if you use "pip install nevergrad",it will tell you nevergrad has been install，but it‘s installed in python,You must to make the R version satisfy M1, and the python version 【3.8/3.9】satisfy r, when you use "version" command in rstudio, you will find R version 4.1.2 and arch is aarch 64, may be you can also use "conda env list" in terminal  at rstudio to find  if you have use "r-reticulate" env【find environment location】; the env of mine is following pictures:  and If you still have problems，Maybe the network is not good and your download fails。
<img width="830" alt="wecom-temp-2acd600fa72de62bf9b650a5a609112e" src="https://user-images.githubusercontent.com/38876426/154877905-c46cdef6-566c-468a-8512-7246c194870e.png">

<img width="881" alt="wecom-temp-fea151d1fe04285d19a3814dc65c8d77" src="https://user-images.githubusercontent.com/38876426/154877894-701ae2bc-cd46-4f88-97e1-f49ac2a788c4.png">
<img width="637" alt="wecom-temp-4f2463eb5bf4f1038f77023f19eaa176" src="https://user-images.githubusercontent.com/38876426/154877947-5f1fead2-d473-4f7a-a4c4-18dc6641a08a.png">

**Comment by Tsurty** [comment]
Hello guys!

It's with great pleasure that I'd like to share with you that I managed to run Robyn on M1 Mackbook for the very first time today.

I did two things specifically and I'm not sure which one made the trick but I believe it's this one.
First of all restart R session and clean variable to have a fresh start.

Then do:
`reticulate::install_miniconda()`

Once it's installed, make sure you have the latest Robyn's version and when prompted update all depencies:
`remotes::install_github("facebookexperimental/Robyn/R")`

Restart R session again and proceed to import and create a new env and install Nevergrad:
```
library(reticulate)
virtualenv_create("r-reticulate-cassandra")
use_virtualenv("r-reticulate-cassandra", required = TRUE)
py_install("nevergrad", pip = TRUE)
```

At this point it went smoothly and surprisingly I don't see Nevergrad in my py_config (see below)
![Schermata 2022-04-05 alle 16 22 58](https://user-images.githubusercontent.com/43139944/161777340-85f9f51b-8857-428c-885c-d0bcca8d21c0.png)

Then I executed the latest demo.R file and it just worked smoothly running everything in < 5mins 

In case this won't work for you, the only other thing that I did in the meantime was a bunch of installations which were not related to Robyn but may have had a positive impact on it maybe so I'll just leave them down here:
```
##1 install devtools and ausgynth and GeoLift
install.packages("devtools", repos='http://cran.us.r-project.org')
devtools::install_github("ebenmichael/augsynth")
devtools::install_github("facebookincubator/GeoLift")

#1.2. install other packages
install.packages(c("tidyverse", "ggplot2", "plotly", "readr","lubridate", "googlesheets4", "knitr", "gsynth","dplyr","doParallel", "MarketMatching"))
```

**Comment by monathiele** [comment]
Hi I had the `"CondaSSLError: OpenSSL appears to be unavailable on this machine"` error all the time but this works real good for me: 

```
library(reticulate)
# create a new environment 
reticulate:::rm_all_reticulate_state() #fixed SSL issue 
conda_create("r-reticulate")
use_condaenv("r-reticulate")
conda_install("r-reticulate", "nevergrad", pip = TRUE)
py_config() 
```
