### ISSUE TITLE
Error running demo.R

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#192]
## Describe issue
running demo.R.   Getting an error in  Step 2a-1.  
Error message is
"Error in robyn_inputs(dt_input = dt_simulated_weekly, dt_holidays = dt_prophet_holidays :  could not find function "robyn_inputs"

## Environment & Robyn version
R version (R --version) 3.6.1

using version 3.0 of robyn
Please make sure you're using the latest Robyn version

**Comment by laresbernardo** [comment]
Hi! You first must install the package, then load it with library(Robyn), and then you won’t have this problem.

**Comment by gufengzhou** [comment]
please reopen if necessary.
