### ISSUE TITLE
Error in RColorBrewer: n too large, allowed maximum for palette BrBG is 11

### ISSUE THREAD

**Issue by joangcc** [facebookexperimental/Robyn#198]
Error found while refreshing model. We were plotting 12 bars on report_decomposition.png, but only 11 bars were finally plotted, both in init-mod and in the bar plot with the refreshed model. Console printed the following error:
```
Warning messages:
1: In RColorBrewer::brewer.pal(n, pal):
n too large, allowed maximum for palette BrBG is 11
Returning the palette you asked for with that many colors
```
This warning message appeared twice. It seems that once for every plot on report_decomposition.png

![error_brewer](https://user-images.githubusercontent.com/92848379/139206939-4ecab272-fb1f-4743-8051-cf35f1f9e97a.png)

Best,

Joan

**Comment by gufengzhou** [comment]
Hi, this should be solved now with this commit https://github.com/facebookexperimental/Robyn/commit/5cb972427b4579de875b0d336ff51c84c403a638. Let me know.

**Comment by gufengzhou** [comment]
please reopen if necessary.
