### ISSUE TITLE
Error in f.plotTrainSize(f)

### ISSUE THREAD

**Issue by victorlee29** [facebookexperimental/Robyn#20]
Hi, 

Great to see there has been a big update. Hopefully the below is a quick fix? :-)

## Issue

There seems to be a bug with the new code.

## Steps to Reproduce

I have just tried to run the set code and example data. No changes were made.

## Expected Behavior

I expected the model to run. 

## Actual Results

Unfortunately I got this error;

Error in f.plotTrainSize(f) : 
  could not find function "f.plotTrainSize"

## Environment

R Studio

Thanks, 

Lee

**Comment by gufengzhou** [comment]
thanks for the heads-up! yes I forgot to include the helper plot functions :) Will fix it right away

**Comment by gufengzhou** [comment]
I've pushed the missing functions. Let me know if it works and thanks again for calling it out!

**Comment by victorlee29** [comment]
Ah, thank you! That's got it working :-)

**Comment by Bolive84** [comment]
Hi @gufengzhou, I am also getting this error: Error in f.plotTrainSize(F) : could not find function "f.plotTrainSize", even after using the last version of the code. Can you please let me know how I can fix this?

**Comment by gufengzhou** [comment]
This is deprecated already. Please check the FB community group for the coming new release on 29/9

**Comment by Bolive84** [comment]
Ok, looking forward to seeing the new version! Thanks @gufengzhou for your quick reply!
