### ISSUE TITLE
Exclude data from a certain time period

### ISSUE THREAD

**Issue by el-wrk** [facebookexperimental/Robyn#201]
## Describe issue
Some of my data for a certain market I know is less correct due to an issue we had collecting it for a month in Dec 2020, is it possible to exclude a given months worth of data from the model in Robyn 3.0?

**Comment by gufengzhou** [comment]
Hi, I'm afraid that currently it can't deal with missing dates properly. Please try to fill in those dates to run Robyn

**Comment by el-wrk** [comment]
No problem, thanks.
