### ISSUE TITLE
Passing additional parameters to Prophet via Robyn

### ISSUE THREAD

**Issue by extrospective** [facebookexperimental/Robyn#202]
## Describe issue
We would like to pass parameters to Prophet, such as changepoint information.

The prophet_decomp() method is documented to take additional parameters for Prophet.
Line 614 reads:
```
#' @param ... Additional prophet parameters
```

And if we use the demo.R code we can modify the second robyn_inputs() to pass additional arguments.

But the challenge I encounter is that the ellipsis arguments are used twice in prophet_decomp: once for the prophet constructor and a second time in fit.prophet.  The second use failed when I tried to pass in what seemed like Prophet args.

Robyn code.  inputs.R around line 630 reads: (note two ellipsis uses)
```
 dt_regressors <- cbind(recurrance, subset(dt_transform, select = c(context_vars, paid_media_vars)))
  modelRecurrance <- prophet(
    holidays = if (use_holiday) holidays[country == prophet_country] else NULL,
    yearly.seasonality = use_season,
    weekly.seasonality = use_weekday,
    daily.seasonality = FALSE,
    ...
  )

  if (!is.null(factor_vars)) {
    dt_ohe <- as.data.table(model.matrix(y ~ ., dt_regressors[, c("y", factor_vars), with = FALSE]))[, -1]
    ohe_names <- names(dt_ohe)
    for (addreg in ohe_names) modelRecurrance <- add_regressor(modelRecurrance, addreg)
    dt_ohe <- cbind(dt_regressors[, !factor_vars, with = FALSE], dt_ohe)
    mod_ohe <- fit.prophet(modelRecurrance, dt_ohe, ...)
```

My code.  So if I pass in arguments such as n.changepoints or changepoint.range:
```
InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters, 
                             # passing through variables to prophet
                             n.changepoints = 1
                             , changepoint.range = 0.1
```

I get an error:
```
Error: passing unknown arguments: n.changepoints, changepoint.range.
```

With backtrace:
```
9: do.call(rstan::optimizing, args)
8: fit.prophet(modelRecurrance, dt_ohe, ...)
7: prophet_decomp(dt_transform, dt_holidays = InputCollect$dt_holidays, 
       prophet_country = InputCollect$prophet_country, prophet_vars = InputCollect$prophet_vars, 
       prophet_signs = InputCollect$prophet_signs, factor_vars = factor_vars, 
       context_vars = InputCollect$context_vars, paid_media_vars = paid_media_vars, 
       intervalType = InputCollect$intervalType, ...)
6: robyn_engineering(InputCollect = InputCollect, ...)
5: robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters, 
       n.changepoints = 1, changepoint.range = 0.1) at adapted_demo_script_VP_template.R#332
```

Here we can see that the prophet constructor appears to have handled these arguments, but not fit.prophet.

* Is this an intended way to pass arguments through to Prophet?
* Am I not using the correct form of these arguments, or did I consult the wrong list of possible arguments?

## Environment & Robyn version
R version (R --version): 4.1.0
Robyn version: 3.3.1

**Comment by gufengzhou** [comment]
Please try it out and let me know. Just fixed it and it appears to run / not showing the "unknown arguments" error anymore

**Comment by gufengzhou** [comment]
can you confirm if this is working now?

**Comment by extrospective** [comment]
Fairly confident we have been using this regularly since the fix.

For example, our code can now look like:
```
InputCollect <- robyn_inputs(InputCollect = InputCollect, 
                             hyperparameters = hyperparameters, 
                             changepoint_range = 0.9433,
                             yearly_seasonality = 20,
                             changepoint_prior_scale = 0.10,
                             seasonality_mode = 'multiplicative'
                             )
```

and i think that was not working for us before.
