### ISSUE TITLE
`calibrate_mmm` scaling decomposition does not take into account `InputCollect$dayInterval`

### ISSUE THREAD

**Issue by sallyhong** [facebookexperimental/Robyn#206]
## Project Robyn

Reference: `model.R` file, `calibrate_mmm` function

```
      ## scale decomp
      mmmDays <- nrow(liftPeriodVec) * 7
      liftDays <- as.integer(liftEnd - liftStart + 1)
      y_hatLift <- sum(unlist(getDecompVec[, -1])) # total pred sales
      x_decompLift <- sum(liftPeriodVec[, 2])
      x_decompLiftScaled <- x_decompLift / mmmDays * liftDays
      y_scaledLift <- liftPeriodVecDependent[, sum(y)] / mmmDays * liftDays
```

## Describe issue

- Currently, this portion scales the x and y lift because the demo input is at a weekly grain (the ` * 7 `) 
- However, if the input is on a daily grain, then it should be ` * 1 `
- Hence, instead of hard-coding I think it would be best to use `InputCollect$dayInterval` as a parameter. 

## Misc

- Side note, the variable `y_hatLift` is never used

**Comment by gufengzhou** [comment]
Hey Sally, you're totally right bout this one. Just fixed it here. Thanks for spotting it! https://github.com/facebookexperimental/Robyn/commit/63bf762e5019f00c33cd050a83e9d2c1e22a2483

**Comment by sallyhong** [comment]
Thanks for the quick fix! 😃
