### ISSUE TITLE
Interaction and hierarchy of channels across the funnel

### ISSUE THREAD

**Issue by joangcc** [facebookexperimental/Robyn#208]
Hi,
My team and I have questions on the interaction and hierarchy of channels in marketing funnel. Specifically:
1) We are interested in knowing if there is a way in Robyn to set a certain priority or sequence when assigning coefficients. That is, as in a marketing funnel we would expect the costumer to travel along several channels such as: a tv advertisement led a client to search for us in Google (paid search) ending up in using a discount. How does the model algorithm give due credit to upper funnel channels, avoiding lower funnel channels to assume higher values?
2) Is it feasible to extract channel interaction through the outputs already available in Robyn? For example, spend in TV led to an increase in paid search due to increasing the traffic of an "x" %.

We see that currently variables are being divided among organic or paid, but we haven't found an option to indicate Robyn where they fall on the funnel.

Thanks,

Joan

**Comment by gufengzhou** [comment]
Good questions!

1) Robyn is a multivariate regression at its core. All indep.vars are treated equally, no matter how you would position each indep.var along the conversion funnel, no matter if they are paid or organic variables, or in your words, no matter how customer travels from one to another channel. However, you can build so-called nested models to capture the funnel logic. Assuming we have TV, OOH & search. First, you can use TV & OOH to predict search as a lower model and gain TV & OOH's contribution to search. Then use all to predict sales as upper model and get each contribution to sales. This way, you can artificially redistribute search's partial effect back to TV & OOH.

2) Robyn is an additive model and thus has no interaction terms --> there's no term as TV x search. One reason is that multiplicative model is significantly harder to decompose.

**Comment by joangcc** [comment]
Hi,

Thanks for your quick answer! We will think about your comments and how to best adapt them to our situation.

Best,

Joan
