### ISSUE TITLE
py_call_impl Error

### ISSUE THREAD

**Issue by cervuspc** [facebookexperimental/Robyn#211]
Hi guys, I tried to run the demo project.
No errors in reticulate and nevergrad installation, but when I run the Step 3 and the first trial is going to start...I receive the following error:
"Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'lower'"

Thanks in advance

**Comment by gufengzhou** [comment]
I've seen this error before that's related to older Nevergrad version. Can you reinstall nevergrad and retry?

**Comment by cervuspc** [comment]
Hi, thank you for your replay. I have updated all the packages but the problem still remains.
nevergrad --> 0.4.3.post8
python --> 3.8.12
let me know.
thanks

**Comment by gufengzhou** [comment]
It's tricky because I can't reproduce your issue. I found this issue that's related to reticulate version.  https://github.com/rstudio/reticulate/issues/831. I have reticulate_1.22. Which one are you using?

**Comment by cervuspc** [comment]
I'm using reticulate 1.22 as well but I have always the same error :(
![image](https://user-images.githubusercontent.com/62520802/140968184-b41ca9c6-6e73-4493-a72d-2c8ffef46fea.png)

**Comment by gufengzhou** [comment]
Hm this is really strange. The "lower" argument is when setting up nevergrad's hyperparameter bounds in ng$p$Array(shape = my_tuple, lower = 0., upper = 1.), a new argument introduced in nevergrad --> 0.4.3.post8. I would assume it's still because of Nevergrad installation issue. A dumb idea is to remove and reinstall python etc again, as specified in the last comment in [this thread](https://github.com/facebookexperimental/Robyn/issues/189). It's really difficult to debug without reproducibility

**Comment by gufengzhou** [comment]
feel free to reopen if necessary

**Comment by wamm0909** [comment]
> I'm using reticulate 1.22 as well but I have always the same error :( ![image](https://user-images.githubusercontent.com/62520802/140968184-b41ca9c6-6e73-4493-a72d-2c8ffef46fea.png)

hi, i have the same error, how did you finally solve it? thanks

**Comment by mirianatrecc** [comment]
I've got the same error. There are some news about it? Thanks

**Comment by lulu-yang-gao** [comment]
I have run the model in a good way for the first 2 trials,  one with the demo and one with my own data, while i have encounter the same issue with py_call_impl, unexpected arguement 'lower', I have tried remotes::install_github("rstudio/reticulate"), but it doesn't work, seems I need to reinstall from the very beginning.

**Comment by miaox018** [comment]
I've got same issue, anyone has a final solution? @gufengzhou 
This is my py_config() returns:
python:         C:/Users/xxxx/anaconda3/envs/r-reticulate/python.exe
libpython:      C:/Users/xxxx/anaconda3/envs/r-reticulate/python39.dll
pythonhome:     C:/Users/xxxx/anaconda3/envs/r-reticulate
version:        3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:53:15) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/xxxx/anaconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.22.3

python versions found: 
 C:/Users/xxxx/anaconda3/envs/r-reticulate/python.exe
 C:/Users/xxxx/AppData/Local/Programs/Python/Python38/python.exe
 C:/Users/xxxx/anaconda3/python.exe

**Comment by lulu-yang-gao** [comment]
> I've got same issue, anyone has a final solution? @gufengzhou This is my py_config() returns: python: C:/Users/xxxx/anaconda3/envs/r-reticulate/python.exe libpython: C:/Users/xxxx/anaconda3/envs/r-reticulate/python39.dll pythonhome: C:/Users/xxxx/anaconda3/envs/r-reticulate version: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:53:15) [MSC v.1916 64 bit (AMD64)] Architecture: 64bit numpy: C:/Users/xxxx/anaconda3/envs/r-reticulate/Lib/site-packages/numpy numpy_version: 1.22.3
> 
> python versions found: C:/Users/xxxx/anaconda3/envs/r-reticulate/python.exe C:/Users/xxxx/AppData/Local/Programs/Python/Python38/python.exe C:/Users/xxxx/anaconda3/python.exe
> 
> and py_module_available("nevergrad") returns TRUE

Hi, what’s your version of Robyn then? My version of Robyn was 3.5.x previously, and currently the latest version is 3.6.3. I thought it might be the Robyn version issue to pop the error warning, so I tried to remove previous Robyn and reinstall, then I found the my rlang should also be updated to 1.0.2. After rlang to 1.0.2, Robyn to 3.6.3, and I also remove packages reticulate and get it reinstalled, now, Robyn works.

**Comment by RanM23** [comment]
@laresbernardo I think i've being using the latest version of Robyn and reticulate. Nevergrad also seems to be successfully installed. However i still have this issue as i reported here #691. Any suggestions? Thank you.
