### ISSUE TITLE
Robyn_refresh failng to run

### ISSUE THREAD

**Issue by tjscarr** [facebookexperimental/Robyn#213]
## Describe issue
When running robyn_refresh I encounter the below error message.
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/5365409/141107774-d1da64b2-0af0-4fdd-aacb-3feabf9ad100.png">
InputCollect should exist as it comes from the robyn object being refreshed.

## Environment & Robyn version
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "4"

$minor
[1] "1.0"

$year
[1] "2021"

$month
[1] "05"

$day
[1] "18"

$`svn rev`
[1] "80317"

$language
[1] "R"

$version.string
[1] "R version 4.1.0 (2021-05-18)"

$nickname
[1] "Camp Pontanezen"

**Comment by tjscarr** [comment]
Bit of additional info. I can run in Rstudio and receive the below warning:

  [ONE-TIME WARNING] Forked processing ('multicore') is not supported when running R from RStudio because it is considered unstable. For more details, how to control forked processing or not, and how to silence this warning in future R sessions, see ?parallelly::supportsMulticore

**Comment by gufengzhou** [comment]
Hey, have you run these two lines? 
`Sys.setenv(R_FUTURE_FORK_ENABLE="true")`
`options(future.fork.enable = TRUE)`

**Comment by tjscarr** [comment]
That appears to have resolved the issue, thank you very much

**Comment by andrey-legayev** [comment]
It was fixed in 5b69457f0af12dee176fe676e6e0c78447dbf7d3
