### ISSUE TITLE
Make plot_folder_sub configurable in robyn_run()

### ISSUE THREAD

**Issue by andrey-legayev** [facebookexperimental/Robyn#215]
## Describe issue
There is a reference to variable ```plot_folder_sub``` inside ```robyn_run()```, but there is no ability to set the value of it.
It would be nice to have ability to configure it in calling code to save plots and CSVs to required place.
This feature is needed in case of automated runs of Robyn MMM.

The value to ```prot_folder_sub``` can be provided via arguments of ```robyn_run()``` --> [model.R#L44](https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R#L44)

I've fixed it in our fork as shown here: 93aa65a55d43a9c1aee3c58f66d100698555bfb0, but this is draft version, it requires refactoring.

## Environment & Robyn version
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by gufengzhou** [comment]
hey I've just added this. let me know if it works as expected. 5b69457f0af12dee176fe676e6e0c78447dbf7d3

**Comment by andrey-legayev** [comment]
Looks good, thank you!
