### ISSUE TITLE
Unble to install Robyn on AWS SageMaker Notebook

### ISSUE THREAD

**Issue by mediascale** [facebookexperimental/Robyn#216]
## Describe issue
Unble to install Robyn on AWS SageMaker Notebook

## Provide dummy data & model configuration

Execuated the following code on SageMaker Notebook:
`install.packages("remotes")`
`remotes::install_github("facebookexperimental/Robyn/R")`

When installing Robyn, receiving the following :

<img width="966" alt="Screenshot 2021-11-12 at 11 20 59" src="https://user-images.githubusercontent.com/52413090/141451314-281df345-241d-443d-bbed-b3c73370095d.png">

## Environment & Robyn version
R version (R --version)
R version 4.1.1 (2021-08-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2018.03
 
Please advise if something that I need to do from my end in order to install Robyn on SageMaker Notebook.

**Comment by gufengzhou** [comment]
Can you try installing the three packages separately and then robyn?

**Comment by mediascale** [comment]
Thanks for your quick response @gufengzhou . I tried to install those 3 packages individually , but I got the same error.

<img width="821" alt="Screenshot 2021-11-12 at 11 46 24" src="https://user-images.githubusercontent.com/52413090/141454747-f62711c2-b311-4cb9-91d3-6da331deb568.png">

**Comment by gufengzhou** [comment]
It definitely looks like a dependency issue. Can you load the other 3 libraries separately? If not, try installing a earlier version than the latest one of the 3 packages and see if it works.

**Comment by tgtod002** [comment]
Hi,

I too am having problems installing Robyn  ( I was successful before)  ..  
Project is in a Dell Laptop: RStudio in Anaconda
Below is the error I am getting when I run remotes::install_github("facebookexperimental/Robyn/R")
<img width="517" alt="error-remoteinstallgithub" src="https://user-images.githubusercontent.com/69650410/141841861-498f66ae-2d99-493d-bc6c-a8b0eff2cd44.png">

**Comment by gufengzhou** [comment]
> Hi,
> 
> I too am having problems installing Robyn ( I was successful before) .. Project is in a Dell Laptop: RStudio in Anaconda Below is the error I am getting when I run remotes::install_github("facebookexperimental/Robyn/R") <img alt="error-remoteinstallgithub" width="517" src="https://user-images.githubusercontent.com/69650410/141841861-498f66ae-2d99-493d-bc6c-a8b0eff2cd44.png">

What is your "remotes" version? if <2.2.0, can you update and retry?

**Comment by tgtod002** [comment]
Thanks gufeng.  That worked.  Not I am getting another error.  See error below:
<img width="638" alt="error-remoteinstallgithub-2" src="https://user-images.githubusercontent.com/69650410/141860354-4df4e7e9-4adb-4e01-bea4-4a07ffb2993a.png">

**Comment by tgtod002** [comment]
Was able to fix it by manually installing rtools package.
