### ISSUE TITLE
Error in f.budgetAllocator(modID = "3_14_4", scenario = "max_historical_response",  : 

### ISSUE THREAD

**Issue by victorlee29** [facebookexperimental/Robyn#22]
Hi again :-)

## Issue

I have tested Robyn with one my own client's data (admittedly it's lacking important variables). Robyn completes the 40 trials no problem, but then struggles with the 

## Steps to Reproduce

Same setup as Github code, just with my own data (columns for fb spend and imp, search spend and clicks, and content spend, as well as a variable column for the Covid infection rate in Norway, which I had to hand).

## Expected Behavior

I expected the budget optimiser to push out some slides.

## Actual Results

I got the below: 

Running budget allocator for model ID 3_14_4 ...
Error in f.budgetAllocator(modID = "3_14_4", scenario = "max_historical_response",  : 
  channel_constr_low & channel_constr_up have to contain either only 1 value or have same length as set_mediaVarName

## Environment

R Studio

Thanks again,

lee

**Comment by gufengzhou** [comment]
You will have to input your own Model ID to get the reallocated result for that model ;) when you look at the result one-pagers, you'll see a ID in the title. Input that into the allocator.

**Comment by gufengzhou** [comment]
Would you mind sharing a bit insight of if one or some the model results and the reallocation make sense? That would be really helpful:)

**Comment by gufengzhou** [comment]
Ah, regarding Lower and upper bounds for the allocator, it needs to be exact the same order as your media variables defined. 
In the sample Code, I put 5 channels. So the lower and upper bounds both have 5 values.

**Comment by victorlee29** [comment]
Hi, I double checked and I was using a model ID from my own data's iterations, and the lower/upper bounds were in the exact same order, so I'm a bit unsure what's going wrong? I am happy to share anything with you's btw (though with this test the data is not complete, and I need some better baseline variables...) :-) All help is appreciated, and I am currently in convo with FB's marketing science team too, in Sweden, regarding getting some support with testing this on a client, and with a plan to push towards some case studies (MMM is not prevalent in Norway and VERY expensive... so Robyn, and it's automation, could be a big deal, especially for agencies without employees specialised in the subject)

**Comment by gufengzhou** [comment]
Could you provide more info on your error? Screenshots of your budget allocator and set_mediaVarName would be great

**Comment by victorlee29** [comment]
<img width="1754" alt="Screenshot 2021-03-05 at 09 25 18" src="https://user-images.githubusercontent.com/72621182/110088197-d3625200-7d94-11eb-94d7-26251129ba71.png">
<img width="1049" alt="Screenshot 2021-03-05 at 09 25 28" src="https://user-images.githubusercontent.com/72621182/110088202-d65d4280-7d94-11eb-8614-e1a1b33dc5a6.png">
<img width="1036" alt="Screenshot 2021-03-05 at 09 25 44" src="https://user-images.githubusercontent.com/72621182/110088207-d6f5d900-7d94-11eb-8c9a-56105269b6b1.png">
<img width="1772" alt="Screenshot 2021-03-05 at 10 14 44" src="https://user-images.githubusercontent.com/72621182/110094032-a5344080-7d9b-11eb-9f36-50ab0f539c77.png">

**Comment by victorlee29** [comment]
Hopefully that helps? :-)

**Comment by gufengzhou** [comment]
Yes, you only have 3 media channels. So you should only need 3 numbers as lower bounds and 3 numbers as upper bounds for the allocator. You're using the default, which has 5 values each. Read the comments behind the function also helps with how to set the bounds

**Comment by victorlee29** [comment]
Oh I am blind. Thanks for confirming. So I just removed two values then, and then I got the below:

Error in f.budgetAllocator(modID = "34_79_5", scenario = "max_historical_response",  : 
  provided modID is not within the best results

I was also wondering if the model one pagers (aka, 40 different PNGS for each iteration) have an order of relevance? Aka, most of the r ratings are basically the same (and mape_lift always equals N/A), but the results can vary massively. With the various models, does Robyn know which one it feels fits best?

Thanks again

<img width="1771" alt="Screenshot 2021-03-05 at 10 35 10" src="https://user-images.githubusercontent.com/72621182/110096744-8a170000-7d9e-11eb-8aa4-78e2783170a8.png">

**Comment by gufengzhou** [comment]
Please run model_output_collect$allSolutions, or look at the Model IDs in the onepager title, to get correct IDs

**Comment by gufengzhou** [comment]
regarding "which one it feels fits best?": all printed results are Pareto-optimal solutions with trade-offs between the two optimisation objective functions: NRMSE (model error) and DECOMP.RSSD (business logic). According to Wikipedia, pareto-optimal means "no individual can be better off without making at least one individual worse off". In other words, all printed solutions can't be better trading off the two objectives. On the other hand, we're also returning a set results instead of just "the best one" on purpose, so that users can relate their business reality to different model outcomes and select the most suitable one. We don't make that choice for you.

**Comment by gufengzhou** [comment]
there's been couple of fixes pushed. please try out the latest version and let us know if everything works.
