### ISSUE TITLE
Errors Understanding: "Bad Loss Warning"/'Invalid value in double scalers"

### ISSUE THREAD

**Issue by RaviP1987** [facebookexperimental/Robyn#221]
Hi FB Team

Request your help in understanding the below errors. I have tried multiple datasets, but i keep getting the below errors. Kindly advise what is likely the root cause here and how i can solve ? Thank you so much

 C:\Users\......\nevergrad\optimization\base.py:399: BadLossWarning: Updating fitness with inf value warnings.warn(f"Updating fitness with {loss} value", errors.BadLossWarning)
C:\Users\....\nevergrad\optimization\multiobjective\hypervolume.py:219: RuntimeWarning: invalid value encountered in double_scalars hypervolume += h * last_node.coordinates[dimension]
C:\Users\....\nevergrad\optimization\base.py:399: BadLossWarning: Updating fitness with nan value
  warnings.warn(f"Updating fitness with {loss} value", errors.BadLossWarning)
C:\Users\....\nevergrad\optimization\multiobjective\hypervolume.py:216: RuntimeWarning: invalid value encountered in double_scalars hypervolume += h * (node.coordinates[dimension] - next_node.coordinates[dimension])

**Comment by gufengzhou** [comment]
Hey, can Robyn run despite of the warnings? If yes, the good news is that usually this warning appears often at the first iterations and goes away as Nevergrad optimises and the loss scores get better. The bad news is that your model is probably suffering from bad fit in general, indicating that you might want to reassess your dataset and consider adding extra independent variables. 
You can also see where the warning is defined [here](https://github.com/facebookresearch/nevergrad/blob/main/nevergrad/optimization/base.py#L405) in Nevergrad: when the loss score is NA or infinite large.

**Comment by gufengzhou** [comment]
feel free to reopen if necessary
