### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by irafikh** [facebookexperimental/Robyn#223]
## Describe issue
Unfortunately it takes time to resolve environment problems on Windows.

Exists already stable Docker image to play with Robyn ?

Thanks!

**Comment by gufengzhou** [comment]
Hi, thanks for reaching out. We'll work on this in Q1 2022. for now there's lack of capacity unfortunately. Meanwhile, you can check this issue for solutions for windows https://github.com/facebookexperimental/Robyn/issues/189

**Comment by gufengzhou** [comment]
please see the other thread about docker image https://github.com/facebookexperimental/Robyn/issues/173

**Comment by Leonelsentana** [comment]
https://hub.docker.com/layers/leosentana/robyn/v3.6.4/images/sha256:43dd6a8995071b64b0960785d50a60046eff6c39c3c30c84884f9d1c02db92ea updated image
