### ISSUE TITLE
Share of spend vs effect plot issue 

### ISSUE THREAD

**Issue by amysheep** [facebookexperimental/Robyn#228]
I noticed when certain channel had zero effect share (ooh here), the cpa_total dots were not representing the CPA values. They all seem to be at x = 0.   

![image](https://user-images.githubusercontent.com/8550146/144174111-d5114f68-0f58-4b76-8f98-3b56ea00149f.png)

## Environment & Robyn version
R version (R --4.0.3)
Please make sure you're using the latest Robyn version - yes i am using the latest Robyn 3.0

**Comment by gufengzhou** [comment]
Hi thanks for raising this. The latest commit should've fixed this. Please check 8539e02

**Comment by gufengzhou** [comment]
feel free to reopen if necessary
