### ISSUE TITLE
issue while running robyn via python using the example.py file

### ISSUE THREAD

**Issue by mehar31** [facebookexperimental/Robyn#229]
I am trying to run robyn using python via this script but it gives an import error as I try to run it. Can someone please address this

  File "example.py", line 9, in <module>
    from python.robyn_v02 import robyn as r
ModuleNotFoundError: No module named 'python'

**Comment by gufengzhou** [comment]
i'm not sure which example.py file your referring to. can you be more specific?

**Comment by gufengzhou** [comment]
it appears that the .py work-in-progress scripts are uploaded unintentionally by our team. it's taken down already.
