### ISSUE TITLE
Error when running initial model build

### ISSUE THREAD

**Issue by tsarax** [facebookexperimental/Robyn#230]
Last time I was using Robyn was a couple months ago so I was running on an older version. I went to try building a new model with additional data and tried updating what version I was using as well. I've never had an issues with the model building before but I am now receiving an error anytime I run the following code: 

```

OutputCollect <- robyn_run(InputCollect = InputCollect 
                           , plot_folder = robyn_object 
                           , pareto_fronts = 1 
                           , plot_pareto = T)
```

Error:

```
>>> Collecting results...

Error in quantile.default(resultHypParam$mape, probs = calibration_constraint): missing values and NaN's not allowed if 'na.rm' is FALSE
Traceback:

1. robyn_run(InputCollect = InputCollect, plot_folder = robyn_object, 
 .     pareto_fronts = 1, plot_pareto = T)
2. quantile(resultHypParam$mape, probs = calibration_constraint)
3. quantile.default(resultHypParam$mape, probs = calibration_constraint)
4. stop("missing values and NaN's not allowed if 'na.rm' is FALSE")
```

I have no nulls or missing values in my input dataframe. I'm running this in an R Jupyter Notebook on GCP. My Robyn package is version 3.4.6

Any guidance would be appreciated! Thank you!

**Comment by laresbernardo** [comment]
Thanks for reporting this issue. With your example I can't replicate the issue but should be fixed by now. Please, update with `remotes::install_github('facebookexperimental/Robyn/R')`, reset your R session and retry. Let us know how it goes and feel free to close this issue in case it's fixed.

**Comment by tsarax** [comment]
hm, I'm now getting this:

```
>>> Collecting results...

Error in RNGseq(n, seed, ..., version = if (checkRNGversion("1.4") >= : NMF::createStream - invalid value for 'n' [positive value expected]
Traceback:

1. robyn_run(InputCollect = InputCollect, plot_folder = robyn_object, 
 .     pareto_fronts = 1, plot_pareto = T)
2. foreach(respN = seq_along(decompSpendDistPar$rn), .combine = rbind) %dorng% 
 .     {
 .         get_resp <- robyn_response(paid_media_var = decompSpendDistPar$rn[respN], 
 .             select_model = decompSpendDistPar[respN, solID], 
 .             spend = decompSpendDistPar[respN, mean_spend], dt_hyppar = resultHypParamPar, 
 .             dt_coef = xDecompAggPar, InputCollect = InputCollect)
 .         dt_resp <- data.table(mean_response = get_resp, rn = decompSpendDistPar$rn[respN], 
 .             solID = decompSpendDistPar$solID[respN])
 .         return(dt_resp)
 .     }
3. do.call("doRNGseq", c(list(n = N_elem, verbose = obj$verbose), 
 .     rngSeed))
4. doRNGseq(n = 0L, verbose = FALSE)
5. RNGseq(n, seed, ..., version = if (checkRNGversion("1.4") >= 
 .     0) 2 else 1, simplify = FALSE)
6. stop("NMF::createStream - invalid value for 'n' [positive value expected]")
```

**Comment by gufengzhou** [comment]
Hi, reading the error message, it seems like N_elem = 0 is causing the problem. Running `doRNG:::doRNGseq(0)` returns the same error. How many iterations are you using? Are you calibrating the model?

**Comment by tsarax** [comment]
@gufengzhou I'm running 10 trials, 2000 iterations. I am calibrating the model with 21 calibrations. My data is daily and running the model for Jan 1, 2020 until july 1, 2021. 

Let me know if I should get you an anonymized version. I'm doing this on the side of some other work so getting an anonymized version might take me a bit.

**Comment by gufengzhou** [comment]
Yes, your dataset and your demo.R script are needed if I should debug. The easiest way is just rename the vars as var1, var2 etc. But of course you should do whatever is necessary to protect sensitive information. feel free to send it over to gufeng@fb.com

**Comment by tsarax** [comment]
Ok, I'll try to get it over to you sometime tomorrow! Thanks!
