### ISSUE TITLE
Scale input data for Robyn

### ISSUE THREAD

**Issue by PetricaR** [facebookexperimental/Robyn#239]
## Project Robyn

I have a question related to the input data need to run Robyn properly. Can we use raw data (no scaling ) or we have to scale the input data (similar with scikit-learn standard scaler)?

Thank you!

**Comment by gufengzhou** [comment]
Hi, input data is raw, like raw media spend, raw impressions etc. Robyn takes over all scaling.

**Comment by PetricaR** [comment]
**Thank you !**
