### ISSUE TITLE
robyn.py - potentially incorrect line of code overwrites variable

### ISSUE THREAD

**Issue by extrospective** [facebookexperimental/Robyn#240]
## Describe issue
robyn.py has line of code which looks wrong on inspection.
Have not attempted to run or evaluate this code -- so it is entirely possible this is not an issue.

Examine last line of this section around line 538 in robyn.py:
```
            # python implementation of scale() is different from R, may need to hard-code the R equivalent
            if use_trend:
                fc_trend = forecastRecurrance['trend'][:recurrence.shape[0]]
                fc_trend = preprocessing.scale(fc_trend)
                dt_transform['trend'] = fc_trend
            if use_season:
                fc_season = forecastRecurrance['yearly'][:recurrence.shape[0]]
                fc_season = preprocessing.scale(fc_season)
                dt_transform['seasonal'] = fc_season
            if use_weekday:
                fc_weekday = forecastRecurrance['weekly'][:recurrence.shape[0]]
                fc_weekday = preprocessing.scale(fc_weekday)
                dt_transform['weekday'] = fc_weekday
            if use_holiday:
                fc_holiday = forecastRecurrance['holidays'][:recurrence.shape[0]]
                fc_holiday = preprocessing.scale(fc_holiday)
                dt_transform['trend'] = fc_holiday
```

The line:
```
dt_transform['trend'] = fc_holiday
```
seems to overwrite the "trend" entry a few lines above.  The inconsistency in parallel code stood out.  I imagine that the intended dt_transform index might be "holiday".  As it stands now, if use_trend and use_holiday are both true, then only one variable will survive.

This observation is simply from code inspection.  I hope this proves helpful.

(Given the number of strings here, I wonder if there is an opportunity to streamline by reducing the use of hard-coded strings.)

**Comment by gufengzhou** [comment]
Hi, if you're referring to the fix branch, it's work in progress so no need to raise issues there

**Comment by extrospective** [comment]
I was referencing the code I read here at github, not having selected any branch.

**Comment by gufengzhou** [comment]
Ah just saw that. Not sure why a draft version is there. Please ignore it and we'll remove it. R is the only working version at the moment

**Comment by gufengzhou** [comment]
please feel free to reopen if necessary
