### ISSUE TITLE
remotes::install_github('facebookexperimental/Robyn/R') error: 

### ISSUE THREAD

**Issue by dcaud** [facebookexperimental/Robyn#241]
Failed to install on rstudio linux machine with:

`remotes::install_github('facebookexperimental/Robyn/R')`

> Installing package into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> * installing *source* package ‘Robyn’ ...
> ** using staged installation
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** byte-compile and prepare package for lazy loading
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
>   libglpk.so.40: cannot open shared object file: No such file or directory
> Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
> Execution halted
> ERROR: lazy loading failed for package ‘Robyn’
> * removing ‘/usr/local/lib/R/site-library/Robyn’
> Warning message:
> In i.p(...) :
>   installation of package ‘/tmp/RtmpL3JBxr/file13365bee9af/Robyn_3.4.8.tar.gz’ had non-zero exit status

## R version

> > version
>                _                           
> platform       x86_64-pc-linux-gnu         
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          4                           
> minor          1.2                         
> year           2021                        
> month          11                          
> day            01                          
> svn rev        81115                       
> language       R                           
> version.string R version 4.1.2 (2021-11-01)
> nickname       Bird Hippie

**Comment by gufengzhou** [comment]
Hey, We haven't seen this before. I'm not sure if this is caused by our package. Have you checked this thread? https://stackoverflow.com/questions/38943764/r-error-in-dyn-loadfile-dllpath-dllpath

**Comment by gufengzhou** [comment]
please reopen if necessary
