### ISSUE TITLE
Possible to run some variable with weibull CDF and some with PDF

### ISSUE THREAD

**Issue by RaviP1987** [facebookexperimental/Robyn#244]
Hi Gufeng, FB team,

In my model,  i have some variables which fit Weibull CDF better and some variables which fit weibull pdf better (per my business understanding).

May i check if there is a way (by changing hyper-parameters), I can use weibull cdf and pdf in the same model ?

Thank you

**Comment by gufengzhou** [comment]
Hey, sofar this is not possible because of the extra level of complexity when transforming back and forth. PDF is the most flexible option of the 3, you can consider use it for all

**Comment by gufengzhou** [comment]
feel free to reopen if further questions come up
