### ISSUE TITLE
organic vars are not among prophet regressors (reopened ticket)

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#245]
Hello Robyn team!

Any reasons for not including organic variables as prophet regressors? 

Thanks, 
slavakx

**Comment by slavakx** [comment]
Follow-up question. Are you using spend features as regressors or only factor variables?

**Comment by gufengzhou** [comment]
Hey, we actually don't use add regressors in prophet. We extract trend & season etc as is. Except when it's a factor, which is rather a practical solution to convert factor into continuous

**Comment by slavakx** [comment]
Thanks!

**Comment by slavakx** [comment]
Hi

I reopened this ticket because I figured out that now media spends are indeed used for season/trend decomposition. I probably missed the discussion about why you changed your approach.
