### ISSUE TITLE
Error:   Dimensions exceed 50 inches (height and width are specified in 'in' not pixels).

### ISSUE THREAD

**Issue by lmcayo** [facebookexperimental/Robyn#247]
Hi Gufeng, FB Team

I'm running a model with a lot of paid variables (more than 20) and I'm getting this error:

**Error:   Dimensions exceed 50 inches (height and width are specified in 'in' not pixels).
  If you're sure you want a plot that big, use `limitsize = FALSE`.**

From the message, I understand that Robyn is not able to plot the different model onepagers because of the number of variables but since it shows me that error, Robyn does not generate the csv outputs either.

Is there any workaround to avoid the plotting error and get the csv output? 

I tried running the model in RStudio 1.3.1073 (R 3.6.1/Robyn 3.4.7 Windows  and R 4.1.2/Robyn 3.4.8 Linux). The demo works perfectly and generated all the plots and csvs so far.

Thank you for all the work,
Lionel

**Comment by gufengzhou** [comment]
hey we're seeing this for the first time. you can set `plot_pareto = FALSE` in the robyn_run function to disable the onepagers. That should solve your problem for now

**Comment by lmcayo** [comment]
Hi Gufeng,

Thanks for your answer. I had set this option to False but it shows me the same error.

This is the full response I got

> rlang::last_error()
<error/rlang_error>
  Dimensions exceed 50 inches (height and width are specified in 'in' not pixels).
  If you're sure you want a plot that big, use `limitsize = FALSE`.
Backtrace:
 1. Robyn::robyn_run(...)
 4. ggplot2::ggsave(...)
 5. ggplot2:::plot_dim(...)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
  Dimensions exceed 50 inches (height and width are specified in 'in' not pixels).
  If you're sure you want a plot that big, use `limitsize = FALSE`.
Backtrace:
    x
 1. \-Robyn::robyn_run(...)
 2.   +-base::suppressMessages(...)
 3.   | \-base::withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
 4.   \-ggplot2::ggsave(...)
 5.     \-ggplot2:::plot_dim(...)

Thanks again for your support.

**Comment by gufengzhou** [comment]
Ok the argument is in ggsave. I'm on holiday from today on. I recommend you to clone the repo first, then open the model.R file under subdir /R/R, search ggsave and add the argument limitsize = TRUE to all ggsave, save the script, restart R session and then run devtools::load_all(). 

This way, you have customised the package. I'll update it when I'm back from PTO

**Comment by gufengzhou** [comment]
this should work now

**Comment by NoamPecan** [comment]
> this should work now

Hi, I just encountered this error using Robyn version Robyn_3.4.12

**Comment by gufengzhou** [comment]
FYI I've pushed another commit to deal with this. https://github.com/facebookexperimental/Robyn/commit/eb0dc8efcf9bac699a42742bb269a43e7c123570
