### ISSUE TITLE
What approach is used to transform categorical into numerical 

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#248]
Hi Robyn Team

When Prophet is applied to categorical variables you transform them into numerical. What approach are you using for this? 

Thanks

**Comment by laresbernardo** [comment]
Hi @slavakx Robyn leverages the time-serie-forecast package Prophet to decompose trend, season, holiday and weekday as model predictor out of the box. This capability often increases model fit and reduces autoregressive pattern in residuals. So it basically adds new features, it doesn't transform nor use categorical variables.

**Comment by slavakx** [comment]
Hi @laresbernardo 

you are right except for one particular case when factor_vars are defined. Internally factor_vars are one-hot encoded / contrast-coded and added as regressors into Prophet. When Prophet is executed some kind of transformation is applied within Robyn code to convert a particular one-hot encoded / contrast coded feature into a numeric representation. This particular conversion is not clear to me. How is it done?

**Comment by laresbernardo** [comment]
Well, you're right about the one hot encoding process for inputing categorical variables into prophet. Check out the code [here](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L616) and [here](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L639). I meant the output from prophet is numerical features and the inputs can be any type (numerical or categorical) and is dealt with OHE.

**Comment by slavakx** [comment]
we are getting closer @laresbernardo  :)

lines [650](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L650) through [654](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L654) is where I have some difficulties

Row-wise summation for each one-hot encoded variable is applied and scaled to the minimum of the sum along with that variable to get the final numerical representation of the factor variable. Is there some literature about this approach?
