### ISSUE TITLE
MMM on media spendings at product category level 

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#249]
Hi Robyn Team

Our client wants a more granular MMM on a daily basis with Media Spendings for different product categories. 
What input would be suitable for Robyn in such a case? 
Something like: TV_category_1, TV_category_2, Radio_category_1 ... ? 
What would you suggest?

Thanks

**Comment by gufengzhou** [comment]
Hi, splitting paid channels is a best practise we advocate for. The split should reflect their business model and/or budget silos. Product category can be meaningful, esp. when media budget is also decided on this level. Take FB as example, we often see client having differntt brand & performance budgets, or prospecting vs retargeting. It's important to think about that whatever split you're using, it'll be the same granularity in the budget allocator. You should ask the question "Does it make sense to allocate budget on this granularity?"
