### ISSUE TITLE
issue with building wheel and installing nevergrad and dependancies

### ISSUE THREAD

**Issue by stefanoallima** [facebookexperimental/Robyn#25]
## Issue

error due to reticulate not finding python version and installing in the proper python version the `bayesian-optimization ` dependency and the `nevergrad`

## Steps to Reproduce

when running the 
```
model_output_collect <- f.robyn(set_hyperBoundLocal
                                ,optimizer_name = set_hyperOptimAlgo
                                ,set_trial = set_trial
                                ,set_cores = set_cores
                                ,plot_folder = paste(script_path,"chart", sep = ''))
```

## Expected Behavior

`import(nevergrad) `
successful with also the `bayesian-optimization ` dependency

## Actual Results

 ```
WARNING: Building wheel for bayesian-optimization failed: [Errno 13] Permission denied: '/Users/stefanoalli/Library/Caches/pip/wheels/14'
Installing collected packages: numpy, threadpoolctl, scipy, joblib, scikit-learn, typing-extensions, cma, bayesian-optimization, nevergrad
    Running setup.py install for bayesian-optimization: started
    Running setup.py install for bayesian-optimization: finished with status 'done'
  DEPRECATION: bayesian-optimization was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

## Environment

R version 4.0.3 (2020-10-10)
Macbook pro

**Comment by gufengzhou** [comment]
great. also on line 45 in the .exec script, I've specified the command to install nevergrad in Rstudio. You need to run it once before using Robyn: conda_install("r-reticulate", "nevergrad", pip=TRUE)

**Comment by stefanoallima** [comment]
yes i run `conda_install("r-reticulate", "nevergrad", pip=TRUE)` but still was throwing errors... it took quite many trials of running the script and investigating to identify the problem that i was experiencing

once i specified the 
use_python command
it accepted nevergrad installation and worked fine
