### ISSUE TITLE
Error: { : task 1 failed - "'probs' outside [0,1]"

### ISSUE THREAD

**Issue by prak-gup** [facebookexperimental/Robyn#251]
## Describe issue
Getting error "{ : task 1 failed - "'probs' outside [0,1]", while running robyn_run() function. 
Getting this error for both types of ad-stocks i.e. geometric and weibull_cdf. 

## Provide dummy data & model configuration
Dummy data and Actual code can be found [(https://tinyurl.com/yufn7r5v)]

## Environment & Robyn version
R version (R --version): R version 4.1.0 (2021-05-18)
Robyn Version: ‘3.4.8’

**Comment by laresbernardo** [comment]
Thanks for reporting @prak-gup 
Now we have implemented underlying check functions that will check that input values from your hyperparameters are all within the permitted bounds and if not return informative errors. Feel free to update to 3.4.9 and test it out. You can also check those limits using the new `hyper_limits()`.
