### ISSUE TITLE
object 'parallel_processing' not found

### ISSUE THREAD

**Issue by tamarDSG** [facebookexperimental/Robyn#252]
## Project Robyn

Hi, 
I'm trying to refresh an existing model. I run the attached code on two different computers. 
The first one has Robyn 3.0.0 and the code runs fine.
When I run the same code on the computer that has Robyn version 3.4.8, it fails.
Below is the error I receive:

Initial model is built on rolling window of ** days:***
 Finished in 0.01 mins
Collecting results...
Error in robyn_run(InputCollect = InputCollect, plot_folder = robyn_object,  : 
  object 'parallel_processing' not found
In addition: Warning message:
In foreach(i = 1:iterPar) %dorng% { :
  Foreach loop (doParallelMC) had changed the current RNG type: RNG was restored to same type, next state
Execution halted

Thanks in advance
[run_robyn_code.R.zip](https://github.com/facebookexperimental/Robyn/files/7776872/run_robyn_code.R.zip)

**Comment by gufengzhou** [comment]
Hi, parallel_processing is a relatively newly added variable. You're somehow missing it. Have you installed the package via install_github() or you just cloned the repo? Shouldn't happen if the version is latest

**Comment by wamm0909** [comment]
> parallel_processing

hi, today i download robyn[3.4.10 lastest] and run demo.r, but it also came error,can you give some advice,thanks 
![93457C869EC79607F9B0986217E27585](https://user-images.githubusercontent.com/38876426/149906963-cd1baca8-1370-443d-8ab7-11da169e0dc4.png)

**Comment by laresbernardo** [comment]
Hi there. Looking at the code, the use of `parallel_processing` is pretty straightforward. Could you please share with me your `.Platform$OS.type` output? Thanks
CC: @wamm0909 + @tamarDSG

**Comment by wamm0909** [comment]
> .Platform$OS.type
.Platform$OS.type : unix
Sorry for taking a long time to reply

**Comment by wamm0909** [comment]
> Hi there. Looking at the code, the use of `parallel_processing` is pretty straightforward. Could you please share with me your `.Platform$OS.type` output? Thanks CC: @wamm0909 + @tamarDSG

.Platform$OS.type : unix
Sorry for taking a long time to reply

**Comment by gufengzhou** [comment]
have you figured it out already? please close ticket if so. thanks!

**Comment by andrewharukihill** [comment]
@laresbernardo I'm getting the same issue. Could you share the fix here?

My .Platform$OS.type is unix as well

**Comment by laresbernardo** [comment]
> @laresbernardo I'm getting the same issue. Could you share the fix here?
> 
> My .Platform$OS.type is unix as well

Can you please check your Robyn's version (`packageVersion("Robyn")`)? If it's not 3.6.1, please update, refresh the session and retry to check if the errors persist.
