### ISSUE TITLE
cv.glmnet cross-validation and time-series data

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#253]
Hi, 
cv.glmnet is not aware of a time-series nature of mmm data. Is it not an issue to use kfold cross validation in this case?

**Comment by gufengzhou** [comment]
Hi, sorry for the late reply. In general, You're right about cv and time series. Two arguments that it's not a big concern in Robyn: 
1, the autoregressive pattern in time series is what's ignored in normal cross validation. Robyn uses prophet trend and season decomposed from the dependent as predictors that fit the autoregressive pattern. We've tested it in multiple datasets that the Durbin Watson score improves significantly when using prophet trend & season. Based on this, autoregressive pattern is also treated in cross validation. 
2, in the future, we'll deprecate glmnet cross validation and integrate lambda selection into hyperparameter optimization. 
Hope it helps.
