### ISSUE TITLE
weibull halflife depends on data length

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#255]
Hi, 

trying to understand how you calculate weibull adstock, I figured out that scaleTrans depends on the time units. So having a fixed scale and shape params, halflife will be different based on time units. Is this a correct behavior?
Example: time units of 20 (halflife ~6.5 weeks) and 100 has a halflife of 18 weeks. 

![image](https://user-images.githubusercontent.com/6716523/147927624-1727ecc7-4fca-45d0-b5fa-d23a48079055.png)

![image](https://user-images.githubusercontent.com/6716523/147927690-4aaa81a6-866b-413b-adda-4c03b345f32e.png)

**Comment by gufengzhou** [comment]
Hi, yes it's expected. Scale is the relative position
