### ISSUE TITLE
Context Variable: Contribution to Target Variable Concerns

### ISSUE THREAD

**Issue by extrospective** [facebookexperimental/Robyn#257]
## Describe issue
We have significant doubts that the interpretation "contribution to target variable" is accurate for non-paid media variables (i.e. context variables)

We have done in depth analysis with our own data sets, and now have created a toy data set (shared here) with the intention to make examining and discussing this issue easier in a non-proprietary context.

We seek to understand whether:
* Robyn correctly calculates contribution to bookings (and if so, why are tests show otherwise), and
* If contribution to bookings for context variables should be presented in key charts (in Robyn) and discussed by Robyn users with their stakeholders

We report below that the paid media variable (only one in our experiments) is accurately measured and our focus is on intepreting non-paid media variables (prophet and context variables) in the target variable waterfall.

## Background
At our company we have been using VAR for MMM, but upon discovering errors in the interpretation of results, and the availability of Robyn, have turned to Robyn for the promise of an accelerated and insightful path forward.  We appreciate the work of the team.

Our stakeholders desire not only ROI for paid media, but also want to know historically which factors drive bookings.  The waterfall charts which Robyn provides seem a promising start on this issue. 

For example, they want to know for last quarter, what % of bookings were driven by each paid media channel, what was driven by discounting, and what was the momentum/inertia in the bookings.  (Think of bookings as revenue; it is a key target variable.)

As with other Robyn users, we sometimes noticed astonishing large values for Trend and Intercept.  As noted on a separate issue https://github.com/facebookexperimental/Robyn/issues/256, we made a modification to our Robyn branch to permit negative intercepts, particularly due to some problems we saw when that constraint persisted with our context variables.  (Below we ran one experiment without allowing negative intercepts, and the problem still occurs.)

## Prophet Variables (Background Reading)

A first learning was that Prophet predictions for all variables except for Trend centered around zero.  That means the weekly, holiday, seasonal variables all typically center on 0 when using a 12 month data set.  

For example, rather than anchoring Sunday at 0, none of the weekdays (categorical variables) will likely be 0; instead we might see negative values for the weekend days, and small positive values for the weekdays, such that over a cycle of 7 days the average is 0.

The same is true for holidays; where the effect of holidays (suppose it is negative and large) is offset by a small positive non-holiday effect so the mean effect is zero.

When Robyn absorbs these variables with mean 0 and then reports on target variable (let's call it bookings) effects in the waterfall, the effect will be nominal (near 0).  This occurs because Prophet's output has removed all biases in individual terms and placed that bias only in the trend variable.  In effect, the trend variable is composed of a Prophet intercept plus a zero-mean trend, but rather than having a separate intercept term Prophet has left it in trend.

Robyn's waterfall sees a non-0 mean for trend, and therefore trend has a significant place on the waterfall.  All other Prophet variables will tend to be zero.

We conclude not to show our stakeholders the waterfall of the individual Prophet variables, because we would just confuse them.  Of course, an analyst could talk about the weekday effect, or seasonal effect, etc., but they would have to select a baseline weekday or season for that conversation.  Our point is that the waterfall produced by Robyn natively is not going to show a useful split across Prophet variables unless it so happens that your Robyn data window is not an even cycle (we use 12 months for the Robyn window to ensure that we have basically cycled the holidays, seasons, and weekdays).  

## Context Variables

I did not read in Robyn documentation about any limitation on the values which could be represented in context variables, so we feel that we have liberty to model as we like.

Here are a few context variables we contemplated:
* Business Confidence Index (BCI): (https://data.oecd.org/leadind/business-confidence-index-bci.htm)
* Average Discount Level for products (0-50% roughly)
* Relative Discount Level for products (today's discount - mean 28 or 56 day discounts; hence varying from about -5% to 50%)

In linear regression models, one normally can model context variables with somewhat arbitrary form:
* The native BCI centers around 100. 
* I could center the BCI at 0 (i.e. subtract the mean from all values)
* The average discount level might center at 10%
* I could center it at 0 (i.e. subtract the mean)
* The relative discount level centers around 0%
* I could center the relative discount level at 100% (i.e. treat 100% as the base and talk about values like 85% or 115%).

Generally re-centerings could involve two operations: a shift and a scale.  (examples above are shifts)

FWIW standarization involves both shift and scale (subtract mean, divide by std err).

How does regression handle this?:
* Scaling, one expects coefficient to change by an inverse amount
* Shifting, one expects the intercept to absorb the shift so the coefficient (slope) remains unchanged.

## Context Variable Challenges with Robyn

Here's what we have found:

With Robyn, when I take a context variable and center it away from 0, it may have a dramatic impact on target variable (bookings) waterfall.  A simple shift could cause the impact to shift from no effect to $1 billion dollars effect.  This occurs because the intercept--[if you allow it, and that depends on the direction you did the context variable shift; in my case I'm shifting to a positive side requiring a negative intercept, to multiply it by -1 you would have a negative and require a positive intercept]--absorbs the offset.  If the intercept is constrained (non-negative for example, as is default in Robyn) it could lead instead to coefficient distortion.

We found good and bad news for context variables:
* Shifting does not change the context variable coefficient.  Again as we reported on [https://github.com/facebookexperimental/Robyn/issues/256]
* Shifting does change the waterfall impact materially.

One observation is about why this shifting topic does not arise with media variables.  My hypothesis is that these variables (whether spend or clicks) scale linearly (or logarithmically) from zero and would be infected with the same problems if we added a huge bias term to them of either sign.  But no one would propose doing such a thing in practice generally, as we all understand 0 clicks, 0 impressions, or 0 spend to be related to 0 target variable; but this is not the case with context variables as defined today.

## Next Steps

At this point, we turn to the Robyn team to ask:
* Is there something broken with the way Robyn handles this case?, or
* Is our interpretation of the Robyn waterfall incorrect?

I am inclined to think the waterfall is not reliable for context variables.

My rationale is that there is always a fixed intercept, but that Robyn is not doing the work of teasing it out of the variables.  Instead, Trend is allowed to have an embedded intercept.  And a context variable may have an embedded intercept as well.  To fix this, Robyn would need to take those constant effects out of all these variables, so the *variation* in the independent variable is driving the effect.

It is also possible we have an interpretation issue.  Our stakeholders want us to answer "what % of bookings would have occurred without media spend".  For this we can sum all non-paid media variables, but it is possible this is not an answerable question. If that is the case, guidance from the Robyn team to abandon the use of the waterfall of all variables would be helpful here.   At present it is the most prominent (upper left chart) on the generated plots.

This interpretation question is very important to our team, because we need to know how to handle the items which fall outside paid media variables, and also understand the reliability of the waterfall for the paid media variables.

## Reproducing - our toy data set

We created a toy data set to provide a transparent way for the team to reproduce issues and also evaluate other aspects of Robyn.

Toy Data Set: [robyn_toy_data_600000err.csv](https://github.com/facebookexperimental/Robyn/files/7818157/robyn_toy_data_600000err.csv)

Our toy data set can be created by running python code in a notebook.

This is the gist of the code which created the above set (to allow you to see what it is):
```
np.random.seed(43)

bookings_columns = ['bookings_tv_noiseless', 'bookings_tv_noisy', 'bookings_tv_context_0_center', 'bookings_tv_context_0_anchored']

#
# data set has no lag effect from media at all here
#
for stderr in [600000]:
    print(f'Creating data set with stderr {stderr}')
    df = pd.DataFrame({'date':pd.date_range(start='2015-01-01', end='2021-12-31')})

    # marketing effort
    #
    # random tv marketing from 0 to 10000 each period
    df['tv'] = np.random.randint(0, 10000, size=len(df))
    
    # 
    df['context_0_center'] = np.random.normal( size=len(df))
    
    df['context_100_center'] = 100 + df.context_0_center
    
    df['context_0_anchored'] = np.random.randint(0, 100000, size=len(df)) * 0.00005
    
    fixed_bookings = 10000000
    tv_scale = 200
    context_scale = 800000
    df['bookings_tv_noiseless'] = fixed_bookings + df.tv * tv_scale
    df['bookings_tv_noisy'] = fixed_bookings + df.tv * tv_scale + np.random.normal(loc=0, scale=stderr, size=len(df)) 
    
    # we use this whether predicting with context_0_center or context_100_center.  Those are two different forms of describing the same context
    df['bookings_tv_context_0_center'] = df.bookings_tv_noisy + df.context_0_center * context_scale
    
    df['bookings_tv_context_0_anchored'] = df.bookings_tv_noisy + df.context_0_anchored * context_scale
    
    for i in bookings_columns:
        print(f'Checking {i} for negative values')
        assert len(df[df[i]<0]) == 0, f'{i} has negative values which is not permitted'
    
    df.to_csv(os.path.join('data', f'robyn_toy_data_{stderr}err.csv'))
```
Full code for the toy data set: [MMMToyDataSet.zip](https://github.com/facebookexperimental/Robyn/files/7818283/MMMToyDataSet.zip)

## Toy Data Set Variable Definitions

There is a single paid media variable (TV).  This is presumed to be a driver of the target variables (bookings_tv_xyz).

We have the following target variables created:
* bookings_tv_noiseless: this is a linear function of TV spend
* bookings_tv_noisy: same as noiseless with an error term
* bookings_tv_context_0: same as noisy with the effect of a zero centered, normally distributed context variable
* bookings_tv_conext_0_anchored: same as noisy with addition of uniform random variable (we will not focus on this here)

Examining context variables the most interesting would be two:
* context_0_center: normal random variable
* context_100_center: same as context_0_center but adding 100 to each value

If you want to run without negative intercepts, you might create a variable which is -context_100_center so you have -100 mean value.

The goal here is to have a simple data set wherein TV is the only paid media variable and it drives bookings, but also a context variable (context_0_center) has variation which drives bookings.   The additional context variable (context_100_center) is intended as a shifted definition of context_0_center which is an equally valid variable from a statistical point of view (the exact same variation is driving the bookings, it's just that we have added a fixed value to each observation).

## Sample Code

The R code we use to run experiments is here:
[simplified_robyn_upload.zip](https://github.com/facebookexperimental/Robyn/files/7818194/simplified_robyn_upload.zip)

Our sample code follows much the same format as the demo code for Robyn.

I have tried to clean up this robyn sample, but there will be some places that you have to modify if you decide to use it:
* version of R to check for (we have an assertion to avoid any version surprises)
* conda environment into which nevergrad is installed (wherever you have done that)
* your local path (setwd -- where you want to put the output)
* path to the data file (relative path of toy data set source file)
* number of cores (it is hard coded to 6 here)

## Our Findings

We ran a series of experiments with this code and the toy data set and produced this set of findings:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/11449919/148300912-8495182b-b246-4382-bcc6-7b9e6aa976a2.png">

The "Result" refers to the target variable impact reported on the Waterfall from one of the Pareto front models (solution).

What we see is that in scenarios 4, 8, and 9, where the context variable is not centered, there is instead a tremendous contribution to bookings from the context variable.  However, we know from our toy data set that the true contribution is relatively small, but instead Robyn waterfall is reporting on the embedded shift (intercept) in the term (context_100_center being a shift of context_0_center).

And for those not yet comfortable with negative intercepts, scenario 9 tackles your concern.  Here, by using the default Robyn (no negative intercept) we see the intercept is pinned at zero (a yellow flag!) and the trend is also zero, so the context variable absorbs all variation not attributable to TV.

### The Good (Great) News

We are very pleased that the contribution of TV to bookings was basically consistent across all scenarios.  (Scenario 6 has a different target, so disregard).  Around 7-8% of bookings were driven by TV in every scenario, so it was not impacted by the various context variable models.

Hence, we see from these experiments an accurate assessment of TV, and focus on how Robyn sorts out Prophet and context variables and the embedded non-zero centering which may exist in those variables.

## Environment & Robyn version
R version:: 4.1.0
Robyn: 3.4.8 (really 3.4.8.X which has a small modification to allow for negative intercepts.)

**Comment by extrospective** [comment]
I realize that pushing this much code & data was cumbersome, so I have created a separate [git repo](https://github.com/extrospective/mmm-toy-data) where you can review:
* scripts to generate the toy data sets
* the toy data sets
* R code to run

The files in the new repo will not be identical to those uploaded here, as they will be further maintained and cleaned up with the hope that the Robyn team and user community might join in using these additional data sets for testing in the future.

**Comment by extrospective** [comment]
Some additional testing with the updated toy data set again demonstrates that the off-center context variable is deemed by Robyn (waterfall chart on Pareto front solution) to be responsible for enormous % of bookings (more than 100%).  This occurs when the context variable is not centered at 0 and has no relation to actual causality in our data set (ground truth knowledge).

Table summarizes some results:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/11449919/148612680-f0389e04-91b7-412d-9bdf-1ac7f12ccf4b.png">

**Comment by gufengzhou** [comment]
Hi, thanks for this extraordinary analysis! This is the typical "reference point" issue that's tricky for interpretation, but not influencing the prediction, as you found out. Also, luckily, media are not impacted exactly due to your hypothesis. Because of the 3 natural assumptions, 1: media metrics are always >=0 regardless of spend or imp or organic etc, 2: sales and conversions always >=0  & 3: when media ==0, sales contribution ==0, the interpretation for media is always intuitive and there's no need to do any scaling. But for context vars, the interpretation could vary a lot and is actually subjected to individual needs, which introduces extra friction in the whole process. Therefore we've decided to leave it untouched and  haven't put too much effort so far. 

Interestingly, we've seen the same question couple of times recently, which indicates advanced needs of robyn users. We're be considering the following options and curious about your feedback:

**For prophet_vars:**
1. All remain as is / unscaled, coef sign default to unconstrained and will not be customisable anymore. Because "useful split" of prophet vars is quite subjective. If sales go up in summer and go down in winter, then it's ok to have 0 as sum of contribution. 
2. Or, we split the total effect for all prophet_vars evenly. This might look "better" in the waterfall chart because season/weekday/holiday are not always small, but is of course a biased option. Coef sign default to unconstrained and will not be customisable anymore. 

**For context vars:**
- We introduce a new argument context_var_ref to set reference for context_vars and it takes on values c( "unscaled", "center_to_first", "center_to_min", "center_to_max", "center_to_mean", "center_to_median", "scale_to_0_1" , "scale_to_0_100" or any numerical values etc). The context_sign default to unconstrained
- Discount rate has context_var_ref = "unscaled", because we want to know how much does sales change when discount changes 1% while 0 discount means no discount effect. 
- For your Business Confidence Index it could be "center_to_first", because the BCI plot begins in year 2008 and it's natural to take the beginning as reference and we want to know how much does it increase or decrease compared to beginning. If we eyeball the range of BCI to be c(95, 102) and the beginning is 100, then context_var_ref = "center_to_first" will be same as context_var_ref = 100, and scaling BCI will be just subtracting 100 from the range and we get the new range c(-5, 2). Assuming slope is 100, then then BCI = 0, meaning the same level as 2008, there's no effect. When BCI = 2, then effect is 2 * 100 = 200 bookings per day (assuming daily data) for your case. 
- For competitor sales with money values, or any brand index, or things like "share of wallet", "share of voice", we might assume the same logic as BCI to have the start value as reference, or alternatively putting some average value from the beginning periods as reference. 
- For categorical variables, like the "event" from our dummy dataset, because we use prophet to decompose factors into continuous already, it can remain context_var_ref = "unscaled"

As you can see, this will definitely introduce some friction into the modelling process when using context_vars. But ultimately it's the right thing to do.
