### ISSUE TITLE
Error in UseMethod("logLik") :    no applicable method for 'logLik' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by BHATT-APOORVA** [facebookexperimental/Robyn#258]
## Describe issue
I am having this issue while changing modelling period. Its monthly, and upto window_start =  "2016-10-01" process runs smoothly, but at window_start =  "2016-11-01" this error appears.

Can this be because number of rows in my data exceed number of columns past this date?
I can't post data here, but I can happily print out any output necessary.

## Provide dummy data & model configuration
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration.

## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version

**Comment by gufengzhou** [comment]
Hi, we haven't seen this error before. How many months do you have and how many independent variables? I sounds like your model suffers from data sparsity. We usually recommend the column : row ratio to be 1:10

**Comment by gufengzhou** [comment]
have you figured it out already? please close ticket if so. thanks!
