### ISSUE TITLE
Robyn on Databricks: Getting Started

### ISSUE THREAD

**Issue by extrospective** [facebookexperimental/Robyn#259]
## Describe issue
Useful to have a few steps on how to get Robyn working on Databricks.
Not covered in current documentation.

## Databricks

Databricks allows one to alternate between R and Python cells.  In this use we are using R as the default language for the notebook.

First install reticulate:
```
install.packages('reticulate')
```

Then with reticulate install nevergrad in the local python environment.  (Note: you do not need to create a virtual environment, and in fact doing so may cause a range of issues and difficulties, such as failure to find python3.8-venv, etc.  We have learned none of this is required, and you simply use reticulate to install nevergrad and you're in business):
```
library(reticulate)
country = dbutils.widgets.get('country')
py_install("nevergrad")
reticulate::py_config()
```

From here on you can install R packages and finally the Robyn package using remotes::install_github as found in the getting started document.

One drawback to this approach is that the install_github takes a long time, for us about 36 minutes.
We are looking towards some sort of image solution to make this faster, but we are also want the flexibility to get the latest Robyn code.

We do run this additional step to assert our library version of Robyn itself:
```
library(Robyn) 
pkg_version = packageVersion('Robyn')
if (pkg_version != '3.4.8.8') {  
  writeLines(as.character(pkg_version))
  stop('Wrong pkg version')
} else {
  writeLines('Libraries loaded. Robyn package version tested')
}
```

**Comment by alberthupa** [comment]
Hi, just to contribute to this issue and save some people some time. DataBricks has problems with reading folders in DBFS with spaces, so default folder names such as "2022-01-17 11.07" are hardly accessible by scripts inside notebooks. If you change spaces for underscores, everything will go smoothly

**Comment by extrospective** [comment]
I did not have a problem with databricks when putting double quotes around the file names, same as when using shell commands.  However, there are advantages to avoiding spaces I would agree.

**Comment by alberthupa** [comment]
> I did not have a problem with databricks when putting double quotes around the file names, same as when using shell commands. However, there are advantages to avoiding spaces I would agree.

Totally agree, my comment was regarding extracting files from DBFS via links in web browsers (in my case spaces in catalog names were a problem).

**Comment by extrospective** [comment]
We have a new innovation to accelerate R Robyn development in databricks.
This is to build the code from Robyn once and cache it as a library.

Problem: The problem databricks users may encounter (we did) is that when a cluster starts up it does not have Robyn nor other R libraries installed.  The process takes over 40 minutes each time we startup.

Summary: The solution is to build the libraries, push them over to dbfs, and then add a dbfs library path to that directory on startup of your Robyn notebook.  The Robyn notebook does not have to install.packages() but merely use the library.

Reference concept: https://github.com/marygracemoesta/R-User-Guide/blob/master/Developing_on_Databricks/package_management.md#custom-packages

dbfs=databricks file system

Details:

## Notebook 1: Install Libraries

### Create a library path where you isntall libraries
```
%sh
mkdir /usr/lib/R/robyn-lib-path
```

Add this new directory to libPaths:
```
.libPaths(c("/usr/lib/R/robyn-lib-path", .libPaths()))
```

### Run installation of packages you wish to have pre-installed

We reviewed our libPaths first:

```
.libPaths()
```

Then we installed a bunch of packages we wanted in place:
```
install.packages('remotes')
install.packages('plyr')
install.packages('dplyr')
install.packages('rlist')
install.packages('stringr')
install.packages('rlist')
install.packages('ggplot2')
install.packages('patchwork')
install.packages('scales')
```
(not sure which of these are absolutely required for robyn)

Finally we installed a specific github version.  For us, we are installing a fork and using a branch on that fork (ref) so our command looks like:
```
remotes::install_github('joangcc/Robyn/R', ref='free_intercept')
```
You would instead reference the Robyn repo in the first argument, and use ref if you have a branch

Verify the libraries installed:
```
%sh
ls -l /usr/lib/R/robyn-lib-path
```

### Copy installations to dbfs so they can be saved across cluster runs.

Consult your local admin about paths you might use.  These happen to be paths we created on /dbfs.
Since you may deploy different versions of Robyn over time and want them simultaneously available, I would suggest putting the branch and version name in the directory as we have done:

```
%sh
mkdir /dbfs/robyn/robyn_free_intercept_3.4.8.10
cp -R /usr/lib/R/robyn-lib-path /dbfs/robyn/robyn_free_intercept_3.4.8.10
ls -l /dbfs/robyn/robyn_free_intercept_3.4.8.10
```
(this command took us 30' when we did the install, but it's only required once)

Verify that the files have been copied:
```
%sh
ls -l /dbfs/robyn/robyn_free_intercept_3.4.8.10/robyn-lib-path
```

## Modify Robyn notebook to use these pre-installed libraries

* Remove all install.packages and install_github corresponding to above packages
* Note that if you *do* want to install packages, you should do that before adding to libPaths below

For us, we did not include reticulate above, so in our Robyn notebook we setup reticulate and then we adjust the libPaths.

After you have installed all packages in Robyn *other than the preinstalled ones*, adjust libPaths with a command appending *your* target directory to libPaths:
```
.libPaths(c("/dbfs/robyn/robyn_free_intercept_3.4.8.10/robyn-lib-path", .libPaths()))
```

At this point the R library() functions will be looking in this library path and find the preinstalled R packages.  This saves copying them to the local cluster and building related code.

Maybe in a later version we will include reticulate in the pre-installs; here I am documenting what worked quickly and well for us so others can avoid the headaches we had with slow startup time.

**Comment by DaveJacques** [comment]
Hi @extrospective,

I just want to say thanks so much for both your pre-install advice and your reticulate advice.

I was going round in some serious circles getting reticulate to install nevergrad within a virtual environment and stumbling upon your post was a god-send!

I really appreciate you taking time to offer advice to the community!

**Comment by syadalam4** [comment]
Hi @extrospective. Thank you for sharing this, it was really useful. Do you have any tips on the configuration for the Databricks cluster?
