### ISSUE TITLE
"unable to start png() device"

### ISSUE THREAD

**Issue by RaviP1987** [facebookexperimental/Robyn#260]
Hi Gufeng, Team

Happy new year! :)

I installed Robyn on a new machine and i keep getting this error. Could you advise what could be the root cause ?

"unable to start png() device"

Thanks
Ravi

**Comment by gufengzhou** [comment]
Are you using Windows and Have you checked this thread already? Doesn't look like a Robyn issue so far 

https://stackoverflow.com/questions/45113597/error-unable-to-start-png-device

**Comment by RaviP1987** [comment]
Thanks Gufeng. Yes, it was a python installation issue on my system
