### ISSUE TITLE
Cannot set yearly.seasonality Fourier terms for Robyn invocation of Prophet.  Error Results.

### ISSUE THREAD

**Issue by extrospective** [facebookexperimental/Robyn#262]
## Describe issue
Our project goal includes passing yearly.seasonality through Robyn to Prophet.

We have determined that we want a different number of Fourier terms than the default for Prophet.
But Robyn's invocation of Prophet makes it impossible to do this.

We would prefer that Robyn allow yearly.seasonality to be passed through successfully.

Currently if passed into Robyn it will be added to the "..." to be passed to Prophet, and Prophet will see two parameters named yearly.seasonality and throw an error.  One comes from Robyn's line of code and other from "...".  

Sample error from this invocation of robyn_inputs() with yearly.seasonality passed in:
```
Error in prophet(holidays = if (use_holiday) holidays[country == prophet_country] else NULL,  : 
  formal argument "yearly.seasonality" matched by multiple actual arguments
```

[BTW, there is no value checking on "..." from prophet, so when we accidentally misspell a parameter or mistakenly use the python spelling such as n_changepoints instead of n.changepoints, no error is thrown.  This hid this error from us, and is a bit of an engineering challenge.]

## Why do we care about yearly.sesasonality being set?
Standalone testing of prophet with our business data suggests that the Fourier order change will produce lower MAPE based on some out of sample testing.  We want to take that learning and feed it through the prophet invocation underlying Robyn.

## Background
* Documentation of yearly.seasonality in Prophet: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html
* Prophet code showing what yearly.seasonality can have as input values (not jsut TRUE/FALSE): https://github.com/facebook/prophet/blob/main/R/R/prophet.R

## Specific Robyn code:
* Robyn code which causes yearly.seasonality to be be supplied by Robyn although we tried to supply a value of 20 (inputs.R line 634+):
```
prophet_decomp <- function(dt_transform, dt_holidays,
                           prophet_country, prophet_vars, prophet_signs,
                           factor_vars, context_vars, paid_media_vars, intervalType,
                           ...) {
  check_prophet(dt_holidays, prophet_country, prophet_vars, prophet_signs)
  recurrence <- subset(dt_transform, select = c("ds", "dep_var"))
  colnames(recurrence)[2] <- "y"

  holidays <- set_holidays(dt_transform, dt_holidays, intervalType)
  use_trend <- any(str_detect("trend", prophet_vars))
  use_season <- any(str_detect("season", prophet_vars))
  use_weekday <- any(str_detect("weekday", prophet_vars))
  use_holiday <- any(str_detect("holiday", prophet_vars))

  dt_regressors <- cbind(recurrence, subset(dt_transform, select = c(context_vars, paid_media_vars)))
  modelRecurrence <- prophet(
    holidays = if (use_holiday) holidays[country == prophet_country] else NULL,
    yearly.seasonality = use_season,
    weekly.seasonality = use_weekday,
    daily.seasonality = FALSE,
    ...
  )
```

## Suggested change
If "..." contains yearly.seasonality do not pass it to prophet() but let it flow with "..."

or any other variant of this that does the job.

**Comment by laresbernardo** [comment]
Thanks for catching this @extrospective
I've enabled the user to be able to change these default parameters passed to `prophet` on this [branch](https://github.com/facebookexperimental/Robyn/tree/issue_262). Feel free to test it out by installing this version and then we can merge it into main branch for everyone else to be able to use this feat. Please, let me know how it goes so we can land it afterward.

**Comment by extrospective** [comment]
Thanks for the quick response.  We may not be able to do this testing in a timely fashion due to absences, and I would not want to hold up release.

**Comment by laresbernardo** [comment]
Sure. I've tested several scenarios and worked out for me. Will release then, and do let us know when you test it on your end. Cheers
