### ISSUE TITLE
is it mandatory to set paid_media_spends variable? 

### ISSUE THREAD

**Issue by lorokidul** [facebookexperimental/Robyn#267]
Is it mandatory to define paid_media_spends variable, in case if i set paid_media_vars with impressions? 
Can i set paid_media_spends to NULL, if i doesn't have  data about spends?

**Comment by igorskokan** [comment]
Hey! This sounds like could be a good case for you to explore organic_vars ( activities without direct spend ): read more about it here: https://facebookexperimental.github.io/Robyn/docs/organic-media

Typically, this is organic marketing (newsletters, organic social media), but in fact this could be any activity that is expected to have carryover (adstock) and saturating behavior but no associated spend.

**Comment by lorokidul** [comment]
> Typically, this is organic marketing (newsletters, organic social media), but in fact this could be any activity that is expected to have carryover (adstock) and saturating behavior but no associated spend.

Hi, thank you for your reply. I have used organic-media option. Now on the waterfall graph i am getting the result, that this organic media variable contributed about 5% to my dependent variable. However, in pareto_aggregated.csv i do not find any effect_share for this variable (it is just skipped; looks like, effect-share is not calculated for variables that doesn't have direct spend)
That's confusing. Why does waterfall graph doesn't match with effect share? 
How Robyn calculates input of organic media to dependent variable ?

**Comment by gufengzhou** [comment]
Please refer to this schema doc for the Pareto aggregated csv https://github.com/facebookexperimental/Robyn/blob/main/demo/schema.R

What you're looking for is column xDecompPerc. effect_share is related to spend_share and thus only for paid media.

**Comment by gufengzhou** [comment]
please reopen if necessary
