### ISSUE TITLE
nlsModel Error 

### ISSUE THREAD

**Issue by floratias** [facebookexperimental/Robyn#268]
## Issue : 
hi, when I am using the Facebook data test CSV, everything is working well, so the configuration on my computer seems good. then I am trying to run the code on my own data. using a CSV with date with format '2021-12-31' and then 'conversions' and 'spend and impressions by channels as a numeric format. 

I get an error when running : 

_dt_mod <- f.inputWrangling()_

 the error : 
**_Error in nlsModel(formula, mf, start, wts) : 
singular gradient matrix at initial parameter estimates_**

 
## Dummy data & model configuration
**Data CSV lookalike :** 

$ DATE : IDate, format "2021-12-31"
$ conversion : int , format : 17899
$ Search_S : int , format : 12456
$ TV_I  : int, format 6578
 and so on .. with for each channel its spend and the number of impressions by day. for the past 6 month 

**Configuration :** 
set_country <- "US" 
set_dateVarName <- c("DATE") 
set_depVarName <- c("conversion") 
set_depVarType <- "conversion" 

activate_prophet <- T 
set_prophet <- c("trend", "season", "holiday") 
set_prophetVarSign <- c("default","default", "default") 

activate_baseline <- F
set_baseVarName <- c("competitor_sales_B") 
set_baseVarSign <- c("negative") 

set_mediaVarName <- c("Search_I","Pinterest_I","Snapchat_I","Tiktok_I","Facebook_I","Instagram_I","TV_I","Search_Brand_I","Youtube_I")
set_mediaVarSign <- c("positive","positive","positive","positive","positive","positive","positive","positive","positive")
set_mediaSpendName <- c("Search_S","Pinterest_S","Snapchat_S","Tiktok_S","Facebook_S","Instagram_S","TV_S","Search_Brand_S","Youtube_S")
                                                                    
set_hyperBoundLocal <- list( 
    Facebook_I_alphas = c(0.5, 3) 
  , Facebook_I_gammas = c(0.3, 1) 
  , Facebook_I_thetas = c(0, 0.3) 
  
  , Instagram_I_alphas = c(0.5, 3)
  , Instagram_I_gammas = c(0.3, 1)
  , Instagram_I_thetas = c(0, 0.3)
  
  , Pinterest_I_alphas = c(0.5, 3)
  , Pinterest_I_gammas = c(0.3, 1)
  , Pinterest_I_thetas = c(0, 0.3)
  
  , Search_Brand_I_alphas = c(0.5, 3)
  , Search_Brand_I_gammas = c(0.3, 1)
  , Search_Brand_I_thetas = c(0, 0.3)
  
  , Search_I_alphas = c(0.5, 3)      
  , Search_I_gammas = c(0.3, 1)      
  , Search_I_thetas = c(0, 0.3)   
  
  , Snapchat_I_alphas = c(0.5, 3)    
  , Snapchat_I_gammas = c(0.3, 1)    
  , Snapchat_I_thetas = c(0, 0.3)  
  
  , Tiktok_I_alphas = c(0.5, 3)      
  , Tiktok_I_gammas = c(0.3, 1)      
  , Tiktok_I_thetas = c(0, 0.3)  
  
  , TV_I_alphas = c(0.5, 3)          
  , TV_I_gammas = c(0.3, 1)          
  , TV_I_thetas = c(0.3, 0.8)  
  
  , Youtube_I_alphas = c(0.5, 3)     
  , Youtube_I_gammas = c(0.3, 1)     
  , Youtube_I_thetas = c(0, 0.3)     
 
)
## Environment & Robyn version
R version: R 4.1.2

Thanks ! 
Flora

**Comment by laresbernardo** [comment]
Hi @floratias Looking at your inputs, it seems you are using Robyn v2. Can you please try installing Robyn as a package (instead of scripts) and try again? I'd recommend you to follow our [demo.R file](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R). Let us know if you run into trouble.

**Comment by floratias** [comment]
when I tried to run the demo.R code you just send me, I get an error running **_emotes::install_github("facebookexperimental/Robyn/R")_**

saying :

_Error: Failed to install 'Robyn' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In safe_build_package(pkgdir, build_opts, build_manual, build_vignettes,  :
  restarting interrupted promise evaluation
2: In safe_build_package(pkgdir, build_opts, build_manual, build_vignettes,  :
  internal error -3 in R_decompress1_

**Comment by gufengzhou** [comment]
have you figured it out already? please close ticket if so. thanks!

**Comment by floratias** [comment]
yes it worked thanks for your help !!
