### ISSUE TITLE
Can't run f.inputWrangling()

### ISSUE THREAD

**Issue by famendez7** [facebookexperimental/Robyn#27]
I am trying to run fb_robyn.exec.R and I get this error message in this line of code:

#### Prepare input data
dt_mod <- f.inputWrangling() 

The error message says:

Error in value[3L] : unused argument (cond)

And the traceback:

4. tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
3. tryCatchList(expr, classes, parentenv, handlers) 
2. tryCatch({
    dateCheck <- as.matrix(dt_transform[, set_dateVarName, with = F])
    dateCheck <- as.Date(dateCheck)
    }, error = function() { ... at fb_robyn.func.R#79
1. f.inputWrangling() 

I saw the same error in another issue, but with no solution so I am re-asking. Thanks very much

**Comment by gufengzhou** [comment]
just pushed the fix, which was related to checking if the DATE format is set correctly. hope it works now?

**Comment by gufengzhou** [comment]
alright this is a tricky one. you're using your own data, right? probably also using some non-spend metrics for set_mediaVarName? This error is related to the spend-reach nonlinear fitting. please try using all spends in set_mediaVarName first and see if everything runs. If yes, then try changing it to impressions etc one by one, so you can see which channel is having problem.

**Comment by LeoUbbiali** [comment]
Hey @gufengzhou  thanks a lot for the quick reply.
Yes, that's correct:
- I'm using my own data
- I'm using the non-spend variables for `set_mediaVarName` (using the corresponding "pressure" metric for each spend metric. I have a 1 pressure metric and one spend metric for each "channel")

Could you please expand/point to underlying model documentation on "This error is related to the spend-reach nonlinear fitting"?

Anyway, I'll follow your advice and then report back.

**Comment by gufengzhou** [comment]
hey, I've pushed a fix for the nls spend reach fitting. hopefully it works now for you. otherwise let me know. regarding documentation, sorry that this is not updated yet. It's fitting the exposure metrics (imps, clicks, GRP etc.) using spends, when you're using non-spend metrics as media variables. For example if you use imp for FB, spend-reach model will fit FB imp with FB spend. This is aiming to better model the nonlinear relationship between spend and exposure and thus enable better ROI calculation, cost-response curve and finally budget allocation. You can check the detail in script .func from line 280 on. hope it helps.

**Comment by famendez7** [comment]
Thank you for the push, I managed to run f.inputWrangling() successfully now.

When running the following line of code now, I get an error saying **'Error: Miniconda installation failed [unknown reason]'**

Is this Miniconda something I need in my pc to be able to run it? Not familiar.

Thanks for the comments

model_output_collect <- f.robyn(set_hyperBoundLocal
                                ,optimizer_name = set_hyperOptimAlgo
                                ,set_trial = set_trial
                                ,set_cores = set_cores
                                ,plot_folder = "~/Documents/GitHub/plots") # please set your folder path to save plots. It ends without "/".

**Comment by gufengzhou** [comment]
Yes, you need to install anaconda first, then install Nevergrad (which is a Python library) through conda. In the .exec script there is a simple guide after the libraries

**Comment by LeoUbbiali** [comment]
Thanks @gufengzhou . My issue was solved by the latest commit. I didn't need to manually loop over the Spend-Media pairs to find the one who did not fit.
Thanks also for updating the step by step guide.
