### ISSUE TITLE
How to save one pager graphs, to be shared using internal shiny app

### ISSUE THREAD

**Issue by Schumzy** [facebookexperimental/Robyn#270]
## Describe issue
how do I get access to the one pager graphs data/plot objects and the refresh graphs data so can plot own graphs to be used in internal shiny app. Assume the model has been selected, and want to edit graphs, or change color scheme to corporate colors, or place graphs in shiny app.

## Provide dummy data & model configuration
N/A

## Environment & Robyn version
R version (R --version) 3.4
Please make sure you're using the latest Robyn version

**Comment by gufengzhou** [comment]
Hi, all initial plots are created in the robyn_run function. Objects of the 6 plots in the onepager are p1-p6, for example. The two refresh plots are in the robyn_refresh function. The allocator plots in the allocation function.

**Comment by gufengzhou** [comment]
please reopen if necessary

**Comment by laresbernardo** [comment]
`robyn_onepagers()` should do the trick
