### ISSUE TITLE
Use prophet settings in robyn_refresh

### ISSUE THREAD

**Issue by joangcc** [facebookexperimental/Robyn#271]
Hi,
We have trained a model using certain values for prophet passing it through robyn_inputs() (eg., changepoint.range,seasonality.mode...). We want to reproduce the same settings of training period in all the refreshes by passing those parameters in robyn_refresh().
However, when doing the refresh for those models, we would like to pass the same parameters, but robyn_refresh() doesn't seem to have the option for that. We have run into an error when running robyn_refresh() and passing those parameters.

`  Robyn <- robyn_refresh(
    , dt_input = data
    , dt_holidays = holidays  
    , refresh_steps = steps
    , refresh_mode = "auto"
    , refresh_iters = iterations 
    , refresh_trials = trials
    , plot_pareto = FALSE
    , changepoint.range = 0.6
    , changepoint.prior.scale = 0.30
    , n.changepoints = 36  
    , seasonality.mode = 'additive'
    , seasonality.prior.scale = 15
    , holidays.prior.scale = 15
  )`

The error was the following: `Error in robyn_refresh(, dt_input = vistaprint_dt_rw_filtered, dt_holidays = holidays,  : 
  unused arguments (changepoint.range = 0.6, changepoint.prior.scale = 0.3, n.changepoints = 36, seasonality.mode = "additive", seasonality.prior.scale = 15, holidays.prior.scale = 15)`
Problem should be solved allowing both robyn_refresh() and the nested call of robyn_engineering() to pass those parameters using "..."

**Comment by laresbernardo** [comment]
Hi, @joangcc
I've just deployed a fix into the main branch for custom prophet inputs on `robyn_refresh()`. Please, do re-install Robyn to match version 3.4.12 and let us know if everything's as expected.
Cheers.

**Comment by joangcc** [comment]
Hi @laresbernardo ,
Thank you for your changes. We have updated our main branch to catch these changes. We are trying the process and running into some errors. Specifically, when running robyn_refresh:

`Robyn <- robyn_refresh(
    robyn_object = our_filename
    , dt_input = our_dt
    , dt_holidays = dt_prophet_holidays 
    , refresh_steps = 30
    , refresh_mode = "auto"# in auto mode will refresh number of iterations
    , refresh_iters = 500
    , refresh_trials = 2
    , plot_pareto = FALSE
  )`
  After running robyn_refresh, the process gives us the following error just when the first trial starts:
'>>> Start running 2 trials with 500 iterations per trial each with TwoPointsDE nevergrad algorithm...
 Running trial nr. 1
Error in {: task 1 failed - "argument is of length zero"'

We will keep working in this, as the error may well be due to some bug on our end.
We will keep you updated.
Cheers.

**Comment by laresbernardo** [comment]
Hi @joangcc I think this error doesn't have a relation to the `robyn_refresh()` changes but let us know...
Just FYI, no need to pass those parameters again to `robyn_refresh()` because they are now saved into the exported object on `robyn_run()`'s results and automatically set to be the new defaults for every iteration. I'd use `robyn_refresh()` parameters in case you'd like to change (for some reason) on new refresh iterations.

**Comment by joangcc** [comment]
Hi @laresbernardo ,

I confirm that robyn_refresh does accept now explicit declaration of prophet parameters and uses them in model training.
However, robyn_refresh does not use the values used during initial training period. I have to declare them again. custom_param, which I assume is the object that should save explicitly declared prophet settings, is an empty list in the RDS file once you save the results from the initial run. I have tested this using your demo script. See code to reproduce the problem:
`
library(Robyn)
set.seed(123)

Sys.setenv(R_FUTURE_FORK_ENABLE="true")
options(future.fork.enable = TRUE)

data("dt_simulated_weekly")
head(dt_simulated_weekly)
data("dt_prophet_holidays")
head(dt_prophet_holidays)

robyn_object <- "path"

InputCollect <- robyn_inputs(
  dt_input = dt_simulated_weekly
  ,dt_holidays = dt_prophet_holidays
  ,date_var = "DATE" 
  ,dep_var = "revenue"
  ,dep_var_type = "revenue"
  ,prophet_vars = c("trend", "season", "holiday")
  ,prophet_signs = c("default","default", "default")
  ,prophet_country = "DE"
  ,context_vars = c("competitor_sales_B", "events")
  ,context_signs = c("default", "default")
  ,paid_media_vars = c("tv_S", "ooh_S"	,	"print_S"	,"facebook_I" ,"search_clicks_P")
  ,paid_media_signs = c("positive", "positive","positive", "positive", "positive")
  ,paid_media_spends = c("tv_S","ooh_S",	"print_S"	,"facebook_S", "search_S")
  ,organic_vars = c("newsletter")
  ,organic_signs = c("positive")
  ,factor_vars = c("events")
  ,cores = 6
  ,window_start = "2016-11-23"
  ,window_end = "2018-08-22"
  ,adstock = "geometric"
  ,iterations = 200
  ,nevergrad_algo = "TwoPointsDE"
  ,trials = 1
)

hyper_names(adstock = InputCollect$adstock, all_media = InputCollect$all_media)

hyperparameters <- list(
  facebook_I_alphas = c(0.5, 3)
  ,facebook_I_gammas = c(0.3, 1)
  ,facebook_I_thetas = c(0, 0.3)
  
  ,print_S_alphas = c(0.5, 3)
  ,print_S_gammas = c(0.3, 1)
  ,print_S_thetas = c(0.1, 0.4)
  
  ,tv_S_alphas = c(0.5, 3)
  ,tv_S_gammas = c(0.3, 1)
  ,tv_S_thetas = c(0.3, 0.8)
  
  ,search_clicks_P_alphas = c(0.5, 3)
  ,search_clicks_P_gammas = c(0.3, 1)
  ,search_clicks_P_thetas = c(0, 0.3)
  
  ,ooh_S_alphas = c(0.5, 3)
  ,ooh_S_gammas = c(0.3, 1)
  ,ooh_S_thetas = c(0.1, 0.4)
  
  ,newsletter_alphas = c(0.5, 3)
  ,newsletter_gammas = c(0.3, 1)
  ,newsletter_thetas = c(0.1, 0.4)
)

InputCollect <- robyn_inputs(InputCollect = InputCollect,
                             hyperparameters = hyperparameters,
                             changepoint.prior.scale =0.3,
                             seasonality.mode = 'multiplicative',
                             seasonality.prior.scale=12,
                             holidays.prior.scale = 12,
                             n.changepoints = 1)


OutputCollect <- robyn_run(
  InputCollect = InputCollect
  , plot_folder = robyn_object
  , pareto_fronts = 3
  , plot_pareto = FALSE
)

OutputCollect$allSolutions
select_model <- "1_17_4" #adapt
robyn_save(robyn_object = robyn_object
           , select_model = select_model
           , InputCollect = InputCollect
           , OutputCollect = OutputCollect
)

Robyn <- robyn_refresh(
  robyn_object = robyn_object
  , dt_input = dt_simulated_weekly
  , dt_holidays = dt_prophet_holidays
  , refresh_steps = 1
  , refresh_mode = "manual"
  , refresh_iters = 200
  , refresh_trials = 1
)
`

Let me know if I should create a separate issue for that.

Thanks,
Joan

**Comment by joangcc** [comment]
Hi @Lares,

THanks for your quick response.Updated. Robyn object saves nowcustom_params. However, seems this parametersarenot having effect.
See the following comparison:
This first image shows prophet_decomp.png before the refresh(initial run). See how the trend only has 1 changepoint as expected.
![prophet_decomp](https://user-images.githubusercontent.com/92848379/151588685-1b2a946c-9729-4c40-9813-6f527d03f7fe.png)
This second image shows prophet_decomp.png after the refresh, using the code I sent you in my previous message. As you can see, in the refresh, Prophet is using more changepoints, ignoring the explicit parameters declared in initial training period-
![prophet_decomp](https://user-images.githubusercontent.com/92848379/151588335-feab8b64-2534-4a97-8ed8-5c2c6681c1d7.png)
Is there any extra step that I have to do to indicate robyn_refresh it should be using custom_params?
Thanks,
Joan

**Comment by laresbernardo** [comment]
Yeah, sorry for that. I didn't even know exactly how to check if it was working OK, so thanks for the example and double-checking. I've just used your reproducible code to test and should work now (both original and refresh versions have 1 change-point on `prophet_decomp` outputs). 
I've also added a message printed for when custom parameters are being used. Please, let us know (again) if it worked alright this time.
Have a nice weekend @joangcc

**Comment by joangcc** [comment]
Hi @laresbernardo ,
It works! Thanks for fixing this issue.
Best,
Joan
