### ISSUE TITLE
Error in 'contracts'

### ISSUE THREAD

**Issue by andybellis** [facebookexperimental/Robyn#274]
## Describe issue
I have run the demo data successfully end to end. Using my first sample data I get Error in `contrasts. I am using the same independent variables as in demo but with my own data.

Michaelis-Menten fitting for facebook_I out of range. Using lm instead
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

## Provide dummy data & model configuration
All configurations in line with demo data

## Environment & Robyn version
R version (R --version) R version 4.1.2 (2021-11-01)
Please make sure you're using the latest Robyn version

**Comment by extrospective** [comment]
Perhaps the code you used and more information about your data set would help assess this issue.

**Comment by andybellis** [comment]
Hi Mark - thanks for responding. I am keeping everything in the code identical to the Demo except for the data schema name and the date window. The test_brand1 data i am using is real data from an ecommerce brand. The spend profiles look reasonable and the facebook Spend to Imp shape and Search Spend to Click shape look good
![image](https://user-images.githubusercontent.com/94903282/150805651-9be9f65d-51aa-4939-ad59-d81e5cc4db22.png)
![testbrand1 hists]

**Comment by andybellis** [comment]
Resolved. It was a formatting issue in the 'Events' column
