### ISSUE TITLE
Should i manually scale the data before substituting them into Robyn

### ISSUE THREAD

**Issue by lorokidul** [facebookexperimental/Robyn#276]
Is it possible to somehow switch off the intercept in the model?

I am getting the result, that 70% of my dependent variable are due to intercept. It doesn't have any managerial sense.
I do not any scaling of my independent variables before modeling, should i do that in order to get rid of intercept?

**Comment by lorokidul** [comment]
> hi, this is related to this thread. Please check it and let me know what you think. #257

Hi, thank you for your reply. I read the thread, however i didn't find there answer to my question. 
For example, in [sklearn LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)
there is fit_intercept = False option. In case if fit_intercept=False, no intercept will be used in calculations.
Does Robyn have something like that?

**Comment by gufengzhou** [comment]
Hey, Robyn uses the library glmnet that has the parameter `intercept` where you can set it `intercept = FALSE` to drop intercept. By default, Robyn sets this as default: `robyn_inputs(..., intercept_sign = 'non_negative')` , meaning it will drop intercept when it's negative, because we wanted to avoid situation where baseline gets largely negative and thus difficult to interpret. But in the thread I sent you, the user has made a great case and now we also allow negative intercept by setting `robyn_inputs(..., intercept_sign = 'unconstrained')`. But so far we have no plan to directly allow turning on/off intercept as in glmnet. Hope it helps

**Comment by gufengzhou** [comment]
please reopen if necessary

**Comment by lorokidul** [comment]
> Hey, Robyn uses the library glmnet that has the parameter `intercept` where you can set it `intercept = FALSE` to drop intercept.

Hi, thanks a lot to your answers. I set intercept to FALSE in all occurences of glmnet: [in cvmod ](https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R#:~:text=%23%20%2Cintercept%20%3D%20FALSE),  i also add intercept=FALSE to [model_refit](https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R#:~:text=model_refit%20%3C%2D%20function(x_train%2C%20y_train%2C%20lambda%2C%20lower.limits%2C%20upper.limits%2C%20intercept_sign%20%3D%20%22non_negative%22)%20%7B)

It works, and on the waterfall plot i see zero intercept. However, now i have another issue. When i examined pareto_aggregated.csv, i found out that now dep_var and depVarHat cumulative sums are not equal to each other (when i've uses previous version of code with intercept these variable sums where equal).

Could you please help me to figure out, why dep_var and depVarHat sums now different? Maybe i should also changed some code about decomposition?

Here is the code of updated  [model.R function](https://github.com/lorokidul/Robyn/blob/main/R/R/model.R)

**Comment by lorokidul** [comment]
Since i am not a collaborator of repo, i cannot reopen my issue myself. Would you please reopen this issue.

**Comment by gufengzhou** [comment]
Hi, dep_var is the true revenue and depVarHat the predicted revenue. Unless you have 100% perfect fitting which is almost impossible, dep_var and depVarHat should be different.
