### ISSUE TITLE
Saturation function and reparameterization of gamma

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#277]
Hi, 

the saturation functions one can find in scientific literature MMM are always for data scaled between 0-1

you reparameterize internally the gamma parameter to make data scale-invariant. right?

what would be the solution if I want to use other saturation functions, for example, logistic with only a slope parameter?

Thanks

**Comment by gufengzhou** [comment]
Hi, Hill function is our saturation function that is two-parametric alpha and gamma in Robyn. When you restrict alpha <1, you'll get the logistic shape. 

Adding extra saturation function is also possible but bit more complicated, because it changes the hyperparameters and you will have to adapt the Nevergrad implementation too.

**Comment by slavakx** [comment]
Hi, thanks for your reply. My question was more theoretical. If I had to model any saturation function like power or negative exponential (which have 1 parameter). What would be the solution of reparameterizing the parameter to make it scale-invariant?

**Comment by gufengzhou** [comment]
Ah ok, well in our implementation, we always require users to input lower and upper bounds for hyperparameters that includes saturation parameters. For example, shape and scale are the two weibull adstock parameters (i know it's not saturation the the analogy holds), while shape can be theoretically 0 to +Inf. By requiring/recommending boundes, 0-3 for example for our weibull_pdf function, you can easily rescale it. In our case, we set all hyperparameter spaces in nevergrad to   be always 0-1. So it's easy to go from 0-3 to 0-1. Does it make sense to you?

**Comment by slavakx** [comment]
It makes sense and I understand why with your approach you set the hyperparameters to be 0-1. 
The flexibility of your approach comes from the reparameterization of the saturation function. So you don't need to somehow scale your data and you can apply it to original data. Moreover the alpha/gamma will be reported always with same range independent of data
What frustrates me is the following hypothetical scenario (outside of Robyn space): I want to apply any of the available saturation functions on channels with different magnitudes. It will require knowing apriori the range of possible parameters because gamma 0-1 will not work out of the box. The consequence is that these alpha/gammas will have completely different ranges and they will be applicable only to the data used to infer them. So it will be also difficult to compare Saturation plots. 
Am I right on these points?

**Comment by gufengzhou** [comment]
Yes you're right. If you search within Robyn you will find a variable called gammaTrans, where I basically scale 0-1 to the respective magnitude of the predictors. This is also one restriction of MMM in general: let's say you spend 1-10k weekly, after adstocking it becomes 2-20k for example, so gammaTrans's upper bound will become 20k. But you won't get a meaningful saturation for 100k spend level. You can't model what's never been there.
`  gammaTrans <- mapply(function(gamma, x) {
    round(quantile(seq(range(x)[1], range(x)[2], length.out = 100), gamma), 4)
  },
  gamma = gammas,
  x = chnAdstocked
  )`
