### ISSUE TITLE
Calibration methodology

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#278]
I have to say that I learn a lot from your MMM implementation and methodology. 

I have never used calibration before. 
Can you please suggest any sources/articles/research on calibration methodology in MMM to deepen my knowledge? 

Thanks!

**Comment by gufengzhou** [comment]
Thanks! Very happy to know that it's helpful. 

There're different options to do calibration. This is a whitepaper 

https://www2.deloitte.com/content/dam/Deloitte/es/Documents/estrategia/Deloitte-es-estrategia-y-operaciones-combinacion-mmm-cle.pdf

Here you can also find more details about calibration https://en-gb.facebook.com/business/news/insights/considerations-for-creating-modern-marketing-mix-models
