### ISSUE TITLE
How frequently do you suggest using Robyn for model retrain and predict with new data?

### ISSUE THREAD

**Issue by Joshuacourse** [facebookexperimental/Robyn#281]
Hi Robyn support team,

The official documentation  (https://facebookexperimental.github.io/Robyn/) of Robyn mentions that Robyn enables frequent modeling outcomes due to stronger automation. My question is how frequently do you suggest using Robyn for model retrain and predict with new data? Could we do it weekly?

Best
Josh

**Comment by gufengzhou** [comment]
Hi, you can use robyn_refresh even daily if you have daily data

**Comment by gufengzhou** [comment]
please reopen if necessary
