### ISSUE TITLE
Data Requirement of Robyn

### ISSUE THREAD

**Issue by Joshuacourse** [facebookexperimental/Robyn#282]
Hi Robyn support team,

Typically, MMM would require at least 3 years of data to start the modeling process. Robyn is designed to use less data for more frequent updates to catch up with the ever-changing media landscape. We are wondering how many years of data are required to build a robust model based on Robyn. 

Best
Josh

**Comment by gufengzhou** [comment]
Hi, we recommend to input as much data as you have. But with the window_start and window_end parameters, you can specify a shorter period to build the model. Assuming you have 3 years of daily data and use the last year to build the model, robyn will derive trend/season and apply adstocking for the whole 3 years of data, while doing saturation transform and running the model only on the last year. Also, we recommend a columns vs rows ratio of 1:10 as rule of thumb. If you have 10 independent variables, we recocmmend to have at least 100 days of data. Hope it helps.

**Comment by Joshuacourse** [comment]
Hi, Robyn support,

Thank you for your reply!

I have a follow-up question.  If I have 10 independent variables,
you recommend having at least 100 days of data. Should the granularity of
data be daily or could be weekly?  What is the data granularity best
practices?

Best
Josh

**Comment by gufengzhou** [comment]
Yes it can be weekly too, so 100 weeks. For monthly it'll be 100 months

**Comment by gufengzhou** [comment]
please reopen if necessary

**Comment by Joshuacourse** [comment]
Hi Robyn developer,

if we only have conversion daily data for 3 years and that data is sparse since conversions didn’t happen every day, only one of the media channels was active over the entire 3 yr period while adv on other media started mid-way in the last 3 yr period. (1) Would a daily data model based on 18 months work? 
(2) Would only Prophet vars be calculated based on 3 yrs or would adstock and saturation for the one channel
that was active all 3 hrs be also calculated based on entire data?
(3) Would a daily model be advisable in such a scenario or a weekly model?

**Comment by SahanaVardhan** [comment]
Hi Robyn Support Team, 

By Deafult, Robyn builds a National level model where input data is at week level or month level (weekly, monthly or daily data). The question is can Robyn build the model at customer_id X year-month level of data? 
If so what are the changes to be made and how accurate and complex would the model be?
Is it feasible to run on customer_id level?
