### ISSUE TITLE
Response curve and mean spend by channel

### ISSUE THREAD

**Issue by jbender5** [facebookexperimental/Robyn#284]
## Describe issue
'Response curve and mean spend by channel' plot does not output a decay curve that meets expectation. The range of the x-axis far exceeds spend for any of the media channels inputted. It also unclear if the y axis, 'response' represents media weight or the dependent variable in the model. If it represents the dependent variable, the range is below expectation. If this is a simple scaling issue that I need to adjust within the plot's x-axis, please let me know. If not, any advice would be appreciated.

## Provide dummy data & model configuration
I attached a screenshot of the 'Response curve and mean spend by channel' 

## Environment & Robyn version
R version 1.4.1717
Robyn version 3.4.8
<img width="341" alt="Response curve and mean spend by channel" src="https://user-images.githubusercontent.com/49889895/151861694-bad44c3a-5cf3-43cc-a422-9d6275b5474d.png">

**Comment by jbender5** [comment]
After reviewing further, there appears to be a data quality issue for one of the media channels and corresponding spend which is impacting the overall y axis and x axis boundaries of the outputted chart.

**Comment by laresbernardo** [comment]
Glad you sorted that out yourself @jbender5 
Do you mind sharing your data quality issue? We could implement an automatic check so to warn users when this is their case as well.

**Comment by jbender5** [comment]
Sure, this is in regard to our direct mail channel in which relatively significant spend occurs on approximately 7 days over the entire two year window_start through window_end period. The media weight, in this case exposures to the mailing, occurs based on estimated delivery date shortly after spend was inputted for a particular date. My thought is that spend for this campaign needs to be distributed proportionately to estimated mail exposures. Rather than how the data was originally structured  i.e. 01/01/1900 spend = $100k IMPS = 0; 01/02/1900 spend = $0 IMPs = 10k. After removing direct mail altogether from the model, the response curves, met my expectation as the x axis range of the plot decreased to fit the data. I plan to reinstate direct mail post conversation with my team.

I agree that a warning message would be beneficial in regard to the relationship between channel spend and media weight discrepancy
