### ISSUE TITLE
Multi cores

### ISSUE THREAD

**Issue by adschem** [facebookexperimental/Robyn#287]
## Describe issue
Using the demo script I only seem to be able to run the code using a single core, even though I have this set to 6 (out of 16 avalible) I have also tried setting this to 12 and 16 with no effect. 

I have also tried editing these two lines to see if this has any effect as per documentation

```
## force multicore when using RStudio
Sys.setenv(R_PARALLELLY_FORK_ENABLE="true")
options(parallelly.fork.enable = TRUE)
``` 

This is running on windows, in Rstudio :) 

Thanks

**Comment by gufengzhou** [comment]
Please review [this thread](https://github.com/facebookexperimental/Robyn/pull/217) about the parallel backend. Long story short, we're forced to use sequential mode on Windows due to large overhead in parallel.

**Comment by gufengzhou** [comment]
please reopen if necessary

**Comment by AdimDrewnik** [comment]
Any change to parallel Robyn behavior on Windows?
