### ISSUE TITLE
Seasonality extraction using weekly data

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#288]
Hi, 

looking into the prophet code, the yearly seasonality period is hardcoded at 365.25. 
The paper also says 
>Let P be the regular period we expect the time series to have (e.g.
P = 365.25 for yearly data or P = 7 for weekly data, when we scale our time variable in days

Since MMM data is usually on a weekly basis, there should be some mismatch in seasonality extracted by Prophet unless it rescales the data as if it was on a daily basis with missing values in between?

**Comment by gufengzhou** [comment]
Hi, looking at [this thread from prophet](https://github.com/facebook/prophet/issues/819), my understanding is that we're good/don't need to specify freq as long as we're not running make_future_dataframe.

**Comment by gufengzhou** [comment]
please reopen if necessary
