### ISSUE TITLE
Installing Robyn: issue with dependencies

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#289]
## I re-installed Robyn due to package changes.    Having issues installing.  Here is the error I am getting 

The downloaded source packages are in
	‘C:\Users\ttodor\AppData\Local\Temp\Rtmp6N9opJ\downloaded_packages’
√  checking for file 'C:\Users\ttodor\AppData\Local\Temp\Rtmp6N9opJ\remotesd005307730b\facebookexperimental-Robyn-d37ec90\R/DESCRIPTION' ... 
-  preparing 'Robyn':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'Robyn_3.5.0.tar.gz'
   
ERROR: dependency 'lares' is not available for package 'Robyn'
* removing 'C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/Robyn'

## Environment & Robyn version
Using Anaconda.
R version:  RBase 3.6.1

**Comment by laresbernardo** [comment]
Hi @tgtod002 
Can you please share your `sessionInfo()`? Are you using windows?
It's weird because the package is actually [available in CRAN](https://cran.r-project.org/web/packages/lares/index.html). I'd like to better understand this issue.
Do you have [Rtools4](https://cran.r-project.org/bin/windows/Rtools/rtools40.html) installed? Rain-checking.

**Comment by tgtod002** [comment]
Here is session info.  I am using windows.  Don't have Rtools4 installed.  Will work on updating R to >4.0.0

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.24

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  Matrix_1.2-17   tools_3.6.1     yaml_2.2.0      Rcpp_1.0.7      remotes_2.4.1   grid_3.6.1      jsonlite_1.7.3  png_0.1-7      
[10] lattice_0.20-38
 The same, showing the RNGkind, but not the locale :
  print(sI, RNG = TRUE, locale = FALSE)
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rejection 
 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.24

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  Matrix_1.2-17   tools_3.6.1     yaml_2.2.0      Rcpp_1.0.7      remotes_2.4.1   grid_3.6.1      jsonlite_1.7.3  png_0.1-7      
[10] lattice_0.20-38
> toLatex(sI, locale = FALSE) # shortest; possibly desirable at end of report
\begin{itemize}\raggedright
  \item R version 3.6.1 (2019-07-05), \verb|x86_64-w64-mingw32|
  \item Running under: \verb|Windows >= 8 x64 (build 9200)|
  \item Matrix products: default
  \item Base packages: base, datasets, graphics, grDevices, methods, stats, utils
  \item Other packages: reticulate~1.24
  \item Loaded via a namespace (and not attached): compiler~3.6.1, grid~3.6.1, jsonlite~1.7.3, lattice~0.20-38, Matrix~1.2-17,
    png~0.1-7, Rcpp~1.0.7, remotes~2.4.1, tools~3.6.1, yaml~2.2.0
\end{itemize}

**Comment by laresbernardo** [comment]
Thanks. Can you also share `options("repos")`? To check if you're installing packages from CRAN repo.

**Comment by tgtod002** [comment]
options("repos")
$repos
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE

**Comment by laresbernardo** [comment]
Ok, that's how it should be. Checking [this issue](https://github.com/sparklyr/sparklyr/issues/230) before upgrading to R4.
What's the output when you run `install.packages("lares", repos = "http://cran.us.r-project.org")`?

**Comment by tgtod002** [comment]
install.packages("lares", repos = "http://cran.us.r-project.org")
also installing the dependency ‘openxlsx’


  There is a binary version available but the source version is later:
         binary source needs_compilation
openxlsx  4.2.3  4.2.5              TRUE

installing the source packages ‘openxlsx’, ‘lares’

trying URL 'http://cran.us.r-project.org/src/contrib/openxlsx_4.2.5.tar.gz'
Content type 'application/x-gzip' length 1340903 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'http://cran.us.r-project.org/src/contrib/lares_5.0.5.tar.gz'
Content type 'application/x-gzip' length 1630039 bytes (1.6 MB)
downloaded 1.6 MB

* installing *source* package 'openxlsx' ...
** package 'openxlsx' successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++  -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/include" -DNDEBUG  -I"C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/Rcpp/include"   -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/../../Library/mingw-w64/include"     -O2 -Wall  -march=x86-64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++  -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/include" -DNDEBUG  -I"C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/Rcpp/include"   -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/../../Library/mingw-w64/include"     -O2 -Wall  -march=x86-64 -mtune=generic -c helper_functions.cpp -o helper_functions.o
g++  -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/include" -DNDEBUG  -I"C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/Rcpp/include"   -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/../../Library/mingw-w64/include"     -O2 -Wall  -march=x86-64 -mtune=generic -c load_workbook.cpp -o load_workbook.o
load_workbook.cpp: In function 'Rcpp::CharacterVector getChildlessNode(std::string, std::string)':
load_workbook.cpp:925:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
     auto itr = 0;
     ^
load_workbook.cpp:925:10: error: 'itr' does not name a type
     auto itr = 0;
          ^
load_workbook.cpp:934:11: error: 'itr' was not declared in this scope
       if (itr == 0) begPos = begPos + begTag.length();
           ^
load_workbook.cpp:945:9: error: 'itr' was not declared in this scope
       ++itr;
         ^
make: *** [load_workbook.o] Error 1
ERROR: compilation failed for package 'openxlsx'
* removing 'C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/openxlsx'
Warning in install.packages :
  installation of package ‘openxlsx’ had non-zero exit status
ERROR: dependency 'openxlsx' is not available for package 'lares'
* removing 'C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/lares'
Warning in install.packages :
  installation of package ‘lares’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\ttodor\AppData\Local\Temp\RtmpoJ46B8\downloaded_packages’

**Comment by laresbernardo** [comment]
Ok, it seems `openxlsx` has an issue there. Can you repeat this process installing `openxlsx` and share the output?

**Comment by tgtod002** [comment]
install.packages("openxlsx", repos = "http://cran.us.r-project.org")

  There is a binary version available but the source version is later:
         binary source needs_compilation
openxlsx  4.2.3  4.2.5              TRUE

installing the source package ‘openxlsx’

trying URL 'http://cran.us.r-project.org/src/contrib/openxlsx_4.2.5.tar.gz'
Content type 'application/x-gzip' length 1340903 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'openxlsx' ...
** package 'openxlsx' successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++  -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/include" -DNDEBUG  -I"C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/Rcpp/include"   -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/../../Library/mingw-w64/include"     -O2 -Wall  -march=x86-64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++  -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/include" -DNDEBUG  -I"C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/Rcpp/include"   -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/../../Library/mingw-w64/include"     -O2 -Wall  -march=x86-64 -mtune=generic -c helper_functions.cpp -o helper_functions.o
g++  -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/include" -DNDEBUG  -I"C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/Rcpp/include"   -I"C:/Users/ttodor/ANACON~3/envs/rstudio/lib/R/../../Library/mingw-w64/include"     -O2 -Wall  -march=x86-64 -mtune=generic -c load_workbook.cpp -o load_workbook.o
load_workbook.cpp: In function 'Rcpp::CharacterVector getChildlessNode(std::string, std::string)':
load_workbook.cpp:925:5: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
     auto itr = 0;
     ^
load_workbook.cpp:925:10: error: 'itr' does not name a type
     auto itr = 0;
          ^
load_workbook.cpp:934:11: error: 'itr' was not declared in this scope
       if (itr == 0) begPos = begPos + begTag.length();
           ^
load_workbook.cpp:945:9: error: 'itr' was not declared in this scope
       ++itr;
         ^
make: *** [load_workbook.o] Error 1
ERROR: compilation failed for package 'openxlsx'
* removing 'C:/Users/ttodor/Anaconda31/envs/rstudio/lib/R/library/openxlsx'
Warning in install.packages :
  installation of package ‘openxlsx’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\ttodor\AppData\Local\Temp\RtmpoJ46B8\downloaded_packages’

**Comment by laresbernardo** [comment]
Ok, I suggest you google this and try different alternatives. I'm 99% sure that if you upgrade your R version it'll get fixed; but for the sake of understanding how to fix this for older R versions, can you please try [this](https://github.com/ycphs/openxlsx/issues/62#issuecomment-615137620) or [this](https://community.rstudio.com/t/unable-to-install-any-packages-in-r-how-to-fix-that/103759/6) or any other solution you find out and let us know if/what worked? Thanks :)

**Comment by tgtod002** [comment]
So, should I install Rtools4?

**Comment by tgtod002** [comment]
Worked.  Upgraded R to 4.1.2.   New version of Robyn installed.

**Comment by laresbernardo** [comment]
That's great. Did you install Rtools or no need? Only upgraded R? Thanks for letting us know

**Comment by tgtod002** [comment]
I just upgraded R.   
It looks like since I have R for Windows, I don't need RTools.  

See below from RTools download site:
_By default, R for Windows installs the precompiled “binary packages” from CRAN, for which you do not need Rtools.__
