### ISSUE TITLE
My changes to robyn_run are not taking effect

### ISSUE THREAD

**Issue by Jumabek** [facebookexperimental/Robyn#294]
Good day all, thank you so much for this wonderful tool

## Describe issue
I opened the robyn_run function through R-studio and modified as follows

![image](https://user-images.githubusercontent.com/4343873/152978508-9f7dc3c9-6122-49ab-be51-75c7b267f425.png)

However, when I run the following from demo.R, it is working same as before. After my change I was expecting it not to run after return(t0)
![image](https://user-images.githubusercontent.com/4343873/152979106-213617b3-f145-4e3a-8ed1-41e1aa2e83be.png)
My end goal is to add custom plot AIC for glmnet models. Hence, I want to robyn to recognize my custom code.

**Comment by Jumabek** [comment]
Noob mistake, after source ing in R-studio changes took an effect.

However, other functions are not recognized, I know once understood how source ing, R studio/ R scripting works, I can fix the issue. 

But, can anyone give me shorter wayout? I am really under the gun

**Comment by gufengzhou** [comment]
hi, Robyn is a package and the modification is bit different than changing raw script. The best way would be cloning Robyn to your private repo, then clone the repo to local, then open Robyn.Rproj in your local path /Robyn/R/, then change the functions as you like, then run the check and the Install and Restart on your panel as in screenshot. Now you have modified the package on your local machine
<img width="284" alt="image" src="https://user-images.githubusercontent.com/14415136/153017679-ed2e029a-04c4-4375-8749-77fe2de070fc.png">

**Comment by laresbernardo** [comment]
Be sure to be using the project as Gufeng mentioned or set your working directory manually to where your DESCRIPTION file is (`setwd("~/your/directory")`

**Comment by Jumabek** [comment]
Thank you so much @gufengzhou @laresbernardo, you really saved me a lot of time, and increased robyn users +1
