### ISSUE TITLE
Prophet holiday effect not showing when turned on

### ISSUE THREAD

**Issue by Joshuacourse** [facebookexperimental/Robyn#297]
Hi Facebook Robyn developer,

We set 
prophet_vars = c("trend","season","holiday") 
prophet_signs = c("default","positive","negative") 
prophet_country = "US"

and found that in the prophet_decomp.png file the holiday effect is not showing up (a horizontal line at 0). We adjusted the holiday prophet_sign to  "default" and still saw the same result (see screenshot). We wonder if there exist any parameter inputs that overwrite the prophet setting. 
![prophet_decomp](https://user-images.githubusercontent.com/17748660/153283179-ad1125ea-d230-4bd1-9b1e-7e18a03d7c23.png)

Best
Josh

**Comment by gufengzhou** [comment]
hey thanks for raising this. would you please try setting prophet_signs  to all default and let us know?

**Comment by Joshuacourse** [comment]
Thank you for the suggestion! We tried setting prophet_signs to all default
and still see that there is no holiday effect. The prophet_decomp.png is
attached for your reference.


Best
Josh

**Comment by gufengzhou** [comment]
This is strange. Although there's no guarantee that it'll be an effect if there's no pattern during holidays. If you're assume this might be a bug, we would need a reproducible dataset (real value masked) and your demo.R script for model specification to check.

**Comment by laresbernardo** [comment]
Sure. You can send it to gufengzhou and bernardolares @fb.com so we can check it out

**Comment by cynthia10wang** [comment]
@gufengzhou @laresbernardo @Joshuacourse 

Hey guys, I have the same issues when my data's date is weekly starting from Sunday. I think it's a problem with the codes in inputs.R where it checks the week_start should be Monday or Sunday but the formula later on changes the date only to Monday.

I'll try manually setting my date variable to be Monday and see whether that can be a workaround.
`if (intervalType == "week") {
    weekStartInput <- lubridate::wday(dt_transform$ds[1], week_start = 1)
    if (!weekStartInput %in% c(1, 7)) stop("Week start has to be Monday or Sunday")
    dt_holidays$dsWeekStart <- floor_date(dt_holidays$ds, unit = "week", **week_start = 1**)
    holidays <- dt_holidays[, .(ds = dsWeekStart, holiday, country, year)]
    holidays <- holidays[, lapply(.SD, paste0, collapse = "#"), by = c("ds", "country", "year"), .SDcols = "holiday"]
  }`

**Comment by cynthia10wang** [comment]
@Joshuacourse by the way after I changed my weekly data's date to Monday, then it works and holiday effect is showing up. Not sure whether yours is weekly too.
