### ISSUE TITLE
Hard coded file output location

### ISSUE THREAD

**Issue by perfectsine** [facebookexperimental/Robyn#3]
# Issue
Hard coded file output location
https://github.com/facebookexperimental/Robyn/blob/master/source/fb_nextgen_mmm_v20.0.exec.R#L148

# Steps to Reproduce
Launch fb_nextgen_mmm_v20.0.exec.R

# Expected Behavior
File output to working directory or source directory.

# Actual Results
"No such file or directory: '/Users/gufengzhou/Documents/mmm.tempout.csv'"

# Environment
R version (R --version)
3.6.3

**Comment by gufengzhou** [comment]
good one, thx! will include this in the next update.
