### ISSUE TITLE
Robyn Refresh Prophet Component

### ISSUE THREAD

**Issue by F1nalFortune** [facebookexperimental/Robyn#306]
## Issue
Currently facing issue of running robyn refresh function without any prophet components (the parameters prophet_vars and prophet_signs of robyn_inputs have been commented out)

Error came up after running robyn refresh function.  (Only seeing this error when not using prophet variables)

`Error: Insufficient values in manual scale. 29 needed but only 28 provided.`

Here's the backtrace:

`> rlang::last_error()`
<error/rlang_error>
Insufficient values in manual scale. 29 needed but only 28 provided.
Backtrace:
  1. Robyn::robyn_refresh(...)
  2. ggplot2::ggsave(...)
  4. ggplot2:::grid.draw.ggplot(plot)
  6. ggplot2:::print.ggplot(x)
  8. ggplot2:::ggplot_build.ggplot(x)
  9. base::lapply(data, scales_map_df, scales = npscales)
 10. ggplot2:::FUN(X[[i]], ...)
 12. base::lapply(scales$scales, function(scale) scale$map_df(df = df))
 13. ggplot2:::FUN(X[[i]], ...)
 14. scale$map_df(df = df)
 15. ggplot2:::f(..., self = self)
 16. base::lapply(aesthetics, function(j) self$map(df[[j]]))
 17. ggplot2:::FUN(X[[i]], ...)
 18. self$map(df[[j]])
 19. ggplot2:::f(..., self = self)
 20. self$palette(n)
 21. ggplot2:::f(...)`

**Comment by Joshuacourse** [comment]
@laresbernardo Thank you. We followed your recommendation and the palette issue was gone. However, there is another error came while we were using the robyn_refresh. The rf1, rf2, rf3 were running successfully. But for rf4 there was error and the folder was not created. Error message below:

>>> Refresh model nr.3 loaded
>>> Refreshing model nr. 4 in auto mode. 0 more to go...
Error in if (newLowB < initBounds[hypNames[h]][[1]][1]) { : 
  argument is of length zero

**Comment by gufengzhou** [comment]
Hi, can you please share the following info 
`
MyRobyn <- readRDS(robyn_object)
MyRobyn$listRefresh2$InputCollect$hyperparameters
MyRobyn$listRefresh3$InputCollect$hyperparameters
`

**Comment by gufengzhou** [comment]
Ok there's no obvious error so far. Must be an edge case. Could you please rebuild the initial robyn_run (you can use less iterations for faster testing) and select any one model, then re-run robyn_refresh and see if this bug repeats?

**Comment by F1nalFortune** [comment]
@laresbernardo 

> Hi @F1nalFortune You should be able to update the package and won't have this issue. I thought 28 colours was enough ha! Just updated to 42 (repeated) colour palette. Let us know if that worked out OK for you. To update: `devtools::install_github("facebookexperimental/Robyn/R")` and refresh your session

Thanks so much, this resolved the issue.

**Comment by guillemsala** [comment]
Hi!

I am having the exact same problem, and it seems to come from this 42 colour palette you're talking about -- my input dataset contains > 50 different channels. Here's the exact code just in case, again I'm trying to refresh a model. 

```
Error in `f()`:
! Insufficient values in manual scale. 51 needed but only 42 provided.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
In melt.data.table(xDecompVecReportPlot[, .(ds, refreshStart, refreshEnd,  :
  'measure.vars' [actual, predicted, ...] are not all of the same type. By order of hierarchy, the molten data value column will be of type 'double'. All measure variables not of type 'double' will be coerced too. Check DETAILS in ?melt.data.table for more on coercion.
```
And I also wanted to ask -- is it possible that Robyn is not meant to be used with this many channels?

**Comment by laresbernardo** [comment]
Hi @guillemsala 
I've enabled 56 colours in the refresh plot palettes. Can you please update the dev version and check again? Are you sure 56 media variables makes sense? Maybe you could re-group some of them if they are too small / similar? Maybe it'd make sense to test this approach.
