### ISSUE TITLE
Is it possible to set MAPE as the objective function instead of NRMSE?

### ISSUE THREAD

**Issue by nscherbakovaspb** [facebookexperimental/Robyn#308]
## Describe issue
Describe your issue and provide error message 

## Provide dummy data & model configuration
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration.

## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version

**Comment by gufengzhou** [comment]
Hi, we believe rmse is a better measure for modelling error than mape and thus have no plan to change it. But you can of course change it by yourself
