### ISSUE TITLE
Robyn Download Error Msg: download from 'https://api.github.com/repos/facebookexperimental/Robyn/tarball/HEAD' failed

### ISSUE THREAD

**Issue by advisorita** [facebookexperimental/Robyn#309]
## I ran 
`remotes::install_github("facebookexperimental/Robyn/R")`
got the error message
download from 'https://api.github.com/repos/facebookexperimental/Robyn/tarball/HEAD' failed

## Environment & Robyn version
R version (4.1.2)

What can I do to resolve this?

**Comment by gufengzhou** [comment]
is there more error message you can share? if it's about rate limit, you should find many solutions by googling "install_github rate limit"

**Comment by laresbernardo** [comment]
@advisorita good news! Just found the solution to this issue. Please, set `options(timeout=400)` and retry. When we have slow connection there's not enough time for the download to happen, so we must extend the timeout default limit. Let me know how it goes.

**Comment by bergerita** [comment]
issue resolved!

**Comment by laresbernardo** [comment]
That's great, thanks for letting us know.
