### ISSUE TITLE
Difference Between xDecompPerc and Effect Share in pareto_aggregated.csv output?

### ISSUE THREAD

**Issue by andrewharukihill** [facebookexperimental/Robyn#312]
## Describe issue
Hi, thanks for building and maintaining this package

I've noticed that there is a slight difference between xDecompPerc and Effect share in the pareto aggregated output and was wondering if you could explain that difference? The waterfall chart in the model one-pager uses xDecompPerc and it makes it seem like that is describing effect share.

Thanks again

**Comment by gufengzhou** [comment]
Hi, please refer to the schema [here](https://github.com/facebookexperimental/Robyn/blob/main/demo/schema.R). Moreover, another subtle difference is that effect share is based on non-zero spending periods.
