### ISSUE TITLE
Michaelis-Menten Fitting warning message

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#315]
## Describe issue
After inputting hyper parameters in Robyn_inputs.   I am getting the following error.   

Trying to  understand what it means.   Please help

Michaelis-Menten fitting for CrossDeviceDisplayimpressions out of range. Using lm instead
Michaelis-Menten fitting for Cross_device_impressions out of range. Using lm instead
Michaelis-Menten fitting for DynamicMobileimpressions out of range. Using lm instead
Warning messages:
1: In summary.lm(modLM) :
  essentially perfect fit: summary may be unreliable
2: In summary.lm(modLM) :
  essentially perfect fit: summary may be unreliable
3: In summary.lm(modLM) :
  essentially perfect fit: summary may be unreliable

**Comment by laresbernardo** [comment]
Hi @tgtod002 They are actually warnings not errors, right?
Can you please update to latest version 3.6.0 (released today?). We've just updated default fitting media variables from `paid_media_vars` to `paid_media_spends`. Spend exposure fitting with Michaelis Menten function now serves only `robyn_response()` function outputs and plotting. `robyn_allocator()` only relies on "direct spend - response" transformation.

**Comment by laresbernardo** [comment]
Closing this ticket now. Let us know if you need further help

**Comment by CJ2407** [comment]
Hi,

I am using the latest version of Robyn, but I am still getting this warning - 
Should I be worried?

Michaelis-Menten fitting for DISPLAY_I out of range. Using lm instead

**Comment by laresbernardo** [comment]
Can you please make sure you did update to latest version and refresh your R session? I've just checked the code and there's no "Michaelis-Menten" warning (all previous code sections referring to this message are commented out).
