### ISSUE TITLE
3.6 Robyn_Run Issue

### ISSUE THREAD

**Issue by F1nalFortune** [facebookexperimental/Robyn#317]
## Issue
Issue arises when running robyn_run function.  Here's how I'm calling the robyn_run function:

```
OutputModels <- robyn_run(
  InputCollect = InputCollect # feed in all model specification
  , cores = 6 # default
  ,iterations = 6000 
  ,trials = 5 
  , outputs = FALSE
)
```

and here's the error:

```Input data has 200 weeks in total: ...
Initial model is built on rolling window of 200 week: ...
Using weibull_pdf adstocking with xx hyperparameters (xx to iterate + 0 fixed) on 1 core (Windows fallback)
>>> Starting 5 trials with 6000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
Error in seq.default(log(lambda_max), log(lambda_max * lambda_min_ratio),  : 
  'from' must be a finite number
```

The error is fixed when I comment out the prophet_vars with robyn_inputs, however, I would like to keep the prophet_vars in the model.  

## Environment & Robyn version
R version 4.1.2 (2021-11-01)
Robyn version Robyn_3.6.0

**Comment by laresbernardo** [comment]
Can you please share a reproducible example? There must be an issue with `lambda_max` calculation which is calculated on `Robyn:::lambda_seq()`. Do you have `NA` values in `dt_mod`? Can you share that data.frame as CSV, preferably anonymized?

**Comment by gufengzhou** [comment]
FYI We got the same issue in the FB group too, see [here](https://www.facebook.com/groups/robynmmm/posts/1141468243287974/). It's due to NA/Inf/-Inf values. Would you please see the post and check too?

**Comment by gufengzhou** [comment]
FYI we've just fixed this error. Let me know if adding back prophet works now https://github.com/facebookexperimental/Robyn/commit/d748aa7c33e10004061e7b394357da726a4763a3

**Comment by F1nalFortune** [comment]
@laresbernardo @gufengzhou Issue resolved!  Thanks for the support.

Best,
Brian

**Comment by ekenheim** [comment]
Having the same error message currently - fresh install of R (all packages updated)

**Comment by gufengzhou** [comment]
We just had a new release V3.8.0. Please try it out!
