### ISSUE TITLE
Issue running Robyn 3.6 with version of foreach package

### ISSUE THREAD

**Issue by Runsicker11** [facebookexperimental/Robyn#319]
## Describe issue
I am getting this error when I run the outputModels function:
Package ‘foreach’ version 1.5.1 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘foreach’ is imported by ‘doFuture’, ‘Robyn’, ‘glmnet’, ‘doRNG’, ‘doParallel’ so cannot be unloaded

## Provide dummy data & model configuration
Here is my setup for the function:

OutputModels <- robyn_run(
  InputCollect = InputCollect # feed in all model specification
  , cores = 3 # default
  #, add_penalty_factor = FALSE # Untested feature. Use with caution.
  , iterations = 2000 # recommended for the dummy dataset
  , trials = 5 # recommended for the dummy dataset
  , outputs = FALSE # outputs = FALSE disables direct model output
)
print(OutputModels)

## Environment & Robyn version
R version (4.1.2)
I just updated the Robyn 3.6

**Comment by gufengzhou** [comment]
Hi, have you tried restarting R session?

**Comment by Runsicker11** [comment]
Yeah, that seemed to fix it. Thank for your help!
