### ISSUE TITLE
Error in qunif(hyppar_for_qunif, min(channelBound), max(channelBound))

### ISSUE THREAD

**Issue by dbs700** [facebookexperimental/Robyn#32]
Hello,

Thanks for a nice implementation of MMM. I installed it successfully, but when I'm running the provided example, I'm getting this error (R 4.0.4; Win 10)

Running trial nr. 1 out of 40 ...

Running 500 iterations with evolutionary algorithm on geometric adstocking, 15 hyperparameters, 100 -fold ridge x-validation using 6 cores...

 Working with:  DiscreteOnePlusOne 
  |                                                                                                                                   |   0%Error in qunif(hyppar_for_qunif, min(channelBound), max(channelBound)) : 
  Non-numeric argument to mathematical function
Called from: qunif(hyppar_for_qunif, min(channelBound), max(channelBound))

**Comment by gufengzhou** [comment]
hi, have you installed anaconda and nevergrad already?

**Comment by dbs700** [comment]
Hi, 

Hm, that is strange. I installed it, then reboot it all and run again. And here the output


conda_install("r-reticulate", "nevergrad", pip=TRUE)  #  must install nevergrad in conda before running Robyn
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


 WARNING: A newer version of conda exists. <==
  current version: 4.8.1
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda



All requested packages already installed.

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nevergrad/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nevergrad/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nevergrad/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nevergrad/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nevergrad/
Could not fetch URL https://pypi.org/simple/nevergrad/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/nevergrad/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement nevergrad
ERROR: No matching distribution found for nevergrad
Error: Error installing package(s): "nevergrad"
>

**Comment by gufengzhou** [comment]
I have conda 4.9.2, so i'd say please update conda. also point the python file to reticulate using use_python("/Users/gufengzhou/Library/r-miniconda/envs/r-reticulate/bin/python3.6") --> the path has to be adapted of course

**Comment by dbs700** [comment]
I've upgraded conda, but the error was there until I added openssl.exe to the %PATH% environment variable of Windows.
So if anyone will have issues regarding SSL like this one:
SSLError("Can't connect to HTTPS URL because the SSL module is not available."))'))

Please upgrade conda and then add latest openssl to path. More info here 
https://stackoverflow.com/questions/54558389/how-to-solve-this-error-while-installing-python-packages-in-rstudio/54566647

Now it works! :)

**Comment by gufengzhou** [comment]
Thanks for sharing! I'll add this information into our documentation. Let us know how it works for you:)
