### ISSUE TITLE
Error Installing Robyn 3.6.0

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#320]
## Describe issue
I am installing Robyn 3.6.0.   I am getting the following error message using the following 

remotes::install_github('facebookexperimental/Robyn/R')

This is the error message I am getting

Installing package into ‘C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
ERROR: failed to lock directory 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1' for modifying
Try removing 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1/00LOCK-Robyn'
Warning messages:
1: In readLines(file, skipNul = TRUE) :
  cannot open compressed file 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1/lares/DESCRIPTION', probable reason 'No such file or directory'
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\colorspace\libs\x64\colorspace.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\colorspace\libs\x64\colorspace.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\cli\libs\x64\cli.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\cli\libs\x64\cli.dll: Permission denied
4: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\glue\libs\x64\glue.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\glue\libs\x64\glue.dll: Permission denied
5: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\jsonlite\libs\x64\jsonlite.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\jsonlite\libs\x64\jsonlite.dll: Permission denied
6: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\dplyr\libs\x64\dplyr.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\dplyr\libs\x64\dplyr.dll: Permission denied
7: In i.p(...) : installation of package ‘lares’ had non-zero exit status
8: In i.p(...) :
  installation of package ‘C:/Users/ttodor/AppData/Local/Temp/Rtmp2NrhG1/file27145a11392/Robyn_3.6.0.tar.gz’ had non-zero exit status

## Environment & Robyn version
R version (R 4.1.2 )
Please make sure you're using the latest Robyn version

**Comment by laresbernardo** [comment]
That's odd. Try removing this file 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1/00LOCK-Robyn'. Restart your R session and try again.

**Comment by tgtod002** [comment]
Took out the directory 00LOCK-Robyn as suggested.  Still getting an error.  See below:

The downloaded source packages are in
	‘C:\Users\ttodor\AppData\Local\Temp\Rtmp27b5gH\downloaded_packages’
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\ttodor\AppData\Local\Temp\Rtmp27b5gH\remotes33bc17ae3956\facebookexperimental-Robyn-d748aa7\R/DESCRIPTION' (484ms)
-  preparing 'Robyn':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'Robyn_3.6.0.tar.gz'
   
Installing package into ‘C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
ERROR: dependency 'lares' is not available for package 'Robyn'
* removing 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1/Robyn'
Warning messages:
1: In readLines(file, skipNul = TRUE) :
  cannot open compressed file 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1/lares/DESCRIPTION', probable reason 'No such file or directory'
2: In readLines(file, skipNul = TRUE) :
  cannot open compressed file 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1/lares/DESCRIPTION', probable reason 'No such file or directory'
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\colorspace\libs\x64\colorspace.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\colorspace\libs\x64\colorspace.dll: Permission denied
4: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\cli\libs\x64\cli.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\cli\libs\x64\cli.dll: Permission denied
5: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\glue\libs\x64\glue.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\glue\libs\x64\glue.dll: Permission denied
6: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\jsonlite\libs\x64\jsonlite.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\jsonlite\libs\x64\jsonlite.dll: Permission denied
7: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\00LOCK\dplyr\libs\x64\dplyr.dll to C:\Users\ttodor\OneDrive - Vericast\Documents\R\win-library\4.1\dplyr\libs\x64\dplyr.dll: Permission denied
8: In i.p(...) : installation of package ‘lares’ had non-zero exit status
9: In i.p(...) :
  installation of package ‘C:/Users/ttodor/AppData/Local/Temp/Rtmp27b5gH/file33bc75f92de/Robyn_3.6.0.tar.gz’ had non-zero exit status
> library(robyn)
Error in library(robyn) : there is no package called ‘robyn’
>

**Comment by laresbernardo** [comment]
Ok, I see two things here:
1. Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/
2. Notice that is "Robyn", not "robyn" for when it successfully gets installed ;)

**Comment by tgtod002** [comment]
Could this be the issue?
![Screenshot 2022-02-24 104823](https://user-images.githubusercontent.com/69650410/155579535-26102278-1075-45f5-94c0-e2ac12e9f389.png)

**Comment by laresbernardo** [comment]
Ok, also delete both versions please, and retry installing Robyn!

**Comment by tgtod002** [comment]
Success!  
Here is what I did:
1.  I did not have to install RTools.   Looked at RTools Documentation.  _"By default, R for Windows installs the precompiled “binary packages” from CRAN, for which you do not need Rtools._

2. I deleted  'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1' for modifying
Try removing 'C:/Users/ttodor/OneDrive - Vericast/Documents/R/win-library/4.1/00LOCK-lares'

3.  Re-installed Lares via RGui(32bit)  using packages -->  install packages --> lares

4. Ran _remotes::install_github('facebookexperimental/Robyn/R')_
