### ISSUE TITLE
Error running f.robyn() 

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookexperimental/Robyn#33]
## Issue

Error when running `model_output_collect`: " Error in { : task 1 failed - "'from' must be a finite number" 
![image](https://user-images.githubusercontent.com/65649681/111151904-002e1a80-8588-11eb-81ce-0c0f52013a82.png)

## Steps to Reproduce
- custom dataset
- `str(set_hyperBoundLocal)`= list of 33

## Expected Behavior
I expect the model to run 
## Actual Results
see error message above
## Environment

R version (R 4.0.3)

**Comment by gufengzhou** [comment]
hey, we're looking into this case now. it does not always occur and thus bit difficult to debug for us. we'll report back asap. also, please make sure the set_hyperBoundLocal is set correctly (right names using local_name, right bounds according to guide) and set_mediaVarName and set_mediaSpendName are set correctly

**Comment by LeoUbbiali** [comment]
Thanks @gufengzhou .

Further context if it can help:
 - I have a 1to1 mapping between set_mediaVarName and set_mediaSpendName (aspend metric for each pressure metric)
 - adstock = 'geometric'
![EED4C5C9-9421-4626-8441-0A44B104FFDF](https://user-images.githubusercontent.com/65649681/111304967-4d74bf80-864e-11eb-9572-8b43de276234.jpeg)

**Comment by gufengzhou** [comment]
I think we found the root cause. What train/test split are you using/ what value do you put in set_modTrainSize? One extreme example, you have 2 years data and one media channel didnt have any spend until 2 recent months. When you set set_modTrainSize = 0.8, that media channel will only contain 0 in the training set and that causes problem in the transformation. What you can already do is set appropriate training split by looking at the plot f.plotTrainSize(T), the higher the bhatta coef the better. Basically you should avoid any channel only containing 0 in the train set.  I'll push a fix to warn this condition

**Comment by LeoUbbiali** [comment]
Yep. That's likely to be the issue. I have channel that were switched on only recently.
I'll play around with f.plotTrainSize(T) to find the best bhatta coef and comeback to you

**Current train-test split**
set_modTrainSize <- 0.74

**Comment by LeoUbbiali** [comment]
I got this output with `f.plotTrainSize(T)'.
I have channels with data only for the last couple of months so I'll work backwords by trying a model with data for most of the weeks (rows) 
![image](https://user-images.githubusercontent.com/65649681/111340471-9178bc00-8670-11eb-838f-3deaba3625ef.png)
` 
![image](https://user-images.githubusercontent.com/65649681/111340424-83c33680-8670-11eb-8fcd-d52d4740da4b.png)

**Comment by LeoUbbiali** [comment]
Issue resolved by aggregating/remove channels containing 0 in the training set.
Thank you very much

**Comment by LeoUbbiali** [comment]
Issue resolved by aggregating/remove channels containing 0 in the training set.
Thank you very much

**Comment by gufengzhou** [comment]
FYI, I've pushed an update to deal with/better warn about situation where some media has many 0. Please use the new version. thanks again for the great use case.

**Comment by LeoUbbiali** [comment]
thanks. Updated and run successfully locally 🙌
