### ISSUE TITLE
Issue with Sundays as weekly starting dates

### ISSUE THREAD

**Issue by laresbernardo** [facebookexperimental/Robyn#340]
_Originally posted by @cynthia10wang in https://github.com/facebookexperimental/Robyn/issues/297#issuecomment-1065465679_

Hey guys, I have the same issues when my data's date is weekly starting from Sunday. I think it's a problem with the codes in inputs.R where it checks the week_start should be Monday or Sunday but the formula later on changes the date only to Monday.

I'll try manually setting my date variable to be Monday and see whether that can be a workaround.
```
if (intervalType == "week") {
    weekStartInput <- lubridate::wday(dt_transform$ds[1], week_start = 1)
    if (!weekStartInput %in% c(1, 7)) stop("Week start has to be Monday or Sunday")
    dt_holidays$dsWeekStart <- floor_date(dt_holidays$ds, unit = "week", week_start = 1) # HERE
    holidays <- dt_holidays[, .(ds = dsWeekStart, holiday, country, year)]
    holidays <- holidays[, lapply(.SD, paste0, collapse = "#"), by = c("ds", "country", "year"), .SDcols = "holiday"]
  }
```

**Comment by laresbernardo** [comment]
Hi @cynthia10wang 
Thanks for catching this potential bug. When checking on `floor_date()`'s documentation, notice that it takes a date-time vector and rounds it down to the nearest boundary of the specified time unit ("week" in this case). So, regardless of what your `weekStartInput` result is, whether 1 or 7, it transforms the `dt_holidays$ds` vector to start in Monday (`week_start  = 1`). That means all days will be shifted to Monday if they were Sunday, and kept as is when they are Monday already. Check out this small RE:
```
> floor_date(Sys.Date()) # Today (Monday)
[1] "2022-03-14 UTC"
> floor_date(Sys.Date(), unit = "week", week_start = 1) # Get first day of today's week, starting on Monday
[1] "2022-03-14"
> floor_date(Sys.Date(), unit = "week", week_start = 7) # Get first day of today's week, starting on Sunday
[1] "2022-03-13"
```
This said, were you having an error or issue when your dates were starting on Sundays (before you manually changed to Mondays)?

**Comment by laresbernardo** [comment]
Ok, thanks for confirming. I've found the bug and quite easy to fix. 
I've set demo.R's `dt_simulated_weekly$DATE <- dt_simulated_weekly$DATE - 1` (to change those Mondays to Sundays) and confirmed `InputCollect$dt_mod$holiday` it's not all zeroes now. Could you please update Robyn, retry and let us know if that worked out for you?

**Comment by cynthia10wang** [comment]
Hey Bernardo, confirming that this is fixed now. I'm able to see holiday effect with Sundays now.
