### ISSUE TITLE
positivity constraint on season not respected

### ISSUE THREAD

**Issue by drbenvincent** [facebookexperimental/Robyn#341]
I am running a model with the following options 
```r
prophet_vars = c("trend", "season", "holiday"),
prophet_signs = c("positive", "positive", "positive"),
```
but when I examine `pareto_alldecomp_matrix.csv` (and just focus on a particular model of interest) then I see both positive and negative values. The positivity constraint does not seem to be applied.

I'd be grateful if you could confirm that this is a bug. If it is, I'd be even more grateful if it could be fixed.

## Environment & Robyn version
R version 4.0.4
Robyn version 3.6.1 (installed by `remotes::install_github('facebookexperimental/Robyn/R')`)

**Comment by laresbernardo** [comment]
Checking [the code](https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R#L559-L587), I don't see any obvious error or bug. I'll further run a hypothetical check without your data to reproduce this scenario first before I get back to you.. thanks for reporting it.

**Comment by laresbernardo** [comment]
Hey @drbenvincent
We've internally discussed this specific case you mention and actually find it quite relevant. We think this is probably one of those very rare cases where it should probably be something only advanced users do and we generally try to discourage, given that forcing a sign for season/holiday logically may not make much sense in most scenarios.
I'd also like to share with you [this ticket](https://github.com/facebook/prophet/issues/1668) where `prophet`'s team discusses this matter with great detail and some illustrated examples.
CC: @Leonelsentana @kyletgoldberg

**Comment by drbenvincent** [comment]
Thanks for that link @laresbernardo. I'll work through that - it looks to touch on issues I've been thinking about.

Just a bit more on the motivation... I'm trying to produce a contribution plot, as in a stacked area plot over time which decomposes the total predicted outcome variable over time into its various component parts. You could argue that (regardless of the implementation details) it would be appealing (and should be possible) to plot the contributions over time from each channel, intercept, trend, seasonality, etc. 

So I'm a little uncertain at the moment if there _is_ a working positivity constraint or not?
But given that the seasonality component is producing positive and negative numbers that it's additive (not multiplicative). If so, I guess you _might_ get positive only contributions from `intercept+seasonality`. 

Either way, it should be possible to find the maths of the seasonality implementation (presumably in Prophet) that would allow generation of a contribution plot over time from the fitted parameters from Robyn.

**Comment by DzimitryM** [comment]
I observe the same issue.
Training the model with the "positive" constrains to all prophet variables results in negative effects at the decomposition waterfall. Some models have negative season effect, some models have negative effect of holidays and weekday.

_Robyn 3.6.3_

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
