### ISSUE TITLE
Cannot access Prophet's logistic trend

### ISSUE THREAD

**Issue by drbenvincent** [facebookexperimental/Robyn#342]
From a private email with @gufengzhou, we worked out that is is not possible to access Prophet's `logistic` trend. This is because the required hyper parameters `logistic_cap` & `logistic_floor` (see https://github.com/business-science/modeltime/issues/25 which @gufengzhou sent me) cannot be accepted into `robyn_inputs()`.

# Environment & Robyn version
R version 4.0.4
Robyn version 3.6.1 (installed by remotes::install_github('facebookexperimental/Robyn/R'))

**Comment by laresbernardo** [comment]
I've tested this approach and it seems to be working OK. Used `InputCollect <- robyn_inputs(..., growth = "logistic", logistic_cap = 300, logistic_floor = 0)` and the trend plot did NOT exceeded 300. Also fixed a `print` bug when using custom parameters.
Please confirm @drbenvincent, thanks!

**Comment by drbenvincent** [comment]
That's excellent @laresbernardo. Sorry for the slight pause - I will be able to review this in the next few days and get back to you.

**Comment by drbenvincent** [comment]
Yes, this works for me @laresbernardo. 

The only change I had to make to get it to run was adding `iterations` and `trials` parameters into `robyn_run()`. Previously they went into `robyn_inputs()` in my initial script.

**Comment by laresbernardo** [comment]
Perfect. Thanks for confirming. That's a change we did in version 3.6.0 given they are not actually part of the inputs but a modeling parameter. Glad you noticed! Cheers
