### ISSUE TITLE
Budget Allocation: budget constraint not hold

### ISSUE THREAD

**Issue by JiaMeihong** [facebookexperimental/Robyn#344]
## Project Robyn
As suggested by @kyletgoldberg, I create this issue below, which is likely to be caused by some bug of allocator. 

## Describe issue
I’ve tried both scenarios of history-based optimization and future optimization with given budget. 
My constraint over channels is (0.8,1.5) for each channel. 

I found 
1) in both of these cases, the optmResponseUnitTotalLift is negative. Meaning the uplift is negative after optimization. 
2) in the future optimization case, I believe expSpendUnitTotal >= optmSpendUnitTotal  should always hold, but the result shows differently. 

## Provide dummy data & model configuration
I've check the model result, it has a R2 above 0.75, and no coefficients of our interest is zero.
So I've detected no abnormality in the model. 

## Environment & Robyn version
R version (R --version): 4.1.2
Robyn version: latest version

**Comment by JiaMeihong** [comment]
@kyletgoldberg 
I think I found some clues. It turns out the order of model channels, and order of channels in allocator are different. And I think in budge allocator the spend share is matching to wrong channels names. 

I've checked input of my model, and found nothing wrong there. paid_media_spends, paid_media_vars and hyperparamters assignment are in the same order.

**Comment by laresbernardo** [comment]
[X-ref](https://www.facebook.com/groups/robynmmm/posts/1153839675384164/): Possibly connected with the same issue

**Comment by JiaMeihong** [comment]
@laresbernardo 
Hi thanks for your reply! I've tested using the branch you shared.
Part of problem is solved: Now the spend share are matching to the right channel names.
But two problems persist:
1. in the max_history case, after optimization, we increase spend share on channel 1, but the mean response of channel 1 decreased. This visualization is still confusing as some points are not lying on the response curve. 
2. in the max future expense case, still the optimizationUnitTotal > expenseUnitTotal. I wonder is it because my expenseUnitTotal is much smaller than Initial Spend unit Total? 

<img width="733" alt="Screen Shot 2022-03-17 at 9 48 35" src="https://user-images.githubusercontent.com/19406334/158714669-278ca78f-8722-4848-a10f-66035b6a3c86.png">

**Comment by laresbernardo** [comment]
Hi @JiaMeihong 
0. Glad to know we at list fixed that first issue :) 
1. I can't seem to replicate those cases where the values are plotted outside the curves. I even set `channel_constr_low = runif(5, 0, 1)` and `channel_constr_up = runif(5, 1, 5)` and ran 10 random simulations and none plotted values outside the curve. I've also re-checked the code if we are sorting the variables and constraints before optimizing. I've slightly changed some code in that branch, maybe try updating the branch version again and retry, please. If not, let me know how can I replicate your case.
2. What do you mean? `optmSpendUnitTotal` values and `expSpendUnitTotal` (exp for expected, not expense) right? So the first one mentioned is the sum of the optimized results (optimal spend) and the second the sum of the expected spend for the period specified. They both depend on your `expected_spend` and `expected_spend_days` inputs. Do they make sense?

**Comment by JiaMeihong** [comment]
Hi @laresbernardo 
Thanks for your reply!
1) I've tried with case of max_history, but still in my data, the dot is outside the line. I've tried with test data provided by Robyn, and for test data, it seems to work fine. Would it be possible I share with you my data, and you test with it?
2) Yes, I give the `expected spend` and `expected inputs`, and expect the optimized budget <= total budget give, and in my understanding,  `expSpendUnitTotal >= optmSpendUnitTotal `should always hold, but the result shows differently. Is it a bug or it's designed to be so?

**Comment by laresbernardo** [comment]
Yes, I think sharing your data will def help me debug this. You can [send it to me](marilto:bernardolares@fb.com) and I'll do my best to understand what's happening there. Share the data file and script you are running so I can replicate it exactly, please.

**Comment by laresbernardo** [comment]
Feel free to re-open if the error or issue persists @JiaMeihong
