### ISSUE TITLE
"'names' attribute [11] must be the same length as the vector [8]"

### ISSUE THREAD

**Issue by robyn007** [facebookexperimental/Robyn#346]
## Describe issue
After running the demo file with demo data, I get the following error:
`"'names' attribute [11] must be the same length as the vector [8]"
`
I'm using the demo.R file provided.

## Environment & Robyn version
R version 4.1.2 (2021-11-01)
Robyn version ‘3.6.1’

**Comment by laresbernardo** [comment]
Feel free to re-open if this particular error or issue persists when updating to 3.6.2 @robyn007 (love your username)
