### ISSUE TITLE
adstock function

### ISSUE THREAD

**Issue by cynthia10wang** [facebookexperimental/Robyn#347]
Hi, I have 2 questions about the adstock function:

1) is the carry-over effect only working for next week? would it make more sense to actually have another hyperparamter to change how many weeks the carry-over effect would last? I'm asking because I have a few offline channels in my case where let's say a campaign is on radio for 2 weeks off for a week and on for another 2 weeks etc. for a campaign period, and I orginally thought the transformation would make the inputs smoother as I was travelling with something more like the geo-decay function here in the past: https://github.com/leopoldavezac/BayesianMMM. Any suggestions then for my case how to treat those spends flucuation week by week? Btw - we don't have exposure metrics for that channel.

2) I know someone asked about the delayed feature in the past (issue #121 ) but you guys didn't prioritize it as not a lot of people asked. I'm checking again to see whether this is something on your plan now? Similar to the case in the first question, we have quite a lot spend on offline channels where we don't have exposures/GRPs metrics, but we're trying to use sales as dependent variables. As these offline channels normally don't impact the sales at least 1-2 weeks later, having this feature would help to interpret the offline channel spend efficiency more accurately I think. 

Thanks,
Cynthia

**Comment by kyletgoldberg** [comment]
@cynthia10wang I was mistaken on question 2 - check the adstock sample charts for the Weibull CDF and PDF, it will show you the differences and that there can be some abiilty to delay the adstock. My apologies!
