### ISSUE TITLE
Unable to run f.inputWrangling() 

### ISSUE THREAD

**Issue by ggplotter** [facebookexperimental/Robyn#35]
Within fb_robyn.exec.R I am getting this error message while trying to run 

dt_mod <- f.inputWrangling()

The error message says:

Error in loadNamespace(name) : there is no package called ‘rstan’ 

Error traceback:

13.stop(cond) 
12.doWithOneRestart(return(expr), restart) 
11.withOneRestart(expr, restarts[[1L]]) 
10.withRestarts(stop(cond), retry_loadNamespace = function() NULL) 
9.loadNamespace(name) 
8.getNamespace(ns) 
7.asNamespace(ns) 
6.getExportedValue(pkg, name) 
5.rstan::optimizing 
4.do.call(rstan::optimizing, args) 
3.fit.prophet(m, df, ...) 
2.prophet(recurrance, holidays = if (use_holiday) {
    holidays[country == set_country]
} else {
    NULL ... at fb_robyn.func.R#471
1.f.inputWrangling() 

Is the rstan library required? I didn't see it in the library list

**Comment by gufengzhou** [comment]
It's actually dependency of prophet and should be installed automatically. But seems like I'm wrong for some cases. Yes please install rstan too. I'll add it to the library list.

**Comment by gufengzhou** [comment]
just added it to the library. thanks for flagging
