### ISSUE TITLE
Refresh vs. Predict

### ISSUE THREAD

**Issue by cynthia10wang** [facebookexperimental/Robyn#351]
Hi, I've read through a few past issues and it seems like we still don't have a predict feature now? I'm wondering how I can manually calculate that then for the model I select. For example, My original data already includes let's say 208 weeks of data but I'm only using 200 weeks for my initial model. When I'm trying to see how the model fits for the next 8 weeks - I know the coefficients for all the variables now, but I wonder how do I get the media tranformation from there? It seems like robyn_refresh will refresh newer window data with different hyperparameters again instead of using the previous model parameters...

**Comment by laresbernardo** [comment]
Hi @cynthia10wang 

We will develop a prediction feature later this year, but we are not there yet. We still have to figure out how to avoid bias and overfitting in a semi-automated way before we deploy a scalable solution to everyone.

The `robyn_refresh()`  builds updated models based on the previously built models saved in the Robyn.RDS object we export in previous steps; it does not predict. When updating the initial build with, for example, 4 weeks of new data, `robyn_refresh()` consumes the selected model of the initial build, sets lower and upper bounds of hyperparameters for the new build around the selected hyperparameters of the previous build, stabilizes the effect of baseline variables across old and new builds, and regulates the new effect share of media variables towards the latest spend level. It returns the aggregated results with all previous builds for reporting purposes and produces reporting plots.

So this "predict" function not yet developed would use data from "the future" which hasn't been used to train the model or refresh the initial model, with features you'd know from the feature. We'll definitely let users know when we have this ready.

**Comment by laresbernardo** [comment]
It's an enhancement we will be working on and sharing once it's done. Closing ticket.

**Comment by iuiu34** [comment]
Any update on this one? 
it's 2024 already (+1.5 year)
