### ISSUE TITLE
Error in object[[name, exact = TRUE]] : subscript out of bounds

### ISSUE THREAD

**Issue by jsatani-tonal** [facebookexperimental/Robyn#359]
## Describe issue
Error in object[[name, exact = TRUE]] : subscript out of bounds --> getting this issue due to hyperparameters not getting added into inputCollect

## Provide dummy data & model configuration
The data does not have any issues, I Was able to run this same dataset before, the only thing is now I added in more media channel columns which I did not use before. I had an issue with the way the media variables were named (it did not like more than 1 underscore so I renamed everything to _s and _i for media variables and took out any other underscores and it fixed itself) but now im getting the same issue again

## Environment & Robyn version
R version (R --version)
3.6

Error here!!
```
> InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)
Michaelis-Menten fitting for fbprosp_I out of range. Using lm instead
Michaelis-Menten fitting for yt_I out of range. Using lm instead
Michaelis-Menten fitting for disc_I out of range. Using lm instead
Error in object[[name, exact = TRUE]] : subscript out of bounds

```
This is the original input collect
```

> print(InputCollect)
Total Observations: 167 (weeks)
Input Table Columns (41):
  Date: week
  Dependent: orders [conversion]
  Paid Media: psoc_I, fbprosp_I, fbrmkt_I, nbsearch_C, bsearch_C, shop_C, drtv_I, yt_I, disc_I, native_I, brandtv_I, brandott_I, drott_I
  Paid Media Spend: psoc_S, fbprosp_S, fbrmkt_S, nbsearch_S, bsearch_S, shop_S, drtv_S, yt_S, disc_S, native_S, brandtv_S, brandott_S, drott_S
  Context: covidfear, promo, shiptimes
  Organic: 
  Prophet (Auto-generated): trend, season on US
  Unused: categoryint, compsearch, newwebvisit, search_S, search_I, ytdisc_S, ytdisc_I, brpod_S, drdmail_S, brpp_S

Date Range: 2019-01-07:2022-03-14
Model Window: 2021-10-04:2022-03-14 (24 weeks)
With Calibration: FALSE
Custom parameters: None

Adstock: geometric
Hyper-parameters: Not set yet

```

These are my ad stocks - I used the hyper names so it should be proper

```
`> hyper_names(adstock = InputCollect$adstock, all_media = InputCollect$all_media)
 [1] "brandott_S_alphas" "brandott_S_gammas" "brandott_S_thetas" "brandtv_S_alphas"  "brandtv_S_gammas"  "brandtv_S_thetas"  "bsearch_S_alphas" 
 [8] "bsearch_S_gammas"  "bsearch_S_thetas"  "disc_S_alphas"     "disc_S_gammas"     "disc_S_thetas"     "drott_S_alphas"    "drott_S_gammas"   
[15] "drott_S_thetas"    "drtv_S_alphas"     "drtv_S_gammas"     "drtv_S_thetas"     "fbprosp_S_alphas"  "fbprosp_S_gammas"  "fbprosp_S_thetas" 
[22] "fbrmkt_S_alphas"   "fbrmkt_S_gammas"   "fbrmkt_S_thetas"   "native_S_alphas"   "native_S_gammas"   "native_S_thetas"   "nbsearch_S_alphas"
[29] "nbsearch_S_gammas" "nbsearch_S_thetas" "psoc_S_alphas"     "psoc_S_gammas"     "psoc_S_thetas"     "shop_S_alphas"     "shop_S_gammas"    
[36] "shop_S_thetas"     "yt_S_alphas"       "yt_S_gammas"       "yt_S_thetas"  `

`hyperparameters <- list(
+    brandott_S_alphas= c(0.5, 3)
+   , brandott_S_gammas = c(0.3, 1)
+   , brandott_S_thetas = c(0, 0.8)
+   , brandtv_S_alphas= c(0.5, 3)
+   , brandtv_S_gammas = c(0.3, 1)
+   , brandtv_S_thetas = c(0, 0.8)
+   , bsearch_S_alphas = c(0.5 ,3)
+   , bsearch_S_gammas = c(0.3 ,1) 
+   , bsearch_S_thetas = c(0, 0.4)
+   , disc_S_alphas = c(0.5, 3)
+   , disc_S_gammas = c(0.3, 1)
+   , disc_S_thetas = c(0, 0.8)
+   , drott_S_alphas= c(0.5, 3)
+   , drott_S_gammas= c(0.3, 1)
+   , drott_S_thetas= c(0, 0.8)
+   , drtv_S_alphas = c(0.5, 3)
+   , drtv_S_gammas = c(0.3, 1)
+   , drtv_S_thetas = c(0, 0.8)
+   , fbprosp_S_alphas = c(0.5, 3)
+   , fbprosp_S_gammas = c(0.3, 1)
+   , fbprosp_S_thetas = c(0, 0.8)
+   , fbrmkt_S_alphas = c(0.5, 3)
+   , fbrmkt_S_gammas = c(0.3, 1)
+   , fbrmkt_S_thetas = c(0, 0.9)
+   , native_S_alphas = c(0.5 ,3)
+   , native_S_gammas = c(0.3 ,1)
+   , native_S_thetas = c(0 ,0.8)
+   , nbsearch_S_alphas = c(0.5 ,3)
+   , nbsearch_S_gammas = c(0.3 ,1) 
+   , nbsearch_S_thetas = c(0, 0.6) 
+   , psoc_S_alphas = c(0.5 ,3)
+   , psoc_S_gammas = c(0.3 ,1)
+   , psoc_S_thetas = c(0 ,0.8)
+   , shop_S_alphas= c(0.5 ,3)
+   , shop_S_gammas= c(0.3 ,1)
+   , shop_S_thetas = c(0 ,0.4)
+   , yt_S_alphas = c(0.5 ,3)
+   , yt_S_gammas = c(0.3 ,1)
+   , yt_S_thetas = c(0 ,0.8)
+   )`
```

**Comment by jsatani-tonal** [comment]
@kyletgoldberg

**Comment by kyletgoldberg** [comment]
Hi - it looks like you are using a fairly old version of R, could you make sure to update that as well as ensure you are using the latest version of Robyn and let us know if that solves the issue?

**Comment by jsatani-tonal** [comment]
Hi Kyle I updated my Version of R but I still get this error
<img width="114" alt="image" src="https://user-images.githubusercontent.com/78436020/161068557-f28fec09-517e-4729-a1e7-9c662328c760.png">

I'm now on R.4.1.0

**Comment by kyletgoldberg** [comment]
Have you installed the latest version of Robyn?

**Comment by jsatani-tonal** [comment]
Yes Robyn 3.6.1 is what I am using. I am available if you'd like to hop on a quick zoom and I can show you / screen share in case you want to look at any other options

**Comment by kyletgoldberg** [comment]
Issue was solved in an outside convo - was related to versioning issues

**Comment by anuragvimal** [comment]
Hi @kyletgoldberg and @jsatani-tonal. I am facing same issue. 
My R version is 4.1.3 and Robyn version is 3.6.1 on my system. Can you guys please help?

**Comment by anuragvimal** [comment]
It is happening for both geometric and weibull adstocks. Can we connect over a call if you have some time?

**Comment by kyletgoldberg** [comment]
can you share the error message?

**Comment by anuragvimal** [comment]
![image](https://user-images.githubusercontent.com/31948869/161984380-6f2799c9-0688-4327-93ba-0b76632a53f9.png)

**Comment by anuragvimal** [comment]
Please have a look at the file shared, Thanks.

**Comment by anuragvimal** [comment]
@kyletgoldberg I have the latest version of Robyn 3.6.2 and also checked that there aren't any NAs in my data. Can we do a screen share to have a quick look please?

**Comment by anuragvimal** [comment]
Okay sure, Let me try and come back to you. If the issue is not resolved, can we connect tomorrow at your convenience?

**Comment by kyletgoldberg** [comment]
@anuragvimal we hope to keep the discussions on the github so that any problem solving we go through is preserved for posterity, but please keep us posted on the debug status

**Comment by jsatani-tonal** [comment]
@anuragvimal  were you able to resolve this issue? I still have this issue and I'm running Robyn 3.6.2 but using Weibull this time.

**Comment by jsatani-tonal** [comment]
I did and it said I was up to date on the remotes, and also the debugger did not specify where the error is happening, everything went through fine! SO I am unsure what to do! I will try to restart my R again and maybe it will work this time.

**Comment by kyletgoldberg** [comment]
@jsatani-tonal the weibull is working fine on my end when i run through demo.R so if you could run through the debug on the specific function erroring out similar to how we did before that would be helpful

**Comment by kyletgoldberg** [comment]
@jsatani-tonal were you able to figure this out?

**Comment by jsatani-tonal** [comment]
Restarting my R session seems to solve it

**Comment by kyletgoldberg** [comment]
@anuragvimal any updates?

**Comment by anuragvimal** [comment]
@kyletgoldberg @jsatani-tonal  Sincere apologies for the late reply..I was able to fix the error by specifying the accurate date format in dt_holidays argument..While doing this, I had the latest version of R Studio and Robyn installed..Thanks for all your help..

**Comment by GrizzledLotus** [comment]
I get this error "**Error in object[[name, exact = TRUE]] : subscript out of bounds**" too often. 

My R version is 4.1.3 and I loaded Robyn in early March. I get the error when I successfully run a model. I save the file and rename it and I modify something in the input, usually dropping a media or context variable or changing the window dates. Sometimes, R lets me run a few different file versions. Sometimes, the error happens on the attempt of the 2nd run. It happens when I run the line "InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters_list)". 

**Solutions tried**: I changed the name of the hyperparameter list. I run the step 2b for setup in one step. I've restarted the computer. I've restarted RStudio. I resave the csv file with the appropriate date format. I've  deleted all objects from the global environment. 

The problem happens when trying to add the hyperparameter list into InputCollect. It starts working again but I don't know why it randomly works and doesn't work. The restart worked in the past, but it's not letting me proceed now. I'm frustrated with RStudio and desperately waiting for an official all-Python version.

**Comment by laresbernardo** [comment]
Hey @GrizzledLotus thanks for reporting this. You mentioned you loaded Robyn in early March, but have you tried updating it to the latest version/commit? Please try once again and let us know if it persists. If it does, can you share with us a minimum reproducible example (anonymized) to help you debug?

**Comment by GrizzledLotus** [comment]
> hyperparameters_list <- list(
+   Media_1_alphas = c(0.5, 3)
+   ,Media_1_gammas = c(0.3, 1)
+   ,Media_1_thetas = c(0, 0.3)
+ 
+   ,Media_2_alphas = c(0.5, 3)
+   ,Media_2_gammas = c(0.3, 1)
+   ,Media_2_thetas = c(0, 0.3)
+ 
+   ,Media_3_alphas = c(0.5, 3)
+   ,Media_3_gammas = c(0.3, 1)
+   ,Media_3_thetas = c(0.3, 0.8)
+ 
+   ,Media_4_alphas = c(0.5, 3)
+   ,Media_4_gammas = c(0.3, 1)
+   ,Media_4_thetas = c(0, 0.3)
+ 
+   ,Media_5_alphas = c(0.5, 3)
+   ,Media_5_gammas = c(0.3, 1)
+   ,Media_5_thetas = c(0, 0.3)
+   
+   ,Media_6_alphas = c(0.5, 3)
+   ,Media_6_gammas = c(0.3, 1)
+   ,Media_6_thetas =c(0, 0.3)
+   
+   ,Media_7_alphas = c(0.5, 3)
+   ,Media_7_gammas = c(0.3, 1)
+   ,Media_7_thetas = c(0, 0.3)
+ 
+   ,Media_8_alphas = c(0.5, 3)
+   ,Media_8_gammas = c(0.3, 1)
+   ,Media_8_thetas = c(0, 0.3)
+   
+   ,Media_9_alphas = c(0.5, 3)
+   ,Media_9_gammas = c(0.3, 1)
+   ,Media_9_thetas = c(0, 0.3)
+ 
+   
+   ,Media_10_alphas = c(0.5, 3)
+   ,Media_10_gammas = c(0.3, 1)
+   ,Media_10_thetas = c(0.1, 0.4)
+ )

> InputCollect <- robyn_inputs(
+   dt_input = data_file
+   ,dt_holidays = dt_prophet_holidays
+   ,date_var = "MediaWeek" # date format must be "2020-01-01"
+   ,dep_var = "TotalSales" # there should be only one dependent variable
+   ,dep_var_type = "revenue" # "revenue" or "conversion"
+   ,prophet_vars = c("trend", "season") # "trend","season", "weekday" & "holiday"
+   ,prophet_country = "US"# input one country. dt_prophet_holidays includes 59 countries by default
+   ,context_vars = c("context_1",
+                     "context_2",
+                     "Holiday_1",
+                     "Holiday_2",
+                     "Holiday_3",
+                     "Holiday_4",
+                     "Holiday_4",
+                     "Holiday_5",
+                     "Holiday_6",
+                     "Holiday_7",
+                     "Holiday_8",
+                     "Promo_1",
+                     "Promo_2",
+                     "Promo_3",
+                     "Promo_4",
+                     "Promo_5",
+                     "Promo_6"
+   ) # e.g. competitors, discount, unemployment etc
+   ,paid_media_spends = c("Media_1",
+                          "Media_2",
+                          "Media_3",
+                          "Media_4",
+                          "Media_5",
+                          "Media_6",
+                          "Media_7",
+                          "Media_8",
+                          "Media_9",
+                          "Media_10") # mandatory input
+   ,paid_media_vars = c("Media_1",
+                        "Media_2",
+                        "Media_3",
+                        "Media_4",
+                        "Media_5",
+                        "Media_6",
+                        "Media_7",
+                        "Media_8",
+                        "Media_9",
+                        "Media_10") # mandatory.
+   # paid_media_vars must have same order as paid_media_spends. Use media exposure metrics like
+   # impressions, GRP etc. If not applicable, use spend instead.
+   #,organic_vars = c("newsletter") # marketing activity without media spend
+   #,factor_vars = c("events") # specify which variables in context_vars or organic_vars are factorial
+   ,window_start = "20yy-mm-dd"
+   ,window_end = "20yy-mm-dd"
+   ,adstock = "geometric" # geometric, weibull_cdf or weibull_pdf.
+   ,hyperparameters = hyperparameters_list # as in 2a-2 above
+   #,calibration_input = dt_calibration # as in 2a-4 above
+ )


Error in object[[name, exact = TRUE]] : subscript out of bounds
In addition: Warning message:
In check_datadim(dt_input, all_ind_vars, rel = 10) :
  There are 29 independent variables & 212 data points. We recommend row:column ratio of 10 to 1

**Comment by laresbernardo** [comment]
Ok, I'd need `data_file` as well to be able to replicate @GrizzledLotus

**Comment by GrizzledLotus** [comment]
give me a few minutes to change the names and values

**Comment by GrizzledLotus** [comment]
[data_file.csv](https://github.com/facebookexperimental/Robyn/files/8533373/data_file.csv)
@laresbernardo here's the file

**Comment by laresbernardo** [comment]
Thanks.

Note: You have duplicated variable names for dt_input in different parameters. Check: Holiday_4

I was able to create the `InputCollect` object with your script, but I see no error:

```
> InputCollect
Total Observations: 208 (weeks)
Input Table Columns (12):
  Date: DATE
  Dependent: revenue [revenue]
  Paid Media: tv_S, ooh_S, print_S, facebook_I, search_clicks_P
  Paid Media Spend: tv_S, ooh_S, print_S, facebook_S, search_S
  Context: competitor_sales_B, events
  Organic: newsletter
  Prophet (Auto-generated): trend, season, holiday on DE
  Unused: 

Date Range: 2015-11-23:2019-11-11
Model Window: 2016-11-21:2018-08-20 (92 weeks)
With Calibration: TRUE
Custom parameters: None

Adstock: geometric
Hyper-parameters for media transformations:
  facebook_S_alphas: [0.5, 3]
  facebook_S_gammas: [0.3, 1]
  facebook_S_thetas: [0, 0.3]
  print_S_alphas: [0.5, 3]
  print_S_gammas: [0.3, 1]
  print_S_thetas: [0.1, 0.4]
  tv_S_alphas: [0.5, 3]
  tv_S_gammas: [0.3, 1]
  tv_S_thetas: [0.3, 0.8]
  search_S_alphas: [0.5, 3]
  search_S_gammas: [0.3, 1]
  search_S_thetas: [0, 0.3]
  ooh_S_alphas: [0.5, 3]
  ooh_S_gammas: [0.3, 1]
  ooh_S_thetas: [0.1, 0.4]
  newsletter_alphas: [0.5, 3]
  newsletter_gammas: [0.3, 1]
  newsletter_thetas: [0.1, 0.4]
```
Can you try deleting the library and installing with `remotes::install_github('facebookexperimental/Robyn/R')`?

**Comment by laresbernardo** [comment]
Thanks. Some notes following your script:
- You have duplicated variable names for dt_input in different parameters. Check: Holiday_4
- 'window_start' must have format '2020-12-31'
- column(s) not found: context_1, context_2
- There are 26 independent variables & 212 data points. We recommend row:column ratio of 10 to 1

I was able to create the `InputCollect` object with your script, but I see no error:

```
> InputCollect
Total Observations: 212 (weeks)
Input Table Columns (57):
  Date: MediaWeek
  Dependent: TotalSales [revenue]
  Paid Media: Media_1, Media_2, Media_3, Media_4, Media_5, Media_6, Media_7, Media_8, Media_9, Media_10
  Paid Media Spend: Media_1, Media_2, Media_3, Media_4, Media_5, Media_6, Media_7, Media_8, Media_9, Media_10
  Context: Holiday_1, Holiday_2, Holiday_3, Holiday_4, Holiday_5, Holiday_6, Holiday_7, Holiday_8, Promo_1, Promo_2, Promo_3, Promo_4, Promo_5, Promo_6
  Organic: 
  Prophet (Auto-generated): trend, season on US
  Unused: MarketBucket, FiscalYear, FiscalMonth, StoreSales, WebSales, Baseline_isJan, Baseline_isFeb, Baseline_isMar, Baseline_isApr, Baseline_isMay, Baseline_isJun, Baseline_isJul, Baseline_isAug, Baseline_isSep, Baseline_isOct, Baseline_isNov, Baseline_isDec, Baseline_isFY19, Baseline_isFY20, Baseline_isFY21, Baseline_isFY22, Holiday_9, Context_1, Context_2, Context_3, Context_4, Context_5, Promo_7, Media_0, Media_11, Media_12

Date Range: 2018-02-05:2022-02-21
Model Window: 2018-02-05:2022-02-21 (212 weeks)
With Calibration: FALSE
Custom parameters: None

Adstock: geometric
Hyper-parameters for media transformations:
  Media_1_alphas: [0.5, 3]
  Media_1_gammas: [0.3, 1]
  Media_1_thetas: [0, 0.3]
  Media_10_alphas: [0.5, 3]
  Media_10_gammas: [0.3, 1]
  Media_10_thetas: [0.1, 0.4]
  Media_2_alphas: [0.5, 3]
  Media_2_gammas: [0.3, 1]
  Media_2_thetas: [0, 0.3]
  Media_3_alphas: [0.5, 3]
  Media_3_gammas: [0.3, 1]
  Media_3_thetas: [0.3, 0.8]
  Media_4_alphas: [0.5, 3]
  Media_4_gammas: [0.3, 1]
  Media_4_thetas: [0, 0.3]
  Media_5_alphas: [0.5, 3]
  Media_5_gammas: [0.3, 1]
  Media_5_thetas: [0, 0.3]
  Media_6_alphas: [0.5, 3]
  Media_6_gammas: [0.3, 1]
  Media_6_thetas: [0, 0.3]
  Media_7_alphas: [0.5, 3]
  Media_7_gammas: [0.3, 1]
  Media_7_thetas: [0, 0.3]
  Media_8_alphas: [0.5, 3]
  Media_8_gammas: [0.3, 1]
  Media_8_thetas: [0, 0.3]
  Media_9_alphas: [0.5, 3]
  Media_9_gammas: [0.3, 1]
  Media_9_thetas: [0, 0.3]
```
Can you try deleting the library and installing with `remotes::install_github('facebookexperimental/Robyn/R')`?

**Comment by GrizzledLotus** [comment]
- I did my best to anonymize my data quickly. 
- i originally anonymized my copy and paste from RStudio and changed the dates to mm-dd etc. then i scrambled to change column names to fit. i apologize for the mismatch.
- context_1 and context_2 were there
- how do you recommend 10:1 row:column ratio at the same time as recommending a 6 to 18-month window to best capture recent media behavior? With weekly data that's 2.6 to 7.8 total allowed columns. I have 10-11 media columns alone. I'm pushing back on my media team to reduce variables, but it's been a hard sell. Plus, your own advice is to expand the medias into more granular sub-categories and your example on this page has 15 independent variables which would need almost 3 years of weekly data to fulfill your 10:1 recommendation.

I deleted my library. I reinstalled it using the remotes command you suggested. I had to manually install arules package in order to load reticulate. I still get the same error when trying to add hyperparameters to robyn_inputs, either as a separate step or all in one.

**Comment by laresbernardo** [comment]
Don't worry, take your time to build the reproducible example so I can replicate the error you get by running exactly the code you share with me. We must be missing something given I haven't been able to replicate the error. And regarding the 10:1 recommendation, it's a [rule of thumb](https://en.wikipedia.org/wiki/One_in_ten_rule) more than a must. Maybe also consider combining those columns that are really sparse or low volume. And I noticed context_1 was actually Context_1, that's why it didn't find those columns.

**Comment by GrizzledLotus** [comment]
[GitHub_Help.txt](https://github.com/facebookexperimental/Robyn/files/8535217/GitHub_Help.txt)
[data_file.csv](https://github.com/facebookexperimental/Robyn/files/8535218/data_file.csv)
I copied the R code into the text file attached. I ran the code and checked all the variable names and used the attached data_file.csv. I ran robyn_inputs both with and without the hyperparameter argument. I get the same 'subscript out of bounds error'.

I'm trying to persuade my company to use this modeling solution but I can't get it to run reliably to compare results to our current methodology. The code works. I have results, but then I make a change to the R file, or copy and paste into another folder to run another input file and I get this subscript error. Restarting worked once or twice, but now I've been stuck with this error and can't get it to run again.

**Comment by laresbernardo** [comment]
Oh, I'm sorry to hear this! I ran your new shared code with no errors at all. Can you once again check if you have the latest version? `packageDescription("Robyn")$GithubSHA1` should match "990aa8f768976b598e473ffdf9304e3242f76b7b". I can't seem to replicate this issue. Can you also share your `sessionInfo()`?

**Comment by GrizzledLotus** [comment]
```
> packageDescription("Robyn")$GithubSHA1
[1] "990aa8f768976b598e473ffdf9304e3242f76b7b"
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arules_1.7-3 Matrix_1.4-0

loaded via a namespace (and not attached):
[1] compiler_4.1.3    generics_0.1.2    tools_4.1.3       remotes_2.4.2     grid_4.1.3        data.table_1.14.2
[7] lattice_0.20-45  
```
my packageDescription output matches your expected value.

**Comment by GrizzledLotus** [comment]
```
> InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters_list)
Error in object[[name, exact = TRUE]] : subscript out of bounds
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.24 Robyn_3.6.2     arules_1.7-3    Matrix_1.4-0   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3       rpart.plot_3.1.0   lubridate_1.8.0    lattice_0.20-45    tidyr_1.2.0       
 [6] png_0.1-7          lares_5.1.2        glmnet_4.1-4       digest_0.6.29      foreach_1.5.2     
[11] utf8_1.2.2         R6_2.5.1           plyr_1.8.7         ggridges_0.5.3     httr_1.4.2        
[16] ggplot2_3.3.5      pillar_1.7.0       rlang_1.0.2        lazyeval_0.2.2     rstudioapi_0.13   
[21] data.table_1.14.2  nloptr_2.0.0       rpart_4.1.16       splines_4.1.3      stringr_1.4.0     
[26] igraph_1.3.0       RCurl_1.98-1.6     munsell_0.5.0      compiler_4.1.3     pkgconfig_2.0.3   
[31] shape_1.4.6        rPref_1.3          tidyselect_1.1.2   tibble_3.1.6       codetools_0.2-18  
[36] fansi_1.0.3        crayon_1.5.1       dplyr_1.0.8        bitops_1.0-7       grid_4.1.3        
[41] jsonlite_1.8.0     gtable_0.3.0       lifecycle_1.0.1    magrittr_2.0.3     pROC_1.18.0       
[46] scales_1.2.0       RcppParallel_5.1.5 zip_2.2.0          cli_3.2.0          stringi_1.7.6     
[51] doRNG_1.8.2        remotes_2.4.2      doParallel_1.0.17  xml2_1.3.3         ellipsis_0.3.2    
[56] generics_0.1.2     vctrs_0.4.1        openxlsx_4.2.5     iterators_1.0.14   tools_4.1.3       
[61] prophet_1.0        glue_1.6.2         purrr_0.3.4        rngtools_1.5.2     parallel_4.1.3    
[66] survival_3.2-13    yaml_2.3.5         colorspace_2.0-3   h2o_3.36.0.4       rvest_1.0.2       
[71] minpack.lm_1.2-2   patchwork_1.1.1
```
sorry. i ran the SessionInfo() first thing this morning before rerunning the code from last night. Here's the state right after i get the error.

**Comment by kyletgoldberg** [comment]
@GrizzledLotus I ran the the code with your file as well this morning and didn't get any errors which makes it difficult for us to debug on our end. I think the best path forward would be if you could run `debug(robyn_inputs)` and then run the function again and go through the debug to see at which line the error is actually being fired since we can't reproduce on our end. Thanks for your patience here

**Comment by GrizzledLotus** [comment]
I'm sorry. I don't  know how to interpret the debug() function. I tried it on Friday, but it highlights different section of code and then ends. I'll see if I have time to read up on the debug() function. It doesn't matter, I now get a different error message this morning. After shutting down my computer for the weekend and clearing the global environment in RStudio, I get this error message after running the same script for the same data file: ```
Error in check_datevar(dt_input, date_var) : 
  You must provide only 1 correct date variable name for 'date_var'
```

**Comment by kyletgoldberg** [comment]
@GrizzledLotus what does your `date_var` have in it when you get that error?
