### ISSUE TITLE
Fitting models using media spends variables. Are media exposure variables ignored?

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#364]
Hi, 

I noticed that in version 3.6 models are fitted using media spend variables only. I see also that the exposure-to-spend conversion in robyn_pareto commented out. 

I cannot find any place in the code where media exposure is used for modeling. Do I miss something here?      
Thanks

**Comment by laresbernardo** [comment]
Hi. Really good observation @slavakx 
We have the `fit_spend_exposure()` function within `robyn_engineering()` within `robyn_inputs()`. Taken from the documentation:
> `fit_spend_exposure()` uses the Michaelis-Menten function to fit the nonlinear model. The fallback model is the simple linear model (`lm()`) in case the nonlinear model is fitting worse. A bad fit here might result in unreasonable model results. 
Also, please read [this comment](https://github.com/facebookexperimental/Robyn/issues/338#issuecomment-1061566424) about why we switched back to spend instead of impressions.

**Comment by slavakx** [comment]
Thanks for your quick reply. It would be good if such changes and new insights from studies that lead to important decisions in your development are reflected in your user guide or somehow communicated.

**Comment by laresbernardo** [comment]
Yes, agreed. We posted on FB Group the relevant new changes on version 3.6 in February [here](https://www.facebook.com/groups/robynmmm/permalink/1140567730044692) and we do the same for [every release](https://github.com/facebookexperimental/Robyn/releases) too. We try to be communicative on these changes as much as possible.

**Comment by Aanai** [comment]
In a case when you have GRPs for a channel but do not have spend data, does it make sense to use it in paid_media_spends alongside other channels with their spends?

**Comment by laresbernardo** [comment]
No. GRP could be considered as "impressions" values instead, but it's not in the same dimension as "spend", thus you shouldn't mix GRP with spend variables. Imagine what ROI or CPA values you'll get for this media variable and then the optimizer trying to maximize it with other paid media variables which were correctly set.
