### ISSUE TITLE
Clusters plot: Sum of Squares is not a monolithic decreasing function

### ISSUE THREAD

**Issue by harell** [facebookexperimental/Robyn#365]
## Project Robyn

Just want to share with you guys a case where the Sum of Squares is not a monolithic decreasing function.

It might just be a simple case of points displayed not in order.

![pareto_clusters_wss](https://user-images.githubusercontent.com/7226303/161858321-b0bd61c8-26c5-44a1-b0fc-2b3164459048.png)

## Environment & Robyn version
R version 4.1.1
Robyn 3.6.2

**Comment by laresbernardo** [comment]
Hi @harell thanks a lot for sharing. The WSS values seem to be correctly sorted ([source](https://github.com/laresbernardo/lares/blob/main/R/clusters.R#L99-L106)). Note that it's quite possible to have these values that are larger than the previous, but it totally depends on your data. Also, note that node 16 is lower than 17 and 18 (but less dramatically than 3 and 4). I tried searching for literature referring to this phenomenon, but I was only able to confirm that in [some plots I found](https://www.researchgate.net/figure/Within-groups-to-Total-sum-of-squares-by-increasing-the-number-of-clusters_fig5_341113984) this also happens (no detailed explanations whatsoever). There are great resources out there though to infer why this happens ([1](https://support.minitab.com/en-us/minitab/18/help-and-how-to/modeling-statistics/multivariate/how-to/cluster-k-means/interpret-the-results/all-statistics-and-graphs/#:~:text=Clusters%20that%20have%20higher%20values,sum%20of%20squares%20becomes%20larger.), [2](https://discuss.analyticsvidhya.com/t/what-is-within-cluster-sum-of-squares-by-cluster-in-k-means/2706), [3](https://stats.stackexchange.com/questions/542149/the-number-of-clusters-in-the-k-means-and-the-within-cluster-ss)).
