### ISSUE TITLE
function low

### ISSUE THREAD

**Issue by Kototra** [facebookexperimental/Robyn#369]
## Describe issue
f.robyn is running for all of the trials but after completing and trying to export plots and results I am recieving this erros: Error in low(ng_collect$nrmse) : could not find function "low"

This is for version: Robyn MMM Open Source 2.0

**Comment by laresbernardo** [comment]
Hi. It seems you are using the old scripts (version 2.0). Can you please install Robyn as a package and retry? You should have version 3.6.2 at least. Thanks
