### ISSUE TITLE
how to add media channel without spend variable

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookexperimental/Robyn#37]
## Issue
I'd like to be able to add a media channel whose only the "exposure" data is available as the media channel does not have easy to quantify variable costs (e.g. acquisition emails/other_direct_marketing_comms to an owned prospect list).

My workaround solution would be to use the channel exposure as a baseline variable --> downside: not able to apply adstock and diminishing return transformations to this channel.

Is there any best-practice/solution you would recommend for this use-case?
## Steps to Reproduce

NA

## Expected Behavior

NA
## Actual Results

NA
## Environment

R version (R --version)

**Comment by gufengzhou** [comment]
Hey, thanks for flagging this. Well this is a tricky one. Robyn does not have the feature yet to deal with variables without spend but requires transformation. For now, the recommendation is just put them as baseline variables. You can maybe try to do adstocking manually and then put them as baseline variable. We'll put this on the wish list

**Comment by LeoUbbiali** [comment]
Hey, thanks for the reply.
Make sense. I'll try to add it as a baseline variable with manual adstocking for the time being 
Thank you!

**Comment by S-C-H** [comment]
Hi,

This would be an awesome feature. How would I calculate the decay manually for these variables? There’s obviously 0 saturation effect.
