### ISSUE TITLE
Scaling of Prophet decomposition 

### ISSUE THREAD

**Issue by math-max** [facebookexperimental/Robyn#370]
## Describe issue
To choose the best model from the Robyn outputs, we are currently trying to calculate some performance metrics on unseen data. For this, we have split our data into train and test sets. We understand that the purpose of the tool is more of decomposition and **not** for forecasting, however, in our use-case, we believe this validation would be valuable to get buy-in from stakeholders and increase confidence in the model. 

We're trying to reconstruct the model from the tool's output to feed it new data and calculate error metrics. The issue I'm running into is the Prophet decomposition. I tried running  [`prophet_decomp` ](https://github.com/facebookexperimental/Robyn/blob/3df97059be8280c23580c2b34a330c1d1aa10ee7/R/R/inputs.R#L689) on the same dataset as passed to `robyn_inputs` and `robyn_run`. However, the values for trend, seasonality and holidays don't match in scale, even though they have the same shape. In the image below the first plot corresponds to the `OutputCollect$xDecompVecCollect` object for a specific solution and the second plot is the output from `prophet_decomp` function when I call it and pass the same 

 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/46674398/163413640-95b24e58-3059-47db-930b-208a8c31e233.png">

As can be seen, the time series for the decomposition seem to match but the orders of magnitude are completely different. I think there's some normalization happening when `robyn_run` is called to the prophet decomposition, but I could not find in the code where this happens. I'm not an expert in R, so I woould appreciate some clarification of what transformation is applied to the prophet decomposition. 

## Model configuration
I'm training Robyn with weekly data, conversion type target variable, and passing trend, season, holiday as `prophet_vars` with default signs. No context, factor or organic vars passed. There are 6 spend variables, none of them use exposure metrics as media variable. 

## Environment & Robyn version
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Robyn version: Robyn_3.6.2

Thanks for the support, Robyn team!

**Comment by kyletgoldberg** [comment]
Thanks for the question - `prophet_decomp` function happens before any of the regression is done, so I suspect that the difference in scale may just be the initial results from `prophet_decomp` * the coefficient assigned to trend, seasonality, etc. in the regression. I don't believe we scale it in any other way. Let me know if that checks out with your data.

**Comment by laresbernardo** [comment]
[XREF](https://github.com/facebookexperimental/Robyn/discussions/373#discussioncomment-2603348) on user that confirmed prophet decomp.

**Comment by math-max** [comment]
Hey @kyletgoldberg and @laresbernardo, thanks a lot for the response! 

I have checked and you're correct. I was comparing the prophet decomposition with the response (ie `prophet_var` * `coef`). I've corrected it. Thanks a lot.
