### ISSUE TITLE
robyn_onepagers print issue

### ISSUE THREAD

**Issue by F1nalFortune** [facebookexperimental/Robyn#371]
## Describe issue
Running into a plotting issue with the _robyn_outputs_ as well as the robyn_onepagers functions.  I am faced with these errors below:

Code I ran:
`OutputCollect <- robyn_outputs(
   InputCollect, OutputModels
   , pareto_fronts = 3
   , csv_out = "pareto" # "pareto" or "all"
   , clusters = TRUE # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
   , plot_pareto = TRUE # Set to FALSE to deactivate plotting and saving model one-pagers
   , plot_folder = robyn_object # path for plots export
 )`

Error:
`Calculating clusters for model selection using Pareto fronts...`
`Auto selected k = 26 (clusters) based on minimum WSS variance of 5%`
`Exporting pareto one-pagers into directory...`
`Generating only cluster results one-pagers (26)...`
`Plotting 26 selected models on 4 cores...`
 ` |==============================================================                                                                                     |  42%`
`Failed exporting results, but returned model results anyways:`
 `Error in {: task 1 failed - "unable to start png() device"`

When trying to run the robyn_onepagers to print all one pagers, am being faced with a new error:
`Generating only cluster results one-pagers (93)...`
`Plotting 93 selected models on 4 cores...
  |                                                                                                                                                   |   0%Error: cannot allocate vector of size 1.1 Mb`

It also seems as though the auto selection of best k value has increased from the 1-20 range based on this [discussion](https://github.com/facebookexperimental/Robyn/discussions/325).  Is there a maximum value of k for clusters?

Thanks in advance!

## Environment & Robyn version
R version: 4.1.2
Robyn version: 3.6.2

**Comment by kyletgoldberg** [comment]
For the amount of clusters, the maximum amount is `limit_clusters <- min(nrow(df) - 1, 30)` where df is essentially your number of paid media variables (see screenshot below). 

![image](https://user-images.githubusercontent.com/84025306/163585263-d2a54924-5eb8-4f51-8d2c-c9c2dd5c9fd5.png)

I found some stackoverflow posts that may help with the other errors as I am think they issues outside of Robyn but hopefully they may point you in the right direction.

https://stackoverflow.com/questions/45113597/error-unable-to-start-png-device
https://stackoverflow.com/questions/5171593/r-memory-management-cannot-allocate-vector-of-size-n-mb

****

**Comment by asana-neishabouri** [comment]
I have an error in robyn_onepagers :
Here is the code
select_model = '1_142_1'
myOnePager <- robyn_onepagers(InputCollect,
OutputCollect,
export=FALSE,
select_model = select_model)

Error in robyn_onepagers(InputCollect, OutputCollect, export = FALSE,  : 
  object 'parallelResult' not found
  PS: I did add the library(parallel) just in case and did run again and the issue persists.
  
  I'll appreciate your help!
