### ISSUE TITLE
Is Robyn able to predict future value?

### ISSUE THREAD

**Issue by YukeLuo** [facebookexperimental/Robyn#385]
I see in the plot _Actual vs Predicted Response_, Robyn is able to predict and fit the existing data very well. But is it possible to forecast future revenue/conversion? Thank you!

**Comment by laresbernardo** [comment]
Same as [this ticket](https://github.com/facebookexperimental/Robyn/issues/351). It's an enhancement we will be working on and sharing once it's done. Closing ticket.
