### ISSUE TITLE
ROI calculations in outputs when target var is conversions

### ISSUE THREAD

**Issue by Jess625** [facebookexperimental/Robyn#387]
## Describe issue
I'm noticing that for my model, where I've made the target variable conversions, there are quite a few outputs where either ROAS, ROI, mROI, etc, is given which doesn't make sense because I haven't given any revenue numbers. It would make more sense for these outputs to show CPA, mCPA, etc. 

## Listing instances below where revenue related metrics are given as outputs in the modeling process:

- `pareto_clusters_detail.png`: This one pager is outputted through robyn_outputs() and shows two graphs, the left of which gives ROI values by channel.

<img width="1216" alt="Screen Shot 2022-05-20 at 10 34 15 AM" src="https://user-images.githubusercontent.com/59290444/169550723-baeefa4d-4d79-4a6f-807f-72a26cbbc972.png">

- `roas_convergence.png`: Another one pager outputted by robyn_outputs() -- by channel, this shows roas convergence
<img width="919" alt="Screen Shot 2022-05-20 at 10 36 18 AM" src="https://user-images.githubusercontent.com/59290444/169551105-e21466b1-0340-4889-81eb-74a416dc7855.png">

- when you run `print(ExportedModel`), it gives you columns for roi_mean and roi_total
<img width="711" alt="Screen Shot 2022-05-20 at 10 43 55 AM" src="https://user-images.githubusercontent.com/59290444/169552983-2da47eae-7704-4dc8-ac26-3655784aec9b.png">

- ` x_xxx_x_reallocated.csv`: Csv output given from robyn_allocator() and it gives ROI metrics as columns
-  for the robyn_response() function, the demo only gives examples for mROI, but would be nice to add examples for CPA, mCPA, et.c 

## Environment & Robyn version
3.6.3 in R Studio

**Comment by laresbernardo** [comment]
Thanks a lot for your feedback. We do change CPA to conversion models in some outputs but we've definitely missed some others. I'll take a deeper look into this and implement a fix soon. Cheers and happy Friday!
