### ISSUE TITLE
The output is null for some specific solution ID

### ISSUE THREAD

**Issue by Zhangwei112358** [facebookexperimental/Robyn#388]
## Describe issue
The model training succeed. Luckily!!! 
While it's found the result is null for some specific solution ID in model result.
model_result$OutputCollect$xDecompVecCollect ,select=c("ds","dep_var")
return Null

Not all xDecompVecCollect is empty.

## Environment & Robyn version
R version version 4.1.3 (2022-03-10)
The latest Robyn version

**Comment by laresbernardo** [comment]
Hi @Zhangwei112358 I'm not sure what the issue is. Can you please share more information on the outputs you got? Also, on the inputs you provided. Which version of Robyn are you using? Not sure what you mean by those Null values, what they are or were they come from.

**Comment by Leonelsentana** [comment]
Adding my 2 cents, could you please share clearly how model_result$OutputCollect$xDecompVecCollect looks like? Moreover, do you happen to have many periods of time with zero investment in channels? (days, weeks or whatever you defined as minimum granularity)
