### ISSUE TITLE
robyn_run() fail in my mac, but the same Rscript works well in my colleagues' windows laptop

### ISSUE THREAD

**Issue by Zhangwei112358** [facebookexperimental/Robyn#389]
## Describe issue
I tried many times with the exact same Rscript with my colleagues.  in robyn_run() function
OutputCollect <- robyn_run(
  InputCollect = InputCollect # feed in all model specification
  , plot_folder = robyn_object # plots will be saved in the same folder as robyn_object
  , pareto_fronts = 5
  , plot_pareto = FALSE
  , csv_out = "all"
  , calibration_constraint = 0.1 # run ?robyn_run to see description
  , lambda_control = 1 # run ?robyn_run to see description
)

They ran successfully. But I fail with error

Using robyn object location: XXXXXXXXXX
>>>Input data has 236 days in total: 2021-08-01 to 2022-03-24
Initial model is built on rolling window of 236 days: 2021-08-01 to 2022-03-24
Using geometric adstocking with 18 hyperparameters & 10-fold ridge x-validation on 6 cores
Start running 5 trials with 100 iterations per trial each with TwoPointsDE nevergrad algorithm...
 Running trial nr. 1
  |                                                                                                            |   0%Error in { : task 1 failed - "object 'spd1' not found"
Timing stopped at: 0.862 0.511 0.654
I've checked myself column "spd1" exists in InputCollect.

Does anyone have this same issue.
## Environment & Robyn version
R version (version 4.1.3 (2022-03-10))
Please make sure you're using the latest Robyn version

**Comment by laresbernardo** [comment]
Hi @Zhangwei112358 
It seems you are using an outdated version of Robyn and demo.R flow (noticed because `lambda_control` was deprecated some months ago). Can you please try updating and following the demo.R file to see if you get this error?
Id `spd1` a column name from your dataset?

**Comment by Zhangwei112358** [comment]
> 

Thanks a lot.
I tried "library(Robyn)" again before running robyn_run() function with my current version of Robyn, then it went through well.

**Comment by Zhangwei112358** [comment]
> Hi @Zhangwei112358 It seems you are using an outdated version of Robyn and demo.R flow (noticed because `lambda_control` was deprecated some months ago). Can you please try updating and following the demo.R file to see if you get this error? Id `spd1` a column name from your dataset?

I tried "library(Robyn)" again before running robyn_run() function with my current version of Robyn, then it went through well.

I will update and try again.
