### ISSUE TITLE
Getting errors in (remotes::install_github("facebookexperimental/Robyn/R")

### ISSUE THREAD

**Issue by Sibusiso1995** [facebookexperimental/Robyn#390]
## Describe issue
I am getting an error when I try loading the package I'm not sure why. 

<img width="671" alt="Screenshot 2022-05-23 at 10 55 41" src="https://user-images.githubusercontent.com/54172627/169782513-09e7d21b-cc86-41c4-a7e5-ed81c895e4d3.png">

<img width="667" alt="Screenshot 2022-05-23 at 10 56 29" src="https://user-images.githubusercontent.com/54172627/169782665-267fcd3d-2e92-4aca-8b12-2a0a5b3094b2.png">

My R studio version is 4.2.0

**Comment by laresbernardo** [comment]
It seems you are having problems installing `h2o` dependency. Try `install.packages("h2o")` first and when that succeeds, try installing Robyn. Installing Robyn from CRAN shouldn't have this issue. If you are OK working with the latest stable (instead of dev) version, try `install.packages("Robyn")` instead of `devtools::remotes(...)`.

**Comment by Sibusiso1995** [comment]
I tried that and I got this message

<img width="665" alt="Screenshot 2022-05-23 at 17 09 22" src="https://user-images.githubusercontent.com/54172627/169850423-457c73db-69d6-4abc-b9fe-8e7b748604fa.png">

**Comment by laresbernardo** [comment]
Try setting `options(timeout=400)` first... checking at [CRAN's status too[l](](https://cran.r-project.org/web/checks/check_results_h2o.html)url), they seem to be OK.

**Comment by Sibusiso1995** [comment]
Thank you so much it worked🙌🏼... Another thing on the demo.R file there is a variable missing of "robyn_inputs" or is it me.

<img width="650" alt="Screenshot 2022-05-23 at 17 27 12" src="https://user-images.githubusercontent.com/54172627/169854083-e69c3acc-87c0-4481-91c3-d33896c0187b.png">

**Comment by laresbernardo** [comment]
Which variable is missing? Not sure what you mean. `?robyn_inputs` (in the commented section) will open the internal package documentation, and the other one is the part where the function prepares and checks the inputs.
