### ISSUE TITLE
README - cross validation

### ISSUE THREAD

**Issue by giorgossideris** [facebookexperimental/Robyn#393]
## Describe issue
The <code>README.md</code> file mentions *Ridge regression with cross validation*, although in [this issue](https://github.com/facebookexperimental/Robyn/issues/81) is described that no test-train validation is performed, for the model selection. So, which is the case? and should README be updated?

**Comment by laresbernardo** [comment]
Hi! Thanks for catching this incongruity in the documentation. We did use cross-validation until February 2022, when we changed the lambda selection to be part of the hyperparameters. Will update now...
