### ISSUE TITLE
Plots titles. Version 3.6.4

### ISSUE THREAD

**Issue by josetigo** [facebookexperimental/Robyn#394]
Hi Robyn team,
Regarding the plots titles, in order to make easy the stakeholders interpretation...

- Geometric Adstock: Isn't it proper something like "Fixed prolonged effect rate over time" instead of "Fixed decay rate over the time"?
![image](https://user-images.githubusercontent.com/94695388/170276204-d20d6242-4304-4bc8-933c-f066ee735cf5.png)
- Initial vs Optimized mean response: Could you correct the labels? they are the same of "Initial vs Optimised budget allocation"
![image](https://user-images.githubusercontent.com/94695388/170275371-cf3cf254-a2e1-4893-b7f7-51c8cffb9bb9.png)

Thanks for the great job !

**Comment by kyletgoldberg** [comment]
Hi thanks for the feedback - I think plot 1 the title we currently have is accurate since we are looking at decay rates specifically with adstock, but can you elaborate on the issue with title 2? Is there a bug going on with the labels? Thank you!

**Comment by laresbernardo** [comment]
Thanks for your feedback @josetigo I've implemented both changes: removed "decay" from the title to have "Geometric Adstock: Fixed Rate Over Time", and fixed the labels to "Initial Mean Response" and "Optimised Mean Response".
