### ISSUE TITLE
Undocumented OS dependencies (ubuntu 20.04)

### ISSUE THREAD

**Issue by perfectsine** [facebookexperimental/Robyn#4]
# Ubuntu 20.04 OS dependencies
- libv8-dev
- libcurl4-openssl-dev

These prevent the default run of the main 'exec' R script.

**Comment by Leonelsentana** [comment]
Thanks so much for testing this @perfectsine! We will update our README with the dependencies you mention for Ubuntu. Please let us know if there are any other dependencies that you would like to add.
