### ISSUE TITLE
Question related to metrics for modeling

### ISSUE THREAD

**Issue by PetricaR** [facebookexperimental/Robyn#405]
Hello Robyn team,

I have a question related to Robyn media metrics inputs.

Can we use **conversions** instead of impressions / clicks ?

Thank you!
Petrica

![conversions](https://user-images.githubusercontent.com/35411971/172106655-8285ca3c-7d9a-4f1d-b591-0a91727fbde0.png)

**Comment by kyletgoldberg** [comment]
Hello - I would not recommend using attributed conversions as an input to the model. The reason for this being that you will be using conversions to predict conversions. This will create some results that will be biased and also less actionable than when using spend as a predictor.

**Comment by PetricaR** [comment]
I would like to use conversions to predict the revenue! not conversions itself.

**Comment by kyletgoldberg** [comment]
It still won't really work since revenue and conversions are extremely correlated i.e. you can't have revenue without a conversion preceeding it. A conversion is a necessary condition for revenue.

**Comment by PetricaR** [comment]
Ok, I understand, thank you very much!
