### ISSUE TITLE
Getting an error while running robyn_run 

### ISSUE THREAD

**Issue by NoufaMukhtar** [facebookexperimental/Robyn#406]
## Describe issue
Even after installing everything, I am getting this error -

Input data has 208 weeks in total: 2015-11-23 to 2019-11-11
Initial model is built on rolling window of 92 week: 2016-11-21 to 2018-08-20
Using geometric adstocking with 19 hyperparameters (19 to iterate + 0 fixed) on 1 core (Windows fallback)
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'lower'

**Comment by kyletgoldberg** [comment]
Check this issue thread - https://github.com/facebookexperimental/Robyn/issues/211

Looks like it is typically a versioning issue, so check the last comment and make sure everything is as updated as possible. If that still does not work please let us know

**Comment by kyletgoldberg** [comment]
@NoufaMukhtar were you able to get this working?
