### ISSUE TITLE
in selectChildren(ac[!fin], -1) : error 'No child processes' in select

### ISSUE THREAD

**Issue by victorlee29** [facebookexperimental/Robyn#41]
Hi, 

## Issue

I have encountered some unexpected errors. 

## Steps to Reproduce

Please provide instructions that can be used to reproduce your issue. Usually
this will include a test case that produces the wrong output.

## Expected Behavior

For the graphs etc., to plot. 

## Actual Results

Though there were some errors after the 1st trial, Robyn did complete all 40, at which time more 'errors' occurred. Both are pictured below. It does mention NaN numbers in the data - could this be because one of my variables (the % increase/decrease in retail sales, m-o-m, y-o-y etc) occasionally has a negative number? We don't have competitor sales, like in your example, so I've been improvising. 

<img width="1034" alt="Screenshot 2021-03-27 at 16 10 12" src="https://user-images.githubusercontent.com/72621182/112725131-f527a280-8f16-11eb-80f9-082b78cd2252.png">

<img width="1033" alt="Screenshot 2021-03-27 at 16 10 22" src="https://user-images.githubusercontent.com/72621182/112725133-f789fc80-8f16-11eb-8fc8-a14bff9be4aa.png">

## Environment

R Studio

Thanks again, 

Lee

**Comment by gufengzhou** [comment]
hi, it's very difficult to debug without seeing the input. would you share screenshots of your .exec script, esp the variable setting and hyperparameters?

**Comment by victorlee29** [comment]
Hi, sure :-) I also just tested removing any minus numbers from my variables, and still got the below error, despite there being no missing values or NaN's. 

Error during wrapup: missing values and NaN's not allowed if 'na.rm' is FALSE
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

Thanks again

<img width="1232" alt="Screenshot 2021-03-29 at 11 25 29" src="https://user-images.githubusercontent.com/72621182/112816349-9894c680-9081-11eb-8217-f393cecac1bb.png">
<img width="1230" alt="Screenshot 2021-03-29 at 11 25 39" src="https://user-images.githubusercontent.com/72621182/112816359-9b8fb700-9081-11eb-819c-b7d40346aa22.png">
<img width="1227" alt="Screenshot 2021-03-29 at 11 26 00" src="https://user-images.githubusercontent.com/72621182/112816365-9c284d80-9081-11eb-9098-b44d21a884fa.png">
<img width="1231" alt="Screenshot 2021-03-29 at 11 26 07" src="https://user-images.githubusercontent.com/72621182/112816367-9cc0e400-9081-11eb-894d-bd1c4e493177.png">

**Comment by Leonelsentana** [comment]
Hi Lee,

Thanks so much for sharing! Could you be so kind to also share with us how the data input file looks like? You should have zeros instead of null values everywhere. You may gray some rows for privacy if you want to share it, just to see if you have the right formats and no data is missing. Also, is your date variable (ds) in "yyyy-mm-dd" format? like 2021-03-29? Is your data weekly or daily aggregated? How many years of history do you have?

Thanks again ;)

**Comment by victorlee29** [comment]
Hi, 

No probs :-) I've triple checked and there are no null values, only zeroes. The date is also formatted correctly, and the data is weekly over the last 2 years ish. 

<img width="1365" alt="Screenshot 2021-03-29 at 16 23 36" src="https://user-images.githubusercontent.com/72621182/112851295-233deb80-90ab-11eb-9568-d27343b7ccb1.png">

Thanks again,

Lee

**Comment by victorlee29** [comment]
Actually, I just saw, after looking at the the screen grab, a single cell with a minus in it *smacks head against table.* Let me re-run the data...

**Comment by victorlee29** [comment]
Nope, unfortunately the error still returns, and during a different trial on every attempt too

<img width="1235" alt="Screenshot 2021-03-29 at 17 05 52" src="https://user-images.githubusercontent.com/72621182/112857339-0ad0cf80-90b1-11eb-9ca9-185ebd951e03.png">

**Comment by gufengzhou** [comment]
I see that you're still using 0.74 as training size, which is the setting for the sample dataset. You should define this for your dataset specifically. Using the f.plotTrainSize will give you an idea how much to use for training. However I won't recommend to set it too low. Please try this out?

**Comment by Leonelsentana** [comment]
Do you have a channel that is complete zeros for the most recent 26% of the data by any chance?

**Comment by victorlee29** [comment]
Hi, 

f.plotTrainSize is still suggesting a size of 0.74/0.73?
Full screengrab of my data below. There are some columns with zeroes in, but not any that are entirely zeroes for the most recent 26%. The 'infected' variable is about  covid obviously and thus does have zeroes pre Feb 2020, but I've used such data before and it hasn't been a problem.

Thanks again, 

Lee

<img width="551" alt="Screenshot 2021-03-30 at 09 53 58" src="https://user-images.githubusercontent.com/72621182/112953781-0acae100-913e-11eb-91fc-686aaf26b67c.png">

<img width="640" alt="Screenshot 2021-03-30 at 09 53 23" src="https://user-images.githubusercontent.com/72621182/112953762-07375a00-913e-11eb-9f3a-589fa0e44150.png">

**Comment by gufengzhou** [comment]
Would you please try using a very high training size and rerun, like 0.95? For the test runs you can reduce iterations and trials, e.g. 100x10

**Comment by victorlee29** [comment]
Same problem unfortunately. Baffling. There are definitely no NaN values either

<img width="1222" alt="Screenshot 2021-03-30 at 10 29 17" src="https://user-images.githubusercontent.com/72621182/112958482-cee64a80-9142-11eb-83ab-dd508ea85e50.png">

**Comment by gufengzhou** [comment]
This is really tricky. Looking at the "bad loss warning" at the Beginning, it Looks like issue in Nevergrad. It seems like this dataset is producing losses that are too far from initial points. Would you please test this dataset with fewer (or even just start with one) variables, if no error, then adding the others one by one?

**Comment by victorlee29** [comment]
Hm, I've tried everything variation now, including removing some of the media columns etc. Just doesn't want to work :-/

**Comment by gufengzhou** [comment]
Is it possible to share the dataset with me? You can anonymise the column names and probably not all variables are needed. Then I'll try to debug based on that.

**Comment by victorlee29** [comment]
Hi, sure no probs. Here's a link to the original data - https://we.tl/t-LZjdmcjlIR

It includes rows Q, R and S, which included negative numbers. I tried without these columns and they didn't work either, but obviously it would be helpful, ha, if Robyn worked with them :-)

Thanks again

**Comment by gufengzhou** [comment]
Hi victorlee, I've found out that the error happens when one iteration produces 0 coefficients for all media channel. I've fixed this by allowing f.robyn to finish with some warning messages and recommendations as in screenshot. The fix is pushed just now. Hope it works now.

![image](https://user-images.githubusercontent.com/14415136/113152006-f538e280-9235-11eb-9427-77dfd2aad8ef.png)

**Comment by gufengzhou** [comment]
Hi victorlee, would be great if you could let me know if your case is solved or not? Thanks.

**Comment by victorlee29** [comment]
Hi, sorry I broke my wrist last week, ha, but now have my cast on etc and can type again :-) I'll test it out today and confirm ASAP. Thanks again

**Comment by victorlee29** [comment]
Hi, well its now pushing out some graphs, phew, but they are unusable. The R rating isn't great (with the variables I'd hope it to be better), but I'm finding it a tad hard to understand/accept, ha, why the coefficient is 0 for every media source, even after widening the thetas etc., to their max, as suggested? Any thoughts? 

Thanks again

<img width="1198" alt="Screenshot 2021-04-06 at 13 31 02" src="https://user-images.githubusercontent.com/72621182/113714193-6c63f000-96e8-11eb-8ac9-663c5348639f.png">
![12_7_9](https://user-images.githubusercontent.com/72621182/113714321-8dc4dc00-96e8-11eb-9ad6-f3cb51933c92.png)

**Comment by gufengzhou** [comment]
first of all: get well soon! Get some rest:) 
I hope not all iterations are having 0-only media. In the screenshot, I see 57 out of 100 is all-0, not great but still you have 43 that are not all-0, right? As recommended, you can increase set_trials to get more results. I expect that in the end you should have some pareto outputs that are not all-0. 

On the other hand, what you can check is also a simple correlation matrix of your media vs. sales. If the "original correlation" is already very weak, then the focus should be really tweaking the input data (splitting channels further, or meaningful merge of channels etc.). Hope it helps

**Comment by victorlee29** [comment]
Hi, 
Thanks! It's healing nicely, though typing is highly annoying with the cast! 

I've done a basic correlation matrix and it isn't great, but I am still surprised at how Robyn is 'handling' it, especially as I was getting far more 'precise' results with similar data via a different client (this was before the latest update I think.) Plot example attached, as well as a screen grab with a few more 'random' warnings. Any thoughts on those please? I guess this is surprising because the work we have done on this global client has driven excellent results. Via using FB attribution and comparing it with GA etc., I basically found that FB was undervalued, but only if they altered their strategy to be more incremental (maybe I/Robyn is struggling because it knows FB just wasn't incremental, like I supposed anyway?) Since then, and comparing jan + fb 2021 with a new strategy vs 2020, we have driven over 200% more unique link clicks and 180% more revenue with 16% less spend. With their overall eccomerce revenue up 33% y-o-y, it's pretty obvious FB has driven a large portion of this, as their paid Google revenue is down 57% with 9% more spend (and fb clicks are often lost in organic or direct conversion paths, thanks to GA's problems measuring cross device/browser.) So yeah, I was hoping Robyn could help validate all the 'standard' analytics! All help is welcome, hehe :-)

Thanks again

<img width="920" alt="Screenshot 2021-04-08 at 16 10 16" src="https://user-images.githubusercontent.com/72621182/114052546-6c055980-988e-11eb-8aec-528441937ffb.png">
<img width="1225" alt="Screenshot 2021-04-08 at 17 17 49" src="https://user-images.githubusercontent.com/72621182/114052562-6f004a00-988e-11eb-92f4-efd58f8279dd.png">

**Comment by Leonelsentana** [comment]
Hey! hope you are getting better. Have you tried using clicks for all channels? Maybe there is a higher correlation between those and sales? Also, have you double checked all your impressions and clicks are just global counts (not attributed) and that also the response variable (e.g. sales, conversions, etc.) is NOT attributed, just global sales or convs?
 Meanwhile, we are trying to understand your warning messages with the Nevergrad experts and will come back to you.
