### ISSUE TITLE
Error plotting summary charts

### ISSUE THREAD

**Issue by txgaritano** [facebookexperimental/Robyn#410]
Each time I try to run Robyn I get the following error message:
"
>>> Plotting summary charts...
Warning in png_dev(..., res = dpi, units = "in") :
  cairo error 'invalid value (typically too big) for the size of the input (surface, pattern, etc.)'
Error in png_dev(..., res = dpi, units = "in") : 
  unable to start device 'png'
"

I am using Robyn version 3.4.12 in a 10 CPU & 30GB machine.

**Comment by kyletgoldberg** [comment]
Could you please update your version of Robyn, that is a bit old version. If it still doesn't work please let me know

**Comment by arturodz** [comment]
I am having the same issue in version 3.6.3 when running robyn outputs

**Comment by kyletgoldberg** [comment]
@arturodz could you follow this SO thread and see if the solutions there will solve this issue? https://stackoverflow.com/questions/45113597/error-unable-to-start-png-device
