### ISSUE TITLE
Control variables in Robyn

### ISSUE THREAD

**Issue by anuragvimal** [facebookexperimental/Robyn#413]
Hi Team,

In MMMs, we often control for independent variables by holding them constant or limited in a research study. For example: Temperature, GDP, Life expectancy etc. Do we have a mechanism that allows us to control for explanatory features so that their contribution can vary within in a certain limit? 

Thanks for your help.

**Comment by anuragvimal** [comment]
@kyletgoldberg Can you please help? Thanks.

**Comment by kyletgoldberg** [comment]
I'm not sure I fully understand the use case here. Could you elaborate on what your goal is with this? In my mind, the natural variation of these variables is important to understand how they contribute, so we wouldn't really want to hold them constant. I may be misunderstanding though.

**Comment by anuragvimal** [comment]
@kyletgoldberg Quite often you see a variable taking a significantly higher contribution that usual, like weather conditions which may not explain the impact of media variables correctly. In Robyn we can set the sign of each media variable to be positive or negative. If it's positive, the impact ranges from 0 to infinity. Can I restrict that between say 0 to 30? Is there a way to tweak that in our source code. Sincere apologies for the late reply.

**Comment by kyletgoldberg** [comment]
@anuragvimal no worries - that isn't currently a possibility because we feel it may introduce too much bias in the model to set values in that manner. is there a reason you feel that these contextual vars are taking up too much of the contribution?

**Comment by anuragvimal** [comment]
@kyletgoldberg Thanks for your response. Let me try to explain this. In one of our MMMs, weather (temperature) was explaining 60% of the sales. As correlation necessarily doesn't imply causation, we want to restrict the contribution of such variables. It's something that we want to control on. I hope I am able to sound better with this explanation. Please feel free to provide your thoughts as I am learning and growing with MMMs. Thanks.
