### ISSUE TITLE
Assign more weight to recent months data

### ISSUE THREAD

**Issue by roh-neenopal** [facebookexperimental/Robyn#414]
## Describe issue
In my dataset, I have few channels in which the spend-allocation has been done recently. All other channels have 2+ years of data whereas the new channels only have 4-5months of data. While running Robyn, the output shows zero importance to the new channels. So, if there a workaround in which we can assign more weightage/importance to recent months in data?

**Comment by kyletgoldberg** [comment]
Good question - there is a way to do this for the budget allocator, but not in the modeling phase. If the channels only represent a small portion of the spend, then it will be difficult for the new channels to receive credit. In terms of how to make sure they appear in the model, calibrating with lift is always a great option. Additionally, exploring recency splits for your older channels may also be helpful in this case

**Comment by laresbernardo** [comment]
If you are modeling with daily data, maybe you could also test narrowing the modeling window to the latest 5-6 months, or wait a couple of months to have enough data.

**Comment by roh-neenopal** [comment]
The data is at a weekly level. Will it make sense just to include the latest 5-6months of data? Since Prophet is also being used, will it be able to understand the seasonality/trend in the data?

**Comment by laresbernardo** [comment]
> The data is at a weekly level. Will it make sense just to include the latest 5-6months of data? Since Prophet is also being used, will it be able to understand the seasonality/trend in the data?

We run prophet on the whole data, not only in the modeling window though.

**Comment by roh-neenopal** [comment]
So let's say I have 5years of data and I want Prophet to run on the entire 5 years of data, but the other models/algorithms used in Robyn which produce the optimized spend for channels should focus more on the recent 2years. Is there a way in which we achieve this?

**Comment by laresbernardo** [comment]
By default, if prophet is enabled it will use all the data provided to decompose trends and seasonalities. If you want to use a specific date range to train the models, then you can use the `window_start` and `window_end` parameters when you create your input object with `robyn_inputs()`. Then, you can also pick the window within the modeled window on `robyn_allocator()` to pick another specific date range which could be considered as your business as usual timeframe, with `date_min` and `date_max` parameters.

**Comment by laresbernardo** [comment]
You must have an outdated version of Robyn. Please update to the latest version and retry. You're doing it right.
