### ISSUE TITLE
Error in check_datevar(dt_input, date_var): Date variable has duplicated dates. please clean data first [Panel data]

### ISSUE THREAD

**Issue by Anil-Pothala** [facebookexperimental/Robyn#418]
I have been exploring the Robyn algorithm to do Market Mix Modeling on my dataset. The dataset is monthly level data of the promotional activity for each customer. In this case the data looks like this-

|Id         |Date    |Revenue|Channels…|
|-----------|--------|-------|---------|
|Customer 1 |Jan-2021|       |         |        
|   …..     |        |       |         |  
|Customer 1 |Dec-2021|       |         |
|Customer 2 |Feb-2021|       |         |
|   …..     |        |       |         |
|Customer 2 |Dec-2021|       |         |

In this way we have over 1000 customers and their monthly data of the channel activity. We have been able to create models using linear regression to get the impact of each channel. Now when we tried to run this data on Robyn we get a duplicate date error, so does this mean we have to run Robyn algorithm for each customer separately? Then we will have only 12 data points for the model and getting daily or weekly is also not possible for us. Is there anyway to run this kind of data on Robyn?

## Environment & Robyn version
R version (R 4.0.5)

**Comment by laresbernardo** [comment]
Hi @Anil-Pothala 

I see you've shared this question as an issue here, but also in a [discussion ticket](https://github.com/facebookexperimental/Robyn/discussions/417), a [FB post](https://www.facebook.com/groups/robynmmm/posts/1219941125440685/), and you emailed me directly. Please, let's just create a single ticket and we'll do our best to help you.

The reason you can't set more than one date per row is that Robyn doesn't deal with panel data. These kinds of models are also called “mixed effect model” or "hierarchical model" (with some nuanced differences). So yes, if you want an MMM for each customer/segmentation you'd have to run a single model for each one as of today. We do have planned to think and develop a solution for this sometime, but the math is quite complex to solve (hierarchical + ridge) and we haven't even started.

On the other hand, as rules of thumb, we strongly recommend 1) weekly/daily data granularity, especially if you have <4 years' worth of data, and 2) 1:10 column:row (data point/variables) relationship.

**Comment by firatfrkn** [comment]
I am facing with the same problem, but in my case I have a datetime which is unique for the customer. The datetime column is like this. Time interval for each date. When I check for duplicates, it is 0, but I am getting this error. Could you please help on this issue. 
![Screenshot 2022-07-19 092354](https://user-images.githubusercontent.com/96492785/179682650-512dd69a-ac1d-4149-ab6e-9ae82e73f0a3.png)

**Comment by CJ2407** [comment]
@laresbernardo I don't have panel data, but I am getting Erron in check_datevar for some reason. Could you please suggest what might be some other reasons to get this data?

I ensured that my CSV file has date in YYYY-MM-DD format and I don't have any duplicate dates in my CSV.
