### ISSUE TITLE
Refresh Error - number of observations in y (310) not equal to the number of rows of x (0)

### ISSUE THREAD

**Issue by Tsurty** [facebookexperimental/Robyn#419]
## Describe issue
I have 3 similar models built with Robyn that I wanted to refresh.
While 2 of them worked without any issue this one model returns me this error.

I've checked the dataset and columns are all there as well as values.
I feel like it may be an easy to solve issue but I can't figure out the problem.

```
> Robyn <- robyn_refresh(
+   robyn_object = robyn_object
+   , dt_input = data.table::fread("~/Desktop/cassandra-workspace/data/dataset-total-r1.csv")
+   , dt_holidays = dt_prophet_holidays
+   , refresh_steps = 118
+   , refresh_mode = "auto"
+   , refresh_iters = 2000 # 1k is estimation. Use refresh_mode = "manual" to try out.
+   , refresh_trials = 3
+   , clusters = TRUE
+ )
>>> Initial model loaded
>>> Refreshing model 1 in auto mode. 0 more to go...
Input data has 939 days in total: 2019-12-01 to 2022-06-26
Refresh model is built on rolling window of 310 day: 2021-08-21 to 2022-06-26
Rolling window moving forward: 118 day
Using weibull_pdf adstocking with 61 hyperparameters (61 to iterate + 0 fixed) on 8 cores
>>> Starting 3 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 3
  |                                                                                                                                                                       |   0%Error in { : 
  task 1 failed - "number of observations in y (310) not equal to the number of rows of x (0)"
Timing stopped at: 2.781 3.593 2.959
```

## Environment & Robyn version
```
> packageVersion("Robyn")
[1] ‘3.6.4’
```

**Comment by laresbernardo** [comment]
Hi @Tsurty Can you share a reproducible example that replicates this error to help us debug?

**Comment by Tsurty** [comment]
> Hi @Tsurty Can you share a reproducible example that replicates this error to help us debug?

Sure, just sent it through the Google Form.
One note I figured out after sending it is: I uploaded the wrong code example but you basically have it up here so you should be good to go.

**Comment by laresbernardo** [comment]
Thanks. I was able to reproduce the error with your RDS file. Will get back to you. Any hint you'd like to share?

**Comment by Tsurty** [comment]
> Thanks. I was able to reproduce the error with your RDS file. Will get back to you. Any hint you'd like to share?

Not really honestly. I have two other similar models created (same client, similar columns and dataset, slightly different data).
Same process but those worked fine in refreshing, this one keeps returning this error.

If you think that can be useful I can share with you those as well.

**Comment by laresbernardo** [comment]
I found the bug and will upload the fix in a few minutes.

**Comment by laresbernardo** [comment]
Hi @Tsurty I've [fixed](https://github.com/facebookexperimental/Robyn/commit/4214c05d14818ad69cf9818b98cd7a717d77f73f#diff-f9c06ec6b4d558eff474def92bcce63ebea95827786670898e40132b5751ffe4R565-R569) this issue. The problem was that when no categorical columns were provided, `model.matrix` returned no data at all instead of ignoring the input and returning the same input as output.

Even though this issue has been fixed (please update and check), you'll get the following error later on, when Robyn ends training the refresh model: `"Input 'metric_value' for fb_re_spend (0) must be a positive value"`. But that depends on your data input.

**Comment by Tsurty** [comment]
> Hi @Tsurty I've [fixed](https://github.com/facebookexperimental/Robyn/commit/4214c05d14818ad69cf9818b98cd7a717d77f73f#diff-f9c06ec6b4d558eff474def92bcce63ebea95827786670898e40132b5751ffe4R565-R569) this issue. The problem was that when no categorical columns were provided, `model.matrix` returned no data at all when doing one-hot encoding instead of ignoring the input and returning the same input as output.
> 
> Even though this issue has been fixed (please update and check), you'll get the following error later on, when Robyn ends training the refresh model: `"Input 'metric_value' for fb_re_spend (0) must be a positive value"`. But that depends on your data input.

Hello @laresbernardo thanks for the quick fix and explaination.
Will test this out tomorrow as I'm running other models atm.
