### ISSUE TITLE
Model cant find some baseline variables in the data

### ISSUE THREAD

**Issue by Tbalsotra09** [facebookexperimental/Robyn#42]
## Issue

I have few variables which are like exposure/impact data such as whether  a person got effected by Covid or not which in turn is a factor **0- No and 1- Yes**. Same with other variable where a launch of website had exposure or not. At present I am injecting them as baseline variable and having the training data 0.60 where Bhatta coefficient is the highest in my data. However, in the last step while running the model it seems that it cant find these columns. I even tried changing their name to match the data naming convention but still it gets stuck at columns cant find. Please see the screenshot attached.

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/46905239/112768632-e01c4380-8fea-11eb-8a2b-d5930b52f834.png)

## Expected Behavior
Should run the model as expected 

## Actual Results

![image](https://user-images.githubusercontent.com/46905239/112768588-b236ff00-8fea-11eb-9ac4-f10f05e677af.png)

## Environment

R version (R 4.04)

**Comment by gufengzhou** [comment]
hi, would you share a screenshot of your .exec sheet, where you set all variables? also, i dont understand how the covid variable looks like: you said it's "whether a person got effected by Covid or not" but our model input is timely aggregated.

**Comment by Tbalsotra09** [comment]
Apologies for the confusion. I realised it yesterday that it cannot be ingested like this so I created a new variable for cases per week and it worked. Yes, it's because of time/ week aggregation that it wasn't recognising the variable type.

Thanks for the help!
