### ISSUE TITLE
To access the one-pager plots to r-console

### ISSUE THREAD

**Issue by Harshitha-HM1999** [facebookexperimental/Robyn#423]
## Project Robyn
Hi team, thanks for this wonderful package.

## Describe issues
I am doing case study on Robyn and I wanted to access the model plots in r console to keep them in a markdown, Is there any options to access them out of folder.
Can you help me in this issue.

Thanks in advance,

**Comment by kyletgoldberg** [comment]
Check the robyn_onepagers function :)

**Comment by Harshitha-HM1999** [comment]
Thanks for the reply, I will check.

**Comment by Harshitha-HM1999** [comment]
Hi, we actually tried one-pagers plotting in R to get the plots in console and below is the screenshot.
![image](https://user-images.githubusercontent.com/85454282/178215393-5d2c5ecc-6cc7-4473-8958-c975496f8476.png)

In above screenshot we get the 6 optimum models in the folder but however in for console it is plotting all models.
How can we get the plots of optimum models.

Thanks in advance.

**Comment by laresbernardo** [comment]
You can set the `select_model` parameter and will only generate only the plots for the models you pick. 

Also, if you assign the output to an object (say `my_plots <- robyn_onepagers(...)`), then you'll have a list with all plots as objects.

**Comment by laresbernardo** [comment]
Hi @Harshitha-HM1999 

Once you run `robyn_onepagers()` and create that object (`my_plots` in your case), you'll get a list that contains all solID you picked, and each solID will internally have the 6 plots that are contained in the one-pager individually, which can be plotted in RStudio, exported, manually edited, etc. This should be enough to use each plot and post in in your markdown report.

Visually, in RStudio's plots panel, you can click on Zoom and it will show a pop-up window that enlarges the plot. In there it will automatically adapt to the window size and you can export it. You can also export the plot as you'd export any plot in R, with the size you want.

On the other hand, let me think of a way to dynamically and automatically create longer (exported) one-pagers for cases that contain a lot of independent variables like in your case so the output doesn't look all overlapped. Note that the screenshot you are sharing is not the exported plot but the plot you see in RStudio, which will force the plot to fit in that window.

**Comment by Harshitha-HM1999** [comment]
Thanks for the detailed explanation @laresbernardo, I will check and correct all these stuff.

**Comment by Harshitha-HM1999** [comment]
Hi @laresbernardo 
I can able to get the plots in .png form same as the plots in one-pager folder but they are not same.
![image](https://user-images.githubusercontent.com/85454282/178919529-f50d1ba1-5993-454c-9c74-f40a3f52c370.png)
![image](https://user-images.githubusercontent.com/85454282/178919646-269106b7-5a3e-40d9-95da-27c0839faadb.png)

1. The first screenshot is the plot which we get in folder.
2. The second screenshot is the plot I got in R graphic device2 and saved as .png format.

The second one is overlapped even though having same format, is this is due to more number of independent variables?

**Comment by laresbernardo** [comment]
There are 2 ways you can get easily fetch each individual plot:

- Based on demo.R file, when you have an exported model, you can: 
```
temp <- plot(ExportedModel)
temp$patches$plots[[1]] # for first plot
temp$patches$plots[[1]] # for second plot
...
```
- With the `robyn_onepagers()` function, it's a similar approach. You can:
```
temp <- robyn_onepagers(InputCollect, OutputCollect, export = FALSE, select_model = "2_119_7")
temp$`2_119_7`$patches$plots[[1]] # for first plot
temp$`2_119_7`$patches$plots[[2]] # for second plot
...
```

**Comment by Harshitha-HM1999** [comment]
thank you @laresbernardo

**Comment by Harshitha-HM1999** [comment]
Hi Bernardo,

for dynamic model selection, we may need to store model selection from user in a variable. But when I am trying from that I am getting error. Below is the code which I am trying -

a <- "2_233_4"

temp2 <- robyn_onepagers(InputCollect,
                OutputCollect,
                export=FALSE,
                select_model = a)

temp2$a$patches$plots[[1]]
NULL

Is there any way to get individual plots same as you mentioned for a dynamic variable like a in our above case?

Thanks,
Harshitha

**Comment by laresbernardo** [comment]
This is purely R related, so I think this ticket is solved. Please, fell free to close it if that's correct.

You can do: `temp2[[a]]$patches$plots[[1]]`

**Comment by Harshitha-HM1999** [comment]
Yes, thanks @laresbernardo

**Comment by CJ2407** [comment]
> temp$`2_119_7`$patches$plots[[1]] # for first plot

Hey @laresbernardo! This is not working for me. I typed the following on the R studio console and nothing is happening!

![image](https://user-images.githubusercontent.com/91983160/210472603-21579470-d326-47f9-a9fb-ae0db3553205.png)
