### ISSUE TITLE
rsq_train is low and in some iterations of output is negative

### ISSUE THREAD

**Issue by roh-neenopal** [facebookexperimental/Robyn#427]
## Describe issue
rsq_train is negative or has values like 0.13 or 0.32. How should we interpet when rsq is so low?

## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version

**Comment by laresbernardo** [comment]
rsq_train can have a negative value when the selected model does not follow the trend of the data, therefore leading to a worse fit than the horizontal line. And very low rsq_train values mean that it wasn't possible to create a good fit for the time series. Check your data granularity, randomness, hyperparameters constraints, etc.

**Comment by laresbernardo** [comment]
How many iterations and trials? Is it converging? Do you have enough variance in your time series? Try adding more context variables to help the model understand what's happening with your data.

**Comment by roh-neenopal** [comment]
2000 iterations ; 5 trails - mean of the revenue column is 9M ; SD is 2.4M. I have visits/ promo as organic_vars too. There are around 20 sales channels.
![image](https://user-images.githubusercontent.com/90190987/178779908-a84d4cdd-97f6-4c55-9a72-7b9a3316ef1e.png)

**Comment by laresbernardo** [comment]
You seem to be using an old version of Robyn (given that plot's theme). Can you please update and let us know if you still have the same issue? Also, try adding more context variables to help the model understand what's happening with your data.
