### ISSUE TITLE
Refresh picks a Best Model that is not Plotted

### ISSUE THREAD

**Issue by Tsurty** [facebookexperimental/Robyn#428]
## Describe issue
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/43139944/178936479-31df11c1-48a1-4198-96aa-8766b4cd4c4e.png">

 As shown above, after a model refresh with the following code
```
Robyn <- robyn_refresh(
  robyn_object = robyn_object
  , dt_input = dataset
  , dt_holidays = dt_prophet_holidays
  , refresh_steps = 15
  , refresh_mode = "auto"
  , refresh_iters = 2000
  , refresh_trials = 3
  , clusters = TRUE
)
```
I got that model 3_249_1 was picked as the best but that was not plotted in the folder
<img width="900" alt="image" src="https://user-images.githubusercontent.com/43139944/178936811-c235896f-17a2-4ca0-a49e-1cff0745a49a.png">

However, when doing the budget allocator, it came out from that Model Id.
I guess it has to do with the clusters probably as it was put in Cluster 2 but it was not the Top Model and hence 3_241_5 came out of the cluster.

I believe it doesn't really make sense for refresh to work like this at all and there should be a check in place to avoid such things and eventually select the top model in the same cluster.

**Comment by laresbernardo** [comment]
Hi @Tsurty I've fixed this issue in branch [test_p_robyn1234](https://github.com/facebookexperimental/Robyn/compare/test_p_robyn1234), but we haven't landed yet as there are big changes coming up and we are still testing all of them. Feel free to use that branch if it's urgent but you should expect we land this fix soon into main branch.

**Comment by Tsurty** [comment]
Hello @laresbernardo thanks for info, you can close it in the meantime as in the end we just picked the model we needed out of the CSV and put it in our custom dashboards. Looking forward to the big changes then!
