### ISSUE TITLE
Is there a way to make the charts interactive?

### ISSUE THREAD

**Issue by Tbalsotra09** [facebookexperimental/Robyn#43]
## Issue
Due to variation in the data values, some charts are hard to read. Is there a way to make them interactive or formatting charts to make some values easy on the eyes? 

## Steps to Reproduce

Please see the screenshot below. 

## Expected Behavior

Should be able to interact or able to focus on specific variable

## Actual Results

What actually happened. For example, an error message you did not expect to see.
![image](https://user-images.githubusercontent.com/46905239/112909866-3c04cc00-90c0-11eb-886e-f14fa27f6cc6.png)

## Environment

R version (R --version)

**Comment by gufengzhou** [comment]
Hi thanks for flagging this. Generally yes, plotly does the interactive job quite well. I'll put this on the wish list and see how it is compatible with the onepager.

**Comment by Tbalsotra09** [comment]
Yes, I tried with plotly but since its a list it didn't work . Just trying to work around it if possible. Let me know if you have any suggestions.
Thanks
