### ISSUE TITLE
Error: Error installing package(s): "'nevergrad'" / MacBook Air (M1, 2020)

### ISSUE THREAD

**Issue by DYX10** [facebookexperimental/Robyn#432]
## Describe issue
Describe your issue and provide error message 

I'm using the [demo.R](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R) script 
But can't install the package "nevergrad".
Error message below:

> ERROR: Command errored out with exit status 1: /Users/dora/.virtualenvs/r-reticulate/bin/python /Users/dora/.virtualenvs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/cl/vlg_dxx14vd5_31txmxqsyq40000gn/T/tmpbrgozh7i Check the logs for full command output.
> WARNING: You are using pip version 19.2.3, however version 22.1.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Error: Error installing package(s): "'nevergrad'"

I assume pip version has already been upgraded to the 22.1.2  as shown below:

![image](https://user-images.githubusercontent.com/109622970/179824059-cd3fa626-8af2-4e90-aa76-02d55708dfa2.png)

## Provide dummy data & model configuration
I'm using the [demo.R](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R) script 

## Environment & Robyn version
R version (R --version) 2022.07.0 Build 548
Please make sure you're using the latest Robyn version - ‘3.6.4’
MacBook Air (M1, 2020)

**Comment by kyletgoldberg** [comment]
i believe this user had a similar problem - can you try following their process? https://github.com/facebookexperimental/Robyn/issues/407

**Comment by Tsurty** [comment]
Been there as well and finally ended up fixing it.
All steps and tests done are in this closed thread here, hope it helps.

https://github.com/facebookexperimental/Robyn/issues/189
