### ISSUE TITLE
Initial vs Optimized Graphs Mis-match

### ISSUE THREAD

**Issue by roh-neenopal** [facebookexperimental/Robyn#437]
## Describe issue
I have run an MMM model with 10 channels. The initial vs optimized budget shows that for a channel we should increase the budget whereas - the initial vs final mean response shows that the mean response for that channel would decrease.  Why should one increase the budget for a particular channel if the response is less than the initial response

## Provide dummy data & model configuration
Trails : 5
Iterations: 200
Adstock: Geometric

Initial vs Optimized Budget
![image](https://user-images.githubusercontent.com/90190987/181063882-4e9926f8-61f7-4c22-8613-9ee7228c1a86.png)

Initial vs Optimized Response
![image](https://user-images.githubusercontent.com/90190987/181064072-0ef87951-4c12-4787-9553-ac81c218c1a8.png)

## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version

**Comment by laresbernardo** [comment]
Hi @roh-neenopal 
Can you please update Robyn to the latest version (stable or dev)? It may be part of a known issue that was already fixed in the latest versions. Please let us know if this issue persists.

**Comment by roh-neenopal** [comment]
This is the version on which the model was executed 
![image](https://user-images.githubusercontent.com/90190987/181074882-4b010680-e3d6-438a-9afd-39a194069ef4.png)

**Comment by laresbernardo** [comment]
Can you try installing the dev version and re-running? It seems weird because we changed those plots theme (white background and less intense blues) in recent versions. Please, update, re-run from scratch, and retry to see if the problem continues. Thanks!

**Comment by roh-neenopal** [comment]
Yes, installing again and re-running from scratch resolved the issue. Thanks!
