### ISSUE TITLE
Extracting output in a data-frame

### ISSUE THREAD

**Issue by rohan1997vk** [facebookexperimental/Robyn#440]
## Describe issue
Is there a way in which we can extract 9 different data frames from the charts.
Response Decomp
Share of Spend v/s Share of effect with roi
Adstock
Actual vs Predicited
Response Curve and Mean Spend by Channel
Fitted vs Residual
Initial vs optimized Busget
Initial vs Optimized mean Response
Response Curve and Mean Spend by Channel
## Provide dummy data & model configuration
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration.

## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version

**Comment by laresbernardo** [comment]
Yes! When you run `this <- robyn_onepagers(...)`, you'll get a list with all the plots. Each plot is a ggplot object and you'll have the data within.

**Comment by rohan1997vk** [comment]
![image](https://user-images.githubusercontent.com/22797824/181295253-015025d1-abfe-4f8b-bd79-8e174b995e9f.png)

So this function is asking for the above mentioned parameters

What should be InputCollect and OutputCollect values ?

**Comment by rohan1997vk** [comment]
Amazing!

this[["model_number"]][1] - this gives us the Actual vs Predicted Graph Data 

Which parameters to use to get the data from the list for other graphs?

**Comment by rohan1997vk** [comment]
![image](https://user-images.githubusercontent.com/22797824/181302876-b9437f7b-33d4-4c14-b941-20587f01e2b3.png)

This is know I have executed the above list

**Comment by rohan1997vk** [comment]
```
this <- robyn_onepagers(select_model = '1_128_1',
                        OutputCollect = OutputCollect,
                        InputCollect = InputCollect,
                        export=FALSE)

a <- this[["1_128_1"]]
b <- a$patches
RespD <- b[["plots"]][[1]][["data"]]
RespD <- as.data.frame(RespD)
Act_Pre <- as.data.frame(b[["plots"]][[2]]['data'])
ShareofSpend_eff <- as.data.frame(b[["plots"]][[3]]['data'])
```

Figured out the answer to the above question. Leaving this for other's reference. Thanks a lot!!!!!

**Comment by laresbernardo** [comment]
Yes, that's how you do it! Feel free to close this ticket if your Q has been solved ;)
