### ISSUE TITLE
Actual inital budget or a channel mis-matches with the output

### ISSUE THREAD

**Issue by roh-neenopal** [facebookexperimental/Robyn#442]
## Describe issue
I have recently switched to the new version of Robyn and the graph 'Initial vs Optimized Budget Allocator' shows incorrect original budget for channels. 

Channel -1 
Actual Original Spend: 5.95%
Initial Budget Allocated( Graph Output): 24.6%

Channel-2
Actual Original Spend: 0.72%
Initial Budget Allocated( Graph Output): 4.0%

Channel-3
Actual Original Spend: 58.49%
Initial Budget Allocated( Graph Output): 49.6%

Channel-4
Actual Original Spend: 22.61%
Initial Budget Allocated( Graph Output): 19.2%

Channel-5
Actual Original Spend: 3.10%
Initial Budget Allocated( Graph Output): 2.6%

## Provide dummy data & model configuration
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration.

## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version

**Comment by kyletgoldberg** [comment]
we exclude 0 spend days from this calculation, so if you have a lot of 0 spend days for the channels that are lower than the budget allocator that would be why.

**Comment by gufengzhou** [comment]
besides what Kyle has explained, please also check [this thread ](https://github.com/facebookexperimental/Robyn/issues/479)for more context

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
