### ISSUE TITLE
GeoLift package recognition issue

### ISSUE THREAD

**Issue by robhannon** [facebookexperimental/Robyn#445]
## Describe issue
When trying to install the geolift package for as a docker image the docker build completes but when trying to actually run the container and call my API geolift is not recognized. This isn’t happening for other packages downloaded with remotes/devtools. Any ideas why?

## Environment & Robyn version
Latest Robyn version

**Comment by laresbernardo** [comment]
Hi! It seems like a docker and GeoLift concern here. Feel free to share how you built your docker and to ask in [GeoLift's repository](https://github.com/facebookincubator/GeoLift).
