### ISSUE TITLE
How do we treat the unattributed traffic or the organic traffic in the raw data which doesn't have any associated marketing channels?

### ISSUE THREAD

**Issue by qiongji75** [facebookexperimental/Robyn#446]
## Describe issue
Describe your issue and provide error message 

## Provide dummy data & model configuration
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration.

## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version

**Comment by kyletgoldberg** [comment]
hi - can you please further describe the issue and provide some detail so we can address the question?

**Comment by qiongji75** [comment]
How does the model identify the organic traffic or unattributed traffic? ie. ios doesn't provide further breakdown for which channel the acquired users come from.

**Comment by kyletgoldberg** [comment]
MMM does not rely on attributed conversion data, in fact it should be fed in unattributed impression/spend data and unattributed conversion data. Including previously attributed data will bias the results

**Comment by qiongji75** [comment]
thanks for the response. MMM performs without attributed data, ie. if we know how many users acquired through facebook, google ads, tiktok etc., we don't need to fed those channel specific data into the MMM model, instead we just fed the total acquired user from ios or andriod into the MMM model, then the model will predict which channel (facebook, google ads, tiktok etc.) is more effective by acquiring users?

**Comment by kyletgoldberg** [comment]
mmm works by feeding channel specific delivery data and using that to predict the contribution of each channel to conversions/revenue. it has a similar goal as attribution (i.e. understand ROI for media spend) but goes about it in a different way.

**Comment by qiongji75** [comment]
what is the channel specific delivery data?

**Comment by kyletgoldberg** [comment]
impressions/spend

**Comment by qiongji75** [comment]
Thanks. Even if we have clean attributed data, like we know the # of users we acquired through facebook etc. we don't feed in those data, instead the model will predict users acquired from each channel?

**Comment by kyletgoldberg** [comment]
correct - that data has some inherent bias due to attribution methodology

**Comment by Aanai** [comment]
In that case, how does one include organic in the model? Because a certain number of users/transactions should be attributed to organic traffic. It's a channel without any spend, but if we were to include it like we do say, newsletters, what input can we use?

**Comment by qiongji75** [comment]
Hi Kyle,Thanks for the message. My question is how the MMM Robyn logic to deal with the traffic of new user acquisitions related to organic or unattributed channels. There are a bunch of new acquired users we can't identify which channel the saw the digital advertisements then decide to use our products? Take ios platform as an example, middle of last year, Apple ceased to reveals the channel information so we don't visibility to measure the channel spend effectiveness (don't know how effective the Facebook, Google or Tiktok etc. are due to no visibility as where the new acquired users are coming from). So we want to understand the algorithm in the Robyn model to deal with such organic or unattributed traffics back to the channels?Hope this helps,Thanks,Joanna 
    On Monday, August 1, 2022 at 12:58:32 PM PDT, kyletgoldberg ***@***.***> wrote:  
 
 


hi - can you please further describe the issue and provide some detail so we can address the question?

**Comment by laresbernardo** [comment]
Closing given the inactivity. Feel free to open in case this issue persists.
