### ISSUE TITLE
check_datevar(dt_input) error in 3.7.0

### ISSUE THREAD

**Issue by nie-moviestarplanet** [facebookexperimental/Robyn#448]
## Describe issue
When upgrading to version 3.7.0 I get the following error:
```
Error in check_datevar(dt_input, date_var) : 
  DATE data has to be daily, weekly or monthly
```
I've been using the same dataset in 3.6.3 and below and it works perfectly fine.

## Environment & Robyn version
R version 3.7.0

**Comment by laresbernardo** [comment]
Hi @nie-moviestarplanet 
Is this happening for your own data or the demo? Can you please check your "DATE" class? What format is it in? Can't debug without a reproducible example. Thanks for sharing.

**Comment by nie-moviestarplanet** [comment]
Found the issue. The data was not ordered by date. After applying ascending order it now works. I guess this was not a requirement for previous versions?

**Comment by laresbernardo** [comment]
We haven't added new checks on that `check_datevar()` really. And we do [sort](https://github.com/facebookexperimental/Robyn/blob/main/R/R/checks.R#L82) the dates in ascending order before we check that. So I'm not sure why or how you got that error. If you'd like to give me a reproducible example ideal, if everything's OK, feel free to close this ticket. Cheers!

**Comment by nie-moviestarplanet** [comment]
I have attached the dataset that I'm using. 

This is the code to reproduce the error:

```
library(Robyn)
library(readr)

robyn_test <- read_csv("robyn_test.csv")
robyn_test$DATE = as.Date(robyn_test$DATE,  format = "%m/%d/%Y")
robyn_test_ordered <- robyn_test[order(robyn_test$DATE),] # It works when using robyn_test_ordered

data("dt_prophet_holidays")

InputCollect <- robyn_inputs(
  dt_input = robyn_test
  ,dt_holidays = dt_prophet_holidays
  ,date_var = "DATE" 
  ,dep_var = "DEP_VAR" 
  ,dep_var_type = "conversion" 
  ,prophet_vars = c("trend", "season", "holiday", "weekday") 
  ,prophet_country = "US"
  ,context_vars = NULL 
  ,paid_media_spends = "MEDIA_S" 
  ,paid_media_vars = "MEDIA_I" 
  ,organic_vars = NULL 
  ,factor_vars = NULL 
  ,window_start = "2022-01-01"
  ,window_end = "2022-07-28"
  ,adstock = "geometric" 
)
```

[robyn_test.csv](https://github.com/facebookexperimental/Robyn/files/9221669/robyn_test.csv)

**Comment by laresbernardo** [comment]
Thanks a lot for your reproducible example @nie-moviestarplanet that did the trick!
It's been fixed now. No need to manually sort the dates before passing the data.frame to `robyn_inputs()`
Feel free to test and close this ticket.

**Comment by nie-moviestarplanet** [comment]
It works now. Thanks!
