### ISSUE TITLE
Calculation for xDecompAgg

### ISSUE THREAD

**Issue by anuragvimal** [facebookexperimental/Robyn#450]
@kyletgoldberg Can you please help me understand the calculation for xDecompAgg? I understand this is being used as a percentage in waterfall decomposition and calculating ROIs. Thank you for your time.

**Comment by kyletgoldberg** [comment]
is there a specific part of xDecompAgg you are having trouble with? if you go into the outputs.R file and/or model.R file you should be able to find the code creating that table

**Comment by laresbernardo** [comment]
Taken from our [schema](https://github.com/facebookexperimental/Robyn/blob/main/demo/schema.R) doc:
```
xDecompAgg : Numeric. Aggregated decomposed effect. 
Pseudo-calc: sum(beta1 * channel1_adstocked_saturated)
```

**Comment by anuragvimal** [comment]
Thanks so much @laresbernardo and @kyletgoldberg. This helps. :)
