### ISSUE TITLE
Issue installing Robyn on Ubuntu

### ISSUE THREAD

**Issue by jaylin92** [facebookexperimental/Robyn#452]
## Describe issue
I'm unable to install Robyn through cran or github.

This is the error I get when I try to install it.
ERROR: dependencies ‘data.table’, ‘dplyr’, ‘ggridges’, ‘glmnet’, ‘lares’, ‘lubridate’, ‘minpack.lm’, ‘nloptr’, ‘prophet’, ‘rPref’, ‘tidyr’ are not available for package ‘Robyn’
* removing ‘/home/jaylin/R/x86_64-pc-linux-gnu-library/4.2/Robyn’
Warning in install.packages :
  installation of package ‘Robyn’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp2HzkzS/downloaded_packages’

## Environment & Robyn version
Session Info:

version  R version 4.2.1 (2022-06-23)
 os       Ubuntu 22.04.1 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/New_York
 date     2022-08-02
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   2.9.2.1 @ /usr/bin/pandoc

**Comment by laresbernardo** [comment]
Hi! We can't replicate your issue but taking a look at [Robyn's CRAN checks by OS](https://cran.r-project.org/web/checks/check_results_Robyn.html), it seems you shouldn't have a problem with any of its flavours (r-devel-linux-x86_64-debian-gcc, r-devel-linux-x86_64-debian-clang). Check your internet connection maybe.

**Comment by laresbernardo** [comment]
[This](https://datawookie.dev/blog/2022/08/linux-packages-for-r/) external post might come useful for Linux users.
