### ISSUE TITLE
How Robyn compute ROI on each spend channel? 

### ISSUE THREAD

**Issue by DioneyC** [facebookexperimental/Robyn#453]
I would like to know how is the compute of each channel ROI. What variables are involved and the general formula in macro?. Thanks.

**Comment by laresbernardo** [comment]
Taken from our [schema](https://github.com/facebookexperimental/Robyn/blob/main/demo/schema.R) doc, you'll get:
```
roi_total: Pseudo-calc: roi_total = xDecompAgg / total_spend.
xDecompAgg (Aggregated decomposed effect). Pseudo-calc: sum(beta1 * channel1_adstocked_saturated)
```

**Comment by DioneyC** [comment]
Thank you! I just read how XdecompAgg is computed in the code but didn't find the ROI calculation. I suppose that isn't in the model.R code.

**Comment by laresbernardo** [comment]
That's right. You can find this calculation in the pareto.R file, [here](https://github.com/facebookexperimental/Robyn/blob/main/R/R/pareto.R#L110).
