### ISSUE TITLE
Calibration Parameters from GeoLift

### ISSUE THREAD

**Issue by robhannon** [facebookexperimental/Robyn#454]
## Describe issue
I am using fb's GeoLift package to calculate Lift but am not not sure what I should add as calibration inputs in Robyn. There are no specific dates in the GeoLift package but rather a treatment period which might not span the full length of the data table. Also not exactly sure what liftAbs might be? I believe I understand spend should be the total investment from the test but if I am wrong please let me know! Thanks

## Environment & Robyn version
R version latest

**Comment by gufengzhou** [comment]
liftAbs means total incremental response. Assuming treament period is from date  A to B, you should just put A and B as start and end date. Assuming GeoLift gives you incremental response of Y during A-B, and if the spend level in GeoLift is the same spend in the same period in Robyn, then you can just put Y as liftAbs. If not, you should scale Y up using the ratio of spend in Robyn & GeoLift within the period, then put that as liftAbs

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
