### ISSUE TITLE
Error in check_paidmedia

### ISSUE THREAD

**Issue by atoontas** [facebookexperimental/Robyn#455]
## Describe issue
I keep on getting the same error message when trying to run the InputCollect:

Error in check_paidmedia(dt_input, paid_media_vars, paid_media_signs,  : 
  Provided 'paid_media_vars' is not included in input data

I have looked for missing values,etc. And there are none and I cannot understand why it isn't running. The simulated data works fine.

## Provide dummy data & model configuration
df = read.csv("~/Desktop/Robyn/Mediabudgetcsv.csv")
df1 = data.frame(df)

library(tidyverse)
library(lubridate)

########### add 2 days to make the week start Monday
df1$Date <- as.Date(df1$Date) +2

data("dt_prophet_holidays")
head(dt_prophet_holidays)

sum(is.na(df))

robyn_object <-  "~/Desktop/MyRobyn.RDS"

InputCollect <- robyn_inputs(
  dt_input = df1,
  dt_holidays = dt_prophet_holidays,
  date_var = "Date", 
  
  dep_var = "n_visitors_rouk", 
  dep_var_type = "conversion", 
  
  prophet_vars = c("trend", "season", "holiday"), 
  prophet_country = "GB", 
  context_vars = c("competitor_S"), 

  paid_media_spends = c("audio_s", "videos_S"), 
  paid_media_vars = c("audio_s", "videos_S"), 
 
  organic_vars = c("email_I", "push_I"), 
  #factor_vars = c("events"), 

  window_start = "2021-01-08",
  window_end = "2022-07-01",
  
  adstock = "geometric" # geometric, weibull_cdf or weibull_pdf.
)
print(InputCollect)
## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version
3.7.1
[Mediabudgetcsv.csv](https://github.com/facebookexperimental/Robyn/files/9269651/Mediabudgetcsv.csv)

**Comment by laresbernardo** [comment]
Taking a look at your data, "audio_s" should be "audio_S" (uppercase S)

**Comment by atoontas** [comment]
I am still getting the same error.

> Taking a look at your data, "audio_s" should be "audio_S" (uppercase S)

**Comment by laresbernardo** [comment]
Please, double-check: `videos_S` should be `video_S`.
Added a new chunk of code to help users detect these errors faster.

**Comment by atoontas** [comment]
You are correct. Sorry for the inconvenience caused @laresbernardo
