### ISSUE TITLE
robyn_json configuration file to be saved in robyn results directory by default

### ISSUE THREAD

**Issue by PetricaR** [facebookexperimental/Robyn#456]
Hello, 

Is it possible to have the exported configuration file (JSON in the same folder with the experiment results)?

robyn_json(InputCollect, dir = "~/experiment_folder_name")

Thanks
Petrica

**Comment by laresbernardo** [comment]
Hi! When you have simply created `InputCollect` you still don't have that folder created. You can export it manually as you suggest or after you have created `OutputCollect`, use `OutputCollect$plot_folder` as `dir`. 

Said that, we can automatically save the InputCollect when we run `robyn_outputs()` (to save `InputCollect` inputs) and when running `robyn_save()` to save the exported model's info too. I'll get this done.

**Comment by PetricaR** [comment]
Great!

**Comment by laresbernardo** [comment]
Hey @PetricaR I've updated the [demo.R file](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R) so people start using these new methods to export and import Robyn models instead of the RDS files. Would you be so kind to test them out? Thanks!
(Remember you must update your Robyn version to the latest dev version)

**Comment by PetricaR** [comment]
I am doing this right now. I will let you know how it works.

**Comment by laresbernardo** [comment]
Cool! Thanks for checking and sharing. For potentially following questions, I'm sharing how to use it to replicate Robyn stuff:

```
# Manually create JSON file with inputs data only
robyn_write(InputCollect, dir = "~/Desktop")

# Manually create JSON file with inputs and specific model data
robyn_write(InputCollect, OutputCollect, select_model)

# Recreate `InputCollect` and `OutputCollect` objects
# Pick any exported model (initial or refreshed)
json_file <- "~/Desktop/Robyn_202208081321_init/RobynModel-1_6_1.json"

InputCollectX <- robyn_inputs(
  dt_input = dt_simulated_weekly, 
  dt_holidays = dt_prophet_holidays,
  json_file = json_file)

OutputCollectX <- robyn_run(
  InputCollect = InputCollectX,
  json_file = json_file,
  export = FALSE)

RobynRefresh <- robyn_refresh(
  json_file = json_file,
  dt_input = InputCollectX$dt_input,
  dt_holidays = InputCollectX$dt_holidays,
  refresh_steps = 10,
  refresh_mode = "manual",
  refresh_iters = 500,
  refresh_trials = 1
)

```
NOTE: keep in mind these files DO NOT store your dataset nor the holiday data, so they must be provided as well to recreate models and objects.

**Comment by PetricaR** [comment]
Awesome!!!
