### ISSUE TITLE
Unable to use the model_id from previous models

### ISSUE THREAD

**Issue by Tony-009** [facebookexperimental/Robyn#46]
## Issue

As mentioned in previous issues comments, I was trying to use one of the Model_id from previous models since it was providing better results. However, it says "not the best model" and "error: model cant be found".Furthermore, Is there any way to recreate the results as in one of the previous model results?

## Steps to Reproduce

Tried to put local bounds as that mode(fixed all hyperparameters). Although, some confusion on this part. An example would help.

## Expected Behavior

Should be able to utilise that model result and apply to the budget allocator

## Actual Results

![image](https://user-images.githubusercontent.com/46905239/113711283-c3e76900-96b2-11eb-90b4-390cc20e7abb.png)

## Environment

R version (R --version)

**Comment by gufengzhou** [comment]
There is a new update with the new function f.robyn.fixed that allows directly using the old hyperparameter csv to rebuild "old models". Description is in the .exec script. Let me know if it works.

**Comment by Tony-009** [comment]
Thanks! I'll take a look

**Comment by Tony-009** [comment]
Hey! I tried the updated script and getting this error below. Tried to tweak my approach but still. Let me know your thoughts.

![image](https://user-images.githubusercontent.com/46905239/114315490-35695200-9acd-11eb-9660-0383f02aedb1.png)

**Comment by gufengzhou** [comment]
This was a bug that should be fixed couple days ago . Would you try the latest version please?

**Comment by Tony-009** [comment]
I just tried few minutes ago by loading all the new function, optim scripts but the same result(unused argument). I even created a new model and tried to ingest that to see if it can pick that up but it was futile. I am not sure why is it happening because I can see this being called in the both aforementioned scripts. Let me know your thoughts or any suggestions you might have

**Comment by gufengzhou** [comment]
the earlier bug fix commit was strangely not merged correctly. sorry for that. maybe try now?

**Comment by Tony-009** [comment]
Great! it works, Thanks for the help! I have another question regarding the budget allocator. So, if we have the initial vs optimised budget allocation which provides the idea as to how much increase the budget should be to get optimal responses but I am a bit confused on the response curve and mean spend by channel. Please see the image below
![image](https://user-images.githubusercontent.com/46905239/114427793-6dce6600-9b89-11eb-94d9-ccbd87c9388b.png)
 Does this mean that this number is how much it should be optimised to? because this number doesn't match the avg optimised spend share . Is it a saturation point? Apprciate the input.

**Comment by gufengzhou** [comment]
Yes the triangle dot is the recommended optimal spend level. If you look at the example plot in readme, you can see for example channel1 increased from 111k-->134k, while the share of spend increased from 34%-->41%. They should match proportionally.

**Comment by Tony-009** [comment]
That makes sense. I reckon they are not matching in my case because its showing me the average optimized budget allocation per week whereas the response curve spends by channel is giving me the definitive optimized number. Just trying to make sense and have a consistent story. Please see the image below So as we follow the line there would be a saturation point after the recommended optimized number, correct?
![image](https://user-images.githubusercontent.com/46905239/114435158-d91c3600-9b91-11eb-808c-63d1995ebaaa.png)

**Comment by gufengzhou** [comment]
Well saturation is the entire curve, not a specific point, in my opinion. Or what do you mean by "saturation point"?

**Comment by Tony-009** [comment]
I see! I just thought there may be a specific point/spend number that wouldn't get any response. I reckon your point makes sense because its a curve, not a particular number. Thanks for the input

**Comment by Tony-009** [comment]
Hey! As I am getting more familiar with budget allocate there are few questions that have been on my mind.
Can the budget allocator provide more insight into the effect on the response if the spending gets increase? Think in terms of actual results such as how much would be the predicted response taking into account diminishing return just to put a number to it to make brand people understand. Thanks for the input
