### ISSUE TITLE
Total Spend Increase

### ISSUE THREAD

**Issue by robhannon** [facebookexperimental/Robyn#461]
## Describe issue
I am not able to find a proper formula that gives the total spend increase from the Robyn_allocator function for the "max_response_expected_spend". I sometimes get negative values which I have been able to mess around with to resolve, but was wondering what the exact formula was?

## Environment & Robyn version
Latest Robyn version

**Comment by kyletgoldberg** [comment]
check this here, should help explain it https://github.com/facebookexperimental/Robyn/issues/409#issuecomment-1177895687

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
