### ISSUE TITLE
question on Budget Allocator Max_response_allocator

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#465]
## Max Response Allocator

Question on the current logic for Max_response in budget allocator. 

It looks like the current logic when computing max_response_expected is to compare histSpend with Expected Spend.   What this does is to compare a previous share allocation at a different budget (histSpend) vs. a new budget (ExpectedSpend).   
	
Shouldn’t the comparision be ExpectedSpend(with old share allocation) to ExpectedSpend (with optimized Share allocation)?  

For example. If we have a historical budget of $1m and historically, it was split Media 1(70%) and Media2(30%).   If we want to optimize on a new budget (let's say $2M).  Should we be comparing the response of new budget with Media 1($2M*.70) and Media2($2M *.3) vs. an optimized share allocation of Media 1 ($2M*OptmizedSharemedia1) and Media2($2M*optimizedsharemedia2).   Then compare/show the expected responses for both.
	
I think currently initSpendUnit = histSpendUnit which compares historical spend vs. new Expected spend.
	
Hope that makes sense.

Robyn version 3.7

**Comment by gufengzhou** [comment]
Hi, we actually compare the optimised spend share with the initial spend share, as well as the optimised response (or allocation) share with initial. I'm not 100% sure about your question. 

You can also check the script in R/R/allocator.R

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
