### ISSUE TITLE
Error in setting/configurate Python and Nevergrad on Linux Server

### ISSUE THREAD

**Issue by DioneyC** [facebookexperimental/Robyn#467]
I'm trying to configure Robyn on a Linux server, but when I set the python path it doesn´t recognize nevergrad. I decided to create a virtual environment without using the R commands we can find in Robyn's installation examples. Then, I download nevergrad in the environment and try to specify the python path with the following line: 

- use_python("/path/anaconda3/envs/r-reticulate/bin/python3.9")

also tried with this option 

- Sys.setenv(RETICULATE_PYTHON = "/path/anaconda3/envs/r-reticulate/bin/")

I also tried to check the environment settings with  **py_config()** but it doesn´t recognize nevergrad. 

How can R Recognice Nevergrad.

Thanks. 

## Environment & Robyn version
R version (4.2.1)
Robyn version (3.6.3)

**Comment by Leonelsentana** [comment]
Hi @DioneyC,

Are you sure that /path/anaconda3/envs/r-reticulate/bin/ is the right path where you have python installed? Does py_config() mention anything on this?

Thanks

**Comment by DioneyC** [comment]
Hi @Leonelsentana , Thanks for answering this issue. I'm sure that is the correct path, except for the "/path/". I replace it to minimize the path size.

**Comment by Leonelsentana** [comment]
Hi @DioneyC, all I can offer you is to try docker. It has been useful for Linux users, you can check the files in https://github.com/facebookexperimental/Robyn/tree/main/R/Docker. Also docker image is here: https://hub.docker.com/layers/leosentana/robyn/latest/images/sha256:fd701fe582d1314d4baae99b6daa664f210b21e310006d003c8c42710ab70382?fbclid=IwAR0Ns3-g0pqYgQzJgKAtNAOJzOPsmJ_CD1jVcbNjtBKQMfybeuyMxY_MgzI

**Comment by laresbernardo** [comment]
Closing given the inactivity. Feel free to open in case this issue persists.
