### ISSUE TITLE
feature engineering | getting error "Error in setup_dataframe(m, history, initialize_scales = TRUE) :    Regressor "...1" missing from dataframe"

### ISSUE THREAD

**Issue by DYX10** [facebookexperimental/Robyn#469]
## Describe issue
Describe your issue and provide error message 

When setting hyper parameters, saw this error message

> Running feature engineering...
> New names:
> • `` -> `...1`
> New names:
> • `...1` -> `...6`
> Error in setup_dataframe(m, history, initialize_scales = TRUE) : 
>   Regressor "...1" missing from dataframe

## Provide dummy data & model configuration
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration.
Apple/M1 Chip
## Environment & Robyn version
R version (R --version)
Please make sure you're using the latest Robyn version
Yes

**Comment by laresbernardo** [comment]
Hi @DYX10 Please share a reproducible example. It seems it [may](https://stackoverflow.com/questions/48925255/fbprophet-giving-error-when-growth-logistic-python) have something to do with prophet. But no chance of reproducing your issue as reported.

**Comment by laresbernardo** [comment]
Taken from an internal message I got from another user that got this same error:

> I found the problem may come from how the code handle categorical input: when there is no "na" in the categorical data column, it will show the error above. When I change one data entry with "na" for that column, it won't show the error. So it could be the mapping issue for the categorical data.

This issue has already been solved in latest versions. Please, update. For reference: when a variable contains only a single value (no variance), when running `robyn_inputs()` it'll check for variables that are being used and have no variance and will stop with an informative error saying so. So you should remove that variable (from the dataset or not use it in any of the parameters).

**Comment by laresbernardo** [comment]
Additionally, we've detected another potential source for this issue (which should've been fixed in the [latest commit](https://github.com/facebookexperimental/Robyn/commit/cb618c116d7b9f9272c915202240555449b83977)). There was a bug when running one-hot-encoding and 1) you had only 1 categorical variable defined in `factor_vars` and 2) it had only 2 levels (unique values). Shouldn't break now. Feel free to update, test, and reply @DYX10

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
