### ISSUE TITLE
Error completing a JSON export and import

### ISSUE THREAD

**Issue by EaPalacios** [facebookexperimental/Robyn#473]
## Project Robyn

I am trying to complete step #331 where I perform a JSON export and import. The instruction is: 
```
ExportedModel <- robyn_write(InputCollect, OutputCollect, select_model)
print(ExportedModel)
```

When I try running it, the error message I receive is:
```
Error in robyn_write(InputCollect, OutputCollect, select_model) : 
  select_model %in% OutputCollect$allSolutions is not TRUE
```
I was able to successfully run all steps prior to this one.

My Robyn package version is 3.7.1. 
My RStudio information is 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6_8) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36.

**Comment by laresbernardo** [comment]
Hi @EaPalacios that's expected when the selected model you wish to export is not one of the models created. Print `OutputCollect` and check the model IDs available for you to export.

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
