### ISSUE TITLE
Confusing log output (hyperparameters check)

### ISSUE THREAD

**Issue by sallyhong** [facebookexperimental/Robyn#474]
## Describe issue
in the `facebookexperimental/Robyn/R/R/checks.R` file,
<img width="751" alt="image" src="https://user-images.githubusercontent.com/8099467/187069442-7da757e0-b455-4e2e-82f6-0e8631fc3461.png">
The output is reversed. 
Line 432 should be `total_in,  total` 

## Provide reproducible example
<img width="700" alt="image" src="https://user-images.githubusercontent.com/8099467/187069503-59515392-503f-4449-b326-922af8544dc6.png">
I literally provided 6 parameters, but 12 were required.

## Environment & Robyn version
Robyn v3.7.1

**Comment by laresbernardo** [comment]
Thanks for reporting this mistake @sallyhong Fixed! :)
