### ISSUE TITLE
Initial Mean response and Optimized mean response issue

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#477]
Is there a way to convert the Initial Mean response from the budget allocator to match the original conversion values?

**Comment by Leonelsentana** [comment]
Please chack my calcs done on the last comment here: https://github.com/facebookexperimental/Robyn/issues/227

**Comment by virithavanama** [comment]
Hi, @Leonelsentana Thanks for the response.
The calculations you mentioned in that comment are for spend but I want the calculations for Initial mean response(conversions) to match to original conversions

**Comment by Leonelsentana** [comment]
So, this would be almost the same but changing to response instead of spend. Does that make sense? Taking the example from https://github.com/facebookexperimental/Robyn/issues/227 you would need to do: 
**[total_conversions (for certain channel) + ((optmResponseUnit - initResponseUnit) x non-zero spend time_units (non-zero spend weeks or days in your window), then divide by the total_conversions].**

**Comment by virithavanama** [comment]
From my data:
Aggregated csv data:
channel 1:
Total_spend=1461776
Roi_total=0.0061
Total conversions_channel1=1461776*0.0061=5006.78
channel 2:
Total_spend=120793.77
roi_total=0.0034
Total_conversions_channel2=120793.77*0.0034=732.23
Total_conversions=5006.78+732.23=5739.01
Reallocated csv data:
optmresponseunit_channel1=45.71
initResponseUnit_channel1=44.63
(optmResponseUnit - initResponseUnit)_channel1=1.08
non-zero spend time_units(as of budget allocator) =51 weeks]
Based on the formula [total_conversions (for a given channel) + ((optmResponseUnit - initResponseUnit) x non-zero spend time_units (non-zero spend weeks or days in your window for that channel), then divide by the total_conversions]
=> (5006.78+(1.08*51))/5739.01 = 0.88 what does this value represent?
What I want is the original conversions for channel 1 which is around 10042

**Comment by virithavanama** [comment]
10042 is the total conversions for 51 weeks directly from the original data and the value without division is 5061.86 which is not matching

**Comment by Leonelsentana** [comment]
How is it that you know that total conversions for a specific channel should be 10042, if MMM works with total non-attributed values for conversions? Please have in mind that your original data should not use any kind of attributed data, rather total spend, clicks, impressions, etc.

**Comment by virithavanama** [comment]
Hi the original data has the total spend and total conversions for each channel split. So based on this we know that that specific channel should have 100042 conversions
<img width="314" alt="Screen Shot 2022-09-06 at 8 57 47 AM" src="https://user-images.githubusercontent.com/89505409/188641251-4b6d6b31-4feb-4964-9b33-f866646a5853.png">

**Comment by Leonelsentana** [comment]
Hi, is your original data the data you used as input to build the model? If so, this is not correct, marketing mix models are built based on TOTAL conversions and TOTAL spend. Please avoid using any type of attributed data as an input for the MMM models.

**Comment by gufengzhou** [comment]
Hi @virithavanama , there's a similar issue about this point, please check it [here](https://github.com/facebookexperimental/Robyn/issues/479)

**Comment by virithavanama** [comment]
Hi Team,
In the demo its mentioned "dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)"" so we have used conversions as per demo. We get daily data from channels like Google ads (paid search), google DCM(paid display), etc. So, we know the total conversions for each channel individually. Then the data is transformed into weekly data and passed to the model. I have attached the screenshot of the sample data that is being passed to the model.
<img width="818" alt="Screen Shot 2022-09-07 at 4 02 31 PM" src="https://user-images.githubusercontent.com/89505409/188998141-cc1dfca9-5e69-4fdd-9f0d-28d35bd7ca41.png">

**Comment by Leonelsentana** [comment]
Hi @virithavanama I presume that when you say "we know the total conversions for each channel individually" you are applying some sort of attribution logic there to indicate which conversions correspond to which channel, correct? MMM works in a different way by looking into the time series correlation of the total Impressions or total spend data points in time from each channel with the total conversions (not on a channel level, just business's total). Does that make sense? You are comparing attributed arbitrary data based on just a rule of clicks or impressions and time between those and the conversion, which does not imply the same methodology as MMM applies.

**Comment by virithavanama** [comment]
We are not applying any logic..the data directly comes from different channels like Google ads which are for paid search so we need the total conversions. There should be logic to convert the initial mean response to business conversions right?

**Comment by Leonelsentana** [comment]
The logic is the one I explained above, avoiding to divide by total_conversions https://github.com/facebookexperimental/Robyn/issues/477#issuecomment-1234002864. If you want the decomposition per day you can also get it directly from pareto_alldecomp_matrix. Each column will show each of the channels and other variables contributions to the explained Y (depVarHat)

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
