### ISSUE TITLE
robyn_run timing break

### ISSUE THREAD

**Issue by sbookhultz** [facebookexperimental/Robyn#478]
## Describe issue
My issue is with using the robyn_run statement (probably more specifically in the robyn_outputs call).

I've run a model with about 3 years worth of daily data, and ran it for 5000 iterations over 10 trials on a machine with 12 threads. My model has 109 hyperparameters (most fixed) and each trial was taking about 2 hours to run. On my 9th of 10 trials it was 99% of the way done where the timing stopped at about 3 hours. 

Is there something internal that doesn't allow a trial to run for more than 3 hours, or do you think this is a personal issue with my machine? Also, to prevent this from happening in the future, is there a way I can save the best fit models on each trial?

## Environment & Robyn version
- Robyn version 3.6.3
- R version 4.1.3

**Comment by laresbernardo** [comment]
Hi @sbookhultz thanks for reporting this.
- AFAIK, there's nothing internal that doesn't allow you to run the function for more than 3 hours. Try with fewer trials to see if you can avoid this problem. Can you share the error you get? Is something printed?
- Yes, you can export any model with `robyn_write()` functions (latest dev version - not 3.6.3 yet) and import with `robyn_read()`. Check out the flow in the last section of our [demo.R](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R) file.
- When you say probably when calling `robyn_outputs()` why do you say this? I think it must happen in `robyn_run()` independently of `robyn_outputs()` given run is to generate the models and outputs to export them. If you run the code (as we do in the demo.R file) with `outputs = FALSE` and then run `robyn_outputs(...)` you'll see they are different steps.
- All this said, I'll think if we should wrap `robyn_run()`'s iterations in a `tryCatch()` so in case something breaks we can return at least what was done so far.

**Comment by sbookhultz** [comment]
* I don't even get an error, which is weird. I get "Timing stopped at: 1.095e+04 2802 7856" from the robyn_run() call. I'll definitely try wit
*

**Comment by sbookhultz** [comment]
Well I didn't mean to close this and thanks for the quick reply!

* I'll definitely try with fewer trials, there's no actual error printed, all that prints out is 
Running trial 9 of 10
  |===================================================== |  99%
Timing stopped at: 1.095e+04 2802 7856

* I understand that I can export any specific model (that is amongst the best models) once the `robyn_outputs()` call is complete, but is it possibly to run the `robyn_write()` call inside the `robyn_run()` call? Or something similar to run the pareto clusters at say trial 5 of 10. 
* Apologies on the `robyn_outputs()`, I thought that's what is actually called. 
* I would definitely appreciate seeing what broke on my side with the `tryCatch()` so I can know if it's my data issue or something with the function call. 

Thanks again @laresbernardo.

**Comment by sbookhultz** [comment]
Well I didn't mean to close this and thanks for the quick reply!

I'll definitely try with fewer trials, there's no actual error printed, all that prints out is
Running trial 9 of 10
|===================================================== | 99%
Timing stopped at: 1.095e+04 2802 7856

I understand that I can export any specific model (that is amongst the best models) once the robyn_outputs() call is complete, but is it possibly to run the robyn_write() call inside the robyn_run() call? Or something similar to run the pareto clusters at say trial 5 of 10.

Apologies on the robyn_outputs(), I thought that's what is actually called.

I would definitely appreciate seeing what broke on my side with the tryCatch() so I can know if it's my data issue or something with the function call.

Thanks again @laresbernardo.

**Comment by laresbernardo** [comment]
Hi @sbookhultz 

I've just deployed the `tryCatch` solution 1) returning the temporal results up to where the function broke/stopped, 2) warning the user the results are partial, and 3) showing the error message if exists.

By default, when running `robyn_run()` we aren't exporting anything, we are simply training models and piling them up. Note that we "know" where to export stuff when we run `robyn_export()` and set the `plot_dir` parameter. That's how it's intended. If you want to export all models while running `robyn_run()` you can customize the code to do that for your personal use-case if needed.

**Comment by sbookhultz** [comment]
Awesome, thanks for the update and addition!
