### ISSUE TITLE
Crash on robyn_refresh() using json_file: Can't combine `..1$ds` <character> and `..2$ds` <date>

### ISSUE THREAD

**Issue by laresbernardo** [facebookexperimental/Robyn#480]
## Describe issue
A user reported in our [FB group](https://www.facebook.com/groups/robynmmm/posts/1252761488825315?comment_id=1252872338814230&reply_comment_id=1265514010883396) that experimented the following issue when running `robyn_refresh()`. The full error is:

```
Error in `bind_rows()`:
! Can't combine `..1$ds` <character> and `..2$ds` <date>.
---
Backtrace:
     ▆
  1. ├─Robyn::robyn_refresh(...)
  2. │ └─listReportPrev$xDecompVecReport %>% ... at R/R/refresh.R:402:4
  3. └─dplyr::bind_rows(...)
  4.   ├─dplyr:::fix_call(vec_rbind(!!!dots, .names_to = .id))
  5.   │ └─base::withCallingHandlers(...)
  6.   └─vctrs::vec_rbind(!!!dots, .names_to = .id)
  7.     └─vctrs (local) `<fn>`()
  8.       └─vctrs::vec_default_ptype2(...)
  9.         └─vctrs::stop_incompatible_type(...)
 10.           └─vctrs:::stop_incompatible(...)
 11.             └─vctrs:::stop_vctrs(...)
 12.               └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))
 ```
## Provide reproducible example
User shared his data and json files to reproduce the error.

```
modelrf.csv <- ".../data_for_refresh.csv"
modelrf.json <- ".../RobynModel-inputs.json"

modelrf.df <- read.csv(modelrf.csv, row.names = NULL)
RobynRefresh <- robyn_refresh(
  json_file = model1.json,
  dt_input = modelrf.df,
  dt_holidays = Robyn::dt_prophet_holidays,
  refresh_steps = 12,
  refresh_iters = 500,
  refresh_trials = 1
)
```

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: 3.7.1
- R version: R version 4.1.1 (2021-08-10)

**Comment by NN-Marketing** [comment]
Hi 

Robyn Version 3.7.2
R version 4.2.2
Robyn Demo.R

Im' geting the same issue with different code..date and IDate.. 

>>> Running Pareto calculations for 10000 models on 3 fronts...
Error in `bind_rows()`:
! Can't combine `..1$ds` <date> and `..2$ds` <IDate>.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_ptype2>
Error in `bind_rows()`:
! Can't combine `..1$ds` <date> and `..2$ds` <IDate>.
---
Backtrace:
 1. Robyn::robyn_outputs(...)
 2. Robyn:::robyn_pareto(...)
 3. dplyr::bind_rows(...)
 6. vctrs::vec_rbind(!!!dots, .names_to = .id)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/vctrs_error_ptype2>
Error in `bind_rows()`:
! Can't combine `..1$ds` <date> and `..2$ds` <IDate>.
---
Backtrace:
     ▆
  1. ├─Robyn::robyn_outputs(...)
  2. │ └─Robyn:::robyn_pareto(...)
  3. │   └─dplyr::bind_rows(...)
  4. │     ├─dplyr:::fix_call(vec_rbind(!!!dots, .names_to = .id))
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─vctrs::vec_rbind(!!!dots, .names_to = .id)
  7. └─vctrs (local) `<fn>`()
  8.   └─vctrs::vec_default_ptype2(...)
  9.     ├─base::withRestarts(...)
 10.     │ └─base (local) withOneRestart(expr, restarts[[1L]])
 11.     │   └─base (local) doWithOneRestart(return(expr), restart)
 12.     └─vctrs::stop_incompatible_type(...)
 13.       └─vctrs:::stop_incompatible(...)
 14.         └─vctrs:::stop_vctrs(...)
 15.           └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))

**Comment by laresbernardo** [comment]
Hi @NN-Marketing this issue has already been fixed in the latest dev version. Can you please update to Robyn >=3.8.1 and try again in a fresh new session? Thanks.
