### ISSUE TITLE
Unable to run robyn_allocator after loading a model using robyn_recreate

### ISSUE THREAD

**Issue by rafpinter** [facebookexperimental/Robyn#481]
## Describe issue
I'm getting an error message while trying to run `robyn_allocator` after loading a model from a JSON file using `robyn_recreate`:

```
Warning messages:
1: In png_dev(..., res = dpi, units = "in") :
  unable to open file 
```

It seems like the function `robyn_allocator` is trying to access a folder that does not exist. The `robyn_allocator` folder is different from the original model folder.

Here is the code that I ran:

![image](https://user-images.githubusercontent.com/62558186/187768733-5ef6efc2-bff9-47f7-a425-3f86f6c48f8d.png)

However, **when I manually created the folder "/Robyn_202208311641_init" at the right location, I was able to sucessfully save the png image**. Could `robyn_allocator` automatically create this folder?

## Provide reproducible example
I'm using demo data and demo scripts.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- R version: 4.2.1

**Comment by laresbernardo** [comment]
Hi @rafpinter thanks for reporting this! I can't seem to replicate your problem. Did you change the original directories? Did you move the results to another folder? Can you check your `InputCollect$plot_folder` - makes sense?

<img width="1084" alt="Screen Shot 2022-08-31 at 5 11 35 PM" src="https://user-images.githubusercontent.com/25909073/187794395-0f61fdc1-c08c-4729-8b53-adc8c716bbd6.png">

**Comment by rafpinter** [comment]
Hi @laresbernardo, thank you so much for your response. I'm going to answer your questions below.

Did you change the original directories? 
No, I didn't. I ran the line `robyn_object <- "~/Desktop"`, but it was unable to find this folder on my machine, so my current working directory was used.

Did you move the results to another folder? 
No, I didn't.

Can you check your OutputCollectX$plot_folder - makes sense? 
It does make sense, once it is te same path ending with **/Robyn_202208311641_init/**. It's indeed the folder where the JSON file of the model is located.

Are you sure you're on the latest dev version?
My package version is ‘3.7.1’. Is this it? Should I reinstall/update it? By the way, I'm running on a Windows machine.

Regarding your test, was the folder "/Robyn_202208311711_init" created at the time you ran robyn_allocator? And was that folder created at your working directory?

**Comment by laresbernardo** [comment]
> No, I didn't. I ran the line robyn_object <- "~/Desktop", but it was unable to find this folder on my machine, so my current working directory was used.

Yeah, that's an example that works in macOS. You should simply pick any (existing) directory that you want to output your results to (Documents, Desktop, etc). If it doesn't exist, it'll dump the outputs in your current directory (`getwd()`).

> Regarding your test, was the folder "/Robyn_202208311711_init" created at the time you ran robyn_allocator? And was that folder created at your working directory?

Correct!

**Comment by rafpinter** [comment]
Hi @laresbernardo, thanks for the info. I did another test in the Vertex AI Workbench and it seems to be working fine. I'm not sure why it wasn't working on my windows machine, but I'll try to set a preexisting folder when I'm runing the code.
