### ISSUE TITLE
Data preparation for Robyn

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#483]
Hi Team,

In the data preparation document for Robyn, it is mentioned that we have to maintain the channel to rows ratio is 1:10. And in the modeling it's mentioned we can give complete data and choose a rolling window for building the model. So if I have data with 3 channels,
 do we need to give complete 2 years of data aggregated in weeks (104 weeks) and select the latest 30 weeks as the rolling window? 
or just take the latest 30 weeks' data as the complete data and build the model?

**Comment by gufengzhou** [comment]
Yes always input all available data. Regarding window length, if you use Robyn's trend season and holiday, you'll add another 3 indep vars so you'll want to go for 60 weeks of window length

**Comment by virithavanama** [comment]
Thank you
