### ISSUE TITLE
Hyperparameters range effect on the model

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#484]
Hi Team,

In the documentation, it is suggested to use custom hyperparameter ranges(eg: alpha=(0.5,3)) for digital channels rather than using the complete range. How is the custom range going to affect the model? And for some data full range is performing better than the suggested range, is it ok to go ahead with the complete range?

**Comment by gufengzhou** [comment]
You can find detailed explanation of what each hyppar means [here](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R#L131). it's also very recommended to look at both helper plots `plot_adstock(plot = TRUE)` and `plot_saturation(plot = TRUE)  ` to assess the change visually

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
