### ISSUE TITLE
Channels with effect share is high and less change in the optimized spend

### ISSUE THREAD

**Issue by roh-neenopal** [facebookexperimental/Robyn#485]
## Describe issue
How do we conclude when the effect share is high and less change in optimized spend for a channel.

## Provide reproducible example
I have 15 channels and a couple of them show a high effect share ~ 10-15% whereas their spend share is around 1%. However, the optimized share shows a small increase only. The up_construct variable has the recommended value of 2 and low_construct is 0.7

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
> packageVersion("Robyn")
[1] ‘3.6.3’

**Comment by gufengzhou** [comment]
how much a channel will increase/decrease in the allocator is all depending on the saturation curve. Assuming one channel is  already reaching a slow increasing part of the curve, but as long as it's still more efficient than other channels, the allocator will still recommend to increase budget for this channel. And vice versa

**Comment by roh-neenopal** [comment]
![image](https://user-images.githubusercontent.com/90190987/188372914-e550ee2c-461c-4841-acf3-1fdbad92cbe2.png)
![image](https://user-images.githubusercontent.com/90190987/188373017-566bd974-71e3-4305-ac37-9e935c9850fc.png)
![image](https://user-images.githubusercontent.com/90190987/188373052-c150759e-d546-4709-8d06-3eade91e9d0a.png)
The first is the response curve; the Second and third are the initial vs optimized spend results. The response curve is increasing and no saturation kis visible for them. However, the initial vs optimized results show very little difference.

**Comment by gufengzhou** [comment]
1.2% & 1.8% are spend shares? Then it looks like spend shares is +50%, effect share is also +50%. Looks very linear to me and looks also appropriate to the purple line that's rising very steeply, if I understood you correctly. You should also experiment increasing/changing the upper constraints to check out alternative allocation solutions

**Comment by roh-neenopal** [comment]
1.2% is the initial spend share for Channel-1 and 0.4% is initial spend for Channel-2. 1.8% is the optimized spend share for Channel-1 and 0.6% is optimized spend for Channel-2
