### ISSUE TITLE
Negative trend

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#486]
what do negative trend and maximum positive season mean?
<img width="372" alt="Screen Shot 2022-09-02 at 10 51 13 PM" src="https://user-images.githubusercontent.com/89505409/188253114-5573766d-3c80-4cb9-86d3-90bcc494b796.png">

**Comment by gufengzhou** [comment]
There's no point in interpreting the model when it's not properly specified.

**Comment by virithavanama** [comment]
What details do you need?

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
