### ISSUE TITLE
Cost vs impressions

### ISSUE THREAD

**Issue by muuratjann** [facebookexperimental/Robyn#488]
When I run the algorithm using the [impressions and costs] and [only costs], I get the same results except that [impressions and costs] give less models to choose from. Otherwise the model codes like 3_1024_3 and the plots and summaries are exactly the same. Is there a reason for that? When I investigated the reason, I found out the following:

I specify the model in this way:

InputCollect <- robyn_inputs(
  dt_input = data,
  dt_holidays = dt_prophet_holidays,
  date_var = "Date", # date format must be "2020-01-01"
  dep_var = "Requests", # there should be only one dependent variable
  dep_var_type = "conversion", # "revenue" (ROI) or "conversion" (CPA)
  prophet_vars = c("trend", "weekday"), # "trend","season", "weekday" & "holiday"
  prophet_country = "BE",
  context_vars = c("Churn", "nps"), # e.g. competitors, discount, unemployment etc
  context_signs = c('negative', 'positive'),
  paid_media_spends = c('Branded_c', "Display_c", "Generic_c", "Native_c", "Facebook_c","TikTok_c", "Youtube_c", "Pinterest_c", "Snapchat_c"), # mandatory input
  paid_media_vars = c('Branded_i', "Display_i", "Generic_i", "Native_i", "Facebook_i","TikTok_i", "Youtube_i", "Pinterest_i", "Snapchat_i"), # mandatory input
  paid_media_signs =c('positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive'),
  adstock = "weibull_cdf" # geometric, weibull_cdf or weibull_pdf.
)
hyper_names(adstock = InputCollect$adstock, all_media = InputCollect$all_media)

But as hyper parameters I only get the ones relating to the costs only. I think it was supposed to be relating to the impressions.

**Comment by gufengzhou** [comment]
Exposure metrics are used to show their to spends as additional information. For main model fitting, only spend is used. The major reason lies in the saturation curve and budget allocation. When using spend, we get cost-response relationship directly via hill function, which can be directly used in budget allocator. When using imps, we need to do extra fitting between imps and spend to recover the cost-response relationship. Considering the quite large uncertainty in imps-spend translation, it could results in very unreliable budget recommendation. 

Even though we're aware of the advantages of using exposure metrics, at least for now it's not worth the trade-off. Hope it makes sense

**Comment by muuratjann** [comment]
@gufengzhou 

Thank you for your response. That makes sense!

**Comment by bart-vanvlerken** [comment]
I would like to re-open this issue, because I may have found some contradicting information in the analyst guide based on this answer: https://facebookexperimental.github.io/Robyn/docs/analysts-guide-to-MMM#feature-engineering

In the costs vs. impressions section, it is stated that "it is recommended to use media exposure metrics like impressions or GRPs for modeling. While it isn’t recommended to use for modeling purposes, media spends should also be collected in order to calculate a Return On Investment (ROI) and to help simulate budget allocations".
