### ISSUE TITLE
Initial vs. Optimised Mean Response - Initial Mean Response

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#490]
The initial Mean response for most channels is showing as 0 for robyn_allocator with max_historical_response

<img width="515" alt="Screen Shot 2022-09-09 at 2 55 54 PM" src="https://user-images.githubusercontent.com/89505409/189451237-f91d964e-6e64-4c7e-96af-098acfcfbd22.png">

<img width="538" alt="image" src="https://user-images.githubusercontent.com/89505409/189451787-a65cf4c2-eaf9-47cf-b729-fdd9bd20338e.png">

**Comment by gufengzhou** [comment]
Can you show the onepager of your selected model, as well as the upper and lower contraints in the allocator?

**Comment by virithavanama** [comment]
channel_constr_low = 0.75
channel_constr_up = c(1.44, 1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5)
![3_159_7](https://user-images.githubusercontent.com/89505409/189660899-f84d1551-001f-4932-8090-f43d64bd811e.png)

**Comment by gufengzhou** [comment]
Only digital audio and paid search has initResponseUnit of about 9, all others are close to 0. So the allocator is showing right values. 

Please share your selected onepaper. You seem to have chosen a model that's not aligned with your expectation

**Comment by virithavanama** [comment]
Above the attached one-pager is the selected model. All the other models are not matching our business.
