### ISSUE TITLE
Some questions about weibull function

### ISSUE THREAD

**Issue by togawakotori** [facebookexperimental/Robyn#492]
Hi, as a beginner to MMM, I try to use your great Robyn to learn MMM. I have a few questions here:

https://github.com/facebookexperimental/Robyn/blob/162449c1dcbf7a4e1983d6c323ef6e1c436a351f/R/R/transformation.R#L129

In Robyn/R/R/transformation.R, line 129, I don't quite understand why a cumprod function is used, as thetaVec seems to be the 
value of adstock rate itself. Could there be some more explanation here?

Also，I'm not clear about the formula of weibull in https://facebookexperimental.github.io/Robyn/docs/features/#adstock
It seems to be unreasonble as alpha is not defined, and the scale, shape parameter don't show up.
![image](https://user-images.githubusercontent.com/26295681/190125170-23d27912-8821-4c72-a670-31ccd07f6c97.png)

**Comment by gufengzhou** [comment]
Hi, good questions. Take geometric as example, when theta ==0.5, thetaVec is c(0.5, 0.5, 0.5, ...) and thetaVecCum is c(0.5, 0.25, 0.125, ...). For Weibull, it's a varying decay rate, so thetaVec is c(0.9, 0.8, 0.6, ...) and thetaVecCum is c(0.9, 0.72, 0.432, ...). Makes sense?

For the documentation, we'll check and update accordingly. @kylescotshank FYI

**Comment by togawakotori** [comment]
Thank you for your explanations! I've understood the function of cumprod.
