### ISSUE TITLE
Robyn mmm for data with multiple Geos

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#494]
How to run Robyn mmm for data with multiple Geos

**Comment by laresbernardo** [comment]
Hi! What you are referring to is being able to use panel data for building hierarchical models. As of now, we are not able to do this straightforward with Robyn, given you must provide a single date per row. Please, read more about it [here](https://github.com/facebookexperimental/Robyn/issues/418#issuecomment-1165613542). We have planned to enable panel data eventually but have other features with higher priority.

On the other hand, please ask for help either on GitHub OR Facebook group for a single same question. I noticed you asked about this [here](https://www.facebook.com/groups/robynmmm/posts/1275753419859455/). There are a couple of suggestions from other community members referring to building multiple Robyn models, one per region.
