### ISSUE TITLE
Latest release notes are not reflected in the webpage

### ISSUE THREAD

**Issue by ogencoglu** [facebookexperimental/Robyn#495]
Last release note that is in the [webpage](https://facebookexperimental.github.io/Robyn/docs/releases) is 3.6.3. Would be nice to have the latest release notes there too as there are important changes.

**Comment by laresbernardo** [comment]
Hi @ogencoglu thanks for reporting this, and you're quite right: we have a bit of a delay updating the website now but @kyletgoldberg will be working on it these following days (after delivering the RobynLearn last week he can spend some more time on the site). For now, you can keep track of all changes on the [Releases](https://github.com/facebookexperimental/Robyn/releases) section of our repository.

**Comment by laresbernardo** [comment]
[Releases](https://facebookexperimental.github.io/Robyn/docs/releases/) section fully up to date.
