### ISSUE TITLE
Docker image for Robyn Learn

### ISSUE THREAD

**Issue by PetricaR** [facebookexperimental/Robyn#505]
Hello Robyn team, 

It is possible to have a docker image for Robyn Learn Web Application.

I would like to deploy this docker image on google cloud run.

Thank you

**Comment by laresbernardo** [comment]
Have you tried deploying with shinyapps.io or a similar service first? Check this [post](https://shiny.rstudio.com/deploy/) about hosting and deploying shiny apps, written by RSTudio. Also, if you happen to build a successful docker file and are willing to share it with the community, please do so via this same ticket :)

**Comment by PetricaR** [comment]
@laresbernardo  is it possible to help us with this docker image ?

**Comment by laresbernardo** [comment]
Hi @PetricaR I've no experience at all with Docker, but I'm sure some one in our community might help. You can try our FB group as well! There are [several threads mentioning Docker](https://www.facebook.com/groups/954715125296621/search/?q=docker).

**Comment by laresbernardo** [comment]
Closing this task given it's been inactive for some months. Feel free to re-open.
