### ISSUE TITLE
robyn_refresh fails to plot refreshed results when plot_folder is specified

### ISSUE THREAD

**Issue by openerror** [facebookexperimental/Robyn#506]
## Describe issue
I am trying to refresh a Robyn model persisted to JSON. The (re)training went fine, but R displays an error when trying to save refreshed plots and CSVs to file. Here is the code I ran.

```
data("dt_prophet_holidays")

df <- read_csv("data/DesignHome_ANDROID.csv") %>%
    mutate(INSTALL_DATE = as.Date(INSTALL_DATE, format="%Y-%m-%d"))

RobynRefresh <- robyn_refresh(
    json_file = json_file,
    dt_input = df,
    dt_holidays = dt_prophet_holidays,
    plot_folder = "robyn_results/refresh_attempt",
    refresh_steps = 7,
    refresh_iters = 700, # 1k is an estimation
    refresh_trials = 5
)
```

And here is a screenshot of the error.
![Screen Shot 2022-10-04 at 2 20 50 PM](https://user-images.githubusercontent.com/11012723/193932177-645a6247-c1ff-41c1-a038-0d956972c4f3.png)

Most output is generated and present, except the files prefixed `report_*`. There are no `report_decomposition.png` and `report_actual_fitted.png`; the associated CSVs are absent, too.

_This problem disappears if I do not specify a `plot_folder` when calling `robyn_refresh`._

## Provide reproducible example
Here is the obfuscated CSV containing refreshed data, along with a JSON file of the model I intend to refresh. (Extension .json changed to .txt, so that GitHub would allow the upload.)

[RobynModel-1_433_1.txt](https://github.com/facebookexperimental/Robyn/files/9710732/RobynModel-1_433_1.txt)

[bug_report.csv](https://github.com/facebookexperimental/Robyn/files/9710991/bug_report.csv)

## Environment & Robyn version
Robyn 3.7.2, R 4.2.1

**Comment by laresbernardo** [comment]
Thanks for reporting this issue and special thanks for sharing a reproducible example; without it would have been pretty hard to debug. That said, I've deployed a fix into the master branch that should take care of this case. Can you please update Robyn to the latest dev version, retry, and let me know if it ran OK?

**Comment by openerror** [comment]
It fixed the problem: Robyn is now producing all expected output files. Thanks for the quick fix!
