### ISSUE TITLE
R2 is too low. 

### ISSUE THREAD

**Issue by roh-neenopal** [facebookexperimental/Robyn#509]
## Project Robyn
r2 is too low. The actual vs predicted is not that bad but still, the R2 value is too low. How is R2 being computed?

Date Range 
2020-01-01 to 2021-01-01
Data is at a week level
r2 is -0.48

## Provide reproducible example
![image](https://user-images.githubusercontent.com/90190987/195366313-df99c73a-23a7-486e-b92f-91ecbec6981b.png)

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)

**Comment by roh-neenopal** [comment]
Also, how exactly is R2 being computed?

**Comment by laresbernardo** [comment]
Hi @roh-neenopal You can read the code [here](https://github.com/facebookexperimental/Robyn/blob/main/R/R/auxiliary.R#L6-L17) to see how we calculate R2 (on trained data). It depends on how well your data explains your dependent variable which usually depends on your data granularity, quality, and context variables.

**Comment by Johannes96** [comment]
I have a similar issue. The R2 is too high, always above 1. I'm using monthly data from 01.10.2021 to 01.10.2022, 12 months in total. Maybe the issue lies with the time range, which is in both our cases one year?

**Comment by gufengzhou** [comment]
time range shouldn't be the reason. we would need reproducible data to debug this. if any of you can send us a table with the two columns actual vs predicted, as well as the number of independent variables you're using, we can debug this.

**Comment by Johannes96** [comment]
That would be nice. I can provide you the data. Where can I find the predictions? Are they somewhere in OutputCollect?

**Comment by gufengzhou** [comment]
@Johannes96 Yes, in OutputCollect$xDecompVecCollect, dep_var is the true value, depVarHat is the predicted value. We also need the number of your independent variables as well as if intercept is included or not. 

@michellegrushkometa  FYI

**Comment by Johannes96** [comment]
Here you go:

   dep_var depVarHat
     <int>     <dbl>
 1   32466    31117.
 2   32883    33051.
 3   27267    27871.
 4   28369    28374.
 5   26034    25646.
 6   29026    28614.
 7   23187    24232.
 8   24380    23335.
 9    6833    10251.
10    1423     6390.
11    9939    12965.
12   33038    22999.

Number of independent variables: 11 (including intercept)

**Comment by gufengzhou** [comment]
@roh-neenopal After checking the RSQ function in excel, it appears to return NOT adjusted R2. As described in the commend above, adjusted R squared can become negative when n and p are very close. How many variables do you have in the model? In general, Robyn's optimisation process isn't affected because it uses the error NRMSE and thus is not impacted by the rsq calculation

**Comment by gufengzhou** [comment]
Please reopen if necessary.
