### ISSUE TITLE
[Solved] Error installing "nevergrad" in python: py_install("nevergrad", pip = FALSE)

### ISSUE THREAD

**Issue by alfonsovc15** [facebookexperimental/Robyn#510]
## Describe issue
I was having trouble executing the following line of code:
`py_install("nevergrad", pip = FALSE)`

## Provide reproducible example
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.2.3; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/alfonso/.virtualenvs/r-reticulate/bin/python -m pip install --upgrade pip' command.
Error: Error installing package(s): "'nevergrad'"
<img width="932" alt="Screen Shot 2022-10-14 at 8 36 44" src="https://user-images.githubusercontent.com/17477168/195860525-a1f62221-dc84-4781-906f-b406f0bc7f46.png">

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)

> packageVersion("Robyn")
[1] ‘3.7.2’
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

**SOLUTION:**
@laresbernardo helped me to fix it as follows:
By uninstalling Python from the package and executing the following line of code:
`system("pip3 install --upgrade pip")`
Then the problem could be solved.

**Comment by laresbernardo** [comment]
Thanks a lot for sharing this error + solution @alfonsovc15 

Could you please copy/paste the whole error so users can find this thread more easily when they get the same error?
