### ISSUE TITLE
Budget allocator - Initial spend and optimised spend are the same

### ISSUE THREAD

**Issue by AruunnAnanda** [facebookexperimental/Robyn#511]
I'm using Robyn version 3.7.3. 

I having issues with Robyn budget allocator for the scenario "max_response_expected_spend". My initial and optimised spend share are the same. 

Robyn produced 5 models in the output folder. I ran budget allocator on each one of them and I see that my initial and optimised spend share are the same for 3 out of 5 models. 

Is this a bug?

![Screenshot 2022-10-17 at 08 47 02](https://user-images.githubusercontent.com/107944288/196108137-f77b96bc-1c96-4c58-a253-c03b86fccec4.png)

![Screenshot 2022-10-17 at 08 46 14](https://user-images.githubusercontent.com/107944288/196108158-06df1a2d-71a4-4a14-aa85-abff1b3885c0.png)

<img width="1402" alt="Screenshot 2022-10-17 at 08 34 58" src="https://user-images.githubusercontent.com/107944288/196108183-e1311b6f-19ae-419b-b17b-0089045be4f8.png">

**Comment by gufengzhou** [comment]
This is strange. Could it be that the coefficients are very small/ close to 0 for these models that are not allocating?

**Comment by AruunnAnanda** [comment]
Hi @gufengzhou,

Sure, will update my package and keep you posted. 

Thanks!

**Comment by gufengzhou** [comment]
Hi Arun, does this still occurs? From what I have seen, unchanged allocation is mostly caused by too narrow channel constraints. Make sure you try out wider constraints for the channels. Also FYI we've made the effort in v3.8.2 to reduce output sizes to ease the memory issue. Hope it works better for you now.

**Comment by AruunnAnanda** [comment]
Hi @gufengzhou , please give me 1 more week to test it again. 

I'll keep you updated. Thank you!

**Comment by jamesvrt** [comment]
A similar issue also occurs for me. I'm using Robyn 3.9.0 with very wide channel constraints for optimization.

```R
    scenario = "max_historical_response",
    channel_constr_low = 0.01,
    channel_constr_up = 5, 
```

**Comment by gufengzhou** [comment]
> A similar issue also occurs for me. I'm using Robyn 3.9.0 with very wide channel constraints for optimization.
> 
> ```r
>     scenario = "max_historical_response",
>     channel_constr_low = 0.01,
>     channel_constr_up = 5, 
>     date_min = "2022-10-05", 
>     date_max = "2023-01-04", 
>     optim_algo = "SLSQP_AUGLAG"
> ```
> 
> When I increase the `date_min` -> `date_max` window size from 3 months to 6 months the optimizer works as expected. When I change the the `optim_algo` to "MMA_AUGLAG" it also works as expected.

Interesting case. without the real data, I can't say why it behaves like this. Good to know that MMA_AUGLAG works, too.

**Comment by jamesvrt** [comment]
> Interesting case. without the real data, I can't say why it behaves like this. Good to know that MMA_AUGLAG works, too.

It would take some work to obfuscate the data, unfortunately. `MMA_AUGLAG` results look reasonable enough for my purposes at least.
