### ISSUE TITLE
Error when running robyn_outputs

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#512]
robyn_run converged both NRMSE and RSSD
<img width="531" alt="Screen Shot 2022-10-17 at 9 21 52 AM" src="https://user-images.githubusercontent.com/89505409/196188212-9124a23c-e0b8-4a3c-b188-dbc333b942fe.png">
But when running robyn_outputs getting below error:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/89505409/196188467-bca20c76-e2ea-4b00-b4ab-a74647a61525.png">

**Comment by laresbernardo** [comment]
Hi @virithavanama can you please share a reproducible example to be able to debug this bug? Also, please share your `sessionInfo()` so I can check your R, OS, and Robyn versions. Thanks.

**Comment by virithavanama** [comment]
<img width="996" alt="Screen Shot 2022-10-17 at 10 07 11 AM" src="https://user-images.githubusercontent.com/89505409/196198799-f96369fd-adc9-43ad-a8da-f0b3c8b1bcbe.png">

**Comment by gufengzhou** [comment]
There's a new release v3.8.0 just now. We're not seeing this error.  Can you update your package and retry please

**Comment by firatfrkn** [comment]
I have received this error after the very recent update on output functions. I was able to run Robyn without any errors on the same dataset before the update.
![Screenshot 2022-11-04 161351](https://user-images.githubusercontent.com/96492785/199998432-9fe02a11-2aa3-423b-8784-4b0ce122e50d.png)

**Comment by gufengzhou** [comment]
Hi, I can't reproduce your error. Although I found a small mistake that I forgot to update robyn_outputs's package documentation. I've used both the dummy dataset as well as the anonymised data from you. Both ran successfully with robyn_outputs. Can you please update (including dependencies) and retry?

**Comment by firatfrkn** [comment]
Hello @gufengzhou I have tried and got the same error. I have sent the anonymized data that I am getting error from via email. (The one I have sent you was for another error). Many thanks.

**Comment by gufengzhou** [comment]
thanks for sharing the data. I've just tried it out with the similar `robyn_inputs()` specification as your previous set and got no error. You've modified some functions right? Have you also updated your function with the latest changes?
<img width="950" alt="image" src="https://user-images.githubusercontent.com/14415136/200008996-d0da5f6f-d5c8-43bc-bba5-9a90693b9332.png">

**Comment by firatfrkn** [comment]
Hello! Yes I have updated all the functions. With the new update on the checks, I have started to receive this error. 
![Screenshot 2022-11-04 184516](https://user-images.githubusercontent.com/96492785/200018096-7d2eb2b0-98c6-4197-b344-c869bd5134df.png)

**Comment by gufengzhou** [comment]
looks like you somehow haven't loaded the robyn_response function. make sure you restart the R session / or just try restart RStudio. sometimes it helps...

**Comment by firatfrkn** [comment]
Yes, I figured it out. Right now it is working. Many thanks. The mutate error seems to be solved as well. I will be testing with different datasets.

**Comment by firatfrkn** [comment]
Hi I have noticed a strange situation. Outputmodels run when it is only 1 trial with 500 iterations with the  anonymized data I have sent you @gufengzhou. However, it gives an error with 5 trials 6000 iterations. (I have updated all the functions including yesterday's update. I was able to run before with 5 trials 6000 iterations on this data)
![Screenshot 2022-11-05 201819](https://user-images.githubusercontent.com/96492785/200134031-5b62f340-72bc-4eb8-bb4d-6f2a67f368b0.png)


Here is the error with 5 trials. The same dataset I have sent you.

![Screenshot 2022-11-05 200010](https://user-images.githubusercontent.com/96492785/200134033-e48ea2c8-7763-46e9-b1b6-af8e3c2b0874.png)

**Comment by gufengzhou** [comment]
I just tried 5 trials * 250 iters and didnt see any error. Does this error show up everytime you run more than 1 trial? Can you run `Robyn:::errors_scores(OutputModels$trial1$resultCollect$resultHypParam)` for all trials to see if any of them throws error? I'm suspecting that there might be an NA in decomp.rssd that causes error in `Robyn:::errors_scores`

**Comment by firatfrkn** [comment]
Hi! 5 trials * 250 iters threw an error for me. 

![Screenshot 2022-11-06 140939](https://user-images.githubusercontent.com/96492785/200167332-cdcfde01-f5de-4942-9250-a517b03ec87c.png)

Robyn:::errors_scores
![Screenshot 2022-11-06 141107](https://user-images.githubusercontent.com/96492785/200167342-bea8c4df-7d80-4875-8bfd-14d04dd3763b.png)

**Comment by firatfrkn** [comment]
![Screenshot 2022-11-06 141426](https://user-images.githubusercontent.com/96492785/200167466-3a63f6b8-c34e-4c03-9990-be93dc924332.png)
![Screenshot 2022-11-06 141456](https://user-images.githubusercontent.com/96492785/200167468-555b6a78-916f-4263-91dd-f3a43240b6ec.png)
![Screenshot 2022-11-06 141524](https://user-images.githubusercontent.com/96492785/200167470-37bbd4cb-d5b8-466a-86f6-242380dd448b.png)

**Comment by firatfrkn** [comment]
Hi! @gufengzhou. I have tried with 1 trial  * 6000 iters. Apparently, my error is due to number of trials not the iterations.

**Comment by gufengzhou** [comment]
I can't reproduce your error unfortunately. I notice that all your Robyn functions are in global env, probably because you're doing changes locally, right? I'm not sure if this would cause issue, because there might be same variables names in both local and global env. When you're "unpacking" the package, they might get mixed up. 

You're doing the changes because of Windows, right? Actually our package is compatible to Windows. I just supported someone to install it on a windows machine and it worked. Would you maybe try the package as is again?

**Comment by firatfrkn** [comment]
Hi @gufengzhou! Thanks for the feedback. I getting closer to the cause of the problem. The anonymized data that I have sent you includes 2 categorical vars. Campaign1 and Campaign2 which I am passing to the input function as   
context_vars = c("Campaign1", "Campaign2"),
 ,factor_vars = c("Campaign1", "Campaign2")

I have just run without those categorical vars, 5 trials  * 250 iters and it successfully generated the output. However, when I include those categorical data into the model the problem consists which is being able to run, but not generating outputs with more than 1 trials. Did you or your colleague run the model with those: 
context_vars = c("Campaign1", "Campaign2"),
 ,factor_vars = c("Campaign1", "Campaign2")  
?,

P.S. I was able to run and to generate the outputs with more than 1 trials and including those categorical vars before the last weeks update. It may help you somehow. Many thanks

**Comment by gufengzhou** [comment]
Thank you very much for reporting this. I could reproduce the error now. I was already suspecting the `Inf` in your error_scores, which is really the cause. Because of the` .min_max_norm()` within the `error_scores` function, the `Inf` will be removed and hence the error of different vector lengths in a dataframe. I've now just replaced the Inf with the finite max. Now it works on my side. Please update and let me know.

It's very strange that this bug occurs because we didn't really touch this part in last update. Must be changes caused by dependencies. Sorry for the bugs tho and thanks for your resilience.

**Comment by firatfrkn** [comment]
Now, it works on my side as well. Thanks for your time and effort.
