### ISSUE TITLE
 Error: package or namespace load failed for ‘Robyn’:  object ‘h2o.import_mojo’ is not exported by 'namespace:h2o'

### ISSUE THREAD

**Issue by andrewvasylyshyn** [facebookexperimental/Robyn#514]
## Project Robyn

[Austin4You](https://www.youtube.com/channel/UCDLyu_GVNO5PQCwmRnULFiA)
I am on mac air with apple silicone. I also have Anacodas set up on my laptop.

I installed everything per instructions, everything was working fine. After I removed all objects and restarted the session and wanted to load Robyn library by using the library(Robyn) command, I started getting this error:

Error: package or namespace load failed for ‘Robyn’:
 object ‘h2o.import_mojo’ is not exported by 'namespace:h2o'

**Comment by laresbernardo** [comment]
Hi @andrewvasylyshyn 
Taken from [here](http://h2o-release.s3.amazonaws.com/h2o/master/1735/docs-website/Ruser/Rinstall.html#download-r-package-directly-from-h2o-ai), can you please try manually installing h2o with the following:
```
# The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }
# Next, we download, install and initialize the H2O package for R.
install.packages("h2o", repos=(c("http://s3.amazonaws.com/h2o-release/h2o/master/1497/R", getOption("repos"))))
```
And then retry loading Robyn in a fresh new session.

**Comment by andrewvasylyshyn** [comment]
Thanks @laresbernardo , I just tried it and for some reason it failed.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/75985108/197083632-e2a81576-1087-44df-9ed3-59fe9d2031da.png">

Then I tried to download from CRANm, and it failed again.
> install.packages("h2o")
> library(h2o)
> localH2O = h2o.init()
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/75985108/197083741-6d54a351-2f99-4109-9d34-1a5e5257eb25.png">

**Comment by laresbernardo** [comment]
Ok it seems you might have a slow or unstable internet connection. Try extending the timeout to 500 seconds with `options(timeout = 500)` and retrying.

**Comment by andrewvasylyshyn** [comment]
@laresbernardo it looks like it actually worked!!!
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/75985108/197258795-1d9c6724-e0cf-4c63-af2b-73ec89c74fd9.png">

**Comment by laresbernardo** [comment]
There you go!! Glad it worked :)
