### ISSUE TITLE
calibration_DT no longer supports daily liftAbs data

### ISSUE THREAD

**Issue by joangcc** [facebookexperimental/Robyn#515]
## Describe issue
Previous versions of Robyn accepted liftStartDate = liftEndDate. However, last version requires liftStartDate < liftEndDate.

Until now, we were using daily liftAbs data, but given this recently added check, Robyn doesn't run. How can we continue using daily data within the current requirements?

Also, what's the reason behind adding those checks for this particular case?

Thanks!
## Robyn version
Robyn 3.7.3

**Comment by joangcc** [comment]
Where to find this check: lines 514 to 523 of checks.R:
`     if (temp$liftStartDate >= temp$liftEndDate) {
        stop(sprintf(
          paste(
            "Your calibration's date range for %s between %s and %s should respect liftStartDate < liftEndDate.",
            "Please, correct this experiment from 'calibration_input'."
          ),
          temp$channel, temp$liftStartDate, temp$liftEndDate
        ))
      }
    }`

**Comment by laresbernardo** [comment]
Hi @joangcc. We did add this check a while ago but you're right, I'll change that check to let users set liftStartDate >= liftEndDate. Actually you replied before I hit enter to this haha so expect this change in the next couple of minutes in our latest dev version

**Comment by laresbernardo** [comment]
There you go. Please, update to the latest dev version and you'll be good to go. Thanks for the feedback. Feel free to close this ticket once you test and use it.

**Comment by joangcc** [comment]
Thanks for fixing this so fast. It works now!
