### ISSUE TITLE
robyn_outputs() with error 'Can't combine `..1$ds` <date> and `..2$ds` <IDate>'

### ISSUE THREAD

**Issue by DpfStat** [facebookexperimental/Robyn#519]
## Describe issue
when I ran robyn_outputs() in the demo file, the error showed up:
<img width="667" alt="Screenshot 2022-10-27 at 11 08 16 PM" src="https://user-images.githubusercontent.com/57167189/198516836-becb0b71-e53c-4f9c-9b3d-c0952a2f93c8.png">
After trace back it seems like the problem happened here:

<img width="865" alt="Screenshot 2022-10-27 at 11 09 03 PM" src="https://user-images.githubusercontent.com/57167189/198517189-5f5cac3c-f0c0-4882-b917-a85a748e2632.png">
<img width="707" alt="Screenshot 2022-10-27 at 11 08 37 PM" src="https://user-images.githubusercontent.com/57167189/198517208-009d231c-6800-4444-9cbb-f2dd575d2a85.png">

## Provide reproducible example
It happened when I ran the code in the demo file. This worked fine on another computer, not sure it is version problem of any package or Mac aarch64 issue.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`: 3.7.2
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`): R version 4.1.2 (2021-11-01)

**Comment by gufengzhou** [comment]
There's a new release v3.8.0 just now. This issue should be fixed. Can you update your package and retry please

**Comment by DpfStat** [comment]
After update to the Robyn 3.8.0 with remotes::install_github("facebookexperimental/Robyn/R"), the new problem showed up:
<img width="679" alt="Screenshot 2022-10-28 at 4 08 34 PM" src="https://user-images.githubusercontent.com/57167189/198749146-38774b3b-b5ed-446e-9db3-ad54debf78b6.png">
I have check the previous issue and found that holiday variable is 0:
<img width="1093" alt="Screenshot 2022-10-28 at 4 00 22 PM" src="https://user-images.githubusercontent.com/57167189/198749184-ffe039eb-8588-4f63-b0cf-9f1d496fa74c.png">
Since I am using the demo file and demo data set, I reran Robyn 3.7.2, the result shows below:
<img width="1089" alt="Screenshot 2022-10-28 at 4 05 44 PM" src="https://user-images.githubusercontent.com/57167189/198749259-d0d38806-840f-4583-938d-0cd305b71458.png">
As you can see, the time series analysis showed different result for 'trend, seaonality and holiday'.

**Comment by gufengzhou** [comment]
I've just pushed a fix. Should work now. Please confirm, thanks!

**Comment by DpfStat** [comment]
The problem all solved after install new version. Thank you!

**Comment by gufengzhou** [comment]
fixed in f6446e4f4b4e4038b2ffe2ffa47f95bb3c00a0e9
