### ISSUE TITLE
Hyperparameters not allowing metrics other than spend

### ISSUE THREAD

**Issue by jaspertambini** [facebookexperimental/Robyn#522]
## Describe issue
Using either my own data or the given example Facebook data, this error now appears when I run InputCollect. The only way I avoid it is replacing Cost in Paid_Media_Spends with Impressions or Clicks. Could someone shed some light on the issue?
Thanks

## Provide reproducible example
![image](https://user-images.githubusercontent.com/114992329/199245905-5f1f8337-cb21-45ec-95ef-a41d2bbd27ad.png)

## Environment & Robyn version
- Robyn version 3.8.1 
- "R version 4.2.1 (2022-06-23 ucrt)"

**Comment by gufengzhou** [comment]
Please check this thread that's a similar question https://www.facebook.com/groups/robynmmm/posts/1234713643963433/

**Comment by jaspertambini** [comment]
Thanks!
