### ISSUE TITLE
 Error: vector memory exhausted (limit reached?) when Running Pareto calculations for 10000 models on auto fronts...

### ISSUE THREAD

**Issue by andrewvasylyshyn** [facebookexperimental/Robyn#523]
## Environment & Robyn version
 Robyn version:  ‘3.8.1’
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5.1

Issue
I have a daily data set that I ran the model on. after 5 trials, I discovered there were no data in the folder where it was supposed to be. I also get this error Error: vector memory exhausted (limit reached?)`

Here's some code:

`Input data has 665 days in total: 2021-01-03 to 2022-10-29
Initial model is built on rolling window of 665 day: 2021-01-03 to 2022-10-29
Using weibull_pdf adstocking with 49 hyperparameters (49 to iterate + 0 fixed) on 7 cores
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
  |===============================================================================| 100%
  Finished in 41.42 mins
  Running trial 2 of 5
  |===============================================================================| 100%
  Finished in 18.83 mins
  Running trial 3 of 5
  |===============================================================================| 100%
  Finished in 23.62 mins
  Running trial 4 of 5
  |===============================================================================| 100%
  Finished in 30.26 mins
  Running trial 5 of 5
  |===============================================================================| 100%
  Finished in 24.76 mins
- DECOMP.RSSD converged: sd@qt.20 0.076 <= 0.092 & |med@qt.20| 0.13 <= 0.15
- NRMSE converged: sd@qt.20 0.00045 <= 0.0021 & |med@qt.20| 0.066 <= 0.07
Total run time: 140.22 mins
> print(OutputModels)
Total trials: 5
Iterations per trial: 2000 (2002 real)
Runtime (minutes): 140.22
Cores: 7

Updated Hyper-parameters:
  Email_Blog_Camp_alphas: [0.5, 3]
  Email_Blog_Camp_gammas: [0.3, 1]
  Email_Blog_Camp_scales: [0, 0.1]
  Email_Blog_Camp_shapes: [1e-04, 10]
  Email_Marketing_Camp_alphas: [0.5, 3]
  Email_Marketing_Camp_gammas: [0.3, 1]
  Email_Marketing_Camp_scales: [0, 0.1]
  Email_Marketing_Camp_shapes: [1e-04, 10]
  FB_Ret_alphas: [0.5, 3]
  FB_Ret_gammas: [0.3, 1]
  FB_Ret_scales: [0, 0.1]
  FB_Ret_shapes: [1e-04, 10]
  FB_TOF_alphas: [0.5, 3]
  FB_TOF_gammas: [0.3, 1]
  FB_TOF_scales: [0, 0.1]
  FB_TOF_shapes: [1e-04, 10]
  G_Display_Ret_alphas: [0.5, 3]
  G_Display_Ret_gammas: [0.3, 1]
  G_Display_Ret_scales: [0, 0.1]
  G_Display_Ret_shapes: [1e-04, 10]
  G_Pmax_Cold_0_78_alphas: [0.5, 3]
  G_Pmax_Cold_0_78_gammas: [0.3, 1]
  G_Pmax_Cold_0_78_scales: [0, 0.1]
  G_Pmax_Cold_0_78_shapes: [1e-04, 10]
  G_Pmax_hot_0_12_alphas: [0.5, 3]
  G_Pmax_hot_0_12_gammas: [0.3, 1]
  G_Pmax_hot_0_12_scales: [0, 0.1]
  G_Pmax_hot_0_12_shapes: [1e-04, 10]
  G_Search_Brand_alphas: [0.5, 3]
  G_Search_Brand_gammas: [0.3, 1]
  G_Search_Brand_scales: [0, 0.1]
  G_Search_Brand_shapes: [1e-04, 10]
  G_Search_TOF_alphas: [0.5, 3]
  G_Search_TOF_gammas: [0.3, 1]
  G_Search_TOF_scales: [0, 0.1]
  G_Search_TOF_shapes: [1e-04, 10]
  G_Shopping_alphas: [0.5, 3]
  G_Shopping_gammas: [0.3, 1]
  G_Shopping_scales: [0, 0.1]
  G_Shopping_shapes: [1e-04, 10]
  YT_Ret_alphas: [0.5, 3]
  YT_Ret_gammas: [0.3, 1]
  YT_Ret_scales: [0, 0.1]
  YT_Ret_shapes: [1e-04, 10]
  YT_TOF_alphas: [0.5, 3]
  YT_TOF_gammas: [0.3, 1]
  YT_TOF_scales: [0, 0.1]
  YT_TOF_shapes: [1e-04, 10]
  lambda: [0, 1]

Nevergrad Algo: TwoPointsDE
Intercept sign: non_negative
Penalty factor: FALSE
Refresh: FALSE

Convergence on last quantile (iters 1902:2002):
  DECOMP.RSSD converged: sd@qt.20 0.076 <= 0.092 & |med@qt.20| 0.13 <= 0.15
  NRMSE converged: sd@qt.20 0.00045 <= 0.0021 & |med@qt.20| 0.066 <= 0.07

> 
> ## Check MOO (multi-objective optimization) convergence plots
> OutputModels$convergence$moo_distrb_plot
Picking joint bandwidth of 0.0178
Picking joint bandwidth of 0.000281
> OutputModels$convergence$moo_cloud_plot
> # check convergence rules ?robyn_converge
> 
> ## Calculate Pareto optimality, cluster and export results and plots. See ?robyn_outputs
> OutputCollect <- robyn_outputs(
+   InputCollect, OutputModels,
+   # pareto_fronts = "auto",
+   # calibration_constraint = 0.1, # range c(0.01, 0.1) & default at 0.1
+   csv_out = "pareto", # "pareto", "all", or NULL (for none)
+   clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
+   plot_pareto = TRUE, # Set to FALSE to deactivate plotting and saving model one-pagers
+   plot_folder = robyn_object, # path for plots export
+   export = TRUE # this will create files locally
+ )
>>> Running Pareto calculations for 10000 models on auto fronts...
Error: vector memory exhausted (limit reached?)`

<img width="612" alt="image" src="https://user-images.githubusercontent.com/75985108/199364599-4c1660e7-4724-4175-a521-0b816dfd6d2e.png">

**Comment by gufengzhou** [comment]
Have you checked this? https://stackoverflow.com/questions/51295402/r-on-macos-error-vector-memory-exhausted-limit-reached

**Comment by andrewvasylyshyn** [comment]
I restarted the R and re-ran it with 2 trials and it worked.

**Comment by laresbernardo** [comment]
Hi @andrewvasylyshyn I've just updated Robyn to version [3.8.2](https://github.com/facebookexperimental/Robyn/releases/tag/v3.8.2) and we've changed how and when we calculate decomposition values for carryover and immediate effects to be memory friendly. Can you please update, refresh, retry, and let us know how it goes with as many trials as you wish to run with? Thanks!
