### ISSUE TITLE
Is it possible to manually add additional modes of seasonaltiy?

### ISSUE THREAD

**Issue by openerror** [facebookexperimental/Robyn#525]
## Describe issue
Prophet has the capability to model custom seasonalities; for example monthly is not available by default but it can be [added](http://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#specifying-custom-seasonalities) using the R function `add_seasonality`.

I notice that `robyn_inputs` is supposed to take additional arguments that can be passed to "prophet functions". Is it possible to trigger `add_seasonality` that way? 

If not, this seems common enough a use case to warrant a feature request.

## Environment & Robyn version
- Robyn version: 3.7.2
- R version (4.2.1)

**Comment by gufengzhou** [comment]
Thanks for reporting this. It can't be simply added as a custom unnamed argument, because it's not an argument but an extra function. We'll consider adding this.

**Comment by laresbernardo** [comment]
Added via PR #545 and landed in main repo now #565. Thanks for the feedback @openerror. Feel free to test and close this thread if applies.
