### ISSUE TITLE
InputCollect error with Robyn version upgrade- 'unexpected symbol'

### ISSUE THREAD

**Issue by sr2naik** [facebookexperimental/Robyn#526]
## Project Robyn

Upgraded Robyn version to 3.7.2 and am running into the following error with my own data as well as when trying the demo:
> InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)
>> Running feature engineering...
Error in `select()`:
! <text>:1:5: unexpected symbol
1: Use of
        ^
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
**<simpleError in select(dt_transform, .data$ds, .data$dep_var): <text>:1:5: unexpected symbol**
1: Use of
        ^>

**To note: We have tried to run the same code on 3 other devices and are facing no issues.**

## Provide reproducible example
Running the exact demo script from https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R 

## Environment & Robyn version
- Running Robyn version 3.7.2
- R version 4.2.1 (2022-06-23 ucrt)

**Comment by gufengzhou** [comment]
Hi, We haven't seen this error so far. please ensure to update all dependencies firstly. I assume you're using the CRAN version of Robyn. If issue still exist, please also try the dev version by `remotes::install_github("facebookexperimental/Robyn/R")`

**Comment by sr2naik** [comment]
This error was resolved after I manually installed each CRAN package that was needed. The automatic install was not installing correctly with the update.

**Comment by gufengzhou** [comment]
@laresbernardo any idea if the auto-install doesn't update the dependencies? If not we can close this one

**Comment by laresbernardo** [comment]
Haven't heard this one. Usually it's a timeout issue that can be fixed with `options(timeout = 500)` given it takes some time to download and the default timeout might be a bit short. Also, user can force dependencies to install with the argument `dependencies = TRUE` for what it's worth.

**Comment by laresbernardo** [comment]
Closing this task given it's been inactive for some months. Feel free to re-open.
