### ISSUE TITLE
Error while running robyn_mmm(); providing PARTIAL results

### ISSUE THREAD

**Issue by ksorger** [facebookexperimental/Robyn#527]
## Describe issue
Am getting an error when executing the model using the demo_data:

1. taken hyperparam list from demo file
2. running InputCollect function: InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)

<img width="463" alt="Screenshot 2022-11-04 at 11 25 26" src="https://user-images.githubusercontent.com/80044633/199950744-772d809d-432d-4872-90b8-d5b2a0894a92.png">

3. Running Robyn:

Getting the following issue:

<img width="955" alt="Screenshot 2022-11-04 at 11 26 38" src="https://user-images.githubusercontent.com/80044633/199951003-302dd3e9-d5d6-4916-bde2-89eb2e33720d.png">

## Environment & Robyn version
packageVersion("Robyn"): 3.8.1
- R version - see attached
<img width="812" alt="Screenshot 2022-11-04 at 11 18 54" src="https://user-images.githubusercontent.com/80044633/199950266-5dcbca24-2880-4c38-9d8f-687297a53a24.png">

**Comment by gufengzhou** [comment]
This should be already fixed. See #520 and #524. Please update and try.

**Comment by ksorger** [comment]
getting.a new error now:

<img width="669" alt="Screenshot 2022-11-04 at 15 34 35" src="https://user-images.githubusercontent.com/80044633/200001112-dbf99d90-29b3-4017-87ae-97b1a8cd790d.png">

**Comment by gufengzhou** [comment]
Hi, would you please update to latest including dependencies, restart R and retry? 

This error with "lower" in nevergrad was very old. strange that you're getting it now. I can't reproduce this currently

**Comment by ksorger** [comment]
Hi, this worked. Thanks!
