### ISSUE TITLE
Robyn Learn App not working

### ISSUE THREAD

**Issue by jaspertambini** [facebookexperimental/Robyn#532]
## Describe issue
Hi, 

Whenever I add my own data to the app, I click "Finalize Variable Assignment" and get the following error with nothing loading:

![image](https://user-images.githubusercontent.com/114992329/201302941-66672469-14ef-4d63-af12-4c851497e6f4.png)

Could someone please assist? The data is all in correct format as far as I am aware.

**Comment by laresbernardo** [comment]
Hi @jaspertambini I've just deployed a fix to this issue. Can you please update RobynLearn and retry? Thanks.

**Comment by jaspertambini** [comment]
hey @laresbernardo, thanks for the quick response, it now seems to have an issue with the package and version of R (tried 4.05, 4.1.2, 4.2.2) is there a different one I should be using?

**Comment by laresbernardo** [comment]
So did you update the package with `remotes::install_github("facebookexperimental/Robyn/app")`, restarted RStudio and tried loading it with `library(RobynLearn)` and get that error? I think you're trying to update CRAN version (and we don't have RobynLearn in CRAN yet).

**Comment by jaspertambini** [comment]
ah yes sorry my mistake, although still seem to be getting the first error again

**Comment by laresbernardo** [comment]
Can you share you anonymized data so I can replicate this case and help be debug?

**Comment by jaspertambini** [comment]
if it helps I am on R 4.2.2 and Robyn 3.8.1

**Comment by jaspertambini** [comment]
[test_mmm.csv](https://github.com/facebookexperimental/Robyn/files/9992177/test_mmm.csv)

**Comment by jaspertambini** [comment]
sure, here's my example

**Comment by laresbernardo** [comment]
Hi @jaspertambini I was able to replicate your issue. Can you please update RobynLearn and retry?

**Comment by jaspertambini** [comment]
Nice one thanks, all working now :)

**Comment by jaspertambini** [comment]
Sorry was a little hasty to close, have a few errors following this so keeping it under the same issue. Now facing a problem with my holidays when computing 
![image](https://user-images.githubusercontent.com/114992329/201641797-c4e9b436-74f4-4154-8eff-2837c1d27548.png)

**Comment by jaspertambini** [comment]
[dt_prophet_holidays.csv](https://github.com/facebookexperimental/Robyn/files/10002207/dt_prophet_holidays.csv)

**Comment by jaspertambini** [comment]
Also is it possible to include events when running the explanatory data analysis? Throws an error when I include them but would be very useful as our data is very heteroskedastic due to the high effect of these events

**Comment by jaspertambini** [comment]
Hey, just wondered if there was any luck with the Holiday file issue?

Really keen to use the app as looks so useful for testing purposes!

**Comment by laresbernardo** [comment]
I've just deployed version 1.0.1. Can you please update and check if this issue persists? Thanks

**Comment by jaspertambini** [comment]
Hey, tried using the new version but error seems to persist. Using the same dataset as before.

**Comment by laresbernardo** [comment]
Closing this task given it's been inactive for some months. Feel free to re-open.
