### ISSUE TITLE
Error: C stack usage

### ISSUE THREAD

**Issue by freudianfaults** [facebookexperimental/Robyn#541]
## Describe issue
Error: C stack usage  7954488 is too close to the limit

## Provide reproducible example
I am running into a C Stack usage issue after running the commands below:

```
library(Robyn)

packageVersion("Robyn")

## Force multicore when using RStudio
# Sys.setenv(R_FUTURE_FORK_ENABLE = "true")
# options(future.fork.enable = TRUE)

################################################################
#### Step 1: Load data
data("dt_prophet_holidays")


# Directory where you want to export results to (will create new folders)
robyn_object <- "~/Desktop"

InputCollect <- robyn_inputs(
  dt_input = df,
  dt_holidays = dt_prophet_holidays,
  date_var = "date", # date format must be "2020-01-01"
  dep_var = "revenue", # there should be only one dependent variable
  dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)
  prophet_vars = c("trend", "season", "holiday"), # "trend","season", "weekday" & "holiday"
  prophet_country = "DE", # input one country. dt_prophet_holidays includes 59 countries by default
  paid_media_spends = c("fb_cost", "ppc_cost",	"gmp_cost",'pint_cost','teads_cost','ms_cost'), # mandatory input
  paid_media_vars = c("fb_clicks",'ppc_cost','gmp_impressions','pint_cost','tead_clicks','ms_clicks'), # mandatory.
  # paid_media_vars must have same order as paid_media_spends. Use media exposure metrics like
  # impressions, GRP etc. If not applicable, use spend instead.
  # factor_vars = c("events"), # force variables in context_vars or organic_vars to be categorical
  window_start = "2019-01-01",
  window_end = "2022-10-03",
  adstock = "geometric" # geometric, weibull_cdf or weibull_pdf.
)
```

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: 3.7.2
- R version (Please, check and share: 4.1.2

**Comment by Amyhaoming** [comment]
Hi @freudianfaults, thanks for trying Robyn out! 

It seems `InputCollect <- robyn_inputs(dt_input = df,` has no value assigned to "df", so it's calling density function of F distribution: df(x, df1, df2, ncp, log = FALSE) (https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Fdist.html) and caused the error. 
Please try importing input data and assign value there, e.g. a quick fix using demo data is:
> data("dt_simulated_weekly") # load demo data, or change to your own
> df <- dt_simulated_weekly  # assign value to "df"
> InputCollect <- robyn_inputs(
  dt_input = df,
  dt_holidays = dt_prophet_holidays,
.....

Or simply 
> data("dt_simulated_weekly")
> InputCollect <- robyn_inputs(
  dt_input = dt_simulated_weekly,
  dt_holidays = dt_prophet_holidays,
.....

Let me know whether it helps.

Thanks,
Amy

**Comment by Deepti0326** [comment]
Even I am facing the same issue, I am using my own dataset. I tried setting the maximum limit for the stack and still faced the same issue
![image](https://github.com/user-attachments/assets/f49237b3-bf5d-46ce-a6dd-0bfbcd90f146)

**Comment by gufengzhou** [comment]
have you checked this? https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit
