### ISSUE TITLE
Adding a penalty factor during initial model build will not allow for a model refresh

### ISSUE THREAD

**Issue by jsabastian** [facebookexperimental/Robyn#543]
## Describe issue
Setting the experimental parameter 'add_penalty_factor = TRUE' during the initial model build will not allow the 'check_hyper_fixed()' function to pass, resulting in the following error:

```
Error in check_hyper_fixed(InputCollect, dt_hyper_fixed, add_penalty_factor) :
Input 'dt_hyper_fixed' is invalid. Please provide 'OutputCollect$resultHypParam' result from previous runs or 'pareto_hyperparameters.csv' data with desired model ID
```

## Robyn Open Source MMM Users Post
[Link](https://www.facebook.com/groups/robynmmm/posts/1325203481581115/?comment_id=1325741678193962&reply_comment_id=1325852241516239&notif_id=1669048098450824&notif_t=group_comment_mention)

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn 3.8.1
- R version 4.2.2

**Comment by laresbernardo** [comment]
Correction on description to be able to replicate this bug: initial model runs OK, but when refreshing with `robyn_refresh()` user gets posted error.

**Comment by laresbernardo** [comment]
Ok, I've just pushed a fix. Given it's an experimental feature, it's expected to suffer some changes such as these: now the names of the hyperparameters for penalization ends (not starts anymore) with "_penalty" to keep the same format as the other hyperparameters (and show up in the prints nicely like attached image). 

<img width="482" alt="Screen Shot 2022-11-21 at 7 09 24 PM" src="https://user-images.githubusercontent.com/25909073/203183176-c785ad1d-28b4-41dc-84a0-0f953b5fb856.png">

If you can please update to latest dev version, recreate your original model, export JSON file and run `robyn_refresh()` it should run smoothly. Please, let me know if that is or isn't the case so we can FUP or close this bug. Thanks @jsabastian

**Comment by jsabastian** [comment]
@laresbernardo Rebuild of the model using the penalty parameter refreshed correctly. Thanks for the fix! Also, I like the pareto front progress bar!

**Comment by laresbernardo** [comment]
Thanks, glad you found it useful. And thanks for checking back, I'll close this thread but feel free to reopen it if you get any further issues or comments.
