### ISSUE TITLE
Can't install new version Robyn 3.8.0

### ISSUE THREAD

**Issue by caarolinagil** [facebookexperimental/Robyn#544]
## Describe issue
I've tried to upgrade package Robyn (version 3.8.0) but I can't because in CRAN don't show it.
I have problems in Budget Allocator because both initial and optimized budget allocation are same and I saw that it could be a bug in the late version.

remotes::install_github('facebookexperimental/Robyn/R@allocation_range') doesn't work for me.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: 3.7.2
- R version: 4.2.1

**Comment by laresbernardo** [comment]
Hi @caarolinagil You can updated to latest dev version using `remotes::install_github('facebookexperimental/Robyn/R') as you mentioned. And we will update CRAN version when 3.8.X is stable enough.

Can you share your anonymized results? Can you share a reproducible example to help us debug in case it's a bug?

On the other hand, have you checked this thread (#511)

**Comment by ogencoglu** [comment]
A side question: what is the logic behind version tags? 3.8.0 jumped to 3.8.2. Where is 3.8.1? Same happened with 3.6.0 to 3.6.2.

**Comment by laresbernardo** [comment]
Hi! They logic behind those skipped versions is that we launched big new features (x.x.0 versions) and then we start fixing some un-squashed bugs with version (x.x.1) and when we consider it's stable enough (no bugs reported in a couple weeks or so) we close x.x.2 version.

**Comment by caarolinagil** [comment]
Hi @laresbernardo, thanks for your comments!

Reviewing my code, I've seen that, in the situation "max_response_expected_spend", I use more than one spends and days combinations. So, I made a loop in the code to show the different combinations in the output and this is why the last iteration reflects the same values.

So far so good!

**Comment by gufengzhou** [comment]
Please reopen if necessary.
