### ISSUE TITLE
Model outputs are not able to export into the robyn_object directory after update to 3.8.2

### ISSUE THREAD

**Issue by jsabastian** [facebookexperimental/Robyn#546]
## Describe issue
Robyn is not able to plot the model outputs into the robyn_object directory. The following error is thrown:

`>>> Running Pareto calculations for 6000 models on auto fronts...
>> Automatically selected 2 Pareto-fronts to contain at least 100 pareto-optimal models (144)
>> Pareto-Front: 1 [65 models]
 00:00:08 [===========================================================] 100% | 65                                        
>> Pareto-Front: 2 [79 models]
 00:00:10 [===========================================================] 100% | 79                                        
>>> Calculating clusters for model selection using Pareto fronts...
>> Auto selected k = 4 (clusters) based on minimum WSS variance of 5%
>>> Collecting 144 pareto-optimum results into: /Users/jss/Desktop/Ollies/Ollies_Robyn/PROS_v_RMK/Robyn_202211232105_init/
>> Exporting general plots into directory...
>> Exporting pareto results as CSVs into directory...
>>> Exporting pareto one-pagers into directory...
>> Generating only cluster results one-pagers (4)...
>> Plotting 4 selected models on 1 core (MacOS fallback)...
  |                                                                                                           |   0%Failed exporting results, but returned model results anyways:
 Error in {: task 1 failed - "Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error in `.data$channels`:
! Column `channels` not found in `.data`."`

## Provide reproducible example
The error was encountered with real time data. A run with out-of-the-box demo.R confirms the error.

## Environment & Robyn version
- Robyn 3.8.2
- R version 4.2.2

**Comment by gufengzhou** [comment]
I've just pushed a fix. could you please update and test it again?
