### ISSUE TITLE
Memory Issue when running robyn_outputs

### ISSUE THREAD

**Issue by Sorkanius** [facebookexperimental/Robyn#547]
## Describe issue
Once the models are trained and you run `robyn_outputs`, if the option `csv_out` is in `'pareto'` or `NULL` it takes up a lot of memory making the R session to close.

I have to turn that option to `NULL` and the usen the `robyn_onepagers` to get the reports.

## Provide reproducible example
My dataset has ~600 observations with around 5 media variables. Cannot provide the data.

## Environment & Robyn version
The machine I am using has ~200GB of RAM.
- Robyn version: `3.8.1`
- R version: `4.2.2`

**Comment by gufengzhou** [comment]
Hi, we've just updated to 3.8.2 with substantial reduction of object size. can you please update, restart R and check?

**Comment by Sorkanius** [comment]
Well, that was fast :')

I will check and come back. Thanks!!

**Comment by matteocaserio** [comment]
Same issue here, outputting the onepagers on version 3.8.2 saturates RAM and swap on my laptop (16GB+4GB) and therefore crashes the R session.

I have monitored RAM usage through `htop` and it's indeed the `Plotting X selected models on Y cores...` step that makes it go through the roof.

I'm using a dataset of ~700 daily observations and ~15 variables (I cannot provide the dataset), on R version 4.2.2 and Ubuntu 18.04.

No such issue on 3.7.2.

**Comment by laresbernardo** [comment]
Have you tried with latest dev version (3.9.0)? Can you please let me know if that's been fixed? I can't seem to replicate the issue on my end given I don't have access to Ubuntu 18.04. How many models are you trying to export? Does running `robyn_onepagers()` manually for a single model have the same outcome? What about setting `export = FALSE`? We've recently reduced the size of the outputs with latest versions.

**Comment by matteocaserio** [comment]
> Have you tried with latest dev version (3.9.0)? Can you please let me know if that's been fixed? I can't seem to replicate the issue on my end given I don't have access to Ubuntu 18.04. How many models are you trying to export? Does running `robyn_onepagers()` manually for a single model have the same outcome? What about setting `export = FALSE`? We've recently reduced the size of the outputs with latest versions.

Hi, it seems to be independent of how many models must be exported (even selecting a single solID does the same effect); I've tried running `robyn_onepagers()` on its own and it's the same.
Setting `export = F` circumvents the problem but of course onepagers don't get saved.
I'll try with 3.9.0, thanks!

**Comment by laresbernardo** [comment]
Ok! Makes sense and it's good to know.
When you update to latest dev version, can you also try setting `OutputModels$cores <- 1` before exporting to avoid the usage of multiple cores?

**Comment by matteocaserio** [comment]
> Ok! Makes sense and it's good to know. When you update to latest dev version, can you also try setting `OutputModels$cores <- 1` before exporting to avoid the usage of multiple cores?

I have updated to 3.9.0 but encountered another problem: when setting hyperparameter ranges, I get the error:

`Error in check_hyperparameters(InputCollect$hyperparameters, InputCollect$adstock,  : 
  16 hyperparameter values are required, and 15 were provided. 
 Use hyper_names() function to help you with the correct hyperparameters names.`

I have verified that hyper_names() output is identical to the names of the hyperparameter list I provide, which is indeed of length 16 (I haven't changed anything in the code).
Should I open a separate issue for this?

**Comment by laresbernardo** [comment]
Yes, that's because we have a new `train_size` hyperparameter for time-series validation. Please add it as well: `train_size = c(0.5, 0.8)` should be OK. I'll add a more friendly and useful error message now, no need for a new ticket.

**Comment by matteocaserio** [comment]
Ok, understood. I'm going on vacation soon and will give it another try after the holidays - maybe in the meantime other users will see this issue and verify if 3.9.0 solves the problem.
Thanks for the support!

**Comment by jamesvrt** [comment]
The problem still persists with 3.9.0. When running `robyn_outputs` with `plot_pareto = TRUE` my 64GB of RAM are exhausted and the R session subsequently crashes.

**Comment by nikitajes** [comment]
@jamesvrt did you manage to figure out if setting `OutputModels$cores <- 1` only affects the convergence plots, or it actually affects all of the results and clusters? I am running into the memory issues even with 128GB of RAM and it seems that to get any outputs I must select `OutputModels$cores <- 1`. However, I am not able to tell if those results are based only on the subset of iterations...

**Comment by jamesvrt** [comment]
@nikitajes just plots, I'm pretty sure. Results look good otherwise.

**Comment by laresbernardo** [comment]
Closing this task given it's been inactive for some months. Feel free to re-open.
