### ISSUE TITLE
About Returns and CSV Interpretation

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#549]
I want to compare the average revenue in my dataset to the optimal revenue after budget allocation, but when I add up the revenue of the individual channels from the optimizer one-pager, I end up with revenue that's about 5x less than the original revenue, even though the one-pager mentions an increase of 22%. Is there a way for me to find the number I'm looking for?

After some digging in the CSV that was generated by the optimizer, I found that 'histSpendTotal' corresponds to the total spend in the dataset, but that 'initResponseUnitTotal' does not correspond to the total revenue in the dataset. There must be some transformation going on here, but I can't find any documentation that helps me to interpret these column names, or any of the CSV's generated by Robyn for that matter. It's not a super technical question, but I would really appreciate some help.

- Bart

**Comment by gufengzhou** [comment]
the allocator only deals with paid media channels. the increase is also related to media contribution. you can find the schema of the csv outputs [here](https://github.com/facebookexperimental/Robyn/blob/main/demo/schema.R)
