### ISSUE TITLE
About Validation...

### ISSUE THREAD

**Issue by Sorkanius** [facebookexperimental/Robyn#550]
## This is not a but its a feature request

So far the library has proved very useful, however I do find a bit opaque all related to validation.

Is there any accessible way to actually make a forecast? 

I have seen that when updating the model the report with the actual fitted does not provide an Rsquared as the ones in your docs. I would like to know the actual error in forecast prior to the refitting.

If I have a model, I make a business decision, I want to know my forecast, after some days, compare it with what I got, refit and continue. Can we do this with Robyn?

Anyway, thanks for the awesome and accessible library that you have created!!

**Comment by laresbernardo** [comment]
Hi! We are currently working on time-series validation (first) and forecasting (second) features. As of today, the allocator optimizes towards past performance, so no need to report forecasting or R2 metrics. On the other hand, keep an eye on following updates for these new fetures and, if you're super curious, feel free to dig into the [ts_validation](https://github.com/facebookexperimental/Robyn/pull/545) branch to see the progress.

**Comment by Sorkanius** [comment]
Thanks for the quick response! I will check the branch and close this issue.
