### ISSUE TITLE
Robyn Predict function development status

### ISSUE THREAD

**Issue by shekharkhandelwal1983** [facebookexperimental/Robyn#552]
As per the issue - https://github.com/facebookexperimental/Robyn/issues/351, there was a plan to develop prediction model within Robyn to predict on new records. Is there any progress or update on this ?

**Comment by laresbernardo** [comment]
Hi @shekharkhandelwal1983 As I just mentioned (#550) this feature is still one of our top priorities and it's currently being developed, but first we have to launch time-series validation. Thanks for your interest

**Comment by shekharkhandelwal1983** [comment]
Thanks @laresbernardo for your response. I will keep an eye for this enhancement request, as it is required for some of our new features.

**Comment by gufengzhou** [comment]
The ts validation feature is already released in v3.9. We'll start working on the forecast function next year. Please stay tuned.

**Comment by yao-hims** [comment]
Hi, I am wondering what is the status of the prediction function?

**Comment by ekladiousm** [comment]
Any updates on the release date for the forecast feature?

**Comment by iuiu34** [comment]
Any update on this one?
it's 2024 already (+1.5 year)
