### ISSUE TITLE
Budget allocator for refreshed model not updating with new time period - 

### ISSUE THREAD

**Issue by ksorger** [facebookexperimental/Robyn#553]
## Describe issue
I refreshed my model and want to use the budget allocator "max_historical_response" but the new added dates are not taken into account. 

## Provide reproducible example
Parameter data_max is not in my data's date range.

<img width="746" alt="Screenshot 2022-11-30 at 15 49 47" src="https://user-images.githubusercontent.com/80044633/204827358-51887921-f360-497c-9bd1-008038ba2de2.png">

<img width="865" alt="Screenshot 2022-11-30 at 15 45 34" src="https://user-images.githubusercontent.com/80044633/204826467-6163c64e-ad4f-4b29-86a2-431ca603632e.png">

update timeframe: 10days from 2022-11-10 - 2022-11-20

## Environment & Robyn version
<img width="782" alt="Screenshot 2022-11-30 at 15 48 50" src="https://user-images.githubusercontent.com/80044633/204827172-f8d44044-bb2d-4922-8897-452a8f5f74aa.png">

**Comment by laresbernardo** [comment]
Hi @ksorger I didn't even have time to check on this one yet. You've marked it as closed now. Can you please share with us if it's actually OK or is there still an issue? Thanks.

**Comment by ksorger** [comment]
Thanks Bernardo for following up.
It all worked in the end.

Bit of feedback that was not clear from the documentation, maybe you can
add it in the R demo code for others :)

- after the refresh I had to recreate InputCollect, OutputCollect with the
recreate() function
- i had to check that the folder path was correct, the model didn't pickup
the correct folder of the refreshed model
- change inputCollect to InputCollectX, OutputCollectX in the budget
allocator

out of interest: is it advised that the refresh of the model are converging
for nrmse and dssr? i added 17 days of daily data so data is still
volatile. our business is still young, less than two years and am training
the data with 365 days only. anything you can recommend here?

**Comment by laresbernardo** [comment]
Thanks for the follow up, will take it from here and see how we can be clearer in the demo.

Taken from the docuementation:

> When should robyn_refresh() NOT be used: The robyn_refresh() function is suitable for updating within "reasonable periods". Two situations are considered better to rebuild model instead of refreshing:
1. Most data is new: If initial model was trained with 100 weeks worth of data but we add +50 weeks of new data.
2. New variables are added: If initial model had less variables than the ones we want to start using on new refresh model.

I'd add as a 3rd case if your new strategy / time series is being changed drastically, not only the model won't be able to mold into this new trend but there's valuable data given the variance that you're not necessarily leveraging as much as you could. @gufengzhou what's your POV here?

**Comment by laresbernardo** [comment]
The refreshed new objects comment was actually there, but commented. I've added an additional comment and un-commented it [now](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R#L478-L481).

**Comment by ksorger** [comment]
Thanks!
Good point re the addtl data points and added value due to variance etc.
