### ISSUE TITLE
Display numbers on plot

### ISSUE THREAD

**Issue by ElijahHoff** [facebookexperimental/Robyn#555]
## Describe issue
I want to add on a saturation curves actual numbers, how to do that?
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/50719209/205508819-2e9d4a5c-9016-44c4-b7cb-134865948f33.png">

## Environment & Robyn version
- Robyn version ‘3.8.2’
- R version 4.2.2

**Comment by gufengzhou** [comment]
please check the `?robyn_response()` function

**Comment by ElijahHoff** [comment]
@gufengzhou unfortunately I couldn't find such parameter, can you please help?

**Comment by gufengzhou** [comment]
Load Robyn first with `library(Robyn)`
Then follow [here](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R#L534) to get response for selected model and selected variable

**Comment by ElijahHoff** [comment]
I know how to do that, I want to display numbers instead of circles and triangles on curves, how to do that?
