### ISSUE TITLE
Search spend

### ISSUE THREAD

**Issue by S-C-H** [facebookexperimental/Robyn#56]
Hi,

Media spend for Search is endogenous as it’s impacted by all other advertising and control variables. How should we estimate the impact of Paid search via this model?

thanks for any help!

**Comment by gufengzhou** [comment]
Hi, this is a typical confounder and one way to address this would be nested models. However Robyn doesn't have this feature yet. Therefore you can only include spend also as media in the main model at the moment and the multicolinearity is solved by ridge regression.

**Comment by S-C-H** [comment]
With a nested model, is the idea that you would predict search spend as a function of the other variables and then that (+ all other variable) are used to predict sales?

Would you be able to obtain an ROI from search using this?

Thanks so much for your reply!!

**Comment by gufengzhou** [comment]
Yes, this would be one option to do it. As you realise, when you're using the predicted search from sub model as predictor in the main model, you need to reverse the predicted value back to spend to obtain ROI, which is not straightforward.
