### ISSUE TITLE
Feature Scaling in Robyn

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#562]
I read in a [closed issue](https://github.com/facebookexperimental/Robyn/issues/239) that Robyn automatically scales the raw data through the glmnet package. When looking into the [model documentation](https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R) and the [glmnet documentation](https://cran.r-project.org/web/packages/glmnet/vignettes/glmnet.pdf), I gather that glmnet standardizes the channel data.

I read that feature scaling is beneficial for machine learning algorithms, and that standardization is useful to prevent domination of features on larger scales. Since all of our channel data is on the same scale (e.g. spend), why standardize and not normalize?

**Comment by gufengzhou** [comment]
Hi, Robyn does normalises media variables through the saturation curve transformation with the hill function, because hill has a normalizing effect
