### ISSUE TITLE
Nevergrad Installation: pip is configured with locations that require TLS/SSL

### ISSUE THREAD

**Issue by MUHAMMAD-LOVE** [facebookexperimental/Robyn#564]
## Project Robyn

Hi When installing "Nevergrad" I get this this massage in the rstudio console 

**WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.**

Note: I have searched the issue online but all the solutions dedicated to anaconda enviroment @laresbernardo

**Comment by laresbernardo** [comment]
Hi @MUHAMMAD-LOVE 
Have you tried running this code beforehand as suggested in #189 and our [demo](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R#L60)?
`reticulate:::rm_all_reticulate_state()`

**Comment by MUHAMMAD-LOVE** [comment]
Yes i did that many times but the error massage is about the SSL/TSL error i have downloaded Openssl but still the same error

**Comment by monathiele** [comment]
@MUHAMMAD-LOVE can you try this which worked for me last week? 

`library(reticulate)
# create a new environment 
reticulate:::rm_all_reticulate_state() #fixed SSL issue 
conda_create("r-reticulate")
use_condaenv("r-reticulate")
conda_install("r-reticulate", "nevergrad", pip = TRUE)
py_config() `

**Comment by monathiele** [comment]
@MUHAMMAD-LOVE also take note that it **DOES NOT work for me specifying "Python 3.9" in line 2**: 
```
reticulate:::rm_all_reticulate_state() #fixed SSL issue 
conda_create("r-reticulate", "Python 3.9") #use conda_create("r-reticulate") instead
use_condaenv("r-reticulate")
conda_install("r-reticulate", "nevergrad", pip = TRUE)
py_config() 
```

**Comment by MUHAMMAD-LOVE** [comment]
Trid to install it through conda give me this massage " **Error creating conda environment 'r-reticulate' [exit code 1]"** 
also used 
reticulate:::rm_all_reticulate_state() #fixed SSL issue 
  
still same error

**Comment by monathiele** [comment]
Thanks for replying :) 

Can you specify if you exactly tried this code:  
```
library(reticulate)
reticulate:::rm_all_reticulate_state() #fixed SSL issue 
conda_create("r-reticulate")
use_condaenv("r-reticulate")
conda_install("r-reticulate", "nevergrad", pip = TRUE)
py_config()
```
Thank you, If this does not work I will try and look into the issue further.

**Comment by laresbernardo** [comment]
Check out [this](https://github.com/rstudio/reticulate/issues/1297#issuecomment-1318905514) thread

**Comment by MUHAMMAD-LOVE** [comment]
The problem not with "RETICULATE" it's installed but can't install "Nevergrad "

When running the query in the Demo code to install it "py_install("nevergrad", pip = TRUE)"

Get the SSL error

**Comment by laresbernardo** [comment]
What version of reticulate package do you have? Can you share your `py_config()` print result?

**Comment by MUHAMMAD-LOVE** [comment]
Providing this massege "could not find function "py_config"

**Comment by laresbernardo** [comment]
I meant `reticulate::py_config()` and which version of reticulate you have

**Comment by MUHAMMAD-LOVE** [comment]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/66889626/208511909-ec0477b2-00c9-4be4-944c-de07e3043494.png">

**Comment by laresbernardo** [comment]
Can you please try to install numpy before installing nevergrad? That's [one of the things](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R#L59-L65) we ask the users to check when debugging nevergrad installation.

For reference, (I'm on macOS):
```
> reticulate::py_config()
python:         /Users/bernardolares/.virtualenvs/r-reticulate/bin/python
libpython:      /opt/facebook/nix/store/p4yr7ykc4mzzbsh489w9bysqcr0l0r8a-python3-3.8.9/lib/libpython3.8.dylib
pythonhome:     /Users/bernardolares/.virtualenvs/r-reticulate:/Users/bernardolares/.virtualenvs/r-reticulate
version:        3.8.9 (default, Jul 27 2021, 02:53:04)  [Clang 7.1.0 (tags/RELEASE_710/final)]
numpy:          /Users/bernardolares/.virtualenvs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.23.3
nevergrad:      /Users/bernardolares/.virtualenvs/r-reticulate/lib/python3.8/site-packages/nevergrad

python versions found: 
 /Users/bernardolares/.virtualenvs/r-reticulate/bin/python
 /usr/local/bin/python3
 /usr/bin/python3
 ```

**Comment by laresbernardo** [comment]
Closing this task given it's been inactive for some months. Feel free to re-open.
