### ISSUE TITLE
How to obtain data for ROI curves?

### ISSUE THREAD

**Issue by ElijahHoff** [facebookexperimental/Robyn#566]
## Project Robyn

Hi everyone, how to plot and / or obtain corresponding data? It should display maximum and optimal spend this is not the same as response marketing curves. Thanks

**Comment by gufengzhou** [comment]
hey, not sure what you mean. Please include reproducible examples for us to debug and/or give advices.

**Comment by michellegrushkometa** [comment]
Closing this ticket because we haven’t had any replies. Feel free to re-open if the issue persists.
