### ISSUE TITLE
Issue with Hyperparameters for ts_validation

### ISSUE THREAD

**Issue by ValaC005** [facebookexperimental/Robyn#570]
## ts_validation error for output models
```
Error in names(hyper_list_all) <- `*vtmp*` : 
  'names' attribute [x] must be the same length as the vector [x]
```
This error comes every time I try to robyn_run. The value x here is practically the number of hyper_ names we have to add for the spend media. 

Provide reproducible example
The hyperparameters I added were only for traditional media hence only newspaper and tv using geometric adstock.
```
hyperparameters_geo <- list(
  newspaper_spend_alphas = c(0.5, 3)
  ,newspaper_spend_gammas = c(0.3, 1)
  ,newspaper_spend_thetas = c(0.1, 0.4)
  
  ,tv_spend_alphas = c(0.5, 3)
  ,tv_spend_gammas = c(0.3, 1)
  ,tv_spend_thetas = c(0.3, 0.8)
  ,train_size = c(0.5,0.8)
)

OutputModels <- robyn_run(
  InputCollect = InputCollect_Geo, # feed in all model specification
  cores = NULL, # default to max available
  add_penalty_factor = FALSE, # Untested feature. Use with caution.
  iterations = 5000, 
  trials = 8, 
  ts_validation = TRUE,
  outputs = FALSE # outputs = FALSE disables direct model output - robyn_outputs()
)
print(OutputModels)
```

**Comment by jsabastian** [comment]
Hi @ValaC005 , I encountered the same error earlier. Depending on how you are adding the list of hyperparameters into InputCollect, train_size is likely not being stored. Hence the length of vector issue.

Here is how I've had my robyn_inputs code set in all previous package versions...
```
InputCollect <- robyn_inputs(
  dt_input = df_weekly, 
  dt_holidays = holidays_US,
  date_var = "week", 
  dep_var = "Revenue",
  dep_var_type = "revenue",
  prophet_vars = c("season", "holiday", "trend"),
  prophet_country = "US",
  context_vars = c("CPI"), #"Unemployment","COVID"
  paid_media_spends = c("PROS_S", "RMK_S"), 
  paid_media_vars = c("PROS_I", "RMK_I"),
  window_start = "2022-05-01",
  window_end = "2022-11-20",
  adstock = "weibull_pdf",
  hyperparameters = list(    
    PROS_S_alphas = c(0.5, 3),
    PROS_S_gammas = c(0.3, 1),
    # PROS_Under_S_thetas = c(0, 0.1)
    PROS_S_shapes = c(0.0001, 2),
    PROS_S_scales = c(0, 0.1),

    RMK_S_alphas = c(0.5, 3),
    RMK_S_gammas = c(0.3, 1),
    # RMK_Ind_S_thetas = c(0, 0.1),
    RMK_S_shapes = c(0.0001, 2),
    RMK_S_scales = c(0, 0.1),

    train_size = c(0.5, 0.8)
  )
)
```

While InputCollect object was created with no issue, when I took a peek at the structure of InputCollect, I noticed that train_size was not included in the hyperparameter list.

I ran the model using demo.R, checked the passed hyperparameter list in InputCollect, and it was present.

So, I changed my code to mimic how demo.R sets the input variables (adding hyperparameters after passing InputCollect) as follows...

```
InputCollect <- robyn_inputs(
  dt_input = df_weekly, # daily
  dt_holidays = holidays_US,
  date_var = "week", # day week
  dep_var = "Revenue",
  dep_var_type = "revenue",
  prophet_vars = c("season", "holiday", "trend"),
  prophet_country = "US",
  context_vars = c("CPI"),  #"Unemployment","COVID"
  paid_media_spends = c("PROS_S", "RMK_S"), 
  paid_media_vars = c("PROS_I", "RMK_I"),
  window_start = "2022-05-01",
  window_end = "2022-11-20",
  adstock = "weibull_pdf",
)

hyperparameters <- list(    
  PROS_S_alphas = c(0.5, 3),
  PROS_S_gammas = c(0.3, 1),
  # PROS_Under_S_thetas = c(0, 0.1)
  PROS_S_shapes = c(0.0001, 2),
  PROS_S_scales = c(0, 0.1),
  
  RMK_S_alphas = c(0.5, 3),
  RMK_S_gammas = c(0.3, 1),
  # RMK_Ind_S_thetas = c(0, 0.1),
  RMK_S_shapes = c(0.0001, 2),
  RMK_S_scales = c(0, 0.1),

  train_size = c(0.5, 0.8)
)

InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)
print(InputCollect)
```

Once I ran it as demo.R has it, I no longer encountered the error. It's merely a workaround, but I hope it helps.

**Comment by ksorger** [comment]
ah, good point - I ran into the same issue.
so adding train_size as hyper_param is solving the issue?
thx for pointing that out!

**Comment by jsabastian** [comment]
@ksorger , Yes, in my case, the hyperparameters had to be added outside of the initial inputs build (robyn_inputs). I could no longer 'set and go'.

**Comment by ValaC005** [comment]
Thank you @jsabastian for the walkthrough. I will try it out.

**Comment by ksorger** [comment]
Great, thanks! it worked for me as well!

**Comment by ValaC005** [comment]
Thanks. It worked for me too!

**Comment by laresbernardo** [comment]
Thanks for reporting this, I've just deployed a fix so hyperparameters can be defined either way.

**Comment by gufengzhou** [comment]
Please reopen if necessary.
