### ISSUE TITLE
Warning while training : "Attention for loop 6: immediate & carryover decomp don't sum up to total"

### ISSUE THREAD

**Issue by MustafaCelen** [facebookexperimental/Robyn#571]
During the training I got this warning "Attention for loop 6: immediate & carryover decomp don't sum up to total". It didnt break the training process but i would like to know what does that mean

I am using
R 4.2.2 
Robyn 3.9.0
Windows 10 

![image](https://user-images.githubusercontent.com/10905725/208107920-bf149215-8d77-4031-b26b-395f9e91ebbc.png)

**Comment by surajsingleview** [comment]
I'm having exactly the same problem when running robyn_refresh with the demo.R script as in Github on the simulated dataset, as well as a couple of other errors which break the refresh. Why might that be?


![image](https://user-images.githubusercontent.com/86753878/208794894-d5a937f8-1530-4c2a-b5ca-5196eb183156.png)

**Comment by gufengzhou** [comment]
Thanks for reporting this. It's an internal Q&A step to check if the sum of immediate & carryover equals to the total. It's not a fatal error. I can only debug with a dataset and model specs (robyn_inputs() and the hyperparameters) that can reproduce this warning.

**Comment by MustafaCelen** [comment]
unfortunatly I cant share my data but i understand . Thanks.
