### ISSUE TITLE
Pareto Front Plot NRMSE values is showing 0 with 3.9.0 ts_validation = TRUE

### ISSUE THREAD

**Issue by MustafaCelen** [facebookexperimental/Robyn#572]
I am not sure if this is normal because I am using ts_validation = TRUE but for my last trials it does not show NRMSE values in the pareto front plot. 

R 4.2.2
Robyn 3.9.0
Windows10 

![image](https://user-images.githubusercontent.com/10905725/208109399-05bca2f2-7ca7-4ec2-9c51-885560fb94dd.png)

**Comment by laresbernardo** [comment]
This is def not expected. Can you share a reproducible example for me to check? Thanks @MustafaCelen

**Comment by MustafaCelen** [comment]
I cant share my data but i am putting my R script , i also switch to ubuntu 20.04 and getting the same error.

**Comment by gufengzhou** [comment]
It doesn't look like an error to me. looking at the x-axis that's extremely large, it looks like it's just the 2 outlier points that are making the NRMSE unreadble. You can check any output tables to see if nrmse has values. It would really surprises me if not. 

Maybe we could either trim /remove outliers for plotting or maybe use log scales for better visualisation.

**Comment by MustafaCelen** [comment]
Yes it is exactly how you describe it , i have 3 models with nrmse values greater then 100 :D  i can exclude them and try to plot again if necessery. Thx a lot.
