### ISSUE TITLE
Issues Launching Robyn Learn App

### ISSUE THREAD

**Issue by ksorger** [facebookexperimental/Robyn#573]
## Describe issue
I have an issue launching the Robyn Learn UI.
Am following the steps from the Github description

- install.packages("remotes")
- remotes::install_github("facebookexperimental/Robyn/app")
- library("RobynLearn")
"Error in library("RobynLearn") : there is no package called ‘RobynLearn’"
- also library(RobynLearn) doesn't work --> am getting same error
- > robyn_learn() consequently doesn't work
Error in robyn_learn() : could not find function "robyn_learn"

Am I missing something?
Would like to play with the UI :)

## Environment & Robyn version
Robyn Version: 3.9.0

**Comment by michellegrushkometa** [comment]
Hey @ksorger! Can you try restarting your R and session and see if that helps? 
Also what happens if you do library(remotes) as its own line and then install_github("facebookexperimental/Robyn/app")?

**Comment by ksorger** [comment]
this worked thanks!
is there a way to load an existing model without refresh and then use the
budget allocator of the robyn learn app?
I was only able to access it through a refresh...

**Comment by ksorger** [comment]
also the link to the holidays.csv from the robynLearnapp is leading to a
404 page:
https://github.com/facebookexperimental/Robyn/blob/main/source/holidays.csv

**Comment by gufengzhou** [comment]
closing this as the learn app is not maintained anymore.
