### ISSUE TITLE
pbplot error while running robyn_onepagers() 

### ISSUE THREAD

**Issue by MustafaCelen** [facebookexperimental/Robyn#575]
While trying to get the one-pager report , i got pblot error, i search for the package but couldnt find :S I am getting this error on ubuntu 20.04 but also the same error happened on windows10 

R 4.2.2
Robyn 3.9
Ubuntu 20.04 

![image](https://user-images.githubusercontent.com/10905725/208241124-484d2887-fce3-4cde-870d-9d2ecdb3613f.png)

**Comment by laresbernardo** [comment]
I think I know what the issue here is. Can you please try setting `quiet = TRUE` within your function?

**Comment by MustafaCelen** [comment]
Thx this fixed the problm for me.
