### ISSUE TITLE
ROI Issue

### ISSUE THREAD

**Issue by ElijahHoff** [facebookexperimental/Robyn#577]
Hi team, I need help

Thank you for an amazing job, can you please help, how to limit ROI in certain border values, for example I want my ROI in output to be in range that I think it should be even if model is not that good considering DECOMP.RSSD и NRMSE, for example Robyn shows ROI to be 0.5 with R2 0.95, I want ROI to be 2 with R2 that might be less

## Environment & Robyn version
Robyn version: ‘3.8.2’
R version 4.2.2 (2022-10-31)

**Comment by laresbernardo** [comment]
Hi @ElijahHoff 
The best way would be to provide experimental results measuring incrementality for that specific media channel, that way Robyn will also minimize the MAPE via the multi-objective optimization and get rid of (~90%) models that are further away from the measured true incrementality for a time period. If the ROI is truly close to 2, then that's the output you'll get. 
Do check [calibration section](https://facebookexperimental.github.io/Robyn/docs/features#calibration-with-experiments) in our features documentation to read more about this feature and methodology.

**Comment by gufengzhou** [comment]
Robyn can't just "give you" the ROI you want. If the media is a straight line (same spend every day), it's impossible to get any effect, not even with calibration. It's a regression model and can't guarantee effect sizes. But calibration is definitely the right way to go if you have strong believe about a certain effect size for a certain channel/period (e.g. from causal experiments).

**Comment by ElijahHoff** [comment]
Hi @gufengzhou, @gufengzhou , can you help with an example of calibration? Where do I get following data from - # Provided value must be tested on same campaign level in model and same metric as dep_var_type
  liftAbs = c(400000, 300000, 200000),

This liftAbs is just something that I have no Idea about? How to get/calculate this data?

**Comment by gufengzhou** [comment]
Sure. Let's say you have FB as a media variable in Robyn. Calibration means you can use result from other methods/tools to "guide" Robyn. Usually we recommend running an experiment. For FB, for example, there's [conversion lift study](https://www.facebook.com/business/m/one-sheeters/conversion-lift) that you can run, which is a randomised controlled experiment. We generally believe that randomised studies are the only way to approach causal effect, thus it's a good idea to use study result to calibrate MMM. If your study has the same spend in the same period than in Robyn, then you can just use the study result as liftAbs. For more details see [here](https://facebookexperimental.github.io/Robyn/docs/features#calibration-with-experiments)

**Comment by gufengzhou** [comment]
Please reopen if necessary
