### ISSUE TITLE
Expected spend allocator not constraining budget or adjusting optimal spend

### ISSUE THREAD

**Issue by dmbernardoni** [facebookexperimental/Robyn#579]
Hello all

I am attempting to run the allocator for an expected spend level on a model I have saved as an RDS object. The output is strange, where the Initial vs. Optimized Budget Allocation is the same across all channels, but Total Spend Increase is negative. Furthermore, the Optimized Mean Response is universally lower. I do not run into this issue when doing max historical response.

I attached a screenshot of the results. The code is as follows: (Note that I get the same issue when I don't constrain date_min or date_max) 

> rds_input <- "~/Documents/Robyn MMMs/MyRobyn_v5_1-651-3.RDS"
> select_model <- "1_651_3"
> start_date <- "2022-01-01"
> end_date <- "2022-12-01"
> budget <- 400000
> n_days <- 31
> 
> rds <- readRDS(rds_input)
> InputCollect <- rds$listInit$InputCollect
> OutputCollect <- rds$listInit$OutputCollect
> 
> paid_vars <- InputCollect$paid_media_spend
> 
> AllocatorCollect <- robyn_allocator(
>   InputCollect = InputCollect
>   , OutputCollect = OutputCollect
>   , select_model = select_model
>   , scenario = "max_response_expected_spend"
>   , channel_constr_low = rep(0.7, length(paid_vars))
>   , channel_constr_up = rep(1.5, length(paid_vars))
>   , export = TRUE
>   , expected_spend = budget
>   , expected_spend_days = n_days
>   , date_min = start_date
>   , date_max = end_date
> )

<img width="894" alt="Screen Shot 2022-12-20 at 3 26 55 PM" src="https://user-images.githubusercontent.com/60370160/208770900-e90038f4-9451-423f-9b0a-632ee4da3300.png">

**Comment by gufengzhou** [comment]
Can you retry with a larger spend, like 1mio? It should look more intuitive. the -30% total spend means that the 400k is 30% less than your historical average in the same length (31days), thus all responses also decrease because of less spend. Check the allocator output table to understand details.

**Comment by laresbernardo** [comment]
Just an additional comment: [since version 3.7.1](https://www.facebook.com/groups/robynmmm/permalink/1261441437957320) you can save Robyn models with JSON files which will contain all the necessary information to replicate them. We won't keep supporting RDS files even though it might still work.

**Comment by dmbernardoni** [comment]
Ok, thank you! Increasing the spend seems to have fixed it.
