### ISSUE TITLE
Actionable insights

### ISSUE THREAD

**Issue by S-C-H** [facebookexperimental/Robyn#58]
The graphs provided and optimisation of spend across channels is great - How would you use this to iterate your media spend over a period of time? Perhaps your creatives change one month and one channel changes effectiveness (decay and saturation may be more global)? Should you just have a rolling time period for the model dataset?

**Comment by gufengzhou** [comment]
Thanks for the feedback. This will be addressed in the next update of Robyn. We'll release a new function to better update the initial model with new datapoints as well as more flexible selection of modelling period.
