### ISSUE TITLE
demo.R script - OutputCollect pareto_fronts error

### ISSUE THREAD

**Issue by aazimh** [facebookexperimental/Robyn#581]
## Describe issue

Just installed Robyn today and while trying to run through the standard `demo.R` script, I have hit an error at the OutputCollect generation line. This is the error I get:

```
> OutputCollect <- robyn_outputs(
+   InputCollect, OutputModels,
+   pareto_fronts = "auto", # automatically pick how many pareto-fronts to fill min_candidates
+   # min_candidates = 100, # top pareto models for clustering. Default to 100
+   # calibration_constraint = 0.1, # range c(0.01, 0.1) & default at 0.1
+   csv_out = "pareto", # "pareto", "all", or NULL (for none)
+   clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
+   plot_pareto = TRUE, # Set to FALSE to deactivate plotting and saving model one-pagers
+   plot_folder = robyn_object, # path for plots export
+   export = TRUE # this will create files locally
+ )
>>> Running Pareto calculations for 1000 models on auto fronts...
Error in 1:pareto_fronts : NA/NaN argument
In addition: Warning message:
In robyn_pareto(InputCollect, OutputModels, pareto_fronts, calibration_constraint,  :
  NAs introduced by coercion
```
The only things I have changed in the demo script are:

- Reduced the `iterations` to 500 and `trials` to 2 - I know this is below recommended levels but I didn't have time so was trying to get something quickly - if this is the reason behind the error then that is simple enough, but just want to be sure as the error message doesn't really indicate it has anything to do with those parameters.
- Deleted `train_size` as a key in the `hyperparameters` list - this was because I got the following error earlier:

```
> InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)
Error in check_hyperparameters(InputCollect$hyperparameters, InputCollect$adstock,  : 
  Input 'hyperparameters' contains following wrong names: train_size
```

## Provide reproducible example

As mentioned above, the standard `demo.R` file on this Github with `iterations=500` and `trials=2` on lines 332 and 333 respectively, as well as deleting `train_size` in the `hyperparameters` list on line 200.

## Environment & Robyn version

- Robyn version: `3.7.2`
- R version: `4.2.1 (2022-06-23 ucrt)`

Any help would be great, thank you! Happy to share additional debug information if needed.

**Comment by aazimh** [comment]
Thank you @laresbernardo! I'm trying `robyn_update()` and getting the following error (of course it couldn't be simple :)):

```
Downloading GitHub repo facebookexperimental/Robyn@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/facebookexperimental/Robyn/tarball/HEAD'
```

I have installed the `remotes` package - I'm on Windows. 

I've also tried the `options(timeout=400)` solution mentioned elsewhere in the repo, but no dice. I might not be doing it properly though - I ran it as a standalone command, as well as an argument to the `remotes::install_github` command, didn't work either way.

For now I'll just use the older demo.R file, but would be great to figure out how to get to the dev branch if that's what you guys recommend. Thanks again!

**Comment by aazimh** [comment]
So I ended up running into an error in the same place in the older demo.R file - keeping it in this thread just in case it's an easy fix otherwise happy to open another issue.

```
> OutputCollect <- robyn_outputs(
+   InputCollect, OutputModels,
+   pareto_fronts = 3,
+   # calibration_constraint = 0.1, # range c(0.01, 0.1) & default at 0.1
+   csv_out = "pareto", # "pareto" or "all"
+   clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
+   plot_pareto = TRUE, # Set to FALSE to deactivate plotting and saving model one-pagers
+   plot_folder = robyn_object # path for plots export
+ )
>>> Running Pareto calculations for 1000 models on 3 fronts...
Error in `bind_rows()`:
! Can't combine `..1$ds` <date> and `..2$ds` <IDate>.
```

Running the last trace gives:

```
<error/vctrs_error_ptype2>
Error in `bind_rows()`:
! Can't combine `..1$ds` <date> and `..2$ds` <IDate>.
---
Backtrace:
     ▆
  1. ├─Robyn::robyn_outputs(...)
  2. │ └─Robyn:::robyn_pareto(...)
  3. │   └─dplyr::bind_rows(...)
  4. │     ├─dplyr:::fix_call(vec_rbind(!!!dots, .names_to = .id))
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─vctrs::vec_rbind(!!!dots, .names_to = .id)
  7. └─vctrs (local) `<fn>`()
  8.   └─vctrs::vec_default_ptype2(...)
  9.     ├─base::withRestarts(...)
 10.     │ └─base (local) withOneRestart(expr, restarts[[1L]])
 11.     │   └─base (local) doWithOneRestart(return(expr), restart)
 12.     └─vctrs::stop_incompatible_type(...)
 13.       └─vctrs:::stop_incompatible(...)
 14.         └─vctrs:::stop_vctrs(...)
 15.           └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))
```

Again, haven't changed anything from the demo.R script this time except reducing the number of trials (2) and iterations (500).

If there's any other output I can provide to help let me know!

**Comment by CJ2407** [comment]
Hi! I am getting this error when trying to add train_size hyperparameter in the Inputcollect. I see that this issue has been brought up here, but I didn't understand the solution besides having the latest dev version of Robyn. I have recently installed Robyn following the instructions provided on the website. @laresbernardo could you please guide me in fixing this error?

**Comment by laresbernardo** [comment]
> ! Can't combine `..1$ds` <date> and `..2$ds` <IDate>.

@aazimh  This error comes from a very old version that was fixed some time ago. It occurred when trying to bind data.table's date format with basic Date format. I strongly suggest you update to latest versions.

> this error when trying to add train_size hyperparameter in the Inputcollect

@CJ2407 what error exactly? The `(...) Can't combine `..1$ds` (...)`? When updating to latest dev version (`Robyn::robyn_update())` be sure to reset your R session before retrying.

**Comment by CJ2407** [comment]
@laresbernardo I keep getting this error and hence unable to enable ts_validation - 

Error in check_hyperparameters(InputCollect$hyperparameters, InputCollect$adstock, :
'hyperparameters' contains following wrong names: train_size

**Comment by laresbernardo** [comment]
> 'hyperparameters' contains following wrong names: train_size

If you're using version >=3.9, then you can define train_size hyperparameter range. If <3.9, then it'll give you that error. So, exclude that hyperparameter from your hyperparameter input if you're in <3.9.

> Robyn::robyn_update()

If you don't have this function, you're not even using the latest stable version from CRAN, thus a very old function. That's the same as running `remotes::install_github("facebookexperimental/Robyn/R")`.

It's quite relevant 1) updating Robyn frequently, 2) knowing which version you're using and 3) knowing what [changes](https://github.com/facebookexperimental/Robyn/releases) and updates we've deployed to understand these errors and warnings.

**Comment by tgtod002** [comment]
I am getting this error when running OutputCollect..

Using robyn object location: C:/BurgerKing_mmm/NM
>>> Running Pareto calculations for 50000 models on auto fronts...
>> Automatically selected 1 Pareto-fronts to contain at least 100 pareto-optimal models (247)
>>> Calculating response curves for all models' variables (494)...
>> Pareto-Front: 1 [247 models]
 00:02:23 [=================================================================================================] 100% | 247                                                                              
Error in robyn_outputs(InputCollect, OutputModels, pareto_fronts = "auto",  : 
  object 'create_files' not found

**Comment by laresbernardo** [comment]
Hey @tgtod002 that's because you have to define the `create_files` object or replace it with TRUE or FALSE.

**Comment by gufengzhou** [comment]
Please reopen if necessary.
