### ISSUE TITLE
Problems with robyn_read function and robyn_recreate

### ISSUE THREAD

**Issue by PauLangle** [facebookexperimental/Robyn#583]
Hi, 

I´m currently trying to read an already build up model in order to continue  with the budget allocation, but there are some problems with both the 3.8.2 and 3.9.0 Robyn Version (the model was built using V 3.8.2 and R 4.2.2).

The way I saved the model was the following one:
`ExportedModel <- robyn_write(InputCollect, OutputCollect, select_model)`
`print(ExportedModel)`

## Problems with version 3.8.2

I´m able to run the following lines without problem
`json_file <-file.path("Robyn_202212221742_init","RobynModel-5_232_1.json")`
`json_data <- robyn_read(json_file)`

![image](https://user-images.githubusercontent.com/60376119/209245851-fa5826f2-e2c3-404b-85a5-1899be697fb8.png)

The problem comes with the `print(json_data)`

![image](https://user-images.githubusercontent.com/60376119/209245913-20aea81e-1d1f-4c4b-ad5e-508d6ad9e999.png)

But okay, I was still able to recreate the Input and Output collects using the _robyn_recreate_ and _robyn_onepagers_ functions and everything went fine. The thing is that after I updated to version 3.9.0, encountered some problems and then returned to the 3.8.2 V, the Immediate vs Carryover Response Percentage plot is now blank.

![image](https://user-images.githubusercontent.com/60376119/209246172-c92405e5-593f-4676-a773-bce136784316.png)

I don´t know if this has to do with the fact that in order to update to version 3.9.0, some other libraries were required to be updated as well. 

## Problems with version 3.9.0
Even when I update Robyn to the newest version I´m still facing the same problem with the `print(json_data)` step.
The new issue here is that while running robyn_recreate() I get the following error message:

![image](https://user-images.githubusercontent.com/60376119/209246980-156fb44a-8cfe-41ae-8a0b-8c3c98fb005d.png)

Here I leave the complete code and the json file. The data used in this example is the one from the demo.

[RobynModel-5_232_1.zip](https://github.com/facebookexperimental/Robyn/files/10291138/RobynModel-5_232_1.zip)

```{r}
json_file <-file.path("Robyn_202212221742_init","RobynModel-5_232_1.json")
json_data <- robyn_read(json_file)
print(json_data)

RobynRecreated <- robyn_recreate(
  json_file = json_file,
  dt_input = dt_simulated_weekly,
  dt_holidays = dt_prophet_holidays,
  quiet = FALSE)
```

I could really use some help
Thanks a lot!!!!

**Comment by laresbernardo** [comment]
Hi @PauLangle
- I've just fixed the issue with the print function (which was present since v3.8.2).
- Given the original model was built with version <3.9.0, we don't have the carryover split data in our JSON file, so we can't recreate that plot. You'd have to recreate the model with version >=3.9.0 to be able to fill that gap. Also, if you don't want to have that white space and wish to go back to previous version to plot the one pagers, you can downgrade to your original version with `remotes::install_github("facebookexperimental/Robyn/R", ref = "v3.8.2")`.
- I was able to reproduce the second error mentioned. Will get back after I understand more what's happening.

**Comment by laresbernardo** [comment]
Ok, I think it's fixed now. If no "train_size" value is available that means you used an older version which means train_size = 1. When importing the JSON file, this value will be added if not present. Thanks for reporting. Please, do update and check if both issues have been fixed.

**Comment by PauLangle** [comment]
Hi Bernardo

Thank you so much for your help! Both issues have been fixed
