### ISSUE TITLE
Update on issue #81 || Model generalisation problem. 

### ISSUE THREAD

**Issue by albertsalgueda** [facebookexperimental/Robyn#584]
Hei!

Follow-up of this issue: https://github.com/facebookexperimental/Robyn/issues/81 

We have created several Robyn models and our customers are a bit worried about no train test split or cross-validation.

I agree with the fact that Ridge regression prevents overfitting, however, I am not sure it is enough. I wonder if Nevergrad should optimize towards R-squared in test data.

Even though it is a decomposition model, several functionalities regarding future estimates are key, and already implemented (i.e. Budget Allocator) So, there is a predictive utility in the model.

Customers prefer a model that can generalize, or at least we can prove it does.

Are you guys considering including that functionality again? Maybe as an option?
It would be very helpful!

Thank you for your amazing work; we are really happy with Robyn and hope to start using it soon.

**Comment by gufengzhou** [comment]
It's just released. Please check https://github.com/facebookexperimental/Robyn/releases/tag/v3.9.0

**Comment by albertsalgueda** [comment]
Amazing, thanks!
