### ISSUE TITLE
[ERROR] Aesthetics must be either length 1 or the same as the data (1): x, y and fill

### ISSUE THREAD

**Issue by satomi999** [facebookexperimental/Robyn#585]
I got an error whiling robyn_onepagers() on a recalled json model.

```R
json_file <- "RobynModel-3_318_4.json"

InputCollectX <- robyn_inputs(
  dt_input = robyn_dataset,
  dt_holidays = holidays,
  json_file = json_file)

OutputCollectX <- robyn_run(
  InputCollect = InputCollectX,
  json_file = json_file,
  export = FALSE)

robyn_onepagers(InputCollectX, OutputCollectX, select_model = "3_318_4", export = TRUE)
```

```R
> robyn_onepagers(InputCollectX, OutputCollectX, select_model = "3_318_4", export = TRUE)
Error in { : 
  task 1 failed - "Aesthetics must be either length 1 or the same as the data (1): x, y and fill"
```
This error occurs in **ver. 3.8 (or higher)**. 
This did not occur in ver. 3.7.2.
R version : 4.2.1

I am sorry to trouble you, but I would really appreciate it if you could confirm.
Thanks.

**Comment by satomi999** [comment]
Thanks @laresbernardo !
I tried the demo data and encountered the same error. (in v3.9)
[RobynModel-1_101_1.zip](https://github.com/facebookexperimental/Robyn/files/10398454/RobynModel-1_101_1.zip)

**Comment by laresbernardo** [comment]
Hi @satomi999 at least with the latest dev version (make sure you have it installed), I can't seem to be able to replicate your issue. This is what I ran and the output (notice you shared model 1_101_1 and not 3_318_4):

```
json_file <- "/Users/bernardolares/Desktop/RobynModel-1_101_1.json"
json_data <- robyn_read(json_file)
print(json_data)
# Re-create InputCollect
InputCollectX <- robyn_inputs(
  dt_input = Robyn::dt_simulated_weekly,
  dt_holidays = Robyn::dt_prophet_holidays,
  json_file = json_file)
print(InputCollectX)
# Re-create OutputCollect
OutputCollectX <- robyn_run(
  InputCollect = InputCollectX,
  json_file = json_file,
  export = FALSE)
# Recreate one-pager
myOP <- robyn_onepagers(
  InputCollectX, OutputCollectX,
  select_model = "1_101_1",
  export = TRUE)
```
![1_101_1](https://user-images.githubusercontent.com/25909073/212114225-ebf15e45-0e42-4195-8696-eed84c760b0e.png)
(I'll check why `myOP$`1_101_1`$patches$plots[[6]]` is empty and wasn't recreated if you have this data available)

**Comment by laresbernardo** [comment]
@Amyhaoming can you please help me with the last check I mention in the previous comment? Thanks!

**Comment by satomi999** [comment]
Hi, @laresbernardo.
I reinstalled the latest development version and got the same error.
However, reinstalling all packages solved the problem！
(Also in this result, myOP$`1_101_1`$patches$plots[[6]] was empty.)
It appears that it was incompatible with version of some packages.

![image](https://user-images.githubusercontent.com/98081674/212270938-161aa95f-fc7c-46e4-8fb0-e5750dfcc1a6.png)

Sorry for the trouble.
Thank you for confirming !!

**Comment by gufengzhou** [comment]
Please reopen if necessary
