### ISSUE TITLE
How to create weekly based forecast with associated ROIs

### ISSUE THREAD

**Issue by ElijahHoff** [facebookexperimental/Robyn#590]
## Describe issue
Hello team, thanks for an amazing job, can you please help with forecasts functionality?

## Provide reproducible example
How to create weekly based forecast with associated ROIs?

## Environment & Robyn version
Robyn ‘3.8.2’
"R version 4.2.2 (2022-10-31)"

**Comment by gufengzhou** [comment]
Hi, we'll be working on the forecast function this half. In very high level, you'll need to define future values for all predictors first, then do adstock and saturation transformation, then you can use the beta coefficients to forecast.

**Comment by gufengzhou** [comment]
Please reopen if necessary
