### ISSUE TITLE
Clusters do not contain enough models to calculate CI

### ISSUE THREAD

**Issue by Angylina** [facebookexperimental/Robyn#592]
## Project Robyn

I was running the model with the new time-series validation feature both on my own data and on the simulated data, but every time I do that robyn_run() gives a warning:  

Input data has 208 weeks in total: 2015-11-23 to 2019-11-11
Initial model is built on rolling window of 208 week: 2015-11-23 to 2019-11-11
Time-series validation with train_size range of 50%-80% of the data...
Using weibull_pdf adstocking with 22 hyperparameters (22 to iterate + 0 fixed) on 16 cores
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
  |=================                                                           
*** WARNING: skipped 83840 bytes of output ***

  |======================================================================| 100%
  Finished in 2.38 mins
- DECOMP.RSSD NOT converged: sd@qt.20 0.13 > 0.11 & |med@qt.20| 0.18 > 0.069
- NRMSE NOT converged: sd@qt.20 0.33 > 0.19 & |med@qt.20| 0.47 <= 1.3
Total run time: 11.95 mins
>>> Running Pareto calculations for 10000 models on 1 front...
>> Pareto-Front: 1 [26 models]
 00:00:13 [=========================================] 100% | 26                      
>>> Calculating clusters for model selection using Pareto fronts...
>> Auto selected k = 10 (clusters) based on minimum WSS variance of 5%
Warning in confidence_calcs(xDecompAgg, cls, all_paid, dep_var_type, k,  :
  Cluster 2 does not contain enough models to calculate CI
Warning in confidence_calcs(xDecompAgg, cls, all_paid, dep_var_type, k,  :
  Cluster 3 does not contain enough models to calculate CI
Warning in confidence_calcs(xDecompAgg, cls, all_paid, dep_var_type, k,  :
  Cluster 4 does not contain enough models to calculate CI
Warning in confidence_calcs(xDecompAgg, cls, all_paid, dep_var_type, k,  :
  Cluster 5 does not contain enough models to calculate CI
Warning in confidence_calcs(xDecompAgg, cls, all_paid, dep_var_type, k,  :
  Cluster 7 does not contain enough models to calculate CI
Warning in confidence_calcs(xDecompAgg, cls, all_paid, dep_var_type, k,  :
  Cluster 9 does not contain enough models to calculate CI
Warning in confidence_calcs(xDecompAgg, cls, all_paid, dep_var_type, k,  :
  Cluster 10 does not contain enough models to calculate CI
>>> Collecting 26 pareto-optimum results into: /dbfs/FileStore/Angelina Sandbox/Robyn_202301041632_init/
>> Exporting general plots into directory...
Failed exporting results, but returned model results anyways:
 Error in ts_validation(OutputModels, quiet = TRUE, ...): object 'OutputModels' not found

After this, it only saves the general plots, but no one-pagers at all. I tried this 2 times with my own data, and 1 time with a simulated data from Robyn. On the screenshot are the only files it produces after this warning. 

![Schermopname (39)](https://user-images.githubusercontent.com/120499663/210620141-24005c92-4d1e-4e5f-918d-a4b6f1d7a513.png)

## Provide reproducible example

My code is exactly the same as in the demo, except ts_validation = TRUE . Everything else is copy pasted from demo. 

## Environment & Robyn version
- Robyn 3.9.0
- R version 4.1.3 (I am running it in Databricks)

Thanks in advance for your help!

**Comment by gufengzhou** [comment]
I found this thread that indicates it's related to Databricks. please check https://stackoverflow.com/questions/58386830/databricks-prints-only-around-280-lines-of-data

**Comment by laresbernardo** [comment]
Hi @Angylina this is a warning that is printed whenever a cluster doesn't contain at least three solutions, this no CI can be calculated. Can you please check how many models per cluster you are getting? It seems the algorithm is setting k=10 and all solutions are in clusters 1 and 8. Did you pick only 1 pareto-front? Can you set it to "auto" (at least 100 models) or increase to more fronts manually to see if you get more solutions per cluster? Did you check the distribution of solutions to see if you're getting really weird and/or extreme results?

**Comment by gufengzhou** [comment]
Old ticket. Please reopen if necessary.
