### ISSUE TITLE
Convergence problem (Does "DECOMP.RSSD" have to converge?)

### ISSUE THREAD

**Issue by akhrt01** [facebookexperimental/Robyn#594]
NRMSE converged, but DECOMP.RSSD NOT converged.
- DECOMP.RSSD NOT converged: sd@qt.20 0.084 > 0.025 & |med@qt.20| 0.17 <= 0.36
- NRMSE converged: sd@qt.20 0.01 <= 0.022 & |med@qt.20| 0.048 <= 0.12
- (R2 train:0.9114, NRMSE=0.048, DECOMP.RSSD=0.0902)

1.If the spending on marketing was very far from ideal, DECOMP.RSSD may not converge.So it is not essential for DECOMP.RSSD to converge.
Also, I use 12 years data ,because I have to use monthly data. In 12 years, media environment and plannnninng  has changed a lot, so spending distribution may not make sense in the first place.

2.DECOMP.RSSD NOT converged, but DECOMP.RSSD = 0.0902 in my model.That seems low enough to me, but isn't it?

3.Looking at "Multi-objective Evolutionary Performance", there is also a darker colored dot in the upper right corner. (iterations is close to 2000, but both NRMSE and DECOMP.RSSD are large)
As for the convergence result, NRMSE has converged, but is this convergence process problematic? (DECOMP.RSSD not converged.)

#Robyn 3.7.1 
#R version 4.2.1

**Comment by akhrt01** [comment]
![image](https://user-images.githubusercontent.com/121992890/210695312-50adb9c7-981d-47b8-ab0b-7c77330379f7.png)

**Comment by gufengzhou** [comment]
This issue is already answered in https://www.facebook.com/groups/robynmmm/permalink/1358750738226389/
