### ISSUE TITLE
The media are not optimally allocated

### ISSUE THREAD

**Issue by akhrt01** [facebookexperimental/Robyn#595]
I made my model and tryed "max_response_expected_spend", but The media are not optimally allocated.
The media were only prorated equally.

I ran it.
>AllocatorCollect2 <- robyn_allocator(
>  InputCollect = InputCollect,
>  OutputCollect = OutputCollect,
>  select_model = select_model,
>  scenario = "max_response_expected_spend",
>  channel_constr_low = 0.0000000001,
>  channel_constr_up = 50,
>  expected_spend = 100000000, # Total spend to be simulated
>  expected_spend_days = 31, # Duration of expected_spend in days
>  export = TRUE
>)

The message then was this, and The media were only prorated equally.
>Warning message:
>In check_allocator(OutputCollect, select_model, paid_media_spends,  :
>  Inputs 'channel_constr_up' > 5 might cause unrealistic allocation

How can I optimize my media allocation?

#Robyn 3.7.1 
#R version 4.2.1

![image](https://user-images.githubusercontent.com/121992890/210702532-d0f03d2f-ee5e-4383-9762-449d8013978f.png)

**Comment by gufengzhou** [comment]
This is already answered in the group https://www.facebook.com/groups/robynmmm/posts/1358757811559015/
