### ISSUE TITLE
Prophet decomposition holiday effect issue

### ISSUE THREAD

**Issue by MustafaCelen** [facebookexperimental/Robyn#602]
Hi , I am using 3 years of data , my prophet decomposition shows that on my 3rd year holidays does not add any effect on my sales , where the first 2 years are captured well. One thing I had to mention here is that I am excluding 2020 and 2021 and treat 2022 as it is 2020(I did this manually changing from excel). I did the same procedure on public_holidays dataset so there is no problem with that. 

![image](https://user-images.githubusercontent.com/10905725/212104617-83c2558f-5628-4c60-9d4b-942e95d6f7e2.png)

Funny thing is that if I just omit 2020&2021 but keep 2022 as is ,it captures the holiday effect as it should . But the training duration is increasing a lot also the graphics looks weird etc.

![image](https://user-images.githubusercontent.com/10905725/212105700-4b4cda3f-03b3-4d86-8b4d-cab89a4fd32b.png)

The code below shows how I replace the year 2022 with 2020. Is there any insights on what might be wrong here ?

public_holidays$date = as.Date(public_holidays$date, format="%Y-%m-%d")
public_holidays = subset(public_holidays, format(as.Date(date),"%Y")==2022 | format(as.Date(date),"%Y") >= 2018)
date1 <- as.Date(public_holidays[format(as.Date(public_holidays$date),"%Y")==2022,"date"], format="%d-%b")
year(date1) <- 2020
public_holidays[format(as.Date(public_holidays$date),"%Y")==2022,"date"] <- date1
public_holidays
public_holidays$year = format(as.Date(public_holidays$date, format="%Y-%m-%d"),"%Y")
public_holidays = as_tibble(subset(public_holidays, select = c(date, name, countryCode, year)))
names(public_holidays) <- c('ds','holiday','country', 'year')
public_holidays$ds = as.Date(public_holidays$ds, format="%Y-%m-%d")
public_holidays$year = as.integer(public_holidays$year)

**Comment by gufengzhou** [comment]
Hey, it looks to me that you have 2020 in there twice? the real 2020 and the other one converted from 2022?

**Comment by MustafaCelen** [comment]
pulic_holidays dataset looks just as it should. There is o repeating holidays etc. 

![image](https://user-images.githubusercontent.com/10905725/212831443-36a518c7-d60d-43d6-847a-4d92e91557e1.png)

**Comment by gufengzhou** [comment]
Does this issue still persists? Feel free to reopen if necessary.
