### ISSUE TITLE
Error in { : task 1 failed - "object 'y_hat' not found"

### ISSUE THREAD

**Issue by Luinehil** [facebookexperimental/Robyn#605]
Hello, 

I'm new to R and Robyn but I did follow up the "Demo" instructions and I get this error. Any idea why?
My dt_input is from Google Sheets, but I hope it's not a problem. I used the newest version of Robyn. 

This is the error I got:

Input data has 365 days in total: 2022-01-01 to 2022-12-31
Initial model is built on rolling window of 365 day: 2022-01-01 to 2022-12-31
Time-series validation with train_size range of 50%-80% of the data...
Using geometric adstocking with 17 hyperparameters (17 to iterate + 0 fixed) on 1 core (Windows fallback)
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
  |                                                                    |   0%Odliczanie zatrzymało się na: 0.53 0.03 0.59
Error in { : task 1 failed - "object 'y_hat' not found"

**Comment by laresbernardo** [comment]
Hi @Luinehil 
Thanks for reporting this bug. I [mistakenly](https://github.com/facebookexperimental/Robyn/commit/5a036c4aa594ab7925a343672c0ac585d9b3d5a5) commented a section out that shouldn't be commented. I've just fixed it. Please, update to latest dev version and retry. Feel free to close this task once you validate it's been fixed.

**Comment by Luinehil** [comment]
Hey @laresbernardo indeed, now it works!
