### ISSUE TITLE
Error during wrapup: vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by emmag123** [facebookexperimental/Robyn#608]
## Project Robyn
Hi Robyn team! Thank you so much for your continued work on this project! 

## Describe issue
I keep getting a memory exhausted error following the conclusion of the first trial, and I am unsure how to resolve. I've included the error below. 

```
>>> Starting 10 trials with 5000 iterations each with calibration using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 10
  |====================================================================================| 100%
  Finished in 57.88 mins
Error: vector memory exhausted (limit reached?)
In addition: Warning messages:
1: In hyper_collector(InputCollect, hyper_in = InputCollect$hyperparameters,  :
  Provided train_size but ts_validation = FALSE. Time series validation inactive.
2: In with_options(`rlang:::visible_bottom` = info$bottom_frame, { :
  restarting interrupted promise evaluation
Error during wrapup: vector memory exhausted (limit reached?)
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

## Provide reproducible example
Here is the input collect. 
```
> InputCollect
Total Observations: 1474 (days)
Input Table Columns (12):
  Date: the_date
  Dependent: us_regs [conversion]
  Paid Media: sem_spend, dm_spend, meta_spend, non_podcast_audio_spend, podcast_spend, tv_spend
  Paid Media Spend: sem_spend, dm_spend, meta_spend, non_podcast_audio_spend, podcast_spend, tv_spend
  Context: wei, t10y3m, sp500
  Organic: 
  Prophet (Auto-generated): trend, season, holiday, weekday on US
  Unused variables: tv_no_strategic

Date Range: 2018-12-31:2023-01-12
Model Window: 2018-12-31:2023-01-12 (1474 days)
With Calibration: TRUE
Custom parameters: None

Adstock: weibull_pdf
Hyper-parameters ranges:
  tv_spend_alphas: [0.5, 3]
  tv_spend_gammas: [0.3, 1]
  tv_spend_scales: [0, 0.002]
  tv_spend_shapes: [0.5, 5]
  non_podcast_audio_spend_alphas: [0.5, 3]
  non_podcast_audio_spend_gammas: [0.3, 1]
  non_podcast_audio_spend_scales: [0, 0.004]
  non_podcast_audio_spend_shapes: [0.5, 5]
  podcast_spend_alphas: [0.5, 3]
  podcast_spend_gammas: [0.3, 1]
  podcast_spend_scales: [0.004, 0.009]
  podcast_spend_shapes: [3, 14]
  dm_spend_alphas: [0.5, 3]
  dm_spend_gammas: [0.3, 1]
  dm_spend_scales: [0.01, 0.017]
  dm_spend_shapes: [3, 10]
  sem_spend_alphas: [0.5, 3]
  sem_spend_gammas: [0.3, 1]
  sem_spend_scales: [0, 0.001]
  sem_spend_shapes: [0, 2]
  meta_spend_alphas: [0.5, 3]
  meta_spend_gammas: [0.3, 1]
  meta_spend_scales: [0, 0.001]
  meta_spend_shapes: [0, 2]
  train_size: [0.5, 0.8]
```

and here is the code that produced the error after the first trial was complete. 

```
OutputCollect <- robyn_run(
   InputCollect = InputCollect
   , cores = 6
   , iterations = 5000
   , trials = 10
   #, add_penalty_factor = FALSE
   , outputs = TRUE
   , pareto_fronts = 3
   , csv_out = "pareto"
   , clusters = TRUE
   , plot_pareto = TRUE
   , plot_folder = robyn_object
 )
```

## Environment & Robyn version

`> packageVersion("Robyn")
[1] ‘3.9.0’`

`R version 4.2.2 (2022-10-31)`

**Comment by laresbernardo** [comment]
Hi! Can you also share your `sessionInfo()`? How many cores do you have available? How many are you using?
Also, do check these threads: #540 & #523 
FYI: We are currently working on cleaning `robyn_run()` and `robyn_outputs()` outputs to be more space efficient and avoid these memory crashes. CC: @michellegrushkometa

**Comment by emmag123** [comment]
Hi! 

Here's the sessionInfo() output: 
```
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7
```

I believe I have 4 cores available on my Mac, and I believe I enabled the usage of all of them via `cores = 6` in robyn_run().

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	512 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by emmag123** [comment]
Hi, @laresbernardo @michellegrushkometa! Any update here? 
I tried the solution proposed in #540, and successfully ran `robyn_run()`.
```
OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = NULL, # NULL defaults to max available - 1
  iterations = 10000, # 2000 recommended for the dummy dataset with no calibration
  trials = 15, # 5 recommended for the dummy dataset
  ts_validation = TRUE, # 3-way-split time series for NRMSE validation.
  add_penalty_factor = FALSE # Experimental feature. Use with caution.
)
```
However, I am now experiencing the same error when running `robyn_outputs()`. 
```
> OutputCollect <- robyn_outputs(
+   InputCollect, OutputModels,
+   pareto_fronts = "auto", # automatically pick how many pareto-fronts to fill min_candidates
+   # min_candidates = 100, # top pareto models for clustering. Default to 100
+   # calibration_constraint = 0.1, # range c(0.01, 0.1) & default at 0.1
+   csv_out = "pareto", # "pareto", "all", or NULL (for none)
+   clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
+   plot_pareto = TRUE, # Set to FALSE to deactivate plotting and saving model one-pagers
+   plot_folder = robyn_object, # path for plots export
+   export = TRUE # this will create files locally
+ )
Using robyn object location: /Users/emmag/Desktop
>>> Running Pareto calculations for 150000 models on auto fronts...
>> Automatically selected 5 Pareto-fronts to contain at least 100 pareto-optimal models (110)
>> Pareto-Front: 1 [17 models]
Error in `bind_rows()`:
! vector memory exhausted (limit reached?)
Run `rlang::last_error()` to see where the error occurred.
```

When I run `sessionInfo()`, here is the output: 
```
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] doRNG_1.8.3    rngtools_1.5.2 foreach_1.5.2  corrplot_0.92  dplyr_1.0.10   remotes_2.4.2 
[7] Robyn_3.9.0   

loaded via a namespace (and not attached):
 [1] nlme_3.1-160         bitops_1.0-7         matrixStats_0.63.0   lubridate_1.9.0     
 [5] RColorBrewer_1.1-3   doParallel_1.0.17    httr_1.4.4           rprojroot_2.0.3     
 [9] rstan_2.21.7         tools_4.2.2          utf8_1.2.2           R6_2.5.1            
[13] rpart_4.1.19         mgcv_1.8-41          DBI_1.1.3            lazyeval_0.2.2      
[17] colorspace_2.0-3     withr_2.5.0          tidyselect_1.2.0     gridExtra_2.3       
[21] prettyunits_1.1.1    processx_3.8.0       compiler_4.2.2       glmnet_4.1-6        
[25] cli_3.5.0            rvest_1.0.3          xml2_1.3.3           shinyjs_2.1.0       
[29] labeling_0.4.2       scales_1.2.1         ggridges_0.5.4       callr_3.7.3         
[33] stringr_1.5.0        digest_0.6.31        StanHeaders_2.21.0-7 extraDistr_1.9.1    
[37] pkgconfig_2.0.3      rlang_1.0.6          rstudioapi_0.14      rPref_1.3           
[41] farver_2.1.1         shape_1.4.6          prophet_1.0          generics_0.1.3      
[45] jsonlite_1.8.4       zip_2.2.2            inline_0.3.19        RCurl_1.98-1.9      
[49] magrittr_2.0.3       loo_2.5.1            patchwork_1.1.2      Matrix_1.5-1        
[53] Rcpp_1.0.9           munsell_0.5.0        fansi_1.0.3          reticulate_1.26     
[57] lifecycle_1.0.3      stringi_1.7.8        pROC_1.18.0          yaml_2.3.6          
[61] pkgbuild_1.4.0       plyr_1.8.8           grid_4.2.2           parallel_4.2.2      
[65] crayon_1.5.2         lattice_0.20-45      splines_4.2.2        lares_5.1.4         
[69] ps_1.7.2             pillar_1.8.1         igraph_1.3.5         codetools_0.2-18    
[73] stats4_4.2.2         glue_1.6.2           rpart.plot_3.1.1     data.table_1.14.6   
[77] RcppParallel_5.1.5   png_0.1-8            vctrs_0.5.1          nloptr_2.0.3        
[81] gtable_0.3.1         purrr_1.0.1          tidyr_1.2.1          assertthat_0.2.1    
[85] ggplot2_3.4.0        openxlsx_4.2.5.1     h2o_3.38.0.1         survival_3.4-0      
[89] minpack.lm_1.2-2     tibble_3.1.8         iterators_1.0.14     timechange_0.1.1    
[93] ellipsis_0.3.2       here_1.0.1       
```   

Any help would be appreciated!

**Comment by michellegrushkometa** [comment]
Hey @emmag123! We are still working on cleaning robyn_run() and robyn_outputs() outputs to be more space efficient.

In the meantime, have you been able to try something like this https://stackoverflow.com/questions/51295402/r-on-macos-error-vector-memory-exhausted-limit-reached ?

In my past experience, I've also found that it helps to have a fresh R session, a clean environment (only containing the data you need to model) and limiting the number of applications that use a high CPU while the script is running. You can do this by going to your activity monitor and sorting by % CPU to see what applications you can quit. 

Let me know if that helps!

**Comment by emmag123** [comment]
Hi @michellegrushkometa! Thanks for your quick reply! 

Ok, I have tried something similar but will retry. I agree restarting Rstudio will help, however I don't want to lose the OutputModels variable as it ran for 20+ hours. Is there a good way to save the OutputModels prior to restarting Rstudio?

**Comment by michellegrushkometa** [comment]
@emmag123 yes! you can save your environment or individual files to your directory, see more info here: 
http://www.sthda.com/english/wiki/saving-data-into-r-data-format-rds-and-rdata

I would recommend only keeping what you need in the environment and removing anything that might be taking unnecessary space. You can do this by going to your environment tab, changing it to be a grid, selecting what you want to get rid of and then click the little broom to delete them. 

<img width="523" alt="Screenshot 2023-01-25 at 12 22 27 PM" src="https://user-images.githubusercontent.com/113440684/214635938-c2ca7ecf-4591-4ade-8007-8956c8ee2d31.png">
<img width="413" alt="Screenshot 2023-01-25 at 12 22 38 PM" src="https://user-images.githubusercontent.com/113440684/214635973-59f8c6a6-8745-4aee-b2dd-73eb9444e6e4.png">

**Comment by michellegrushkometa** [comment]
Hey @emmag123! 

That is a really big output! Given the memory you have on your computer, could you try adjusting your  `OutputModels` to have a smaller number of iterations and trials? You currently have 10k iterations and 15 trials, try it with the recommended 2000 iterations, and 5 trials and see how your computer is able to handle that size of the output.

`OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = NULL, # NULL defaults to max available - 1
  iterations = 10000, # 2000 recommended for the dummy dataset with no calibration
  trials = 15, # 5 recommended for the dummy dataset
  ts_validation = TRUE, # 3-way-split time series for NRMSE validation.
  add_penalty_factor = FALSE # Experimental feature. Use with caution.
)`

**Comment by michellegrushkometa** [comment]
Closing this ticket because we haven’t had any replies. Feel free to re-open if the issue persists.

Will be working on updating "OutputModels" to contain less information and help prevent memory issues for the future.
