### ISSUE TITLE
Unexpected error on model_output_collect <- f.robyn()

### ISSUE THREAD

**Issue by MiguelRER** [facebookexperimental/Robyn#61]
# Issue

When we try to execute the model, at the end of the first iteration we find the following error:

<img width="1136" alt="Captura de pantalla 2021-04-13 a las 17 07 04" src="https://user-images.githubusercontent.com/75400817/114741760-549ff380-9d08-11eb-8486-0f54d8704d2c.png">

Apparently the issue is on the class of the data we are trying to run, because the error says "x is not a data.table or data.frame" but we are not sure about that.

Looking forward on reading your comments.

# Environment

R 4.0.3

**Comment by gufengzhou** [comment]
are you using the simulated data? have you changed any setting?

**Comment by MiguelRER** [comment]
I'm running with my company data. I didn't any settings.

According to Facebook Office in Mexico, there is a new version of the code which we are testing at this moment. 

It looks like the new code is running fine.
