### ISSUE TITLE
Refreshing Data

### ISSUE THREAD

**Issue by laresbernardo** [facebookexperimental/Robyn#613]
### Discussed in https://github.com/facebookexperimental/Robyn/discussions/612

<div type='discussions-op-text'>

<sup>Originally posted by **KristiGourlay** January 26, 2023</sup>
Disclaimer: I'm a pythonista and my R is very basic.

I'm trying to refresh my model with 3 new weeks of data. I followed the demo and wrote:

```
RobynRefresh <- robyn_refresh(
  json_file = json_file,
  dt_input = refreshed_data,
  dt_holidays = dt_prophet_holidays,
  refresh_steps = 3, 
  refresh_iters = 1000, 
  refresh_trials = 3
)
```

Then I got an error for no object `refreshStart` detected and then for no object `refreshEnd` detected. So I updated to:

```
refreshStart <- '2023-01-08'
refreshEnd <- '2023-01-22'
units <- "weeks"

RobynRefresh <- robyn_refresh(
  json_file = json_file,
  dt_input = refreshed_data,
  dt_holidays = dt_prophet_holidays,
  refresh_steps = 3, 
  refresh_iters = 1000, 
  refresh_trials = 3
)

```
Now it runs. It successfully re-created my model 1_122_7. But then I get this:

```
>>> Building refresh model #1 in manual mode
>>> New bounds freedom: 100%
>> Running feature engineering...
NOTE: potential improvement on splitting channels for better exposure fitting. Threshold (Minimum R2) = 0.8 
  Check: InputCollect$plotNLSCollect outputs
  Weak relationship for: 'fbawareness_I', 'microsoft_I', 'mtv_I'and their spend
Input data has 264 weeks in total: 2018-01-07 to 2023-01-22
Refresh #1 model is built on rolling window of 3 week: 2018-01-28 to 2023-01-22
Rolling window moving forward: 3 weeks
Fitting time series with all available data...
Using geometric adstocking with 26 hyperparameters (25 to iterate + 1 fixed) on 9 cores
>>> Starting 3 trials with 1000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 3
  |                                                                                   |   0%Timing stopped at: 0.531 0.52 0.32
Error in { : 
  task 1 failed - "arguments imply differing number of rows: 12, 13"

```

What I have tried:
* Confirmed no null values.
* Confirmed dimensions of data (261, 23) and now (264, 23) </div>

**Comment by laresbernardo** [comment]
Hi @potatosalad thanks for reporting this and glad that being a pythonista you're starting to get the handle of R!
That said, can you please check your version and make sure you're running on the latest dev version?
Would it be possible for you to share your JSON file and dataset to help us debug your issue?
Thanks for reporting it; it def seems like a bug.

**Comment by potatosalad** [comment]
@laresbernardo I think you may have tagged the wrong person 🙂

**Comment by KristiGourlay** [comment]
@laresbernardo Thank you for the quick reply. The version I am using is 3.9.0

I can share those with you. How would you like me to send them? I cannot make the dataset public since it's my companies data.

**Comment by laresbernardo** [comment]
That's ok. Please, send them to bernardolares and amyhao @ meta.com. Amy will help us debug these couple of issues. Thanks for sharing it.

**Comment by KristiGourlay** [comment]
Perfect - thank you! It's sent.

**Comment by KristiGourlay** [comment]
Any update on this?  @laresbernardo @Amyhaoming

**Comment by Amyhaoming** [comment]
works on latest version
