### ISSUE TITLE
Meaning of coefficients in pareto_clusters.csv

### ISSUE THREAD

**Issue by Angylina** [facebookexperimental/Robyn#616]
## Describe issue
This is more of a question. Along with other csvs, we get pareto_clusters.csv as an output of robyn_outputs(). The main information we have there is which clusters the model belongs to, and which coefficients it has. 

My question is about those coefficients, specifically those attached to media channels. What do they mean? 

![Schermopname (57)](https://user-images.githubusercontent.com/120499663/216007320-84c67622-d0ff-4ad4-a447-ec4efc3188cb.png)

I tried looking into the code, but cannot seem to find it. Initially, it made sense to me that these would be the ROI's, since the clustering is done on them, but they don't match other ROI values we get from e.g., pareto_aggregated.csv. 

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: 3.9.0
- R version 4.2.2.

**Comment by laresbernardo** [comment]
Hi @Angylina thanks for asking! 
Given we need to normalize the data for us to correctly create the clusters with k-means, those values are the ROI/CPA for each channel but normalized to 0-1. We provide these normalized values given those were the ones used to clusterize. In the other files you'll be able to fetch the un-normalized ROI/CPA values.
