### ISSUE TITLE
Run error - clusterKmeans unused argument

### ISSUE THREAD

**Issue by kungfoolabs** [facebookexperimental/Robyn#617]
## Describe issue
Describe your issue and provide warnings and error messages.
Getting an error when I run the demo script (https://github.com/facebookexperimental/Robyn/tree/main/demo)
> Couldn't automatically create clusters: Error in clusterKmeans(df, k = NULL, limit = limit_clusters, ignore = ignore, : unused argument (dim_red = dim_red)

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.

Using Docker Desktop on Mac M1 Max using docker file from:
https://github.com/facebookexperimental/Robyn/tree/main/R/Docker

Demo script from:
https://github.com/facebookexperimental/Robyn/tree/main/demo

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)

> Robyn version
> 3.9.0

> R version 4.1.0 (2021-05-18)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.5 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

**Comment by laresbernardo** [comment]
Hi @kungfoolabs can you please check and share which version of `lares` package are you using? Was it an error or a warning?

**Comment by kungfoolabs** [comment]
@laresbernardo hey there, love how the package is named after you?! 

The package is 5.0.1

Only error that I got from lares was on the theme:

> In theme_lares(legend = "top") :
>   Font 'Arial Narrow' is not installed, has other name, or can't be found

**Comment by laresbernardo** [comment]
@kungfoolabs that's right, it's my package :) 

> The package is 5.0.1

Please, update to latest CRAN version ([5.1.4](https://cran.r-project.org/web/packages/lares/index.html)) or dev version ([5.2.0](https://github.com/laresbernardo/lares)) and this issue should be fixed given `clusterKmeans()` is a function from the lares package and that parameter was included about a year ago (your version [5.0.1](https://cran.r-project.org/src/contrib/Archive/lares/) is from 2021-06).

> Font 'Arial Narrow' is not installed, has other name, or can't be found

Given we use `theme_lares()` by default in our plots to have a standard style, we use "Arial Narrow" by default, and it checks once per session and warns the user if not found. Nothing to worry about.

**Comment by kungfoolabs** [comment]
Awesome. Ya, that worked! Thanks @laresbernardo 

I think it was the `rocker/verse` setup from the Dockerfile (https://github.com/facebookexperimental/Robyn/blob/main/R/Docker/Dockerfile)
was point to a CRAN snapshot so pulling the old version of `lares`. Just pulled from `remotes` and everything good now.
