### ISSUE TITLE
Interpretation of "tsd" in the Response decomposition waterfall  chart

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookexperimental/Robyn#62]
# Contributing to FB NextGen MMM R script

# Issue
Hi, 
I have a question related to the _Response decomposition waterfall by predictor chart_:
What does "tsd" stands for? How should I interpret it?

![image](https://user-images.githubusercontent.com/65649681/114838061-3e5b6b80-9dcc-11eb-9dcb-d788d192dbe5.png)

**context**: dependant variable is a "conversion"

**Comment by Leonelsentana** [comment]
Hey Leo! Nice to see you trying the code and speak again with you :)

I believe it is thousands, it's just an abbreviation. You may also encounter the word mio which is millions, if you ever work with greater numbers.

Hope it helps ;)

**Comment by LeoUbbiali** [comment]
Hey Leonel! 
Thanks for the fast reply. Howcome didn't I get it 😄 

Yes, I'm really enjoying working with this codebase. Keep up the good work 🙌
