### ISSUE TITLE
How to limit ROI values

### ISSUE THREAD

**Issue by ElijahHoff** [facebookexperimental/Robyn#624]
## Describe issue
I need to set a certain border conditions for ROI while modelling.
## Provide reproducible example
I use "constraints" parameter, but the output doesn't seem to take this into a count

```
OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = 8, # NULL defaults to max available - 1
  iterations = 4000, # 2000 recommended for the dummy dataset with no calibration
  trials = 5, # 5 recommended for the dummy dataset
  add_penalty_factor = TRUE, # Experimental feature. Use with caution.
  outputs = FALSE, # outputs = FALSE disables direct model output - 
  constraints = (ROI > 0.5 & ROI <= 20)
)
```

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version:  ‘3.8.2’
- R version 4.2.2 (2022-10-31)

**Comment by laresbernardo** [comment]
Hi @ElijahHoff 
This `constraints` parameter doesn't actually exist. Did you get that from another source/reference you can share with us? It's not something we have ever enabled in Robyn as you show.
That said, we kind of constrain (or at least try to minimize) extreme ROI by optimizing towards DECOMP.RSSD, which in other words represent the difference of the distribution of spending and response for every channel. If you want to be more strict on these high/low ROI you should pick from the range of models with lowest DECOMP.RSSD error.
I believe this `constraints` parameter is not an enhancement or feature request we will enable for the time being.
