### ISSUE TITLE
Calculating True Spend For Response Curve.

### ISSUE THREAD

**Issue by bowie-tey** [facebookexperimental/Robyn#628]
Project Robyn

My model is currently using weibull adstock to account for the lag effects of media spend. From my understanding, the X-axis of the response curve is media spend that's transformed by adstock. Is there anyway to reverse this transformation to get the true associated spend value ? Since decay rate varies over time on  weibull, will taking the average give a sufficient approximation ?

**Comment by gufengzhou** [comment]
why do you need to revert that? if you just need the transformed data, check out pareto_media_transform_matrix.csv

**Comment by laresbernardo** [comment]
Closing this task now. Feel free to reach back anytime.
