### ISSUE TITLE
ts_validation Dates

### ISSUE THREAD

**Issue by mtodisco10** [facebookexperimental/Robyn#630]
## Describe issue
When `ts_validation = TRUE` is there any easy way to get the dates included in the test, train, and validation splits?

**Comment by laresbernardo** [comment]
Hi @mtodisco10 
Once you have your results, you'll have a `train_size` value. Based on the code shown below, you could calculate it as follows:
https://github.com/facebookexperimental/Robyn/blob/619765dcd5e59dd4c12b532773c6c95ec96e0d1b/R/R/model.R#L654-L668
