### ISSUE TITLE
If intercept is not required (redirected from Facebook by Gufeng Zhou)

### ISSUE THREAD

**Issue by MaximSat** [facebookexperimental/Robyn#632]
# Theme: If intercept is not required

### Intro
Let's say my business works only with online advertising and with "one-page" landing pages. My revenue comes only from paid media. I have no SEO traffic, I have no recommendations. If I am not advertising - there would be no sales. I have tested it several times

### Problem
 From model to model, the intercept has ~30-50% on the Waterfall chart, but it is unsuitable in my case.

### My issue is
How can I refuse from the intercept (may be somewhere in robyn_inputs or robyn_run), to let Robyn reallocate the share of effects only on my paid_media? If there is no place to refuse, then, what logic should I follow to redistribute the intercept to media channels on my own?

 link to FB message https://www.facebook.com/groups/robynmmm/permalink/1388958841872245/

**Comment by laresbernardo** [comment]
Yours is a very specific case but it makes sense. We could implement a parameter on `robyn_inputs()` to help you get rid of the intercept. Adding this task to our backlog now and will keep you posted.

**Comment by MaximSat** [comment]
Thank you! I'm looking forward to this update!

**Comment by laresbernardo** [comment]
@MaximSat We've recently enabled the `intercept` parameter on `robyn_run()` which could be turned off by setting it to `FALSE`. Can you please test it out and see how it goes? Make sure to update to latest dev version first.

**Comment by MaximSat** [comment]
@laresbernardo Accepted. I will do it as soon as possible

**Comment by MaximSat** [comment]
@laresbernardo I've been testing this feature for some time. It seems cool. Haven't noticed anything strange. Thank you!

**Comment by laresbernardo** [comment]
Thanks for confirming. Closing this issue
