### ISSUE TITLE
Error in Robyn package installation

### ISSUE THREAD

**Issue by vincejuan** [facebookexperimental/Robyn#633]
## Describe issue
I'm trying to run the code from demo.R file but I'm having issues running line 19:
remotes::install_github("facebookexperimental/Robyn/R")

Was able to install the Robyn and remotes packages 
line 16: install.packages("Robyn")
line 18: install.packages("remotes")

Tried running the next line
line 19: remotes::install_github("facebookexperimental/Robyn/R")
and then selecting option 1 to update all packages but some dependencies were not able to get installed. To resolve this, I've tried running this line:
install.packages("doParallel(_uninstalled dependencies_)", repos="https://cran.rstudio.com/")
but still unsuccessful. Also tried setting-up rtools but this resulted to the same error .

## Provide reproducible example
This is the original block of code from demo.R:

install.packages("Robyn")
install.packages("remotes") 
remotes::install_github("facebookexperimental/Robyn/R")

##ERROR MESSAGE:
ERROR: dependencies 'doParallel', 'jsonlite', 'lubridate', 'minpack.lm', 'nloptr', 'prophet', 'rPref', 'tidyr' are not available for package 'Robyn'
* removing 'C:/Users/n0850/AppData/Local/R/win-library/4.2/Robyn'
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\n0850\AppData\Local\R\win-library\4.2\00LOCK\curl\libs\x64\curl.dll to C:\Users\n0850\AppData\Local\R\win-library\4.2\curl\libs\x64\curl.dll: Permission denied
2: In i.p(...) :
  installation of package ‘C:/Users/n0850/AppData/Local/Temp/RtmpYforiT/file46b815a56843/Robyn_3.9.1.9000.tar.gz’ had non-zero exit status

Running this code to install missing dependencies:
install.packages("doParallel", repos="https://cran.rstudio.com/")

##ERROR MESSAGE:
Installing package into ‘C:/Users/n0850/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘iterators’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/iterators_1.0.14.zip'
Warning in install.packages :
  downloaded length 0 != reported length 15247
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/iterators_1.0.14.zip?_sm_nck=1': HTTP status was '403 Forbidden'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/iterators_1.0.14.zip'
Warning in install.packages :
  download of package ‘iterators’ failed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/doParallel_1.0.17.zip'
Warning in install.packages :
  downloaded length 0 != reported length 15251
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/doParallel_1.0.17.zip?_sm_nck=1': HTTP status was '403 Forbidden'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/doParallel_1.0.17.zip'
Warning in install.packages :
  download of package ‘doParallel’ failed

## Environment & Robyn version
Currently using R v4.2.2 with RStudio RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

Device Specs: Lenovo ThinkPad L14 Gen 3 8GB   512SSD INTEL CORE i5-1235U 1.30GHz Win10 Pro

**Comment by laresbernardo** [comment]
This seems to be a connection issue with CRAN. Try later and see if it gets fixed by itself.
