### ISSUE TITLE
ERROR: robyn_outputs() - "Error in summary.connection(connection) : invalid connection" + no one-pagers

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#637]
## Describe issue
After running robyn_outputs, only 1 out of 4 onepagers was created in the output folder. When running robyn_outputs again, I get the following error message:

_Error in summary.connection(connection) : invalid connection_

Here is the traceback of the error message:
![image](https://user-images.githubusercontent.com/118725564/222112681-601b7b5d-4d57-4b84-b259-efa2670884a0.png)

## Environment & Robyn version
![image](https://user-images.githubusercontent.com/118725564/222112981-ef700d81-ce3e-455f-bbdd-75d8092de46c.png)

**Comment by laresbernardo** [comment]
Hi @bart-vanvlerken can you please try in a fresh new R session? Usually it's a memory issue that gets fixed by itself. The issue on the one-pagers not being created is weirder and I'm not sure how to replicate it on my end.

**Comment by bart-vanvlerken** [comment]
For some reason, when I start a new R session, OutputModels is not ported over to the new environment (all other data/variables are). So when I start a new R session, I can't run robyn_outputs() unless I re-run the robyn_run().

**Comment by bart-vanvlerken** [comment]
UPDATE: I decreased the amount of trials from 5 down to 1, and robyn_outputs() now exports all pareto-optimal models! Also, re-running robyn_outputs() does not lead to the 'invalid connection' error, nor does generating a single onepager using robyn_onepagers(). Decreasing the amount of trials isn't a great solution, but hopefully it can give you a better idea of what causes the problem.

**Comment by laresbernardo** [comment]
This must be a memory issue. Did you try with 2 trials? 3? I guess you reached a limit and that's the reason it crashes. FYI: we are currently studying how we can reduce the size of `robyn_run()` and `robyn_outputs()` outputs so users can run more iterations without having memory issues.

**Comment by bart-vanvlerken** [comment]
UPDATE: two trials produced onepagers (both in robyn_outputs() as well as robyn_onepagers(). Three trials produced onepagers only in robyn_outputs() for some reason. I suspect 4 trials will not produce any onepagers. My models are based on a rolling window (= input data) of 281 weeks, optimizing 110 hyperparameters.

**Comment by laresbernardo** [comment]
Yes, it's definetly a memory issue you're having. 110 hyperparameters sounds like a lot. How many iterations per trial are you running? There's no immediate solution other than trying to run your iterations in another computer with higher specs or less iterations or less trials (depending on your convergence).

**Comment by bart-vanvlerken** [comment]
110 hyperparameters is a lot indeed, but we wanted to start as granular as possible with the channels before deciding on which to aggregate. For now we ran 2000 iterations per trial, but I am aware that I will probably need more given the amount of hyperparameters included. How much more is still something I'm wondering about - is there a good rule of thumb?

My laptop has 16gb of RAM so it's fairly decent, getting a laptop with better specs is out of the question I'm afraid. Are you aware of any instances of Robyn using cloud computing? That might be a solution.

**Comment by laresbernardo** [comment]
Yes, there are users running Robyn in cloud instances. You could try that and see how it goes. You could also start top to bottom, with less granular variables and see how it goes. Not always less granular is necessarily better, especially when each channel represent <5% of your spend (rule of thumb). 

Regarding how many iterations, I tend to look at the criteria we use for convergence, especially giving more importance to NRMSE than to DECOMP.RSSD. I also see the MOO cloud to see if the solutions are kind of not getting any better and also the TS validation plot (when being used).

**Comment by bart-vanvlerken** [comment]
Thanks for all the help and feedback! I was always under the impression that there was no such thing as 'too much channel granularity' in MMM, especially if there is enough data to allow for it. If I'm not mistaken, the size of OutputModels is a function of trials, iterations, observations in rolling window, and number of hyperparameters (or number of organic/spend channels) yes?

Since my laptop is not powerful enough for greater iterations/trials anymore, so I'm curious how many of Robyn's users have started using cloud solutions (open question to the community). I get the idea that most users run Robyn locally, but I also think that more and more users will start experiencing similar memory problems. This is not a criticism of Robyn by any means.

**Comment by AGMortimer** [comment]
Hello both, I was also having this issue yesterday and managed to get around it, though not in a way I would like.
I'm running on 32GB but still couldn't get more than one, one-pager out before it hit memory issues and aborted (Error in summary.connection(connection)).
I was using four organic contextual variables which I removed. This lowered the size of the OutputModels from ~ 2.4GB to 1.6GB which then allowed the programme to run and export all the one-pagers.

Not an ideal situation, I will be spinning up an AWS server to run these on moving forwards to avoid this.

This is using daily data over three years. I appreciate I could use weekly data over two years, but I'd rather have the granularity.
A few more points:
- 110 pareto_hyperparameters (I am assuming this is what you're referring to @bart-vanvlerken)
- 2 paid media impressions and their respective spends
- 3 year's worth of daily data for these, plus revenue
- Originally had three organic contextual vars but removed these to get it to work

Thanks!

**Comment by bart-vanvlerken** [comment]
UPDATE: I think I found a fix! I set OutputModels$cores <- 1, which fixed the memory use issue. Mind that OutputModels was significantly larger than before (4.5 GB) and it worked fine! All of the output has generated successfully: the CSVs, the onepagers and all other plots. I'm not sure why this works, but I hope others with the same problem will find solution helpful.

**Comment by laresbernardo** [comment]
Thanks for sharing @bart-vanvlerken 
That's because you're "turning off" the parallel computing by setting 1 core and they have different computing behaviours. What happens if you set it to 2 cores?

**Comment by bart-vanvlerken** [comment]
I set it to 2 cores, and it 1) took significantly longer, 2) used a lot more memory, and 3) only printed 2 out of the 17 onepagers. It exported the CSVs and other plots fine though.
