### ISSUE TITLE
Error on AWS EC2

### ISSUE THREAD

**Issue by chandra692** [facebookexperimental/Robyn#64]
# All Socket Connections are in use
# Issue
 I've created an EC2 instance with 8 cores and 32GB RAM. I've also installed all the required packages and Anaconda3 etc..
I've also assigned 6 cores for set cores. When I run the model(below one) it's throwing below error. Tried lot of things from all the side.

model_output_collect <- f.robyn(set_hyperBoundLocal
                                ,optimizer_name = set_hyperOptimAlgo
                                ,set_trial = set_trial
                                ,set_cores = set_cores
                                ,plot_folder = "") 

Error:

r in socketAccept(socket = socket, blocking = TRUE, open = "a+b",  : 
  all connections are in use

**Comment by gufengzhou** [comment]
Hey thanks for flagging this. It's the first time we're dealing with EC2 bugs to be honest. First of all, is it running well locally? For parallel on EC2, maybe this helps? https://win-vector.com/2016/01/22/running-r-jobs-quickly-on-many-machines/
