### ISSUE TITLE
New Budget Allocator function produces output in old format

### ISSUE THREAD

**Issue by ksorger** [facebookexperimental/Robyn#642]
## Describe issue
Hi there, 

When running the new allocator function am receiving the output in the old format.
My model is not using TS validation might that be the reason?
NRMSE of the model converged but not DECOMP.RSSD

I also created the model under Robynv3.9 last week and reiinitiated the model using the Robyn_recreate() function after installing the update.

## Provide reproducible example
```
AllocatorCollect2 <- robyn_allocator(
  InputCollect = InputCollectX,
  OutputCollect = OutputCollectX,
  select_model = select_model,
  date_range = "last_30", # When NULL, will set last month (30 days, 4 weeks, or 1 month)
  total_budget = 500000, # When NULL, use total spend of date_range
  scenario = "max_historical_response",
  channel_constr_low = 0.1,
  channel_constr_up = 2,
  channel_constr_multiplier = 5,
  export = TRUE
  #expected_spend = 850000, # Total spend to be simulated
  #expected_spend_days = 31 # Duration of expected_spend in days
)
```
Any help would be much appreciated!

## Environment & Robyn version
Robyn.v10

**Comment by laresbernardo** [comment]
Hi! Please refresh your session (close and open without saving cache) and run everything again. The `robyn_allocator()` will work as intended once you do (no way it can return the previous outputs).

**Comment by ksorger** [comment]
the good old refresh worked :)
