### ISSUE TITLE
Response Cruves Mean Spends Are Changing For each Model

### ISSUE THREAD

**Issue by MustafaCelen** [facebookexperimental/Robyn#643]
I have been trying 3.10, when I train and evaluate the results, which gave me 6 clusters, each model shows different mean spends on the same media channel on the response curves, I put 2 of the models and even though it is not really visible it is there, how is it possible to have different mean spends ? Or am I missing something. Also new response cureves are definetly not readable , it was not even readable before now it is just impossible with those areas...

![image](https://user-images.githubusercontent.com/10905725/223420346-c282c61b-91dc-459e-b983-dababdf70431.png)

![image](https://user-images.githubusercontent.com/10905725/223420570-02d08f20-e7cc-4891-b96f-0c6bbc3fc1ad.png)

**Comment by laresbernardo** [comment]
Hi @MustafaCelen 
Mean spend looks the same, mean response is different which is desired. 
The issue with the areas under the curves happened to me when I built the OutputModels and OutputCollect objects (based on the demo object names), then updated, and recreated those one-pagers. Can you make sure you build those `robyn_run()` and `robyn_outputs()`, both, with v3.10?

**Comment by MustafaCelen** [comment]
I retrain my model just to avoid such issues, so i am sure that both robyn_run() and robyn_outputs() with 3.10 ... In the response curves , the number I see on the curves are the mean spends right, in the above model i see the media channel imaj_rated_tv_cost is 134K and in the below model I see 94.7 K, is it because of the different adstock effects between models. Thank you for your quick response btw.

**Comment by laresbernardo** [comment]
Ah that's because the mean spends are adstocked and adstock depends on hyperparameters and those change for every model (because are the values we are playing with to minimize the errors).

And yes, with the new models, when exporten into the JSON files, contain information regarding adstock that the old models didn't have, that's why those plots look like that with weird areas under the curves.

**Comment by MustafaCelen** [comment]
Thanks @laresbernardo
