### ISSUE TITLE
Invalid 'media_metric' input. When running robyn_response

### ISSUE THREAD

**Issue by arturodz** [facebookexperimental/Robyn#647]
## Describe issue
I am trying to run robyn_response to identify the incremental response from a specific media channel. When I do I get this error:

```
Response2 <- robyn_response(
  json_file = "RobynModel-2_172_8.json",
  dt_input = data,
  dt_holidays = holidays,
  metric_name = "ms_groovin",
  metric_value = Spend1,
  metric_ds = NULL
)
```

This is what I get after I run it.

```
Imported JSON file succesfully: RobynModel-2_172_8.json
>> Running feature engineering...
NOTE: potential improvement on splitting channels for better exposure fitting. Threshold (Minimum R2) = 0.8 
  Check: InputCollect$plotNLSCollect outputs
  Weak relationship for: 'impr_fb_inst', 'imp_fb_ecom', 'impr_google_nonbrand', 'impr_google_shopping', 'impr_dv'and their spend
>>> One Hot Encoding applied to 12 variables: 'XXXXXX', 'XXXXXX', 'XXXXXX', 'XXXXX', 'XXXXXX', 'XXXXXX', 'XXXXXX', 'XXXXX', 'XXXXXX', 'XXXXXX', 'XXXXX', 'XXXXX'
Input data has 1492 days in total: 2019-01-01 to 2023-01-31
Initial model is built on rolling window of 1127 day: 2020-01-01 to 2023-01-31
Successfully recreated model ID: 2_172_8
Error in robyn_response(json_file = "RobynModel-2_172_8.json",  : 
  Invalid 'media_metric' input. It must be any media variable from paid_media_spends (spend), paid_media_vars (exposure), or organic_vars (organic); NOT:  
- paid_media_spends: tv_abierta, tv_paga, radio, ms_fb_inst, ms_fb_ecom, ms_google_nonbrand, ms_google_shopping, ms_google_video2, ms_groovin, ms_dv 
- paid_media_vars: tv_abierta, tv_paga, radio, impr_fb_inst, imp_fb_ecom, impr_google_nonbrand, impr_google_shopping, impr_google_video2, imp_groovin, impr_dv 
- organic_vars: mail_sesiones
```
I've obfuscated certain variables to maintain client confidentiality.

I continue to get the same error no matter what variable I use. I also continue to get the same error if I run robyn_response with Input/Output Collect or from the Json.

## Environment & Robyn version
Robyn Version "3.9.0"
R "4.4.2"

Thanks for the help

**Comment by laresbernardo** [comment]
Hi @arturodz nice hearing from you!

First, I'd recommend using the arguments InputCollect, OutputCollect, and select_model instead of the json file so that you don't have to recreate the model every time, but just once. You can recreate those with:
```
RobynRecreated <- robyn_recreate(
  json_file = json_file,
  dt_input = data,
  dt_holidays = holidays,
  quiet = FALSE)
InputCollect <- RobynRecreated$InputCollect
OutputCollect <- RobynRecreated$OutputCollect
```

That said, you should be able to run the response calculations with:
```
temp <- robyn_response(
  InputCollect = InputCollect,
  OutputCollect = OutputCollect,
  # select_model = select_model, # If there's only one model, no need to define
  metric_name = "ms_groovin",
  metric_value = 10000, # making sure you have a number here
  metric_ds = NULL # will take last date by default
)

Can you try that? I've just tested on my end and works OK. Make sure you're actually using the right InputCollect and OutputCollect that contains "ms_groovin" information.

**Comment by arturodz** [comment]
Hi @laresbernardo !

So, thanks for the recreated tip. That worked well.

I'm still having issues with Robyn_response though.

After declaring the input/output variables:

```
InputCollectX <- RobynRecreated$InputCollect
OutputCollectX <- RobynRecreated$OutputCollect
```

I ran

```
Response2 <- robyn_response(
  InputCollect = InputCollectX,
  OutputCollect = OutputCollectX,
  # select_model = select_model,
  metric_name = "ms_groovin",
  metric_value = "37878",
  metric_ds = NULL
)
```

But still no success.

Here is the first part of my inputcollectx, as you can see, the ms_groovin variable is there.
```
> InputCollectX
Total Observations: 1492 (days)
Input Table Columns (49):
  Date: fecha
  Dependent: venta_analytics [revenue]
  Paid Media: tv_abierta, tv_paga, radio, impr_fb_inst, imp_fb_ecom, impr_google_nonbrand, impr_google_shopping, impr_google_video2, imp_groovin, impr_dv
  Paid Media Spend: tv_abierta, tv_paga, radio, ms_fb_inst, ms_fb_ecom, ms_google_nonbrand, ms_google_shopping, ms_google_video2, ms_groovin, ms_dv
```

I also checked the outputcollectx, and the ms_groovin variable is there too... Btw, same thing if I test other paid media vars.

**Comment by laresbernardo** [comment]
Hey @arturodz I can't seem to be able to replicate your issue on my end. Can you please share a reproducible example? Easiest way would be sharing your JSON file and data. You can shuffle your data a bit and change some channels names to anonymize your dataset.

One last observation: you should have gotten the following error though:   Input 'metric_value' for paid_var9_cost (37878) must be a numerical value.

**Comment by arturodz** [comment]
I’ll give that a try and get back to you. Thanks!

**Comment by laresbernardo** [comment]
Better so if you get v2.10.0 update or simply latest dev version by removing that `ref` parameter.

**Comment by laresbernardo** [comment]
> v3.10.0?

https://github.com/facebookexperimental/Robyn/releases/tag/v3.10.0

**Comment by laresbernardo** [comment]
Ha, yes, good one! Updated. Have a nice weekend and thanks for your comment @rocker-david :)

**Comment by arturodz** [comment]
😛

**Comment by arturodz** [comment]
> Hey @arturodz I can't seem to be able to replicate your issue on my end. Can you please share a reproducible example? Easiest way would be sharing your JSON file and data. You can shuffle your data a bit and change some channels names to anonymize your dataset.
> 
> One last observation: you should have gotten the following error though: Input 'metric_value' for paid_var9_cost (37878) must be a numerical value.

@laresbernardo still getting the same error, I'll work on anonymizing the data before I send it on this public forum. Actually, do you mind if I send it to you by email?

**Comment by laresbernardo** [comment]
Yes, send it to my email. Thanks

**Comment by banalytics** [comment]
I ran into the same issue, curious to see what the outcome is.

**Comment by laresbernardo** [comment]
Received the data to reproduce this error but ran OK on my end. Will report again once we can figure it out. Meanwhile, feel free to share a reproducible example @banalytics

**Comment by navneetsonak-ds** [comment]
I was having the same issue. it worked for me when changed parameter 'metric_name' to 'media_metric'.

Response2 <- robyn_response(
  json_file = "RobynModel-2_172_8.json",
  dt_input = data,
  dt_holidays = holidays,
  **media_metric** = "ms_groovin",
  metric_value = Spend1,
  metric_ds = NULL
)
