### ISSUE TITLE
robyn_recreate function Error in UseMethod("select")

### ISSUE THREAD

**Issue by firatfrkn** [facebookexperimental/Robyn#650]
I am running dev version. It is the first time I am using recreate function after the update and received this error. (I used recreate function before the update many times.) I am not sure whether the problem is on my end. I can provide anonymized data. 

![Screenshot 2023-03-14 094919](https://user-images.githubusercontent.com/96492785/224918634-6b1f9bf2-f720-4dc3-a62f-2fef3e71d7dc.png)

**Comment by laresbernardo** [comment]
Hi @firatfrkn thanks for reporting. Can you please share the reproducible example so we can replicate and check what's happening? Probably you're recreating an older Robyn model with a newer Robyn version.

**Comment by firatfrkn** [comment]
Hi @laresbernardo! Thanks for your quick response. I have sent the anonymized data to your gmail. Actually, I am receiving this error when I try to recreate the  models built after the update.

**Comment by laresbernardo** [comment]
Hi! Sorry, I can't replicate the issue without the JSON file and data you used. It's probably a compatibility of versions issue. I'd recommend you re-create the model from scratch, recreate your JSON file and that way you will be able to re-create the model.

**Comment by firatfrkn** [comment]
I have sent you the data and the script as you have asked. Can you check your email

**Comment by laresbernardo** [comment]
I only received the script with no data.

**Comment by firatfrkn** [comment]
@laresbernardo It would be nice if you ask me first before closed the unsolved issue. I am sending 3rd time the data both to your corporate and gmail addresses. Besides, since when does the Robyn team requires Jsonfile which contains highly confidential data of  our clients ? 4 mo ago I found another bug and solve dthe issue with @gufengzhou "by sending only the anonymized data.

**Comment by laresbernardo** [comment]
You're recreating a model here; I can't recreate a model if I don't have either the values you input when building the model or the script. The JSON file contains all the information needed to replicate a model (with the data) and to debug (Robyn's version for example). I don't need your data per se, just need to replicate the issue. And I wouldn't need any of this if I'd be able to replicate it on my end, which I couldn't. 

I quote your email:

> Currently, I am **not able to send the json file** since it is not anonymous. The script is attached. The select_model val, json_file before recreate function I intentionally left blanc here, but in my original script I  assigned those. 

Given you can't (and didn't) share the JSON file nor the data, I couldn't replicate your issue, thus I closed the ticket. No need to get offended. We still have the log if another user might expect the same issue.

That said, in your latest email, I've received the data.. will check it out.

**Comment by firatfrkn** [comment]
@laresbernardo not offended but rather surprised as it was closed suddenly. I should have attached the files on the same email, that's on my end. Thanks for reopening and for your time

**Comment by laresbernardo** [comment]
I wasn't able to replicate this issue. I ran the model as shared (with only 1 trial and 1000 iterations), exported one random model as JSON, and then replicated the model successfully:

```
> json_file <- "Robyn_202303141651_init/RobynModel-1_11_3.json"
> RobynRecreated <- robyn_recreate(
+     json_file = json_file,
+     dt_input = data,
+     quiet = FALSE)
>>> Recreating model 1_11_3
Imported JSON file succesfully: Robyn_202303141651_init/RobynModel-1_11_3.json
>> Running feature engineering...
NOTE: potential improvement on splitting channels for better exposure fitting. Threshold (Minimum R2) = 0.8 
  Check: InputCollect$plotNLSCollect outputs
  Weak relationship for: 'IV7_Impressions'and their spend
>>> One Hot Encoding applied to 2 variables: 'Campaign1', 'Campaign2'
n.changepoints greater than number of observations. Using 18
Input data has 24 weeks in total: 2022-02-14 to 2022-07-25
Initial model is built on rolling window of 24 week: 2022-02-14 to 2022-07-25
>>> Calculating response curves for all models' variables (9)...
Successfully recreated model ID: 1_11_3
Warning message:
In check_datadim(dt_input, all_ind_vars, rel = 10) :
  There are 13 independent variables & 24 data points. We recommend row:column ratio of 10 to 1
```

I suggest you re-create the JSON file with your latest Robyn version and retry.

**Comment by firatfrkn** [comment]
alright, will try. thanks for your time

**Comment by firatfrkn** [comment]
On my end, it is solved. I have uninstalled and reinstalled vctrs, tidyverse and dplyr. It worked somehow.
