### ISSUE TITLE
Error in signif(nevergrad_hp_val[[co]][index], 6) when running robyn_run()

### ISSUE THREAD

**Issue by merlin95555** [facebookexperimental/Robyn#653]
Input data has 208 weeks in total: 2015-11-23 to 2019-11-11
Initial model is built on rolling window of 163 week: 2015-11-23 to 2018-12-31
Fitting time series with all available data...
Using geometric adstocking with 17 hyperparameters (16 to iterate + 1 fixed) on 1 core (Windows fallback)
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
  |                                                                                         |   0%Cronometro fermo a: 0 0 0
Error in signif(nevergrad_hp_val[[co]][index], 6) : 
  non-numeric argument to mathematical function
In addition: Warning message:
In hyper_collector(InputCollect, hyper_in = InputCollect$hyperparameters,  :
  Provided train_size but ts_validation = FALSE. Time series validation inactive.

**Comment by laresbernardo** [comment]
Closing this task now. Feel free to reach back anytime.
