### ISSUE TITLE
How to consider impressions

### ISSUE THREAD

**Issue by AlessioPallotti** [facebookexperimental/Robyn#656]
## Describe issue
What does it mean in the model when you put the same variable twice when you have no impressions? What happen? Is there still a way to consider impressions in the model or does it work only through spendings?

Thanks

**Comment by laresbernardo** [comment]
Hi @AlessioPallotti the modeling only works through spending. The exposure metrics (impressions) are only used to analyze the relationship between exposure and spend and, when the relationship is poor, recommend the user if possible to provide more segmented spend values if that specific channel can be disaggregated. Let's say Facebook spend be split into Facebook Brand and Facebook Performance, or different optimization objectives...

Taken from the documentation:

> paid_media_vars: Recommended to use exposure level metrics (impressions, clicks, GRP etc) other than spend. Also recommended to split media channel into sub-channels (e.g. fb_retargeting, fb_prospecting, etc.) to gain more variance. paid_media_vars only accepts numerical variable.

**Comment by AlessioPallotti** [comment]
Thank you for your answer! So, apart from possibly providing more segmented spend values, aren't the impressions used to improve the models?

**Comment by laresbernardo** [comment]
Correct, we don't use impressions for modeling. We took this decision especially because for budget optimization we don't have to transform exposure metrics nor add more noise to the modeling, but have a direct spend optimization.

**Comment by AlessioPallotti** [comment]
Thank You! But I don't understand why if we consider the feature Facebook_I (impressions), it is still present in the output as if it were in the model. So the same reasoning also applies to clicks?
Also, is it possible to have more information about the Michaelis-Menten function? Specifically how the model is applied and what it consists of.
Lastly, please, do you have a dataset available in which there is a negative (and not positive) effect of competitors' spending? Or if you at least know where to find similar datasets.

Thank you very much!

**Comment by AlessioPallotti** [comment]
Thanks a lot for your answers!
But going back to the Michaelis-Menten mic_men() function, where is it applied then and what is it actually used for? From the documentation it is not possible to understand why it is applied and what is the use of the result

**Comment by gufengzhou** [comment]
It fits spend to imp (or clicks , GRP etc if any) once before modelling and derives a nonlinear relationship between the two. We used to use exposure metrics to fit the model. The problem is that the fit between spend & exposure is often very bad, so that the budget allocation in the end is off. It's a trade off between having cost efficiency vs allocation accuracy. We choose the latter. Nevertheless we'll improve it if there's a better way.

**Comment by AlessioPallotti** [comment]
Thank you ! And is it possible to make the budget allocation not for the future but for the past? (meaning on a date prior to the last available date of my dataset)

**Comment by laresbernardo** [comment]
The budget allocator, as it is now, only works for past scenarios (using `date_range` input, you can customize the date range).

**Comment by AlessioPallotti** [comment]
Thank you! But is it now possible to make predictions?
