### ISSUE TITLE
Prophet Trend Decomposition

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#657]
Hi everyone, I have a question regarding the trend decomposition of Prophet. In the plot below you can find the Prophet decomposition of trend, seasonality, weekday (I'm using daily data), Prophet holidays and black friday (a context variable I specified as a factor). For all of these variables, I can see how together they lead to my dep_var. Except for trend. How can Prophet gather a trend of around 28k when the average revenue is around 8k?

**Comment by gufengzhou** [comment]
where are you getting these numbers? and are these all your predictors?

**Comment by bart-vanvlerken** [comment]
I got this data from dt_mod after running robyn_inputs. These are not all my predictors, just the ones included in the prophet decomposition (dep_var, trend, season, weekday, holiday and black friday - a context variable specified as a factor)

**Comment by gufengzhou** [comment]
dt_mod is model input. you should look at the output for decomposition / contribution, like OutputCollect$xDecompVecCollect

**Comment by bart-vanvlerken** [comment]
But I'm not looking for output, I'm trying to understand the input data. I'm still puzzled by the trend that Prophet extracted from my data.

**Comment by gufengzhou** [comment]
You can easily verify this by doing a simple simulation. Like the below. The beta for v2 is exactly 10x of that for v3. In other words, if trend is larger, beta will become smaller, because the correlation doesn't change.
```
v1 <- seq(50, 60, length.out = 100) + rnorm(100, 10, 1)
v2 <- seq(20, 30, length.out = 100) + rnorm(100, 15, 1)
lm(v1 ~ v2, data.frame(v1=v1, v2=v2))

v3 <- v2*10
lm(v1 ~ v3, data.frame(v1=v1, v3=v3))
```

**Comment by bart-vanvlerken** [comment]
Right okay, thanks for clearing that up!
