### ISSUE TITLE
Use Custom Seasonality Instead of Prophet

### ISSUE THREAD

**Issue by bowie-tey** [facebookexperimental/Robyn#658]
Hi Robyn Community, 

I currently have a dataset that is fairly sporadic, i.e. the company only sells in certain periods of the month. The industry releases a general trend report for the entire sectors performance each year. So i am curious, is there a way to disable Prophet and use the trend data released inplace of prophet ?

**Comment by laresbernardo** [comment]
Hi @bowie-tey You can turn prophet functionality off by setting `robyn_inputs(..., prophet_vars = NULL)`

**Comment by laresbernardo** [comment]
Closing this task now. Feel free to reach back anytime.
