### ISSUE TITLE
How do I export plots that show up in one pager output individually in separate files? 

### ISSUE THREAD

**Issue by CJ2407** [facebookexperimental/Robyn#665]
For e.g. how do I get just the "Response Decomposition Waterfall" chart exported? 

Idea is to format different charts to be bigger so that I can read the charts in case of many variables in the model.

**Comment by CJ2407** [comment]
Hi @laresbernardo ! Thanks, but I ran the exact code you gave above with just my model's ID and when I run the myplots%patches$plots line I get NULL. I think I am missing something. Where will get plots separated out for the chosen model? Will it be in the same folder where all the one_pagers and CSVs were generated or they will be available locally in R studio?

**Comment by laresbernardo** [comment]
Just added to the demo.R file as a reference:

```
# Pick any available model ID
select_model <- "1_2_3"

# To plot model's one-pager:
myOnePager <- robyn_onepagers(InputCollect, OutputCollect, select_model, export = FALSE)

# To check each of the one-pager's plots
myOnePager[[select_model]]$patches$plots[[1]]
myOnePager[[select_model]]$patches$plots[[2]]
myOnePager[[select_model]]$patches$plots[[3]] 
# ...
```

**Comment by CJ2407** [comment]
@laresbernardo . Thanks, but I just ran this on R console - 
![image](https://user-images.githubusercontent.com/91983160/228372649-dc6ad1e5-ec60-4b39-a9ca-7ee88476e8c2.png)

It seemed to have run, but I don't see any plot anywhere.. neither in R studio nor in the folder where I am getting CSVs etc. exported. Sorry, but I am confused as to where it's going.

**Comment by laresbernardo** [comment]
This is a basic R / RStudio question unrelated to Robyn. But, usually when you run a plot function you'll be able to visualize the plot in the Files/Plots panel. Note that the parameter `export` is set to FALSE. That means you're only creating the R object (list) without creating the PNG file. You can change that and the file will be create where you set to files be created; to check where that is, print `OutputCollect$plot_folder`.

**Comment by CJ2407** [comment]
Hey @laresbernardo, Thanks for all the help and I was able to figure out the last bit of plotting code. 

For anyone, who doesn't use RStudio frequently and has trouble figuring out this last bit of getting individual plots out of the one_pagers, please follow the below code - 

# Pick any available model ID
select_model <- "1_101_4"

# To plot model's one-pager:
mymodel <- robyn_onepagers(InputCollect, OutputCollect, select_model, export = TRUE)

# To check each of the one-pager's plots
setwd("wherever/you/want/the/plots/to/go") 

jpeg("plotname.jpeg")

mymodel$`1_101_4`$patches$plots[[4]]

dev.off()

**Comment by laresbernardo** [comment]
I see what you mean. You can actually use `ggplot2` directly to export the plot as well:

```
myplot <- mymodel$`1_101_4`$patches$plots[[4]]
ggplot2::ggsave(myplot, "plotname.png")
```

And, as you mention, you can use `setwd()` to set a working directory to export plots to and `getwd()` to see where you're currently standing (and plots will be exported to).
