### ISSUE TITLE
Constrain betas of prophet variables

### ISSUE THREAD

**Issue by dmacoritto** [facebookexperimental/Robyn#666]
Hello,

Following a discussion with @gufengzhou on Facebook, we agreed on creating a ticket to propose an improvement to Robyn. Here is the post I did on Facebook a few days ago:

_"My main issue is related to the baseline and more specifically to the trend which comes out of the Prophet. I believe the trend estimation which comes out of the prophet process is good. No issues with that. The problem comes when inserting the trend in the ridge regression. According to Robyn's documentation, the trend (and the seasonality) get a beta. The fact that the trend gets a beta is fine in my view, but I believe it should be constrained. From my point of view, I do not see any situation where it makes sense for the beta of the trend to be lower than zero (this case is already taken care of in the current package) or greater than 1. So for me, the trend should be constrained within [0,1]. I understand the trend can "absorb" some credit of the marketing, and should therefore be decreased by assigning it a beta lower than 1, but I do not identify any case where it should be greater than 1. I believe the same reasoning applies to the seasonalities betas. If not constrained in that range, it seems to me that very unrealistic outputs can come out."_

The original post is there: _https://www.facebook.com/groups/robynmmm/permalink/1404910073610455/_

I believe you should add an option to constrain the betas for all the prophet variables between 0 and 1. That would improve the results by ruling out unrealistic cases.

**Comment by gufengzhou** [comment]
Can you try setting intercept_sign = „unconstrained“ in robyn_run() and see if the negative trend still occurs?

**Comment by dmacoritto** [comment]
Hello, yes I tried and it does remain negative.

**Comment by gufengzhou** [comment]
Hey, I've implemented in a branch, can you test it and share some before/after info with me please? I mostly agree with you, but would like to see bit more evidence. Thanks! 

You can install it via: `remotes::install_github("facebookexperimental/Robyn/R", ref = "prophet_vars_coef_constrains-#666")`

**Comment by gufengzhou** [comment]
@dmacoritto  can you please feedback on this?

**Comment by dmacoritto** [comment]
@gufengzhou, I have been doing some tests and I find the results more reliable (even though I can't replicate the exact results from the siMMMulator with Robyn). For me, it makes much more sense not to get a negative trend.

Nonetheless, I can see a small improvement in the package to make it still more correct. In the image below, as you can see, all the baseline is absorbed by the trend. As a consequence, almost nothing is attributed to the intercept. I know this is not correct as in my made-up data, the intercept is much bigger than the trend. When looking at the trend in the output plots, I se that the trend starts at 550K (which implicitly implies the intercept is 550K). So basically what would make more sense to me would be to decompose the current trend into the trend and the intercept.

This point is not so key as it does not fundamentally influences the betas for the marketing channels (what is interesting for us), whereas constraining the betas for the prophets betas does. Therefore, I think it is a good improvement.

![image](https://user-images.githubusercontent.com/64702803/234511488-f0713a9d-ed13-4f4f-84f9-588cf6f6483c.png)
![image](https://user-images.githubusercontent.com/64702803/234559906-887ac212-46c9-407c-a8ae-07934c8798b0.png)

I will make a few more tests to see if I see any other issue.

**Comment by gufengzhou** [comment]
This is interesting. I agree that trend has absorbed intercept that is a result from using prophet. I'm ok with that because their interpretations are very similar in MMM. 

I also agree with you that there should be no cases where any prophet_vars get coef >1 or <0, because the signs of coefs are actually already assigned by prophet, so Robyn only need to follow that. Moreover, the magnitudes of the prophet_vars effects are estimated by prophet to the upper bound, because they're estimated without the media regressors. This means there's no need to assign even more credit to any prophet_vars. 

The 0-1 constraint for prophet coefs is a very smart solution. Thanks for suggesting it and testing it out! I feel confident to land this feature. 

@laresbernardo FYI
