### ISSUE TITLE
channel_constr_up not working in robyn_allocator function with "target_efficiency" scenario

### ISSUE THREAD

**Issue by tingwei-lin** [facebookexperimental/Robyn#667]
## Describe issue
channel_constr_up not working in robyn_allocator function with "target_efficiency" scenario

## Provide reproducible example
Below is the code I ran for budget allocator. The channel_constr_up doesn't seem to work since the channel I put 1.25 down for constraints still has an over 90% delta between initial spend and optimized spend, for example.

```
AllocatorCollect <- robyn_allocator( 
  InputCollect = InputCollect,   
  OutputCollect = OutputCollect,   
  select_model = select_model,   
  channel_constr_up = c(1.15, 1.25, 1.25, 1.15, 1.15, 1.15, 1.25, 1.15, 1.15), # THIS
  date_range = c("2022-08-01", "2022-09-30"), # Default last month as initial period   
  scenario = "target_efficiency",   
  target_value = 50, # Customize target ROAS or CPA value   
  export = TRUE 
)
```

I was wondering if the channel constraint feature is going to work with target_efficiency scenario, and if the interpretation of channel_constr_up has changed for the latest robyn version.

## Environment & Robyn version
Robyn version: ‘3.10.1.9000’
R version: "R version 4.2.2 (2022-10-31)"

**Comment by fraschen** [comment]
@gufengzhou here my code for your reference
```AllocatorCollect <- robyn_allocator(
  InputCollect = InputCollect,
  OutputCollect = OutputCollect,
  select_model = select_model,
  date_range = "last_12",
  total_budget = 200000,
  channel_constr_low = 0.7,
  channel_constr_up = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.0, 1.5),
  channel_constr_multiplier = 5,
  scenario = "max_response",
  export = create_files
)

**Comment by gufengzhou** [comment]
Hi, channnel_constr_up at 1.0 doesn't mean the share of that channel won't go up, it means the absolute spend can change between [-30%, 0%] of the initial value, but the share of spend won't stay necessarily. 
You can check AllocatorCollect$dt_optimOut for more details.

**Comment by fraschen** [comment]
@gufengzhou this makes sense in general, but not in my scenario in which `Initial abs. mean spend: 0`. 

IF constr_up = 1.0 shouldn't the spend remain at 0?

**Comment by gufengzhou** [comment]
Yes it should. I can't reproduce your issue with the standard dataset. can you share AllocatorCollect$dt_optimOut here?

**Comment by fraschen** [comment]
| solID | dep_var_type | channels | date_min | date_max | periods | constr_low | constr_low_abs | constr_up | constr_up_abs | unconstr_mult | constr_low_unb | constr_low_unb_abs | constr_up_unb | constr_up_unb_abs | histSpendAll | histSpendAllTotal | histSpendAllUnit | histSpendAllUnitTotal | histSpendAllShare | histSpendWindow | histSpendWindowTotal | histSpendWindowUnit | histSpendWindowUnitTotal | histSpendWindowShare | initSpendUnit | initSpendUnitTotal | initSpendShare | initSpendTotal | initResponseUnit | initResponseUnitTotal | initResponseMargUnit | initResponseTotal | initResponseUnitShare | initRoiUnit | initCpaUnit | total_budget_unit | total_budget_unit_delta | optmSpendUnit | optmSpendUnitDelta | optmSpendUnitTotal | optmSpendUnitTotalDelta | optmSpendShareUnit | optmSpendTotal | optmSpendUnitUnbound | optmSpendUnitDeltaUnbound | optmSpendUnitTotalUnbound | optmSpendUnitTotalDeltaUnbound | optmSpendShareUnitUnbound | optmSpendTotalUnbound | optmResponseUnit | optmResponseMargUnit | optmResponseUnitTotal | optmResponseTotal | optmResponseUnitShare | optmRoiUnit | optmCpaUnit | optmResponseUnitLift | optmResponseUnitUnbound | optmResponseMargUnitUnbound | optmResponseUnitTotalUnbound | optmResponseTotalUnbound | optmResponseUnitShareUnbound | optmRoiUnitUnbound | optmCpaUnitUnbound | optmResponseUnitLiftUnbound | optmResponseUnitTotalLift | optmResponseUnitTotalLiftUnbound
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Channel1 | 4_141_2 | revenue | Channel1 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 175.72275 | 1.5 | 376.54875 | 5 | 0 | 0 | 3.5 | 878.61375 | 29058.32 | 2755535.08 | 182.756729559748 | 17330.4093081761 | 0.0105454364239123 | 3012.39 | 297233.73 | 251.0325 | 24769.4775 | 0.0101347515303865 | 251.0325 | 24769.4775 | 0.0101347515303865 | 297233.73 | 15361.0668802561 | 140249.30519577 | 146.597785283557 | 1682991.66234924 | 0.109526866167459 | 61.1915464342511 | 0.0163421266215992 | 16913.3333333333 | -0.317170362865614 | 376.54875 | 0.5 | 16913.3333333315 | -0.317170362865688 | 0.0222634262908972 | 202959.999999978 | 878.61375 | 2.5 | 16913.3333333315 | -0.31717036286569 | 0.0519479946787602 | 202959.999999978 | 40038.4241263371 | 247.450520765822 | 151150.932053396 | 1813811.18464075 | 0.264890355503683 | 106.329988152496 | 0.00940468458028816 | 1.60648719509185 | 235969.035492546 | 461.087424106838 | 348229.951177438 | 4178759.41412926 | 0.677624181075422 | 268.56970482484 | 0.00372342815304576 | 14.3615004304057 | 0.0777303448484763 | 1.48293530361063
Channel2 | 4_141_2 | revenue | Channel2 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 365.49975 | 1.5 | 783.21375 | 5 | 0 | 0 | 3.5 | 1827.49875 | 23201.71 | 2755535.08 | 145.922704402516 | 17330.4093081761 | 0.0084200379695402 | 6265.71 | 297233.73 | 522.1425 | 24769.4775 | 0.0210800772846339 | 522.1425 | 24769.4775 | 0.0210800772846339 | 297233.73 | 0 | 140249.30519577 | 0 | 1682991.66234924 | 0 | 0 | Inf | 16913.3333333333 | -0.317170362865614 | 0 | -1 | 16913.3333333315 | -0.317170362865688 | 0 | 202959.999999978 | 0 | -1 | 16913.3333333315 | -0.31717036286569 | 0 | 202959.999999978 | 0 | 0 | 151150.932053396 | 1813811.18464075 | 0 | NA | NA | NA | 0 | 0 | 348229.951177438 | 4178759.41412926 | 0 | NA | NA | NA | 0.0777303448484763 | 1.48293530361063
Channel3 | 4_141_2 | revenue | Channel3 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 84.1746477987422 | 1.5 | 180.374245283019 | 5 | 0 | 0 | 3.5 | 420.873238993711 | 19119.67 | 2755535.08 | 120.249496855346 | 17330.4093081761 | 0.00693864147793757 | 0 | 297233.73 | 0 | 24769.4775 | 0 | 0 | 24769.4775 | 0 | 297233.73 | 0 | 140249.30519577 | 0 | 1682991.66234924 | 0 | NA | NA | 16913.3333333333 | -0.317170362865614 | 0 | NA | 16913.3333333315 | -0.317170362865688 | 0 | 202959.999999978 | 0 | NA | 16913.3333333315 | -0.31717036286569 | 0 | 202959.999999978 | 0 | 0 | 151150.932053396 | 1813811.18464075 | 0 | NA | NA | NA | 0 | 0 | 348229.951177438 | 4178759.41412926 | 0 | NA | NA | NA | 0.0777303448484763 | 1.48293530361063
Channel4 | 4_141_2 | revenue | Channel4 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 2640.29383333333 | 1.5 | 5657.7725 | 5 | 0 | 0 | 3.5 | 13201.4691666667 | 429703.52 | 2755535.08 | 2702.53786163522 | 17330.4093081761 | 0.1559419522977 | 45262.18 | 297233.73 | 3771.84833333333 | 24769.4775 | 0.152278074227982 | 3771.84833333333 | 24769.4775 | 0.152278074227982 | 297233.73 | 14014.2138427329 | 140249.30519577 | 1.46933566780717 | 1682991.66234924 | 0.099923588378359 | 3.71547649964706 | 0.269144482570403 | 16913.3333333333 | -0.317170362865614 | 2640.29383333333 | -0.3 | 16913.3333333315 | -0.317170362865688 | 0.156107242806481 | 202959.999999978 | 1562.57695596674 | -0.585726461438647 | 16913.3333333315 | -0.31717036286569 | 0.0923872855321392 | 202959.999999978 | 12088.4994416668 | 1.98150699263169 | 151150.932053396 | 1813811.18464075 | 0.0799763473333819 | 4.57846747549504 | 0.21841369527079 | -0.137411518239726 | 9508.44404326888 | 2.92561678226048 | 348229.951177438 | 4178759.41412926 | 0.0273050724416979 | 6.08510448522911 | 0.164335715586706 | -0.321514274723338 | 0.0777303448484763 | 1.48293530361063
Channel5 | 4_141_2 | revenue | Channel5 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 1258.922 | 1.5 | 2697.69 | 5 | 0 | 0 | 3.5 | 6294.61 | 50266.86 | 2755535.08 | 316.143773584906 | 17330.4093081761 | 0.0182421411960395 | 21581.52 | 297233.73 | 1798.46 | 24769.4775 | 0.0726079102798999 | 1798.46 | 24769.4775 | 0.0726079102798999 | 297233.73 | 0 | 140249.30519577 | 0 | 1682991.66234924 | 0 | 0 | Inf | 16913.3333333333 | -0.317170362865614 | 0 | -1 | 16913.3333333315 | -0.317170362865688 | 0 | 202959.999999978 | 0 | -1 | 16913.3333333315 | -0.31717036286569 | 0 | 202959.999999978 | 0 | 0 | 151150.932053396 | 1813811.18464075 | 0 | NA | NA | NA | 0 | 0 | 348229.951177438 | 4178759.41412926 | 0 | NA | NA | NA | 0.0777303448484763 | 1.48293530361063
Channel6 | 4_141_2 | revenue | Channel6 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 2267.43358333333 | 1.5 | 4858.78625 | 5 | 0 | 0 | 3.5 | 11337.1679166667 | 248839.8 | 2755535.08 | 1565.03018867925 | 17330.4093081761 | 0.0903054371566919 | 38870.29 | 297233.73 | 3239.19083333333 | 24769.4775 | 0.130773482538472 | 3239.19083333333 | 24769.4775 | 0.130773482538472 | 297233.73 | 14721.4726676206 | 140249.30519577 | 2.13427461977517 | 1682991.66234924 | 0.10496645703215 | 4.54479943451535 | 0.220031711939921 | 16913.3333333333 | -0.317170362865614 | 2285.03998838464 | -0.294564566906608 | 16913.3333333315 | -0.317170362865688 | 0.135102876727526 | 202959.999999978 | 2276.84001374919 | -0.297096055496621 | 16913.3333333315 | -0.31717036286569 | 0.134618053631224 | 202959.999999978 | 12341.1911570654 | 2.91716811043989 | 151150.932053396 | 1813811.18464075 | 0.0816481313704748 | 5.40086441366381 | 0.185155546114076 | -0.16168773086069 | 12317.2310718975 | 2.92573486676702 | 348229.951177438 | 4178759.41412926 | 0.0353709697579155 | 5.40979207916117 | 0.184849987830782 | -0.163315291208001 | 0.0777303448484763 | 1.48293530361063
Channel7 | 4_141_2 | revenue | Channel7 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 10630.7623333333 | 1.5 | 22780.205 | 5 | 0 | 0 | 3.5 | 53153.8116666667 | 1740744.99 | 2755535.08 | 10948.0816981132 | 17330.4093081761 | 0.631726666314116 | 182241.64 | 297233.73 | 15186.8033333333 | 24769.4775 | 0.613125704138625 | 15186.8033333333 | 24769.4775 | 0.613125704138625 | 297233.73 | 95941.7025815243 | 140249.30519577 | 2.20480365942058 | 1682991.66234924 | 0.684079699700489 | 6.31743892876672 | 0.15829199320732 | 16913.3333333333 | -0.317170362865614 | 10666.6699628714 | -0.297635603177974 | 16913.3333333315 | -0.317170362865688 | 0.630666335999559 | 202959.999999978 | 10625.31529005 | -0.300358669508243 | 16913.3333333315 | -0.31717036286569 | 0.628221243006572 | 202959.999999978 | 84505.5611349662 | 2.91758665634552 | 151150.932053396 | 1813811.18464075 | 0.559080648640086 | 7.92239390823131 | 0.126224473509328 | -0.119198858669831 | 84384.7250957928 | 2.92610335937934 | 348229.951177438 | 4178759.41412926 | 0.242324719084244 | 7.94185610424327 | 0.125915149667054 | -0.120458332245158 | 0.0777303448484763 | 1.48293530361063
tv_cost | 4_141_2 | revenue | tv_cost | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 660.377358490566 | 1 | 943.396226415094 | 5 | 0 | 0 | 1 | 943.396226415094 | 150000 | 2755535.08 | 943.396226415094 | 17330.4093081761 | 0.0544358883647382 | 0 | 297233.73 | 0 | 24769.4775 | 0 | 0 | 24769.4775 | 0 | 297233.73 | 210.849223635337 | 140249.30519577 | 3.67550087617519 | 1682991.66234924 | 0.00150338872154139 | Inf | 0 | 16913.3333333333 | -0.317170362865614 | 660.377358490566 | Inf | 16913.3333333315 | -0.317170362865688 | 0.0390447787834432 | 202959.999999978 | 147.970122307689 | Inf | 16913.3333333315 | -0.31717036286569 | 0.00874872619083792 | 202959.999999978 | 1996.65435154511 | 2.32555133704386 | 151150.932053396 | 1813811.18464075 | 0.0132096727715828 | 3.02350516091117 | 0.330741952396284 | 8.46958360633245 | 685.479369118513 | 2.92495823203103 | 348229.951177438 | 4178759.41412926 | 0.00196846757954267 | 4.63255256147675 | 0.21586371373652 | 2.25104051748394 | 0.0777303448484763 | 1.48293530361063
Channel9 | 4_141_2 | revenue | Channel9 | 2022-12-12 | 2023-02-27 | 12 weeks | 0.7 | 284.403440251572 | 1.5 | 609.435943396226 | 5 | 0 | 0 | 3.5 | 1422.01720125786 | 64600.21 | 2755535.08 | 406.290628930817 | 17330.4093081761 | 0.0234437987993243 | 0 | 297233.73 | 0 | 24769.4775 | 0 | 0 | 24769.4775 | 0 | 297233.73 | 2.79057138076297e-10 | 140249.30519577 | 0.00109621419750046 | 1682991.66234924 | 1.98972207161219e-15 | Inf | 0 | 16913.3333333333 | -0.317170362865614 | 284.403440251572 | Inf | 16913.3333333315 | -0.317170362865688 | 0.0168153393920932 | 202959.999999978 | 1422.01720125786 | Inf | 16913.3333333315 | -0.31717036286569 | 0.0840766969604662 | 202959.999999978 | 180.601841815296 | 1.35152470103478 | 151150.932053396 | 1813811.18464075 | 0.00119484438079083 | 0.635019891656525 | 1.57475381974473 | 647185888381.178 | 5365.03610481466 | 7.77271173496956 | 348229.951177438 | 4178759.41412926 | 0.0154065900611775 | 3.77283488558996 | 0.26505268063 | 19225582767022.9 | 0.0777303448484763 | 1.48293530361063


@gufengzhou Check the tv_cost var

**Comment by gufengzhou** [comment]
the date_range in your  allocator function is c("2022-08-01", "2022-09-30"), which is different than the date_min and date_max in the table?

**Comment by gufengzhou** [comment]
it does look wrong that your constr_up_abs is 943 but initSpendUnit is 0. But I can't reproduce your issue. are you on the latest version? are the model objects (inputcollect, outputcollect) also created from the latest version? If issue persists, I would need your dataset and the model json file created from robyn_write to debug.

**Comment by fraschen** [comment]
@gufengzhou  [RobynModel-4_141_2.txt](https://github.com/facebookexperimental/Robyn/files/11237863/RobynModel-4_141_2.txt)
[dt_input.csv](https://github.com/facebookexperimental/Robyn/files/11237898/dt_input.csv)
The bug occurs on the latest version (3.10.3.9000) as well.

Try the following:

```AllocatorCollect3 <- robyn_allocator(
  InputCollect = InputCollect,
  OutputCollect = OutputCollect,
  select_model = select_model,
  date_range = "last_12",
  total_budget = 202960,
  channel_constr_low = 0.7,
  channel_constr_up = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.0, 1.5),
  channel_constr_multiplier = 5,
  scenario = "max_response",
  export = create_files
)```

**Comment by gufengzhou** [comment]
@fraschen hey sorry for getting back late. You also need to anonymise the json file so that I can recreate your model. Now the data and the input don't match.

**Comment by fraschen** [comment]
@gufengzhou 
[RobynModel-4_141_2.txt](https://github.com/facebookexperimental/Robyn/files/11336980/RobynModel-4_141_2.txt)

Sorry wrong file. This one should work.

**Comment by gufengzhou** [comment]
We couldn't reproduce this error so far. Please reopen if issue reoccurs.
