### ISSUE TITLE
Nevergrad Installation Failure - Option 1

### ISSUE THREAD

**Issue by jalo90** [facebookexperimental/Robyn#670]
## Describe issue
Describe your issue and provide warnings and error messages.

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)

=================
packageVersion("Robyn") - ‘3.9.0’
R.version$version.string - "R version 4.2.1 (2022-06-23 ucrt)"

Hello! 

My team is having trouble in installing nevergrad to be able to run Robyn.

Used nevergrad installation via PIP (option 1) lifted from the site:
![image](https://user-images.githubusercontent.com/128504382/229367874-52077e39-9209-4ca6-97a8-4246ea579dac.png)

there was an error regarding what python path to use, Then I used the path "C:/Users/johaloda/Documents/.virtualenvs/r-reticulate/Scripts/python.exe")

![image](https://user-images.githubusercontent.com/128504382/229368030-251ef3e7-388d-450d-b8e5-4b6de3cf4936.png)

Another error saying that the module can't be found, 

Downloaded and installed Python, then i used another path where the python.exe is located in "C:/Program Files/Python39"

![image](https://user-images.githubusercontent.com/128504382/229368217-aa558316-6fbe-4ce7-9ff8-6737bed20e62.png)

Is nevergrad successfully installed? But numpy says [NOT FOUND]. just in case I run Robyn (Demo.R) (which i will save, rename, and attach later). The below issue where shown where nevergrad wasn't successfully installed:

![image](https://user-images.githubusercontent.com/128504382/229368445-2de6d147-00f9-4b40-8685-088dcec1eb1d.png)

Then I restarted R and then ran the second part in the installation guide, this happens:

![image](https://user-images.githubusercontent.com/128504382/229368598-135fb3eb-2e54-41ce-8ab8-db586d1612de.png)
![image](https://user-images.githubusercontent.com/128504382/229368612-b3f86da9-e838-4864-967e-43a746264429.png)

same as the first part where numpy was not found

I still reran the Robyn program, it still says to install nevergrad.

Please advise on what to do or what I may be doing wrong?

Thank you

**Comment by jalo90** [comment]
I can't seem to upload *.R file :(

**Comment by laresbernardo** [comment]
Closing this task now. Feel free to reach back anytime.
