### ISSUE TITLE
Status 103

### ISSUE THREAD

**Issue by jalo90** [facebookexperimental/Robyn#671]
## Describe issue
Describe your issue and provide warnings and error messages.

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)

================

> R.version$version.string
[1] "R version 4.2.1 (2022-06-23 ucrt)"
> packageVersion("Robyn")
[1] ‘3.9.0’

Hello!

There was a previous error that I encountered previously regarding status 103. i don't know i it went away, just want to know how this came about? It may happen again when installing in another machine.

When trying to install nevergrad option 1 #6 - #8, this happened:

 ![image](https://user-images.githubusercontent.com/128504382/229369353-0d515690-16e0-4cab-95a3-b577c5b379bf.png)

what is status 103 and why would this appear?

**Comment by gufengzhou** [comment]
Hi, you can easily google status 103 to find out what it's about. Related to nevergrad install, the issues are very individual so I can't really tell just by looking at it. Please also try option 2.

**Comment by laresbernardo** [comment]
Closing this task now. Feel free to reach back anytime.
