### ISSUE TITLE
budget optimization for past periods

### ISSUE THREAD

**Issue by AlessioPallotti** [facebookexperimental/Robyn#672]
Is it possible to optimize the budget for past periods?  or instead of doing budget optimization on the last month, can you do it on other previous months (not up to today)?

**Comment by fraschen** [comment]
@AlessioPallotti yes. In robyn_allocator() you can select `date_range = c("2022-01-01", "2022-12-31"))`

**Comment by laresbernardo** [comment]
That's right @fraschen Thanks. Also, it's not only "possible" to optimize the budget for past periods but it's the only way for the time being. We will work on a forecasting functionality to optimize toward future scenarios but currently we only optimize using past periods, customizable using the `date_range` parameter mentioned.
