### ISSUE TITLE
Budget allocation uses all values to calculate SpendUnit instead of values greater than 0

### ISSUE THREAD

**Issue by JulesCorbel** [facebookexperimental/Robyn#673]
## Robyn - budget allocator

Hi, I'm trying to use optimize budget between 3 variables. The problem I have is there are weeks when there are no investments, as showed in the [attached CSV](https://github.com/facebookexperimental/Robyn/files/11148373/vars.csv) and the results are in the table below.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">

channels | date_min | date_max | periods | constr_low | constr_low_abs | constr_up | constr_up_abs | initSpendUnit | initSpendUnitTotal | initSpendShare | initSpendTotal | initResponseUnit
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
var1 | 03-01-22 | 24-10-22 | 43 weeks | 0.8 | 1488.368 | 2 | 3720.92 | 1860.46 | 2   995.35 | 0.60 | 128 800.00 | 15.00
var2 | 03-01-22 | 24-10-22 | 43 weeks | 0.8 | 312.56 | 2 | 781.4 | 390.7 | 2   995.35 | 0.17 | 128 800.00 | 40.00
var3 | 03-01-22 | 24-10-22 | 43 weeks | 0.8 | 595.352 | 2 | 1488.38 | 744.19 | 2   995.35 | 0.24 | 128 800.00 | 12.00
</body>
</html>

As you can see, for var1 initSpendUnit equals 1860.46, but i would have expected it to be 10 000.

 In the changelog of version 3.10, i saw that the method for calculating SpendUnit changed. Before, only values greater than 0 were used to calculate the mean, now all values are taken. I wonder if this change was intended and if so, what is the idea behind this change.

V3.9
histSpendUnit <- unlist(summarise_all(histSpendB, function(x) sum(x) / sum(x > 0)))
V3.10
initSpendUnit <- histSpendWindowUnit <- unlist(summarise_all(select(histFiltered, any_of(mediaSpendSortedFiltered)), mean))

Thanks.

## Environment & Robyn version
Robyn version: 3.10.0.9000
R version 4.1.2 (2022-10-31)

**Comment by gufengzhou** [comment]
Hi, yes this change of mean calculation is intended, because with the old calculation it was difficult to keep consistency of mean spend between the allocator and the model onepager which often led to confusion. Both approaches have their own justification. We've now decided for a more intuitive one. Note that the mean spend only serve as a starting point of the allocation. If you expect to spend way higher than initSpendUnit, you can raise the upper constraint to the desired level to allow that.
