### ISSUE TITLE
Zero effect on channels

### ISSUE THREAD

**Issue by RomanRudnitskiy** [facebookexperimental/Robyn#675]
## Project Robyn

Hello! When using Robin, there is always an effect that one or more channels show a zero effect.

![1_135_5](https://user-images.githubusercontent.com/129966638/230106515-6bdf1ef8-56c7-4a74-9b54-0bb11af1e87c.png)
![1_199_3](https://user-images.githubusercontent.com/129966638/230106500-8f9d63a3-36d0-4ea2-b51a-fae9c14b0d1b.png)

**Here is some information on this case :**
- data with weekly granulation for 2 years
- rolling window = 1 year (2022-2023)
- paid_media_vars are equal to spends, because I cannot collect impressions for all the spend channels (it should work in this setting as well, right?)
- Report is being picked from the experiment with 5 trials, 2k iterations. Majority of reports (models) share same effect or huge intercept value
- Channel 5 (zero effect)
- No gaps in spends, no zero values
- Doing 40 trials and 500 iteration like recommended in another issue [Share of effect as zero #160](https://github.com/facebookexperimental/Robyn/issues/160) doesn’t help
- Also tried experiment with 5 trials, 8k iterations -  doesn’t help too 

**Interesting cases:**
- If I remove (multiply by zero) spends in this channel in last 3 weeks (points) (1% of spends in this channel) the zero-share effect disappears
- zero-effect appears in experiments with different target metrics (revenue/conversion)
- I tried different approaches on ROI calculations (D1/W1/M1...)
- I noticed that zeroing occurs at the decompMedia stage
- Removing channel spend data from data set doesn’t remove zero-effect channel: once you remove a particular zero-effect channel this effect appears in another
- There were thoughts on L1 regularization, but following final formula there is L2 regularization. There still can be same problem, if spends for this channel are constant, but they are not. Spend std is even not the minimal among the dataset.

-![image](https://user-images.githubusercontent.com/129966638/230105323-c89a8efd-e958-4854-a8b8-9e668bbba4ee.png)

**Comment by laresbernardo** [comment]
Hi @RomanRudnitskiy thanks for sharing your analysis.
[We are about to deploy](https://github.com/facebookexperimental/Robyn/pull/680) a new penalizing system when calculating DECOMP.RSSD in which models with more coef-0 media variables are penalized and models with no coef-0 media are not, that way we can minimize these scenarios.

**Comment by laresbernardo** [comment]
Closing this task now. Feel free to reach back anytime.
