### ISSUE TITLE
Want to get a sense of baseline sales %  by running a Robyn model without any media variables.

### ISSUE THREAD

**Issue by CJ2407** [facebookexperimental/Robyn#676]
## Describe issue
I want to get a sense of baseline sales % for my company by running a Robyn model without any media variables, but throws an error asking for paid media vars. Is there a way to run Robyn with just context vars such as Trend and Seasonality?

Currently with intercept, number of SKUs, trend, and seasonality variable, I have somewhere between 50 to 55% baseline sales, which seems a bit higher. According to marketing analytics + marketers on our team, this should be between 20-30%, but their estimation is not data driven. Hence, want to test it out.

**Comment by gufengzhou** [comment]
Robyn is designed to estimate and optimise media spendings, so media is required. Apart from thst, It's recommended to include all necessary predictors in MMM (media, seasonality and others). leaving media out might introduce bias / overestimation of remaining  predictors.
