### ISSUE TITLE
speed up loading / avoid Running feature engineering...

### ISSUE THREAD

**Issue by iuiu34** [facebookexperimental/Robyn#679]
## Describe issue
Hi,
i have a model build. Then a script that given some configs, outputs a budget allocation.

In the script, all running time (~10s) goes to loading the model. In particular, executing `robyn_recreate`.
There is no way to speed up this?
I don't want to recreate/redo the statistical process. The `Running feature engineering...` part.
I only want to load the model and predict with it.

I know it's not the same, but to make a point, a torch-bert model with millions of parameters takes <5s. 
Why robyn should take 10s?
thanks

## Provide reproducible example
Initial model is built on rolling window of 160 week: 2019-12-30 to 2023-01-15
```
robyn_recreated = robyn_recreate(
  json_file = json_file,
  dt_input = dt_input,
  dt_holidays = dt_prophet_holidays,
  # export = FALSE
)
```

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- 3.9.0
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)
"R version 4.2.2 (2022-10-31 ucrt)"

**Comment by laresbernardo** [comment]
Hi! Yes, you could simply save locally your InputCollect and OutputCollect as R objects with saveRDS and then re-load them, but they are pretty big objects, thus pretty big files. Given users usually save a lot of different models, we enabled the current read and write functions to recreate any models given the parameters on a JSON file which it’s extremely light and easy to read / interpret. Given we have to run feature engineering and transformations and so on, it takes some time (probably we could optimize the code/flow a bit more but this was the reasoning behind it).
Hope this helps.

**Comment by iuiu34** [comment]
cool, thanks!
