### ISSUE TITLE
Deprecating normalization of decayed independent variables

### ISSUE THREAD

**Issue by jesuiskelly** [facebookexperimental/Robyn#68]
Hello! I was checking out this code (and have been very impressed!). I noticed that for the f.transformation function, "step 2: normalize decayed independent variable" has been deprecated. Would you be able to shed some light on this? Thank you!

**Comment by jesuiskelly** [comment]
Ah makes sense. Can you point out which function that is so I can have a look at the documentation? thank you!

**Comment by gufengzhou** [comment]
this is the one used in Robyn. You can check the details in glmnet's docu
![image](https://user-images.githubusercontent.com/14415136/115763352-ac8fc780-a3a4-11eb-8137-b970a88ede57.png)
