### ISSUE TITLE
Error in Robyn_outputs: allocate vector of size 437.6Mb

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#684]
## When running robyn_outputs.  Get  the following error"
"Error: cannot allocate vector of size 437.6 Mb"

## Environment & Robyn version
Windows 10
Robyn Version 3.10.0.9
R version 4.2.2

**Comment by laresbernardo** [comment]
Hi @tgtod002 
I've just released a new version for Robyn (dev-main) in which these memory issues shouldn't occur because we've reduced the size of the `OutputModels` objects 88%. Please, update to latest dev version and retry. Thanks!

**Comment by laresbernardo** [comment]
Closing this task now. Feel free to reach back anytime.
