### ISSUE TITLE
Fail to run demo.R

### ISSUE THREAD

**Issue by RanM23** [facebookexperimental/Robyn#691]
## Describe issue
I have been running the [demo code](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R) with no changes, and have been running into an error when I get to the robyn_run():
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
Error: TypeError: __init__() got an unexpected keyword argument 'lower'

## Environment & Robyn version
<img width="752" alt="image" src="https://user-images.githubusercontent.com/53442195/232344504-5faa4e59-593a-43ef-bfb2-eada989521f1.png">

> packageVersion("reticulate")
[1] ‘1.28’

**Comment by laresbernardo** [comment]
Hi @RanM23 thanks for reporting. Duplicated issue: https://github.com/facebookexperimental/Robyn/issues/211
Let's please follow up there. Closing this task meanwhile.
