### ISSUE TITLE
High RAM Usage 

### ISSUE THREAD

**Issue by MustafaCelen** [facebookexperimental/Robyn#695]
Hi , I have been trying to train a daily model for 15 months with 15 variables (Weibull pdf). I am reducing the number of trials and iterations from 8*8000 to 6*5000 however in all the scenarios all the ram is allocated by Robyn and eventually my R studio server becomes unreachable and even the training is finished cache is still full. As you see I am using 32gb of ram with 32 core cpu additional 8gb of swp memory. I have been facing similar optimization issues with Robyn that I always had to find a workaround. Is there any recommendations that I can try to be able to train my model and get the results and also can you please check for any improvements in terms of memory and cpu usage. Also an average system requirements matrix would be nice so we know what to expect before we start training and allocating our servers or local machines.

Robyn 3.9
R 4.2.2

<img width="682" alt="image" src="https://user-images.githubusercontent.com/10905725/233073590-7fb6a3b4-33ca-4f79-a5ce-a5e529cf101f.png">

**Comment by laresbernardo** [comment]
Hi @MustafaCelen 
Last week we deployed a new dev version that deals with very large datasets (lots of iterations) way better by reducing the size of the OutputModels 88%. Can you please update Robyn to latest dev version and retry?
On the other hand, 65K iterations seems like a lot? Have you tried with 5-8K instead and checked the convergence?

**Comment by MustafaCelen** [comment]
I ll update and try again for sure. I was trying to write 8 x 8000 and 6 x 5000 but GitHub convert the asterisk symbol :D. Also for the cores I use 30 only from 32 possible.

**Comment by MustafaCelen** [comment]
I have updated to the ‘3.10.3.9000’ version and it is fixed.

**Comment by AdimDrewnik** [comment]
What is a recommended number of iterations and trials? I assumed the 2000 and 5 as in demo file is enough but from this discussion it is clear much higher numbers are expected.
