### ISSUE TITLE
I can´t install nevergrad

### ISSUE THREAD

**Issue by andreagcast** [facebookexperimental/Robyn#697]
## Describe issue
I am trying to install nevergrad doing the steps that appears in this guide: https://github.com/facebookexperimental/Robyn/blob/main/demo/install_nevergrad.R

Option 1: At the 3rd step returns this Error:

use_virtualenv("r-reticulate", required = TRUE)
Error in python_config_impl(python) :
Error 103 occurred running C:/Users/andreagcast/OneDrive - Inditex/Documents/.virtualenvs/r-reticulate/Scripts/python.exe:
In addition: Warning message:
In system2(command = python, args = shQuote(script), stdout = TRUE, :
running command '"C:/Users/andreagcast/OneDrive - Inditex/Documents/.virtualenvs/r-reticulate/Scripts/python.exe" "C:/Users/andreagcast/OneDrive - Inditex/Documents/R/win-library/4.1/reticulate/config/config.py"' had status 103

On the other hand, if I try Option 2:
Step 6 returns this error:
Error in py_discover_config(required_module, use_environment) :
Python specified in RETICULATE_PYTHON (~/Library/r-miniconda-arm64/envs/r-reticulate/bin/python) does not exist
If I continue the steps and, then, I run a code with robyn_run function it returns this error:
Error in robyn_run(InputCollect = InputCollect, cores = NULL, iterations = 2000, :
could not find function "robyn_run"

How can I solve this situation?

## Environment & Robyn version

- Check and share Robyn version: ‘3.10.3.9000’
- R version 4.1.0

**Comment by andreagcast** [comment]
![image](https://user-images.githubusercontent.com/131348588/233395644-d020b525-877a-48e5-accb-457a06e9fd7d.png)

**Comment by gufengzhou** [comment]
Option 2 step 5, you need to read the instruction and use your own python path. The one provided is from Mac and you have a windows, right?

**Comment by gufengzhou** [comment]
The issue is that sometimes , for whatever reason, reticulate can't find the right python version on your system. It's a reticulate issue and it varies from machine to machine. 

You can also try [this](https://docs.posit.co/ide/user/ide/guide/environments/py/python.html#selecting-a-default-version-of-python) to specify your python path. Hope it works.
