### ISSUE TITLE
Same Spend and Same Revenue ; Robyn shows two different results for a particular channel

### ISSUE THREAD

**Issue by rohan1997vk** [facebookexperimental/Robyn#698]
## Project Robyn
I have two datasets. In dataset-1, there are 5 channels and in dataset two there are 9 channels.
Dataset-1
Channel-A
Channel-B
Channel-C
Channel-D
Channel-E

Dataset-2
Channel-A
Channel-B1
Channel-B2
Channel-C1
Channel-C2
Channel-D1
Channel-D2
Channel-E1
Channel-E2

B1 and B2 make channel B and similarly for all. However, when Robyn was given both the datasets, the Response Curve for Channel-A is different. When input is dataset-1, Robyn suggests to increase the spend of this channel however, when during the other dataset, Robyn suggests to reduce the spending of this channel. If the revenue and total marketing spend of the Channel-A is same in both cases, why does Robyn suggest increasing the spending in one case and reduce in the other.

**Comment by laresbernardo** [comment]
Hi! Are these 3 different models? If that's correct, maybe try picking a "more similar" model when selecting the model.
That said, we always recommend using calibration feature to avoid these. When we don't calibrate, we are simply generating mathematical good fits and models without grasping real and measured incremental values via experiments, thus, there's no way to "know" which model reflects "reality" the best.
