### ISSUE TITLE
possibility of calculating how much the target increases as spending varies

### ISSUE THREAD

**Issue by AlessioPallotti** [facebookexperimental/Robyn#699]
Hi all, is there a way to calculate how much our response variable increases/decreases as overall spending varies? Or at least by jointly varying all the variables in which the expenditure is made. Thank you

**Comment by laresbernardo** [comment]
Not sure what you mean here. Maybe recreating the spend-response curves you mean? Try `robyn_response()` for that.

**Comment by AlessioPallotti** [comment]
Thank you for your answer.
I would like to understand if there is a way to know what value my target assumes if I modify the explanatory variables of spent.  This not only considering a single explanatory variable at a time and leaving the other constants , but making them all assume possibly different values

**Comment by laresbernardo** [comment]
So you mean the budget allocator to optimize spend variables to maximize your response? Then try `robyn_allocator()`. You can either set a range for it to optimize of fix the values based on their mean spends during the `date_range` periods.

**Comment by AlessioPallotti** [comment]
Yes, but not only to maximize, also for DETERMINE my response. Is it possible?

**Comment by laresbernardo** [comment]
Yes, `robyn_allocator()` will give you the response for each of the scenarios (spends per channel).

**Comment by laresbernardo** [comment]
Reference - same as FB post: https://www.facebook.com/groups/robynmmm/posts/1423442928423836/

**Comment by AlessioPallotti** [comment]
Thank you very much!
