### ISSUE TITLE
Feature Idea: log-link models

### ISSUE THREAD

**Issue by lorenze3** [facebookexperimental/Robyn#70]
# Contributing to FB NextGen MMM R script

# Issue

Current decomp function only allows for linear GLM.  Would be particularly relevant for modelling count data (ie with granular enough data on conversion events, we might get enough zeros to need want to use a poisson regression)

# Steps to Reproduce
Follow the documentation

# Likely steps to add the function
At a minimum, the decomp function needs to be re-written to account for logged models.  I'm unsure how deep into the optimization functions changes would have to be made.  It seems like the sign constrained, regularization estimation can still be done with the glmnet() function.

R version (R --version)

**Comment by gufengzhou** [comment]
Hi there, you're totally right about the log-linear model, which can be specified in glmnet as family = "poisson". The reason why we haven't touched this part is that first we lacked real count data for the dev at the beginning and second how to do decomp is still quite controversial. Would you elaborate your approach to decomp a multiplicative equation?

**Comment by gufengzhou** [comment]
Thanks for sharing your experience! Providing multiplicative model is on own roadmap, as well as other interesting options like Bayesian model for better calibration, state space model for time varying coefficients etc. For the moment, an update feature to help refreshing the model regularly will be coming next.
