### ISSUE TITLE
total response of budget allocation is not equl to actual revenue

### ISSUE THREAD

**Issue by ghltk** [facebookexperimental/Robyn#700]
-Project Robyn
Hi, I have a few questions about the 'initial total repose' value in the budget allocation section.

1. I understood the meaning of the initial part as the expected value of Y (Revenue) when used at the same cost as the last 4 weeks. Is my understanding correct?

2. If I'm correct, the total response means the expected revenue for the next 4 months?
    - 1.53M seems too small for 4 months of revenue
    - 1.64 ROAS also seems too small
    - (In the sample code, the last 4 months' ROAS is over 1000%, and the weekly Revenue is greater than 2 million)

I'd be grateful if you could explain what I'm misunderstanding.
Thank you 

![image](https://user-images.githubusercontent.com/131640422/233924288-68205f22-0e6e-4725-9c90-0c32320d8ecd.png)

![image](https://user-images.githubusercontent.com/131640422/233924025-6cf6021b-d19a-4f83-b895-f256dd48a32a.png)

-Environment & Robyn version
Robyn version: 3.10.2.9000
R version 4.1.3 (2022-03-10)

**Comment by ghltk** [comment]
-  When I just ran the example code directly, the total response value was smaller.
   Why does it appear differently each time I run it?


![image](https://user-images.githubusercontent.com/131640422/233909762-71f1b2f0-133f-4749-b23d-63574c830fa4.png)

**Comment by gufengzhou** [comment]
Look at the subtitle, it's for 4 weeks, not 4 months

**Comment by ghltk** [comment]
> Look at the subtitle, it's for 4 weeks, not 4 months, so 932k is 4 weeks' spend and 1.53M the response on it.



Sorry I know it's 4 weeks.  It was just a typo.  
Does 1.53 million mean the sum of revenue over the next 4 weeks?

Even if it's 4 weeks, isn't it too small?

In the example data used, more than 2 million revenues were generated in one week.

**Comment by gufengzhou** [comment]
1.53m is media response only, without "the rest" like trend / season etc. We can't allocate budget for variables that dont have spend.

**Comment by ghltk** [comment]
> 1.53m is media response only, without "the rest" like trend / season etc. We can't allocate budget for variables that dont have spend.


 
We can understand it as revenue excluding the baseline.  Thanks for the explanation.
