### ISSUE TITLE
Check in organic vars, if numeric are indeed all numeric ( error: can't subset columns)

### ISSUE THREAD

**Issue by mdebarrio** [facebookexperimental/Robyn#704]
## Describe issue
When providing organic vars, there is no check if the values are indeed all numeric. 

For the paid media vars, there is that check available. If the CSV contains a value with a thousand indicator (,) such as 500,000 , the following error appears.

```
Error in check_paidmedia(dt_input, paid_media_vars, paid_media_signs,  : 
  All your 'paid_media_vars' must be numeric. 
```

However, this case/check does not appear for Organic_vars, and as a result, later the following error appears. 
"! Can't subset columns that don't exist."
See below for full error. 

What i found out after trying/pilotting is: it's the thousand indicator in the values that i use for Organic_Vars. 

Request/thought: can there a check on thousand indicators, similar to the error for paid_media_vars ? 

## Provide reproducible example

Code:
```
> InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)
>> Running feature engineering...
```
Error I get , after running the code:

```
Error in `all_of()`:
! Can't subset columns that don't exist.
✖ Column `gamail` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in `all_of()`:
! Can't subset columns that don't exist.
✖ Column `gamail` doesn't exist.
```

## Environment & Robyn version
Robyn: ‘3.10.3.9000’

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by laresbernardo** [comment]
Before I dig deeper into this issue, is the typo in `gamail` intended? Should it be "gmail" instead?

> When providing organic vars, there is no check if the values are indeed all numeric.

That's ok. Organic variables can actually be character/factor vectors. We'll transform them with one hot encoding later on while doing feature engineering.

If you're intending to pass numerical values, get rid of those commas and force it to be numerical; something like this could work: `as.numeric(gsub(",", "", vector))`

**Comment by mdebarrio** [comment]
> Before I dig deeper into this issue, is the typo in `gamail` intended? Should it be "gmail" instead?
It's referring to GoogleAnalyticsMail ;) , we are tracking received clicks in GA

> > When providing organic vars, there is no check if the values are indeed all numeric.
> 
> That's ok. Organic variables can actually be character/factor vectors. We'll transform them with one hot encoding later on while doing feature engineering.

Which I also understand. 


> 
> If you're intending to pass numerical values, get rid of those commas and force it to be numerical; something like this could work: `as.numeric(gsub(",", "", vector))`

Thanks, clear.
