### ISSUE TITLE
[Error in names(hyper_list_all)] Step 3: build initial model error

### ISSUE THREAD

**Issue by OlivR22** [facebookexperimental/Robyn#705]
I followed all steps of the Robyn R code and reached step 3, where I continuously have the same error message. Can anyone explain why this is happening and how to resolve this? 

This is the code and associated error message which I do not seem to be able to resolve. 

```
> ## Run all trials and iterations. Use ?robyn_run to check parameter definition
> OutputModels <- robyn_run(
+   InputCollect = InputCollect, # feed in all model specification
+   cores = NULL, # NULL defaults to (max available - 1)
+   iterations = 2000, # 2000 recommended for the dummy dataset with no calibration
+   trials = 5, # 5 recommended for the dummy dataset
+   ts_validation = TRUE, # 3-way-split time series for NRMSE validation.
+   add_penalty_factor = FALSE # Experimental feature. Use with caution.
+ )
Input data has 105 weeks in total: 2021-01-04 to 2023-01-02
Initial model is built on rolling window of 105 week: 2021-01-04 to 2023-01-02
Time-series validation with train_size range of 50%-80% of the data...
Error in names(hyper_list_all) <- `*vtmp*` : 
  'names' attribute [3] must be the same length as the vector [2]

```
If needed, this is my original input in step 2a for the model specification. 

```
InputCollect <- robyn_inputs(
  dt_input = DEMMM,
  dt_holidays = dt_prophet_holidays,
  date_var = "date", # date format must be "2020-01-01"
  dep_var = "sales", # there should be only one dependent variable
  dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)
  prophet_vars = c("trend", "season", "holiday"), # "trend","season", "weekday" & "holiday"
  prophet_country = "DE", # input one country. dt_prophet_holidays includes 59 countries by default
  context_vars = c("promo"), # e.g. competitors, discount, unemployment etc
  paid_media_spends = c("google_total", "meta_total", "pr", "influ_collab", "on_offline"
                        ,"retail_ad", "general_ad"),
  adstock = "weibull_pdf" )

```
I also correctly specified my hyperparameters based on the weibull_pdf adstock model

**Comment by mdebarrio** [comment]
Sorry,for some reason i posted a link incorrect. Was referring to:

https://github.com/facebookexperimental/Robyn/issues/570

**Comment by OlivR22** [comment]
I followed along with the post, but it does not seem to apply to my case as I had already only applied the hyperparameters after the robyn_input was run and additionally I can see that my InputCollect accurately included the train_size information so this is not the issue either. I wonder if this is a bug related to the version of RStudio?

**Comment by laresbernardo** [comment]
Can you please share which version of Robyn are you using? Can you try with latest dev version?
Can you also print and share your `InputCollect` object to especially check your hyper-parameters list?

**Comment by OlivR22** [comment]
I managed to resolve by updating my RStudio to the newest version!
