### ISSUE TITLE
robyn refresh fails after few runs

### ISSUE THREAD

**Issue by navneetsonak-ds** [facebookexperimental/Robyn#707]
## Describe issue
I'm running Robyn on databricks. I have 2 separate notebooks in databricks: one for model training and one with robyn_refresh() function. The second notebook, with robyn_refresh() function is scheduled to run on daily new data. But the second notebook fails after running a few times with below error. I was able to reproduce the error using demo data and ran into below error after 7 runs:

```
Error in data.frame(solID = names(chainData), window_start = as.Date(unlist(lapply(chainData,  : 
  arguments imply differing number of rows: 8, 7
Error in data.frame(solID = names(chainData), window_start = as.Date(unlist(lapply(chainData, : arguments imply differing number of rows: 8, 7
Error in data.frame(solID = names(chainData), window_start = as.Date(unlist(lapply(chainData, : arguments imply differing number of rows: 8, 7
```

## Provide reproducible example
```
create_files <- TRUE
robyn_directory <- "/dbfs/FileStore/xyz" # folder in databricks file system

data("dt_simulated_weekly")
data("dt_prophet_holidays")

InputCollect <- robyn_inputs(
  dt_input = dt_simulated_weekly,
  dt_holidays = dt_prophet_holidays,
  date_var = "DATE", # date format must be "2020-01-01"
  dep_var = "revenue", # there should be only one dependent variable
  dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)
  prophet_vars = c("trend", "season", "holiday"), # "trend","season", "weekday" & "holiday"
  prophet_country = "DE", # input one country. dt_prophet_holidays includes 59 countries by default
  context_vars = c("competitor_sales_B", "events"), # e.g. competitors, discount, unemployment etc
  paid_media_spends = c("tv_S", "ooh_S", "print_S", "facebook_S", "search_S"), # mandatory input
  paid_media_vars = c("tv_S", "ooh_S", "print_S", "facebook_I", "search_clicks_P"), # mandatory.
  organic_vars = "newsletter", # marketing activity without media spend
  window_start = "2016-01-01",
  window_end = "2018-12-31",
  adstock = "geometric" # geometric, weibull_cdf or weibull_pdf.
)

hyper_names(adstock = InputCollect$adstock, all_media = InputCollect$all_media)
plot_adstock(plot = FALSE)
plot_saturation(plot = FALSE)

hyper_limits()

hyperparameters <- list(
  facebook_S_alphas = c(0.5, 3),
  facebook_S_gammas = c(0.3, 1),
  facebook_S_thetas = c(0, 0.3),
  print_S_alphas = c(0.5, 3),
  print_S_gammas = c(0.3, 1),
  print_S_thetas = c(0.1, 0.4),
  tv_S_alphas = c(0.5, 3),
  tv_S_gammas = c(0.3, 1),
  tv_S_thetas = c(0.3, 0.8),
  search_S_alphas = c(0.5, 3),
  search_S_gammas = c(0.3, 1),
  search_S_thetas = c(0, 0.3),
  ooh_S_alphas = c(0.5, 3),
  ooh_S_gammas = c(0.3, 1),
  ooh_S_thetas = c(0.1, 0.4),
  newsletter_alphas = c(0.5, 3),
  newsletter_gammas = c(0.3, 1),
  newsletter_thetas = c(0.1, 0.4),
  train_size = c(0.5, 0.8)
)

InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)

OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = NULL, 
  iterations = 1000, 
  trials = 1,
  ts_validation = TRUE, 
  add_penalty_factor = FALSE
)

OutputCollect <- robyn_outputs(
  InputCollect, OutputModels,
  pareto_fronts = "auto", 
  csv_out = "pareto", 
  clusters = TRUE, 
  export = create_files, 
  plot_folder = robyn_directory, 
  plot_pareto = create_files

print(OutputCollect)

#Compare all model one-pagers and select one that mostly reflects your business reality
select_model <- "1_10_13" 

ExportedModel <- robyn_write(InputCollect, OutputCollect, select_model, export = create_files)
print(ExportedModel)

```

Below code is basically updating model path to the latest model json so that it can be used in robyn refresh function %python

```
import os
from datetime import datetime, date

folder_path = "/dbfs/FileStore/Navneet/mmm_experimentation/new_version_robyn_test/"
subFolder_path = [folder_path + sfd for sfd in os.listdir(folder_path)]
new_file_path = subFolder_path[-1]

subFolders=[]
for root, subdirs, files in os.walk(new_file_path):
  subFolders.append(root)

new_file_path= subFolders[-1]
modelName = [i for i in os.listdir(new_file_path) if '.json' in i ]
modelName = modelName[0]

modelPath = new_file_path+'/'+modelName
print(modelPath)

spark.conf.set("mydata.modelPath", modelPath)
```

Now refreshing a refreshed model, following the same approach. Run this and above python code block multiple times to get the error.

```
json_file <- as.character(sparkR.conf("mydata.modelPath"))
RobynRefresh <- robyn_refresh(
  json_file = json_file,
  dt_input = dt_simulated_weekly,
  dt_holidays = dt_prophet_holidays,
  refresh_steps = 1,
  refresh_iters = 1000, # 1k is an estimation
  refresh_trials = 1
)
```

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")` : 3.9.0
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)

**Comment by laresbernardo** [comment]
Hi! This one seems a bit complex to replicate. We will check on our end to see if we can replicate by simply following the demo as you mentioned.
Additionally, can you confirm this is happening the first time you run a refresh model? Also, are you renaming or customizing the structure of the chained folders? Lastly and before we start debugging, have you tried with the latest dev version and can you please confirm this issue persists with version 3.10.3.9000?

**Comment by navneetsonak-ds** [comment]
No, the first few model refreshes runs fine. And, the same code starts throwing error after a few runs. Demo script failed after 7th run.

I'm not changing the folder structure of the chained folders. 

The only change from demo script is: json_file <- as.character(sparkR.conf("mydata.modelPath")). Basically this the last refreshed model folder structure path. This helps run robyn refresh function daily in prod without changing json_file path.

**Comment by navneetsonak-ds** [comment]
This is the log of 7th run of robyn refresh. It fails after it prints decomp-rssd converged:

 Recreating model 1_10_2 Imported JSON file succesfully: /dbfs/FileStore/Navneet/mmm_experimentation/new_version_robyn_test/Robyn_202304241811_init/Robyn_202304241823_rf1/Robyn_202304241827_rf2/Robyn_202304241832_rf3/Robyn_202304241840_rf4/Robyn_202304241848_rf5/Robyn_202304241852_rf6/RobynModel-1_10_2.json >> Running feature engineering... Input data has 208 weeks in total: 2015-11-23 to 2019-11-11 Refresh #6 model is built on rolling window of 157 week: 2016-02-15 to 2019-02-11 Rolling window moving forward: 1 weeks Successfully recreated model ID: 1_10_2 >>> Building refresh model #7 in manual mode >>> New bounds freedom: 0.64% >> Running feature engineering... Input data has 208 weeks in total: 2015-11-23 to 2019-11-11 Refresh #7 model is built on rolling window of 157 week: 2016-02-22 to 2019-02-18 Rolling window moving forward: 1 weeks Warning in hyper_collector(InputCollect, hyper_in = InputCollect$hyperparameters, : Provided train_size but ts_validation = FALSE. Time series validation inactive. Fitting time series with all available data... Using geometric adstocking with 20 hyperparameters (19 to iterate + 1 fixed) on 63 cores >>> Starting 1 trials with 1000 iterations each using TwoPointsDE nevergrad algorithm... Running trial 1 of 1 |================================================================== | 94% Finished in 1.04 mins >>> Running Pareto calculations for 1000 models on auto fronts... >> Automatically selected 1 Pareto-fronts to contain at least 100 pareto-optimal models (170) >> Pareto-Front: 1 [170 models] 00:01:13 [=========================================] 100% | 170 >>> Calculating clusters for model selection using Pareto fronts... >> Auto selected k = 4 (clusters) based on minimum WSS variance of 5% >>> Collecting 170 pareto-optimum results into: /dbfs/FileStore/Navneet/mmm_experimentation/new_version_robyn_test/Robyn_202304241811_init/Robyn_202304241823_rf1/Robyn_202304241827_rf2/Robyn_202304241832_rf3/Robyn_202304241840_rf4/Robyn_202304241848_rf5/Robyn_202304241852_rf6/Robyn_202304241856_rf7/ >> Exporting general plots into directory... >> Exporting pareto results as CSVs into directory... >>> Exporting pareto one-pagers into directory... >> Generating only cluster results one-pagers (4)... >> Plotting 4 selected models on 63 cores... |======================================================================| 100% >> Exported model inputs as /dbfs/FileStore/Navneet/mmm_experimentation/new_version_robyn_test/Robyn_202304241811_init/Robyn_202304241823_rf1/Robyn_202304241827_rf2/Robyn_202304241832_rf3/Robyn_202304241840_rf4/Robyn_202304241848_rf5/Robyn_202304241852_rf6/Robyn_202304241856_rf7/RobynModel-inputs.json - DECOMP.RSSD converged: sd@qt.20 0.036

**Comment by laresbernardo** [comment]
> No, the first few model refreshes runs fine. And, the same code starts throwing error after a few runs. Demo script failed after 7th refresh.

When you say "few runs" you mean iterations or refresh models? Or you refreshed 6 models correctly and the 7th crashed after a few successful iterations?

> This is the log of 7th run of robyn refresh. It fails after it prints decomp-rssd converged:

It fails but I can't actually see the error message.

> Lastly and before we start debugging, have you tried with the latest dev version and can you please confirm this issue persists with version 3.10.3.9000?

Please, can you confirm?

Ideally, if you can format the logs so that each line is a new line it'll be way easier to read. Thanks!

**Comment by navneetsonak-ds** [comment]
Here's log:

![image](https://user-images.githubusercontent.com/107073950/234392717-db2fa916-8fa2-497b-86a1-3de89cdb8e05.png)

**Comment by laresbernardo** [comment]
No, I wasn't able to replicate. It could be related to [this other issue](https://github.com/facebookexperimental/Robyn/issues/711) though. Both of you are using 3.9.0. I strongly recommend you updating to latest dev version first and see if this issue persists. We can't fix past versions but from current onwards and there are a bunch of [improvements and new features available](https://github.com/facebookexperimental/Robyn/releases) since then.

**Comment by navneetsonak-ds** [comment]
Thanks! But what do you think is causing this? When can the code fail on 'chainData' error, specifically when it's being used to create a dataframe? I'm trying to make sure that this is not an error on my end which can be fixed easily before I commit myself to upgrade to the newer version of Robyn.

**Comment by laresbernardo** [comment]
It seems [unexported function `robyn_chain()`](https://github.com/facebookexperimental/Robyn/blob/main/R/R/json.R#L283-L312) is trying to create a data.frame with vectors lengths 8 and 7 at the same time and returns this error. You can play with it easily, given it only requires de `json_file` as an input (try something like `Robyn:::robyn_chain(your_json_file)` with different files and compare).

**Comment by navneetsonak-ds** [comment]
I upgrade the version of Robyn to '3.10.3.9000'. While trying top replicate the above scenario, my code started failing at robyn_save function(which was running fine in Robyn 3.9.0). I have attached screenshot of the error I'm seeing. Is this a know issue?

![Screen Shot 2023-05-04 at 11 45 19 AM](https://user-images.githubusercontent.com/107073950/236260561-da702085-8088-497d-8db6-78ddea08ee52.png)

**Comment by navneetsonak-ds** [comment]
@laresbernardo Did you get a chance to look into the above error? I'm getting it with latest version of Robyn. Thanks!

**Comment by laresbernardo** [comment]
Ah, I see. You're using `robyn_save()` instead of `robyn_write()`. Can you please try with `robyn_write()` and `robyn_read()`? Notice we stopped supporting `robyn_save()` when we migrated to JSON files (see [demo.R](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R)).

**Comment by navneetsonak-ds** [comment]
I tried robyn_write() as well. Still getting the exact same error i.e " Error in OutputModels$convergence: $ operator is invalid for atomic vectors". Here's what I got when I tried OutputModels$convergence if it helps:

$moo_distrb_plot
Picking joint bandwidth of 0.0215
Picking joint bandwidth of 0.0759

$moo_cloud_plot

$errors
# A tibble: 40 x 15
# Groups:   error_type [2]
   error_type  cuts      n median    std med_var_P first_med first_med_avg
   <chr>       <ord> <int>  <dbl>  <dbl>     <dbl>     <dbl>         <dbl>
 1 DECOMP.RSSD 50       50  0.730 0.0325     NA        0.730         0.723
 2 DECOMP.RSSD 101      50  0.715 0.0452      2.11     0.730         0.723
 3 DECOMP.RSSD 151      51  0.725 0.0400      1.28     0.730         0.723
 4 DECOMP.RSSD 202      50  0.711 0.0488      1.9      0.730         0.723
 5 DECOMP.RSSD 252      51  0.698 0.0472      1.88     0.730         0.723
 6 DECOMP.RSSD 302      50  0.677 0.0454      3.13     0.730         0.723
 7 DECOMP.RSSD 353      50  0.670 0.0504      1.03     0.730         0.723
 8 DECOMP.RSSD 403      51  0.667 0.0587      0.45     0.730         0.723
 9 DECOMP.RSSD 454      50  0.690 0.0647      3.33     0.730         0.723
10 DECOMP.RSSD 504      51  0.650 0.0582      6.14     0.730         0.723
# i 30 more rows
# i 7 more variables: last_med <dbl>, first_sd <dbl>, first_sd_avg <dbl>,
#   last_sd <dbl>, med_thres <dbl>, flag_med <lgl>, flag_sd <lgl>

$conv_msg
[1] "DECOMP.RSSD NOT converged: sd@qt.20 0.068 > 0.039 & |med@qt.20| 0.6 <= 0.65"
[2] "NRMSE NOT converged: sd@qt.20 0.21 <= 0.27 & |med@qt.20| 1.2 > 0.95"        

attr(,"sd_qtref")
[1] 3
attr(,"med_lowb")
[1] 2

**Comment by navneetsonak-ds** [comment]
I'm using the demo data provided on Robyn github repo and the same code as demo.R (which you linked above). I running code on a Databricks cluster and Robyn version is: '3.10.3.9000'. 
----------------------------------------------------------------------------------------------------------------------------

create_files <- TRUE
robyn_directory <- "/dbfs/FileStore/xyz" # folder in databricks file system

data("dt_simulated_weekly")
data("dt_prophet_holidays")

InputCollect <- robyn_inputs(
  dt_input = dt_simulated_weekly,
  dt_holidays = dt_prophet_holidays,
  date_var = "DATE", # date format must be "2020-01-01"
  dep_var = "revenue", # there should be only one dependent variable
  dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)
  prophet_vars = c("trend", "season", "holiday"), # "trend","season", "weekday" & "holiday"
  prophet_country = "DE", # input one country. dt_prophet_holidays includes 59 countries by default
  context_vars = c("competitor_sales_B", "events"), # e.g. competitors, discount, unemployment etc
  paid_media_spends = c("tv_S", "ooh_S", "print_S", "facebook_S", "search_S"), # mandatory input
  paid_media_vars = c("tv_S", "ooh_S", "print_S", "facebook_I", "search_clicks_P"), # mandatory.
  organic_vars = "newsletter", # marketing activity without media spend
  window_start = "2016-01-01",
  window_end = "2018-12-31",
  adstock = "geometric" # geometric, weibull_cdf or weibull_pdf.
)

hyper_names(adstock = InputCollect$adstock, all_media = InputCollect$all_media)
plot_adstock(plot = FALSE)
plot_saturation(plot = FALSE)

hyper_limits()

hyperparameters <- list(
  facebook_S_alphas = c(0.5, 3),
  facebook_S_gammas = c(0.3, 1),
  facebook_S_thetas = c(0, 0.3),
  print_S_alphas = c(0.5, 3),
  print_S_gammas = c(0.3, 1),
  print_S_thetas = c(0.1, 0.4),
  tv_S_alphas = c(0.5, 3),
  tv_S_gammas = c(0.3, 1),
  tv_S_thetas = c(0.3, 0.8),
  search_S_alphas = c(0.5, 3),
  search_S_gammas = c(0.3, 1),
  search_S_thetas = c(0, 0.3),
  ooh_S_alphas = c(0.5, 3),
  ooh_S_gammas = c(0.3, 1),
  ooh_S_thetas = c(0.1, 0.4),
  newsletter_alphas = c(0.5, 3),
  newsletter_gammas = c(0.3, 1),
  newsletter_thetas = c(0.1, 0.4),
  train_size = c(0.5, 0.8)
)

InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)

OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = NULL, 
  iterations = 1000, 
  trials = 1,
  ts_validation = TRUE, 
  add_penalty_factor = FALSE
)

OutputCollect <- robyn_outputs(
  InputCollect, OutputModels,
  pareto_fronts = "auto", 
  csv_out = "pareto", 
  clusters = TRUE, 
  export = create_files, 
  plot_folder = robyn_directory, 
  plot_pareto = create_files

print(OutputCollect)

#Compare all model one-pagers and select one that mostly reflects your business reality
select_model <- "1_10_13" 

ExportedModel <- robyn_write(InputCollect, OutputCollect, select_model, export = create_files)
print(ExportedModel)

----------------------------------------------------------------------------------------------------------------------------
code fails on robyn_write(). Please let me know if you need any more info from my side.

**Comment by laresbernardo** [comment]
Hi @navneetsonak-ds thanks for the reproducible example. I've run exactly the same code and am not experiencing this error. Are you getting [this](https://github.com/facebookexperimental/Robyn/issues/707#issue-1683686388) error when running this code you shared? Wasn't the original issue a problem with refresh models?

**Comment by navneetsonak-ds** [comment]
Yes. When I was using Robyn version 3.9.0, I was getting error with robyn_refresh() function. And then upgraded the Robyn version to 3.10.3.9000 and started getting error with robyn_write() function.

Did you run the code on Robyn 3.10.3.9000? Anything else I can try?

**Comment by laresbernardo** [comment]
> upgraded the Robyn version to 3.10.3.9000 and started getting error with robyn_write() function.

Is the error you are getting exactly the same you shared when refreshing? That doesn't make much sense given we don't use chainData if not refreshing nor exporting a model.

> Did you run the code on Robyn 3.10.3.9000? Anything else I can try?

Correct. Latest dev version. And the error didn't show up. Try on a fresh new session. I honestly have no idea why are you experiencing this issue (and others aren't) but must be related to the instance or R version.

**Comment by navneetsonak-ds** [comment]
No, the error with Robyn version 3.9.0 was related to chainData(robyn_refresh function). Error with Robyn version 3.10.3:9000 is "Error in OutputModels$convergence: $ operator is invalid for atomic vectors" (robyn_write function). Both are separate errors and  are not related to each other.

Ok. Thanks!

**Comment by laresbernardo** [comment]
Ok, ideally to report different issues it's better to have 2 different tickets so we can split un-related problems.

Given I wasn't able to replicate these errors I can't seem to understand the issue nor fix it if necessary. With the provided code I wasn't able to replicate neither of the issues reported. Nevertheless, I'll leave this ticket open in case someone else experiences the same problem or you want to provide additional information.
