### ISSUE TITLE
Challenges in Budget Allocation: Overall ROI Lower than Raw Data

### ISSUE THREAD

**Issue by chloeeeee666** [facebookexperimental/Robyn#715]
We are a digital agency that tries to use Robyn to allocate a fixed budget among several channels to achieve a specific ROI. We know the original contribution of each channel in terms of cost and revenue, and we try to use models that yield a close ROI for each channel. Recently, we discovered that the intercept and some prophet variables could account for 50% of the total revenue(the model has a 85 R^2), leading to a significant decrease in all channel individually and overall ROI. Given these findings, we are questioning whether Robyn is the best method for budget allocation in my case. If it is, how can we attribute the intercept contribution to individual channels? I would appreciate hearing your thoughts.

**Comment by gufengzhou** [comment]
Hi, without questioning your believe of "We know the original contribution of each channel" (and you should always, esp when the knowledge is coming from attributional system), I recommend you to update to the latest github version of Robyn, where we have a stricter constraint for prophet variables. Moreover, if you strongly believe that your "prior knowledge" about channel effect is the ground truth, then you could also use the calibration feature to guide Robyn to the desired direction.

The allocator is a separate piece and it does provide the target_efficiency scenario if you have a target ROAS. But you need to pick a model first.
