### ISSUE TITLE
The best model selected through refresh is not plotted

### ISSUE THREAD

**Issue by ghltk** [facebookexperimental/Robyn#716]
After refreshing my initial model, '1_65_10' is selected as the best. 
The folder where all the outputs of refresh model are saved, there are several Onepager plots but I can't find Onepager for the 1_65_10 model.
However, refresh model was saved with the name '1_65_10.json' and report_decomposition came out from that Model ID.
I think the onepager for the selected model should be output. 
I would be grateful if you could explain what I'm misunderstanding.

Thank you

-Environment & Robyn version
Robyn version: 3.10.3.9000
R version 4.1.3 (2022-03-10)

![image](https://user-images.githubusercontent.com/131640422/235578485-9d65cb4f-35f9-4e2d-abce-a81afcb1989e.png)
![image](https://user-images.githubusercontent.com/131640422/235580350-659375d6-ba7d-41c8-baf9-f656522df223.png)

**Comment by ghltk** [comment]
@gufengzhou 
This bug will be fixed in the next update? Could I ask when the next update is scheduled?

**Comment by Amyhaoming** [comment]
Hi @ghltk, I'm looking into this and will get back to you asap.

**Comment by gufengzhou** [comment]
this is being dealt with in the latest issue [here](https://github.com/facebookexperimental/Robyn/issues/960). Please follow there.
