### ISSUE TITLE
Different performance metrics than NRMSE 

### ISSUE THREAD

**Issue by lisazaki** [facebookexperimental/Robyn#717]
I saw a past issue post and response that it is technically possible to include MAPE instead of NRMSE. Now i have further questions on how to do them. 

Is it possible to do it without calibration? If so, how can I do it?
Also, if I want to manually calculate MAPE to compare with another model, is it possible to extract the prediction results and hold-out-data? 

Thanks in advance for any helps!

**Comment by gufengzhou** [comment]
You can use OutputCollect$xDecompVecCollect or the pareto_alldecomp_matrix.csv to calculate MAPE by yourself. dep_var is the true dependent, depVarHat is the predicted dependent
