### ISSUE TITLE
Definition of MAPE on Robyn e-Course website

### ISSUE THREAD

**Issue by SeanRichterWalsh** [facebookexperimental/Robyn#718]
## Describe issue
MAPE is described as Mean Average Percentage Error. I am familiar with MAPE as Mean Absolute Percentage Error. Looking for clarity here on what Robyn uses as MAPE. Thanks.

![image](https://user-images.githubusercontent.com/42702165/236153758-cbff2023-e9a6-4057-9c80-804e41319711.png)

**Comment by gufengzhou** [comment]
Hey sorry that's a typo. You're right.
