### ISSUE TITLE
Error: Error creating conda environment 'r-reticulate' [exit code 1]

### ISSUE THREAD

**Issue by martins2022** [facebookexperimental/Robyn#719]
Hi! I'm new to Robyn. Currently installing nevergrad via pip

# 2. create virtual environment
virtualenv_create("r-reticulate")

This error appears.

> virtualenv_create("r-reticulate")
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: Y
* Installing Miniconda -- please wait a moment ...
+ "C:/Users/XXXXXX/AppData/Local/r-miniconda/condabin/conda.bat" update --yes --name base conda
Collecting package metadata (current_repodata.json): ...working... failed

CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

Exception: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

+ "C:/Users/XXXXX/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--name" "r-reticulate" "python=3.8" "numpy" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... failed

CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

Error: Error creating conda environment 'r-reticulate' [exit code 1]

**Comment by martins2022** [comment]
Thank you for this. I am using my office laptop for this. But when I used my personal laptop, it went smoothly.

**Comment by laresbernardo** [comment]
Yes, this problem occurs usually when using companies' laptops and installing stuff goes against their default policies and permissions. Thanks for confirming.
