### ISSUE TITLE
Ridge Regression - where to apply priors?

### ISSUE THREAD

**Issue by famendez7** [facebookexperimental/Robyn#72]
Hi Team, regarding ridge regression, was wondering if it's possible to choose what prior (weight) to apply to each of the variables? Would be useful to force in variables that the model dropped from the model (coef=0) Thanks

**Comment by gufengzhou** [comment]
Hi, this can be achieved by using the parameter penalty.factor in glmnet, see the library documentation [here](https://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html) 
![image](https://user-images.githubusercontent.com/14415136/116402336-96628b00-a82c-11eb-8100-63666df9dbb9.png)
