### ISSUE TITLE
object 'dt_modAdstocked' not found

### ISSUE THREAD

**Issue by ChrisHaferl** [facebookexperimental/Robyn#720]
## Describe issue
Trying to calibrate with calibration_input but getting error `Error in { : task 1 failed - "object 'dt_modAdstocked' not found"` when running `robyn_run`.

## Provide reproducible example
calibration_input defined:
`calibration_input <- data.frame(
 channel = c("channel1",  "channel1"),
 liftStartDate = as.Date(c('2022-10-06', '2022-10-06')),
 liftEndDate = as.Date(c('2022-12-07', '2022-12-07')),
 liftAbs = c(44200, 1017900),
 spend = c(149099, 113658),
 confidence = c(0.83, 0.83),
 metric = c("revenue_usa", "revenue_usa"),
 calibration_scope = c("immediate", "immediate")
 )`

`InputCollect <- robyn_inputs(InputCollect = InputCollect, calibration_input = calibration_input)`

robyn_input here (this is the step with the error):
`OutputModels <- robyn_run(
  InputCollect = InputCollect, 
  iterations = 2000,
  trials = 10,
  ts_validation = TRUE,
  seed = 5128
)
print(OutputModels)`

Error Traceback:
<img width="1220" alt="Screen Shot 2023-05-04 at 1 34 55 PM" src="https://user-images.githubusercontent.com/46723137/236311022-46b461da-e356-4d5a-9fce-214e5f04d43d.png">

## Environment & Robyn version
‘3.10.3.9000’

**Comment by laresbernardo** [comment]
Hi @ChrisHaferl I can't seem to be able to replicate this issue. I've checked for `dt_modAdstocked` usage around and I don't see any issue either. Would you mind trying to update to latest version again, retrying, and confirming if the issue persists? If so, please share a reproducible example. I've tested using the demo data modifying your data.frame a bit and the error didn't show up, with "immediate" not "total".

```
calibration_input <- data.frame(
  channel = c("facebook_S",  "tv_S"),
  liftStartDate = as.Date(c('2017-10-06', '2017-10-06')), 
  liftEndDate = as.Date(c('2017-12-07', '2017-12-07')), 
  liftAbs = c(44200, 1017900),
  spend = c(149099, 113658), 
  confidence = c(0.83, 0.83), 
  metric = c("revenue", "revenue"),
  calibration_scope = c("immediate", "immediate"))
```

**Comment by ChrisHaferl** [comment]
Updated to the latest version again and it seems to be working fine now, haven't changed anything else. Thanks for checking on it. This can be closed!
