### ISSUE TITLE
Filter error on adding calibration input to robyn_inputs

### ISSUE THREAD

**Issue by vaishnav-ira** [facebookexperimental/Robyn#723]
## Describe issue
Error in `filter()`:
i In argument: `get(date_var) >= temp$liftStartDate`.
Caused by error in `temp$liftStartDate`:
! $ operator is invalid for atomic vectors
Run `rlang::last_trace()` to see where the error occurred.

Receiving this error on the following code

calibration_input <- data. Frame(
  channel = c("display_s","sp_s"),
  liftStartDate = c("2022-04-01","2022-04-01"),
  liftEndDate = c("2022-05-01","2022-05-01"),
  liftAbs = c(74314,1234),
  spend = c(50888,56478),
  confidence = c(0.8,0.8),
  metric = c("revenue","revenue"),
  calibration_scope = c("immediate","immediate")
)
InputCollect <- robyn_inputs(InputCollect = InputCollect, calibration_input = calibration_input)

## Environment & Robyn version
> packageVersion("Robyn")
[1] ‘3.10.3.9000’
> R.version$version.string
[1] "R version 4.1.3 (2022-03-10)"

**Comment by laresbernardo** [comment]
Hi! I've noticed a couple of things here:
- I guess it's a typo but `data. Frame(...` should be `data.frame(...`
- I see in your sample data that the dependent variable es named "revenue" and you're setting "revenue_i" as metric. Is this intended? It should have popped out an explanatory error when checking the input.
- I can't seem to replicate the error. Would you mind sharing the code importing this CSV and all the steps I can follow to replicate this issue please?

This is the reproducible example I tested with:

```
# Import the CSV data
df <- read.csv("~/Desktop/Sample_input.csv")
df$date_i <- as.Date(df$date_i, tryFormats = "%d-%m-%Y")
# Dummy hyperparameters for the sake of the checks
hyperparameters <- list(
  sp_s_alphas = c(0.5, 3),
  sp_s_gammas = c(0.3, 1),
  sp_s_thetas = c(0, 0.3),
  display_s_alphas = c(0.5, 3),
  display_s_gammas = c(0.3, 1),
  display_s_thetas = c(0.1, 0.4),
  train_size = c(0.5, 0.8)
)
# Create InputCollect with no calibration data
InputCollect <- robyn_inputs(
  df, dep_var = "revenue_i", dep_var_type = "revenue",
  paid_media_spends = c("display_s", "sp_s"),
  adstock = "geometric",
  hyperparameters = hyperparameters)
calibration_input <- data.frame(
  channel = c("display_s","sp_s"),
  liftStartDate = c("2022-04-01","2022-04-01"),
  liftEndDate = c("2022-05-01","2022-05-01"),
  liftAbs = c(74314,1234),
  spend = c(50888,56478),
  confidence = c(0.8,0.8),
  metric = c("revenue_i","revenue_i"),
  calibration_scope = c("immediate","immediate")
)
# Add calibration data to InputCollect
InputCollect <- robyn_inputs(
  InputCollect = InputCollect,
  calibration_input = calibration_input)
```

```
Warning messages:
1: In check_calibration(dt_input = InputCollect$dt_input, date_var = InputCollect$date_var,  :
  Your calibration's spend (50,888) for display_s between 2022-04-01 and 2022-05-01 does not match your dt_input spend (~508.9K). Please, check again your dates or split your media inputs into separate media channels.
2: In check_calibration(dt_input = InputCollect$dt_input, date_var = InputCollect$date_var,  :
  Your calibration's spend (56,478) for sp_s between 2022-04-01 and 2022-05-01 does not match your dt_input spend (~668.3K). Please, check again your dates or split your media inputs into separate media channels.
```
