### ISSUE TITLE
Budget Allocator Optimum Original Plot

### ISSUE THREAD

**Issue by rayjin2022** [facebookexperimental/Robyn#725]
## Describe issue
I was trying to get the optimized budget allocation, and expecting to get results as is shown in Robyn document.
![image](https://user-images.githubusercontent.com/100131499/236619657-30084852-2bd0-4258-8b88-97d3fdb4a15c.png)

However, I got something as below:
![recent_budget_allocator](https://user-images.githubusercontent.com/100131499/236619673-6d860ffe-ff2e-416e-821b-cea8c4eed960.png)

## Provide reproducible example
I was using demo code trying to regenerate the result:

`AllocatorCollect1 <- robyn_allocator(
  InputCollect = InputCollect,
  OutputCollect = OutputCollect,
  select_model = select_model,
  channel_constr_low = 0.7,
  channel_constr_up = c(1.2, 1.5, 1.5, 1.5, 1.5),
  scenario = "max_response",
  export = create_files
)
print(AllocatorCollect1)
plot(AllocatorCollect1)`

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)
I'm using Robyn version 3.10.3.9000 and R version 4.3.0

**Comment by gufengzhou** [comment]
we've released an update for the allocator recently. sorry that the documentation is lagging behind. @michellegrushkometa @laresbernardo  FYI
