### ISSUE TITLE
Impressions from channel but no spend information. 

### ISSUE THREAD

**Issue by hd-fernandez** [facebookexperimental/Robyn#726]
## Describe issue
Not really an error, but I'm putting together the dataset to use for Robyn. If I have data on a channel's impressions but not the channel's spend -- do I include the impression variable?

A similar question I have is: If they're organic impressions, do I just leave them in? 

Wondering what people have done in this situation.

Thanks!

**Comment by laresbernardo** [comment]
Hi @hd-fernandez 
Are you referring to a paid channel that you don't have the spend information of? If that's the case, you must have spend data for it to make sense. If it's organic, it's OK to pass it via the organic variables. Keep in mind we will be able to use the budget allocator afterwards only with paid media variables.

**Comment by hd-fernandez** [comment]
@laresbernardo Got it. So if it's a paid channel, it must have spend data if I am going to include the impressions. If it's organic, put it into the organic variable argument. Thank you!

**Comment by AdimDrewnik** [comment]
So in the case described in this thread paid channel without known spend but with known impression data should be excluded from the model? Or is it better to treat it as if it was organic?
