### ISSUE TITLE
hyperparameters'names  are paid_media_spends but not paid_media_vars

### ISSUE THREAD

**Issue by wjxkq** [facebookexperimental/Robyn#727]
## Describe issue
Describe your issue and provide warnings and error messages.

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)

**Comment by wjxkq** [comment]
I have a question, why my hyperparameters'names  are paid_media_spends but not paid_media_vars?Aren't the parameters of adstock and suration specific to paid_media_vars?

**Comment by laresbernardo** [comment]
Please, read the documentation by running `?robyn_inputs`. 

> paid_media_spends | Character vector. When using exposure level metrics (impressions, clicks, GRP etc) in paid_media_vars, provide corresponding spends for ROAS calculation. For spend metrics in paid_media_vars, use the same name. media_spend_vars must have same order and same length as paid_media_vars.

> paid_media_vars | Character vector. Recommended to use exposure level metrics (impressions, clicks, GRP etc) other than spend. Also recommended to split media channel into sub-channels (e.g. fb_retargeting, fb_prospecting, etc.) to gain more variance. paid_media_vars only accepts numerical variable.

In short, we use paid_media_spends to model and paid_media_vars only to check correlations between spend and the exposure metric and provide recommendations when it's low.

**Comment by wjxkq** [comment]
So the result of the hyperparameters'names should be spend, right?

**Comment by gufengzhou** [comment]
We've migrated to spend only modelling a while ago. So hyppar requires spend names now. The video's not updated unfortunately. However you can still use GRPs etc in paid_media_vars, where you'll get some extra information. You can see the fit between spend and GRP by running `InputCollect$modNLS$plots`. If you observe a good fit, then spend and GRP are providing similar information in the modelling. If the fit is not good, you might want to consider splitting this variable. For Meta for example, you could split by objectives (reach vs. retargeting), or something else that makes sense to you.
