### ISSUE TITLE
one pager not produced anymore

### ISSUE THREAD

**Issue by lisazaki** [facebookexperimental/Robyn#728]
If I am correct, OutputCollect allow to produce some candidate models that I can choose from by produing one-pager PNG. 
However, after running different models for several times, my Robyn stopped producing png files of one-pager summary of the best models. 

I ran the following codes; 
OutputCollect <- robyn_outputs(
  InputCollect, OutputModels,
  pareto_fronts = "auto", # automatically pick how many pareto-fronts to fill min_candidates
  min_candidates = 100, # top pareto models for clustering. Default to 100
  csv_out = "pareto", # "pareto", "all", or NULL (for none)
  clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
  plot_pareto = TRUE, # Set to FALSE to deactivate plotting and saving model one-pagers
  plot_folder = robyn_object, # path for plots export
  export = TRUE # this will create files locally
)
print(OutputCollect)

I also tried to produce the one pager by running another code; 
robyn_onepagers(
  InputCollect,
  OutputCollect,
  select_model = "clusters" ,
  quiet = FALSE,
  export = TRUE
)

 but I got the error message: error writing to connection.

How can I fix this issue ?

**Comment by laresbernardo** [comment]
@lisazaki  When you say "stopped" you mean it was creating plots and suddenly it wasn't? 
I've search for that "error writing to connection" error and it seems either the directory you defined for "robyn_object" doesn't exist or you don't have permission to write to it or there is insufficient room on your drive to  save the files. Please check all of those and feel free to report back which one was it.

**Comment by lisazaki** [comment]
I ran the model for several times, and every time it saved a local folder "Robyn_dates_init" of all the csv and png of candidate one-pager that I can compare. But yes, now it does not produce any one-pager png anymore, but only csv and png files of other things. I believe that in this case, robyn_object is correctly identified and there is till room on my drive to save files. 

I assumed that the code of Outputcollect would produce the Top N models one-pager to compare for the step 4 of producing the selected model results, but let me know if I am wrong.

**Comment by laresbernardo** [comment]
Hi @lisazaki not sure I do understand what you mean. Yes, the intended behaviour is for `OutputCollect` to contain the top results based on clustering and lowest combined errors so that user can pick out the one that better reflects their business out of those provided models. If you print `OutputCollect`, then you'll see the IDs of the top models you can pick from. Can you share the result of `print(OutputCollect)`?

I've also noticed `select_model = "clusters"` in you example for `robyn_onepagers()`. That's not correct. You should pick of the available model IDs.

**Comment by lisazaki** [comment]
the result of print (Outputcollect) is  a list of different models (in the format of X_XXX, Y_YYY,...) followed by the number of clusters and selected model. So yes, the Outputcollect indeed indicates  the top candidate in the text format. However, I do not have any png files of one-pagers of those selected models in the folder. I thought that it should be produced when plot_pareto = TRUE, so that I can compare the one-pagers before actually selecting the one model. Is my understanding incorrect?

I also tried with the approach of updating Robyn and running the robyn_onepagers code again. But then I encountered some issues that NRMSE is not converged anymore. Has there been any update about the computation? My input variables has not changed at all.

**Comment by gufengzhou** [comment]
Does this problem still persists? Am I understanding you right that only onepager png are not plotting, other png are ok?

**Comment by LMiddles** [comment]
having the same error code for output collect

**Comment by gufengzhou** [comment]
please see the latest related issue https://github.com/facebookexperimental/Robyn/issues/964
