### ISSUE TITLE
Issue downloading Nevergrad

### ISSUE THREAD

**Issue by shalinibattoo** [facebookexperimental/Robyn#729]
## Describe issue
I am trying to install nevergrad on my machine, MacOS Big Sur, Version 11.6.8, but am unable to do so. I have tried multiple things but I am somehow getting this error everytime - `sh: /Users/shalinibattoo/.virtualenvs/r-reticulate/bin/python: No such file or directory`
<img width="964" alt="Screenshot 2023-05-12 at 9 08 47 PM" src="https://github.com/facebookexperimental/Robyn/assets/23060914/76b51dae-8c74-4dd7-bafa-2fdfd1a4940f">

## Provide reproducible example
I tried running these lines:
```
library(reticulate)
Sys.setenv(RETICULATE_PYTHON = "/usr/local/bin/python3.11")
reticulate::virtualenv_create("r-reticulate")
reticulate::virtualenv_install("r-reticulate", c("nevergrad", "numpy"))
```
<img width="961" alt="Screenshot 2023-05-12 at 9 11 55 PM" src="https://github.com/facebookexperimental/Robyn/assets/23060914/560d6d3a-fc25-4629-acce-a65b5c0fcc25">

The issue is I have a Python environment setup in my machine and I cannot get the machine to use the python version installed which is 3.11 and is available at `/usr/local/bin/python3.11`. But whenever I run `which python` on my terminal I get this `/Users/shalinibattoo/.pyenv/shims/python`

I even tried to do use_python() by setting the path as `/Users/shalinibattoo/.pyenv/shims/python`, but it does not work and I get this below error.
<img width="975" alt="Screenshot 2023-05-12 at 9 15 55 PM" src="https://github.com/facebookexperimental/Robyn/assets/23060914/32d44ed6-e825-47ba-ab29-f3742909940f">

I tried to rebuild python by using this on the command line
`env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.1` but even this does not work and gives the below error
<img width="1101" alt="Screenshot 2023-05-12 at 9 33 54 PM" src="https://github.com/facebookexperimental/Robyn/assets/23060914/5b7874e0-7015-48a3-881f-7c39b47814bc">

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn version `3.9.0`
- R version `4.3.0`

**Comment by laresbernardo** [comment]
Similar to #697. Closing this task.
