### ISSUE TITLE
Error in Robyn Refresh

### ISSUE THREAD

**Issue by JJohnson-DA** [facebookexperimental/Robyn#731]
## Describe issue
When trying to use robyn_refresh() I get the following error

```
>>> Building refresh model #1 in manual mode
>>> New bounds freedom: 3.62%
Error in if (newLowB < getRange[1]) { : argument is of length zero
In addition: Warning message:
Unknown or uninitialised column: `lambda_max`
```

I started looking at the code and I think the issue may be in `Robyn/R/R/refresh.R` on [`line 532`](https://github.com/facebookexperimental/Robyn/blob/main/R/R/refresh.R#L532). The code is trying to pull from column `lambda_max` which doesn't exist in `listOutputPrev$resultHypParam`. This causes an issue with the value calculated on `line 534` which then causes the error being thrown from `line 539`.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn version: 3.10.2.9000
- R version: 4.2.1

**Comment by laresbernardo** [comment]
Hi @JJohnson-DA that was actually a temporal bug we noticed and fixed some weeks ago. Would you mind updating to latest version and retry? Thanks for confirming afterwards.

**Comment by laresbernardo** [comment]
Additionally, if it doesn't work updating, please try recreating the model from scratch given the `lambda_max` values might have not been exported when you built the model with that buggy dev version, and retry running the refresh function.

**Comment by JJohnson-DA** [comment]
@laresbernardo, that seems to have fixed the issue. Thanks for the quick response! I hadn't realized you had released a new version yesterday.

**Comment by laresbernardo** [comment]
That's OK! We are constantly updating Robyn. Thanks for getting back. Closing this task.
