### ISSUE TITLE
Clarify `hyper_names` documentation

### ISSUE THREAD

**Issue by richin13** [facebookexperimental/Robyn#732]
## Describe issue

I noticed an inconsistency in the documentation of the `hyper_names` function, where for `all_media` it reads:

> A character vector. Default to InputCollect$all_media. Includes InputCollect$paid_media_vars and InputCollect$organic_vars.

But then, `InputCollect$all_media` [gets set to `paid_media_SPENDS` + `organic_vars`](https://github.com/facebookexperimental/Robyn/blob/a6af850efd325298593941f3abe395fcf1b2b9d3/R/R/inputs.R#LL239C7-L239C7)

So my question is, is it the docs that are incorrect or the way `all_media` is being built in the `robyn_inputs` function?

**Comment by laresbernardo** [comment]
Yes, definitely an inconsistency on the documentation. Thanks for reporting it @richin13, we'll take care of it ASAP.

**Comment by laresbernardo** [comment]
I've updated the `paid_media_spends` and `paid_media_vars` parameters definitions and fixed the `all_media` on `hyper_names()` too. These are legacy errors from when we started modeling with exposure instead of spend variables.

```
paid_media_spends | Character vector. Names of the paid media variables. The values on each of these variables must be numeric. Also, paid_media_spends must have same order and length as paid_media_vars respectively.

paid_media_vars | Character vector. Names of the paid media variables' exposure level metrics (impressions, clicks, GRP etc) other than spend. The values on each of these variables must be numeric. These variables are not being used to train the model but to check relationship and recommend to split media channels into sub-channels (e.g. fb_retargeting, fb_prospecting, etc.) to gain more variance. paid_media_vars must have same order and length as paid_media_spends respectively and is not required.
```

Thanks again for reporting it and your feedback. Feel free to close if everything makes sense now.

**Comment by richin13** [comment]
Awesome, thank you for the quick response/fix!
