### ISSUE TITLE
Understanding Input for Response Curves 

### ISSUE THREAD

**Issue by slavakx** [facebookexperimental/Robyn#736]
Hi, 

I'd like to understand how mean spend that is shown on the response curve is calculated? My assumption was that it is a mean spend within the start-end window for a media channel. However, the number do not match and vary from model to model. Same question to the x-axis which doesn't show the complete spend range

Thanks!

**Comment by gufengzhou** [comment]
Are you talking about the onepager response curve? By default, it uses the mean spend of last month (so for weekly data it's the last 4 weeks, daily it's last 30 days etc.). The reasoning behind is that we want to reflect your most recent spending level that should be more actionable is most cases. The x-axis relates to that.

**Comment by SeanRichterWalsh** [comment]
Is it still the case? I am checking recent 4-week mean and not seeing the numbers on the 1-pager response curves.
