### ISSUE TITLE
Segfault caused when running 12k iters and 12 trials

### ISSUE THREAD

**Issue by sbookhultz** [facebookexperimental/Robyn#737]
## Project Robyn
Wanted to thank both Bernardo and Gufeng (and the rest of the team), y'alls work on Robyn has been an excellent tool for creating and understanding MMMs. 

## Describe issue
I currently run Robyn on a server with a total of 4 cores (single threaded) with 64GB of RAM. I was running a Robyn model for 12k iterations and 12 trials (I've successfully ran a model with 30k iters and 4 trials), and with a dataset that's weekly with 235 weeks and 50 hyper parameters to optimize, I thought it would compile fine enough in approximately 12 hours. 

I tried to run an identical version of this yesterday, and Robyn just stopped compiling results for the Pareto front calc 4/4 (total). 

When I ran it last night, I got a segfault error on trial 10/12: Picture:

![screenshot_2023-05-24_at_8 55 40_am_720](https://github.com/facebookexperimental/Robyn/assets/109177324/4ae811bc-e749-4f99-829f-af6703ea5d4e)

## Provide reproducible example
I can provide more reproducible results, but here is initial set up.

In check_hyperparameters(InputCollect$hyperparameters, InputCollect$adstock,  :
  Automatically added missing hyperparameter range: 'train_size' = c(0.5, 0.8)
Input data has 235 weeks in total: 2018-07-01 to 2022-12-25
Initial model is built on rolling window of 235 week: 2018-07-01 to 2022-12-25
Fitting time series with all available data...
Using geometric adstocking with 50 hyperparameters (49 to iterate + 1 fixed) on 3 cores
>>> Starting 12 trials with 12000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 12

## Environment & Robyn version
Make sure you're  using the latest Robyn version before you post an issue. (Not sure if 3.10.3 has fixed this, or if this is a non-standard issue)
R version: 4.1.1
Robyn version: 3.9.0

**Comment by gufengzhou** [comment]
Thanks! We haven't seen this sofar. An initial research suggests it might be memory issue. Are you using the latest dev version? Because we had a big objective size reduction commit since 3.9.0 which might help.

**Comment by sbookhultz** [comment]
Yeah I upgraded the CPU and increase RAM allocation to this and it seemed to fix. On your guy's end, what's the largest number of iterations / trials were you able to run in a single robyn_run statement?

**Comment by gufengzhou** [comment]
This really depends on your infrastructure. Many users run Robyn on the cloud and scale it up greatly. We don't have visibility into that unfortunately.
