### ISSUE TITLE
Robyn Allocator Function Prioritizing Minimization Over Optimization

### ISSUE THREAD

**Issue by shamzos** [facebookexperimental/Robyn#738]
Body: 

**Description:**
I'm experiencing an issue with the Robyn Allocator function, where it seems to prioritize minimizing spend rather than optimizing it. 

**Details:**
While working on the Robyn model, I expected the allocator function to distribute the spend in an optimal way based on given data. However, I've noticed that it appears to minimize spend instead, which does not yield the most efficient outcomes.

**Expected Behavior:**
I expected the allocator function to distribute spend in a manner that optimizes output, instead of merely minimizing spend.

**Screenshots:**
I've attached a screenshot to demonstrate this issue.

![Screenshot from 2023-05-24 11-01-00](https://github.com/facebookexperimental/Robyn/assets/8883242/b1be8888-16ef-4f38-aadd-9a469001f94f)

**Environment:**
- Robyn version: 3.10.3
- Operating System: ubuntu EC2 AWS
- R version: 

I would greatly appreciate your help on this issue. Thank you in advance!

**Comment by gufengzhou** [comment]
Hi, we're looking into this issue systematically so it'll take some time for a final fix. But meanwhile you could just raise your lower bound, that will already force the allocator to "go higher". I'm seeing you having lower bounds to 0, which allows these channels and also the total budget to go 0.

**Comment by shamzos** [comment]
in that case, it always chooses the lower bound. thank you for your support.

**Comment by gufengzhou** [comment]
Ok I missed it. Your display channel hast no effect, so there's only one channel left and thus nothing to optimised. You need to choose a model in which both channels have >0 effects.
