### ISSUE TITLE
Robyn Allocator: Can't find `stat` called 'align'

### ISSUE THREAD

**Issue by mtodisco10** [facebookexperimental/Robyn#739]
When trying to run `robyn_allocator` I am receiving the below error.  Can you please assist?

![image](https://github.com/facebookexperimental/Robyn/assets/13875567/720d8ea8-3e16-46b6-a8fa-894d77ebe90d)

- Robyn version 3.10.3
- R version 4.1.3

**Comment by CMoranoA** [comment]
Same problem here!

**Comment by gufengzhou** [comment]
It's a ggplot issue. Can you update ggplot and retry?

**Comment by mtodisco10** [comment]
Updating ggplot2 to latest version 3.4.2 solved this issue for me.  Thank you.
