### ISSUE TITLE
Immedaite vs Carryover Response and bootstrapped ROl Plots

### ISSUE THREAD

**Issue by ilborobio** [facebookexperimental/Robyn#742]
## Describe issue
Hello there,

I've just updated the Roby library and I have discovered that there are two additional plots in one-model-pager. But I cannot find any reference in the official documentation and no info about their meaning.

I can imagine their surface meaning. But, like with the other plots, is there any place where I can find explanations about this two new plots? Or can someone explain them here?

Thanks a lot!

Iván

**Comment by gufengzhou** [comment]
sorry we're lagging behind with documentation. This is the release post. https://www.facebook.com/groups/robynmmm/posts/1310953473006116 

More details also in this note https://medium.com/p/f608841fc6d4
