### ISSUE TITLE
Zero Spend Channels Included in Allocator

### ISSUE THREAD

**Issue by mtodisco10** [facebookexperimental/Robyn#744]
When running `robyn_allocator` with scenario as `max_response` I'm seeing channels included that had 0 spend in the allocator date_range.  Is this intentionally?  Is there a way to only optimize over channels with spend in the designated dates?

- Robyn version 3.10.3
- R version 4.1.3

**Comment by mtodisco10** [comment]
I'm also seeing an increase in Spend in the "Bounded" pillar with the `max_response` scenario.  Shouldn't spend be fixed in this case?
![image](https://github.com/facebookexperimental/Robyn/assets/13875567/82cb5e8f-db98-4e40-ba9c-6275e1cbab56)

**Comment by gufengzhou** [comment]
> 

To this, yes it's intentional. You can set lower and upper bound for that channel to 1 and 1 to not allow any new allocation.

**Comment by gufengzhou** [comment]
> I'm also seeing an increase in Spend in the "Bounded" pillar with the `max_response` scenario. Shouldn't spend be fixed in this case? ![image](https://user-images.githubusercontent.com/13875567/242391395-82cb5e8f-db98-4e40-ba9c-6275e1cbab56.png)

This looks like a bug. I'd need your dataset, the selected model json & your allocator function specs to debug this error though. Any chance you can share those?

**Comment by mtodisco10** [comment]
I'm unfortunately not at liberty to share our dataset or the model json, but here's a snapshot of the allocator function: 
![image](https://github.com/facebookexperimental/Robyn/assets/13875567/730a6b3b-ed11-4886-a98b-6f2cdaed9628)

**Comment by mtodisco10** [comment]
> > When running robyn_allocator with scenario as max_response I'm seeing channels included that had 0 spend in the allocator date_range. Is this intentionally? Is there a way to only optimize over channels with spend in the designated dates?
> 
> To this, yes it's intentional. You can set lower and upper bound for that channel to 1 and 1 to not allow any new allocation.

Can you share what date ranges are used to make decisions for channels that have $0 spend during the reallocation period?  Is it the entirety of `window_start` to `window_end` defined in the `robyn_inputs` functions?  Previous year's reallocation period?
