### ISSUE TITLE
Adjusted R2 for test data should not be used

### ISSUE THREAD

**Issue by sahbakn** [facebookexperimental/Robyn#745]
Based on the formula for adjusted R-squared which has an adjustment on R-squared based on number of parameters and sample size, the proposed Adjusted R-squared for test data in Robyn is misleading to the user and it needs to be used only for the train dataset. The test data being much smaller in size compared to the train data, we could potentially have a very different level of adjustment and we end up with very different values for adjusted R-squared from test and train, not because of overfitting, but because of different adjustment levels (more likely to get negative adjusted R2 for test too). 
I propose adding MAPE for train and test data or the original R-squared when it comes to comparing between test and train and keeping the adjustment R2 only for train data

**Comment by gufengzhou** [comment]
Hi, this is already considered. When using ts_validation, the rsq_test will take the sample size of the training set. I would love to know your feedback if this makes sense to you. 

https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R#L1087
