### ISSUE TITLE
Why spend shares % from the one pager do not match with the Initial Avg. Spend Shares % that we get from the budget allocator? 

### ISSUE THREAD

**Issue by CJ2407** [facebookexperimental/Robyn#747]
## Describe issue
For some paid channels, both the spend share %s are close, but for some channels these %s are very off between one pager and budget allocator plot 1.

![image](https://github.com/facebookexperimental/Robyn/assets/91983160/e28b0131-9d47-4145-9823-56dfbddd777e)
![image](https://github.com/facebookexperimental/Robyn/assets/91983160/41d3be1f-9e59-4963-92e8-fcf9aecd1846)

Channels that concern me are Tiktok, Pinterest, Facebook Prospecting, Display Remarketing, Paid Search PLA, etc.

Both the charts are showing % spend share for the entire modeling period right (Cz in allocator function I kept date_range = NULL)? Please correct, if my understanding is incorrect. Thanks!

**Comment by gufengzhou** [comment]
Please check my last reply in this thread: https://github.com/facebookexperimental/Robyn/issues/734#issuecomment-1590407471

**Comment by gufengzhou** [comment]
Feel free to reopen if there're more questions.
