### ISSUE TITLE
Channels with Coefficients of 0 in the Budget Allocator

### ISSUE THREAD

**Issue by mtodisco10** [facebookexperimental/Robyn#748]
I'm looking to keep the optimized spend for channels with coefficients = 0 constant.  ie if channel X had $100 in historical spend and a 0 coefficient, the optimized spend should remain $100.  I tried achieving this by setting upper and lower constraints to 1, but it is still outputting the optimized spend as $0 for these channels (and reallocating elsewhere).  

Is it possible to get this desired output?

**Comment by gufengzhou** [comment]
In my opinion you should select another model with coef >0. the allocator will always exclude coef 0 channels because the return is always 0, so makes no sense to invest anything there.

**Comment by mtodisco10** [comment]
Got it.  Thank you for the quick response.
