### ISSUE TITLE
Grps instead of the spent

### ISSUE THREAD

**Issue by AlessioPallotti** [facebookexperimental/Robyn#749]
As far as TV is concerned, I only have the overall investment, but I also have the detail per channel, format, seconding etc (I do not have the investment in this detail though). My intention was firstly to run a model considering the total investments per TV. As a second step, I would like to find a way to get the curves for the GRPs on the 4 details for which I do not have the investments, so instead of considering the investments consider the grps. Is there a way to fix the parameters of the first model? My goal is to reweight the overall TV investment for the 4 levels of GRPs for which I don't have the investment detail, while still considering the effect of all other variables. Do you have any advice?

**Comment by gufengzhou** [comment]
This is the same issue as. https://github.com/facebookexperimental/Robyn/issues/733, so closing this one
