### ISSUE TITLE
Robyn Allocator failure

### ISSUE THREAD

**Issue by jaspertambini** [facebookexperimental/Robyn#753]
## Describe issue
Allocator fails to run providing response below: 

## Provide reproducible example
![image](https://github.com/facebookexperimental/Robyn/assets/114992329/64d9ebca-8b44-4de6-956f-547a6c7fa9d7)

**Comment by gufengzhou** [comment]
Please provide more information for trouble shooting, at least your allocator specification

**Comment by jaspertambini** [comment]
AllocatorCollect1 <- robyn_allocator(
  InputCollect = InputCollect,
  OutputCollect = OutputCollect,
  select_model = select_model,
  channel_constr_low = 0.7,
  channel_constr_up = 1.5,
  scenario = "max_response",
  export = create_files
)

**Comment by jaspertambini** [comment]
[raw_data_fb.csv](https://github.com/facebookexperimental/Robyn/files/11744152/raw_data_fb.csv)

**Comment by jaspertambini** [comment]
raw data and allocator info above, please let me know if you need anything else

**Comment by gufengzhou** [comment]
very sorry that i didnt get to reply in time. does this still occur?
