### ISSUE TITLE
Prophet results issue

### ISSUE THREAD

**Issue by jaspertambini** [facebookexperimental/Robyn#754]
## Describe issue
Not 100% sure if these are errors or questions:

Why is "Trend" very negative on waterfall predictor but not on prophet decomposition? (This is the case on all models)
Why are values showing a baseline >0 on prophet if any negative spikes occur?
Why are events showing negative spikes when context variable is set to positive?

## Provide reproducible example
![image](https://github.com/facebookexperimental/Robyn/assets/114992329/e9d50669-5bac-49da-91a4-2470ff3cea49)
![image](https://github.com/facebookexperimental/Robyn/assets/114992329/b14f6708-333f-4c11-9a2d-7d48b67f09af)

**Comment by gufengzhou** [comment]
- Trend from prophet serves as a predictor in Robyn and will obtain a beta coefficient that's can be positive or negative, as shown in the waterfall. It's true that negative trend is hard to interpret. You could constrain the beta for trend to positive by setting prophet_var_sign = "positive" for trend. Check `?robyn_inputs` for the usage of this param. 
- Not sure what you mean. Are you saying "ufc" in your prophet plot has a positive baseline? Is it a categorical variable? If yes, and if you want to have the baseline at 0, you can set the 1st level of this variable to the most frequent level.
- Negative spike in a categorical variable just mean that that specific level has negative coefficient from Prophet.

**Comment by jaspertambini** [comment]
Thanks gufengzhou.

So point 1 I understand, I will take a look at the robyn inputs

Point 2 if I follow correctly, as "UFC" is categorical, you're saying we should set the base level to 0 for example? I have done this already but let me know if I am misunderstanding

Point 3 shouldn't forcing the context variable to be positive also provide a positive response in prophet? Or is this not taken into consideration when prophet is calculat
[raw_data_fb.csv](https://github.com/facebookexperimental/Robyn/files/11744233/raw_data_fb.csv)
ing?

**Comment by gufengzhou** [comment]
As closing comment, sometimes non-media variables might be difficult to interpret due to how the data is collected (scores, categories, centerred around 0 etc.). Usually we recommend to group all non-media into "baseline" for easier interpretation. Check `?robyn_outputs` and you'll see the argument `baseline_level`. With `baseline_level = 4`, you'll aggregate all none-paid and none organic into baseline in the onepager, for example.
