### ISSUE TITLE
Robyn is not working in Databricks

### ISSUE THREAD

**Issue by Angylina** [facebookexperimental/Robyn#756]
## Describe issue
Hi all, 

I'm having difficulties with running Robyn in databricks. Everything works well up to the robyn_outputs function. All the files get saved in the specified folder, but once that is done my cluster restarts, and all objects are erased from its memory. It means I can't choose the best model, run robyn_response, and everything that comes after that. 

I already had a conversation with Microsoft about this, and they mentioned that the code overloads the cluster's driver, and the workload isn't distributed across workers for optimal performance. 

This is the message I get, when i run robyn_outputs:
`The spark driver has stopped unexpectedly and is restarting. Your notebook will be automatically reattached.`

Is there any way to force the code to distribute the workload across workers instead of concentrating on the driver?

## Provide reproducible example
This happens with every model configuration, even with demo. 

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: 3.10.3
- R version 4.2.2

**Comment by gufengzhou** [comment]
Have you checked this thread? https://github.com/facebookexperimental/Robyn/issues/259

**Comment by gufengzhou** [comment]
I'm no expert on databricks, so can't really help you debug. Maybe a workaround, you can set plot_pareto = TRUE in robyn_outputs() to limit the export files, then use robyn_onepagers() to recreate those onepagers if needed?

**Comment by Angylina** [comment]
That could work as a workaround. Thanks! Otherwise I have to figure this out with databricks
