### ISSUE TITLE
Robyn error while running OutputModels <- code - Error in task 7 failed - "arguments imply differing number of rows: 7, 9"

### ISSUE THREAD

**Issue by andrelsouza** [facebookexperimental/Robyn#758]
## Describe issue
This error keep showing while I try to test Robyn in a small sample of dataframe, I'm using the latest dev version.

#### Step2: Creating First Inputs
InputCollect <- robyn_inputs(
  dt_input = subset_data,
  dt_holidays = dt_prophet_holidays,
  date_var = "DATE", # date format must be "2020-01-01"
  dep_var = "revenue", # there should be only one dependent variable
  dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)
 'prophet_vars = c("trend", "season", "holiday"), # "trend","season", "weekday" & "holiday"'
 'prophet_country = "BR", # input one country. dt_prophet_holidays includes 59 countries by default'
 'context_vars = c("competitor_sales_B", "events"), # e.g. competitors, discount, unemployment etc'
  paid_media_spends = c("Bing", "Tik_Tok", "Facebook"), # mandatory input
  paid_media_vars = c("Bing", "Tik_Tok", "Facebook"), # mandatory.
  'paid_media_vars must have same order as paid_media_spends. Use media exposure metrics like'
  ' impressions, GRP etc. If not applicable, use spend instead.'
  ' organic_vars = "newsletter", # marketing activity without media spend'
  ' factor_vars = c("events"), # force variables in context_vars or organic_vars to be categorical'
  window_start = "2023-06-05",
  window_end = "2023-06-11",
  adstock = "geometric" # geometric, weibull_cdf or weibull_pdf.
)
print(InputCollect)

OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = NULL, # NULL defaults to (max available - 1)
  iterations = 2000, # 2000 recommended for the dummy dataset with no calibration
  trials = 5, # 5 recommended for the dummy dataset
  ts_validation = TRUE, # 3-way-split time series for NRMSE validation.
  add_penalty_factor = FALSE # Experimental feature. Use with caution.
)
print(OutputModels)

Error:
Input data has 7 days in total: 2023-06-05 to 2023-06-11
Initial model is built on rolling window of 7 day: 2023-06-05 to 2023-06-11
Time-series validation with train_size range of 50%-80% of the data...
Using geometric adstocking with 11 hyperparameters (11 to iterate + 0 fixed) on 1 core (Windows fallback)
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
  |                                                                                             |   0%Timing stopped at: 0.71 0.09 0.81
Error in { : 
  task 7 failed - "arguments imply differing number of rows: 7, 9"

## Environment & Robyn version
Robyn Version: >‘3.10.4.9000’
R version 4.2.0
[dummy_data.csv](https://github.com/facebookexperimental/Robyn/files/11761659/dummy_data.csv)

**Comment by gufengzhou** [comment]
I've never seen Model fitting with only 7 days. Please use the full dates and retry
