### ISSUE TITLE
rssd_zero_penalty = TRUE ; is this the default setting?

### ISSUE THREAD

**Issue by boxx0r** [facebookexperimental/Robyn#759]
Hi there,

I am wondering if the new rssd_zero_penalty feature is set to true by default? Ie if the user does not specify this parameter in robyn_run, does it default to true? I was looking in the demo script but could not find this line - perhaps because it is a new feature not yet included in the demo script. 

Thanks, much appreciated.

**Comment by gufengzhou** [comment]
You can check the argument by running <?robyn_run>. Yes default is true.
