### ISSUE TITLE
Run allocator without robyn_write JSON export?

### ISSUE THREAD

**Issue by boxx0r** [facebookexperimental/Robyn#769]
Hello,

I have an old model run where I did not run the robyn_write function and thus I don’t have the JSON output from that, however I do have the CSVs in the export folder. Is there a way I can run allocator without this JSON file? Or a way I can create the JSON file using the export CSVs? I have run new models since so I do not have the R history for this particular run. 

Thank you.

**Comment by gufengzhou** [comment]
you need the json file unfortunately. you can hack it by rerunning everything using the expact hyperparameters in your csvs.
