### ISSUE TITLE
Graphs are not scaling properly

### ISSUE THREAD

**Issue by AdimDrewnik** [facebookexperimental/Robyn#770]
Most of the graphs that are generated by the Robin do not scale well. For example for high trials number e.g. > 5 or 10 the graph with ts validation is too compressed to see anything useful. Same with graph for clustering results. When there are too many clusters e.g. more than 5 or so the graph is so compressed that nothing can be seen. Same with graphs for individual models when there are many channels e.g. more than 10, the waterfall graph is too compressed, etc. 
Robyn graphs should scale better (mostly vertically) to accommodate for real world cases, e.g. trials > 10, number of channels > 10-15. 

Also, for an unknown reason many graphs have black background which makes text on the graphs unreadable.

**Comment by gufengzhou** [comment]
Hey, I've just pushed a PR to fix these with #785 . Should work better now. But pls reopen the issue if it still exists.
