### ISSUE TITLE
demo.r | document error

### ISSUE THREAD

**Issue by gyang274** [facebookexperimental/Robyn#775]
## Describe issue
demo/demo.r, line 120: [Also, to convert weekly to daily we can transform the parameter to the power of (1/7), so to convert 30% **daily to weekly** is 0.3^(1/7) = 0.84.](https://github.com/facebookexperimental/Robyn/blob/15a62998163abc9c00d1791fe446a08373699daa/demo/demo.R#L120)

shouldn't this be "convert 30% **weekly to daily** is 84%"?

**Comment by gufengzhou** [comment]
Calling the theta "decay rate" could be bit misleading, because 30% means 30% carrying over to the next period, not 30% less. The doc is correct. Daily theta should be higher than weekly.
