### ISSUE TITLE
Robyn_outputs: vector size error

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#778]
## Describe issue
When running robyn_outputs getting the following error:

>>> Running Pareto calculations for 50000 models on auto fronts...
Error: cannot allocate vector of size 6.3 Gb

## Environment & Robyn version
 Robyn ‘3.10.3’
[1] "R version 4.2.3 (2023-03-15 ucrt)"

**Comment by AdimDrewnik** [comment]
You ran out of memory. You need to increase the amount of RAM or decrease number of trials and iterations.

**Comment by gufengzhou** [comment]
Could you solve this with more RAM?
