### ISSUE TITLE
Convert Single Plot to Two

### ISSUE THREAD

**Issue by sujithnair2021** [facebookexperimental/Robyn#78]
# Issue

Is there a way to split the model one pager and/or budget allocator to multiple plots. I want to look at 10 spending variables and all of them in a single plot are cluttered. If not, do you have suggestions on how to start working on additional code that could do that?

**Comment by gufengzhou** [comment]
For the moment it's only aggregated. In Script .func, you can find the onepager plotting Loop from line 1599 on. We'll consider it in the future pipeline how to best offer the plot per channel.

**Comment by sujithnair2021** [comment]
Thank you!
