### ISSUE TITLE
robyn_recreate() error: Must provide 'hyperparameters' in robyn_inputs()'s output first

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#782]
Hi everyone, hope you are well. I've stumbled upon the following error when trying to reproduce a model using robyn_recreate(): Must provide 'hyperparameters' in robyn_inputs()'s output first. The strange thing is, the hyperparameters are in the JSON, as you can see from the output of print(robyn_read(json_file)) below:
![image](https://github.com/facebookexperimental/Robyn/assets/118725564/715d6d32-3879-477c-9c6c-40d5cf58923d)

**Comment by bart-vanvlerken** [comment]
Specifically, robyn_inputs() is not able to extract the hyperparameters from the JSON it seems.

**Comment by gufengzhou** [comment]
I can't reproduce your error. I just exported an random model json and robyn_recreate() works.  This is my screenshot. are you doing something differently? the json is from a selected model exported by the robyn_write() function.

![image](https://github.com/facebookexperimental/Robyn/assets/14415136/5d17d809-b92d-485b-90d2-0298cbf5dc74)

**Comment by bart-vanvlerken** [comment]
No I'm doing just that, actually. I found a 'fix' by running the following code:
`# Re-create InputCollect
InputCollectX <- robyn_inputs(
  dt_input = dt_simulated_weekly,
  dt_holidays = dt_prophet_holidays,
  json_file = json_file)

# Re-create OutputCollect
OutputCollectX <- robyn_run(
  InputCollect = InputCollectX,
  json_file = json_file,
  export = create_files)
`

Before running robyn_run() I copy-pasted the hyperparameters from the JSON and ran robyn_inputs() again. I got fairly similar results, but since I couldn't specify the penalty factors of the variables in my model they were slightly different.
