### ISSUE TITLE
Robyn CSV Data Dictionary?

### ISSUE THREAD

**Issue by MC-Dave** [facebookexperimental/Robyn#783]
## Describe issue
I have not been able to locate a Data Dictionary which describes each output from the various .csv file's which Robyn can output.

Namely, column descriptions and documentation for the following 

```
    pareto_hyperparameters.csv
    pareto_aggregated.csv
    pareto_alldecomp_matrix.csv
    pareto_media_transform_matrix.csv
    pareto_hyperparameters.csv
    pareto_clusters_ci.csv
    pareto_clusters.csv'
```

Is there any documentation which elucidates the meaning of each column?

Thank you in advance!

## Environment & Robyn version
Robyn: `3.10.3`

**Comment by gufengzhou** [comment]
yes her you go https://github.com/facebookexperimental/Robyn/blob/main/demo/schema.R
