### ISSUE TITLE
Does Robyn still use only spend data as input but not exposure metrics?

### ISSUE THREAD

**Issue by MikitoKonishi** [facebookexperimental/Robyn#787]
## Describe issue
I found some explanation that Robyn uses only spend data in modeling but not exposure metrics ([1](https://github.com/facebookexperimental/Robyn/issues/727), [2](https://github.com/facebookexperimental/Robyn/issues/656), [3](https://github.com/facebookexperimental/Robyn/issues/733), [4](https://github.com/facebookexperimental/Robyn/issues/466)). Does the latest model only use spend data as input? If you have any plan to use exposure metrics as input, I would like to know it.

Thank you very much!

**Comment by AdimDrewnik** [comment]
I wouldn't worry about about such a small thing when each run with different seed gives wildly different results and algorithm doesn't reach convergence even after tens of thousand of iterations and dozens of trials. Basically run Robin multiple times and you will get every model under the sun.

**Comment by MikitoKonishi** [comment]
Thank you for your comment, but I'm talking about "paid_media_vars". From [this issue](https://github.com/facebookexperimental/Robyn/issues/466) , "paid_media_vars" is not used in ver 3.7.1. And [laresbernardo](https://github.com/laresbernardo) said like this in May 24, 2022.

> Hi, as explained a bunch of times in different tickets (https://github.com/facebookexperimental/Robyn/issues/727#issuecomment-1546282846, https://github.com/facebookexperimental/Robyn/issues/466#issuecomment-1226678875, https://github.com/facebookexperimental/Robyn/issues/656, ...), we model using spend data only, not exposure (like GRP, impressions, etc). We do this because when optimizing budget allocation we have a 1:1 relationship with CPA or ROAS and no need to transform the variables (once again) thus avoiding additional unnecessary noise.

I would like to know it's same in latest model or not.

**Comment by gufengzhou** [comment]
yes it is still the case. only `paid_media_spend` is used for fitting.

**Comment by MikitoKonishi** [comment]
I understand. Thank you very much.
