### ISSUE TITLE
Attribution for Brand Direct

### ISSUE THREAD

**Issue by ar-asur** [facebookexperimental/Robyn#789]
I am working with a dataset of 2.5 yrs history with 6 media channels and 3 context variables. KPI is number of new customers. I have a question about understanding the output from Robyn model. The brand direct channel(search campaigns that target brand keywords) is being attributed the highest, on one side it seems intuitive since this channel is not expensive/super low funnel and is correlated with  the target. But I also think the other channels are misattributed (underestimated). How can I change the model setup/feature engg to solve this issue?

I am looking for suggestions to improve my modeling and hopefully move towards capturing better attribution for all the channels. 

Thanks!

**Comment by igorskokan** [comment]
Have you checked the analyst guide to MMM?
https://facebookexperimental.github.io/Robyn/docs/analysts-guide-to-MMM/
and specifically the feature to calibrate MMM with ground truth (usually
experiments):
https://facebookexperimental.github.io/Robyn/docs/features/#calibration-with-experiments


MMM is modelling so you won't be able to make sure you are misattributing
or not, so either use existing (from the past) experiments or design some
in the future and use the results to calibrate your MMMs.

**Comment by AdimDrewnik** [comment]
Try starting from multiple different seeds. That way maybe you will converge to different local optima that makes more sense to you.
