### ISSUE TITLE
Make predictions

### ISSUE THREAD

**Issue by gibrano** [facebookexperimental/Robyn#79]
# Question about prediction

Hi guys, is there a predict function or a way to make predictions given the media spend? I know that f.budgetAllocator function return optmResponseUnitTotal as a total of each media, but what about intercept, season, holidays, and others variables?

**Comment by gufengzhou** [comment]
Hi, at the moment Robyn doesn't have a prediction function, because it's thought to be more of a decomposition tool than a prediction tool. It's controversial how to best provide future dataframe for intercept/trend/season/other baselines etc. We'll consider this in future pipeline

**Comment by gibrano** [comment]
it's good to know that, thank you.

**Comment by maisiemoore** [comment]
Hi, still curious about this issue. Is there anyway for us to "back into" the non-media vars decomposition values?
