### ISSUE TITLE
Error in {: Task 1 failed - "object 'dt_geometric' not found"

### ISSUE THREAD

**Issue by madut1** [facebookexperimental/Robyn#790]
## Describe issue
I've been running models using weibull_pdf and have been getting intended results (all Pareto optimal plots, allocation plots/CSVs generated) but all of a sudden I started getting the following error during the "calculation of pareto fronts, clustering and exporting results and plots". I haven't changed any settings. I have my RobynRun iterations set to 3000, and trials set to 6. 

Error message: 
Plotting 8 selected models on 1 core (MacOS fallback)...0%
Failed exporting results, but returned model results anyways:
 **Error in {: task 1 failed - "object 'dt_geometric' not found"**

## Environment & Robyn version
Version: ‘3.10.4.9001’

**Comment by AdimDrewnik** [comment]
From what I have read Robyn on multicore is not deterministic, so there is a chance each run gives different results. I was getting similar errors when Robyn run out of RAM.

**Comment by gufengzhou** [comment]
I've just pushed a fix and it works for me now. pls test and confirm

**Comment by madut1** [comment]
Seeing the fix! Thank you very much for resolving @gufengzhou
