### ISSUE TITLE
Impression modelling

### ISSUE THREAD

**Issue by cbSuccessAcademies** [facebookexperimental/Robyn#792]
## Describe issue
Is it possible to switch to fitting the model using the impression data?

**Comment by AdimDrewnik** [comment]
You need to explain your problem in more detail.

**Comment by cbSuccessAcademies** [comment]
Apologies, so I am reading the demo script and I am seeing this where the default modeling variable has changed from paid_media_vars to paid_media_spends. I would prefer to model on impressions because it could build a better model. My thinking is because impressions are the point of contact for the media served. I would like to know how to switch the modeling variable to paid_media_vars 

![image](https://github.com/facebookexperimental/Robyn/assets/135134846/83ba3a6c-4988-4a55-89a9-e07fab60d272)

**Comment by gufengzhou** [comment]
Robyn doesn't support imp modelling anymore due to the uncertainty it introduces to budget allocation.

**Comment by AdimDrewnik** [comment]
@gufengzhou So having some TV ads is it no longer possible to use GRPs in Robyn modelling? Only TV spend should be used or can I use GRPs in place of spend?
