### ISSUE TITLE
Output of robyn_recreate() returns warning message referencing an object that does not exist anymore?

### ISSUE THREAD

**Issue by SeanRichterWalsh** [facebookexperimental/Robyn#799]
Hi,

When recreating a model from a saved JSON file, the message below can sometimes appear if weak relationships exist between spend and exposure. However, I cannot find InputCollect$plotNLSCollect to check as guided by the message. Does it need updating or have I missed it? Thanks.

NOTE: potential improvement on splitting channels for better exposure fitting. Threshold (Minimum R2) = 0.8 
  Check: InputCollect$plotNLSCollect outputs
  Weak relationship for: 'tv_G', 'search_I' and their spend

**Comment by gufengzhou** [comment]
you should be able to find the plots in `InputCollect$modNLS$plots`. We'll adapt the message
