### ISSUE TITLE
Error in NRMSE calculation

### ISSUE THREAD

**Issue by Jakobus51** [facebookexperimental/Robyn#801]
In Robyn/R/R/Model.R line 1097 and 1098, there is a mistake in the calculation of the NRMSE. 

` nrmse_val <- sqrt(mean(sum((y_val - y_val_pred)^2))) / (max(y_val) - min(y_val))
    nrmse_test <- sqrt(mean(sum((y_test - y_test_pred)^2))) / (max(y_test) - min(y_test))`

It should be without the sum, just like you did for the nrmse_train calculation 
` nrmse_val <- sqrt(mean((y_val - y_val_pred)^2)) / (max(y_val) - min(y_val))
    nrmse_test <- sqrt(mean((y_test - y_test_pred)^2)) / (max(y_test) - min(y_test))`

**Comment by gufengzhou** [comment]
you're right. Will fix that soon. To assure things: it doesn't affect the optimisation process, because either mean or sum will be just minimised. So theoretically it doesn't really matter. But sure we'll Correct it.
