### ISSUE TITLE
Factorial Variables

### ISSUE THREAD

**Issue by mirgolian** [facebookexperimental/Robyn#806]
Hi, 
I would like to ask what is the correct interpretation of factorial variables used in Robyn? When I look at the waterfall graph, do I compare its effect with average category, or with a default one. If the latter is correct, how do I find out which one has been set as the default, and possibly change it?
And lastly, when I have more than one category, where can I find effect of each of them? 
Thanks!

**Comment by gufengzhou** [comment]
I've answered a similar question in the fb group https://www.facebook.com/groups/robynmmm/posts/1494220064679455/
