### ISSUE TITLE
Budget Allocator Question

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#809]
Hi everyone, my model one-pager displays the following values:

![image](https://github.com/facebookexperimental/Robyn/assets/118725564/c8ef1555-18c1-418d-94d2-2dbcf6e98859)

However, when I run the budget allocator on the same date range, it gives the following values:

![image](https://github.com/facebookexperimental/Robyn/assets/118725564/7b7cd1a1-5fd2-4a48-be63-7657b953711a)

As you can see, the effect share differs between the two. Does anyone know what can be the cause of this?

**Comment by gufengzhou** [comment]
what is your date range in the allocation? the first plot/ model onepager is default to the total modelling window.

**Comment by bart-vanvlerken** [comment]
@gufengzhou I set `date_range = "all"`, so I would expect the effect shares to be the same.

**Comment by gufengzhou** [comment]
hm that's weird. just to be sure, you're comparing the same model ID right? if yes, I'd need your data (unfortunately) to debug.

**Comment by bart-vanvlerken** [comment]
Yes, I am using the same model ID. Is there a way to share it with you privately?

**Comment by gufengzhou** [comment]
gufeng@meta.com. I'd need the dataset and your model specific json file.

**Comment by bart-vanvlerken** [comment]
@gufengzhou I sent it over, let me know what you think.

**Comment by bart-vanvlerken** [comment]
@gufengzhou Thanks for the update! I understand now how the allocator operates in allocating effect share, but I must say it doesn't make a lot of sense and it is difficult for me to communicate this to my clients. How can the simulated effect share be so different from the historical response, wouldn't it make more sense when these values are the same when using the same date range? 

Of course I can tweak the date range to produce 'desirable' results, but this doesn't feel right. In addition, most clients would like to include all marketing channels in the allocator which often forces me to use a large date range since some channels only ran campaigns during a certain period. Here is the model one-pager and allocator one-pager of another client, and I'm running into the same issue. I really appreciate all the work you're putting into this package, and I'd love to hear your opinion on this.
![2_2082_3](https://github.com/facebookexperimental/Robyn/assets/118725564/833fca7a-4696-4b93-bb8d-6ad5de37a23e)
![2_2082_3_reallocated_best_cpa](https://github.com/facebookexperimental/Robyn/assets/118725564/ea57ab68-c60a-4cff-a1c7-d0585250b944)

**Comment by gufengzhou** [comment]
ok this definitely doesn't look right. I assume the high carryover from weibull is the reason. Would you mind sharing the dataset as well as this specific model json file with me? I can try to debug. gufeng@meta.com

**Comment by iamlostcoast** [comment]
I'm pretty sure I am experiencing this exact issue.  Was there ever a resolution to this?
