### ISSUE TITLE
Robyn not working anymore  during "Calculating response curves for all models' media variables (615)."

### ISSUE THREAD

**Issue by federicoSalaVv** [facebookexperimental/Robyn#815]
## Describe issue
Since yesterday afternoon (CET timezone), all our Robyn trainings and allocations stopped working with error:

Error in { : task 1 failed - "argument is of length zero"
Calls: robyn_outputs ... robyn_pareto -> %dorng% -> do.call -> <Anonymous> -> <Anonymous>

Since we use Robyn through a docker file:
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile 
RUN Rscript -e "install.packages('remotes');"
RUN Rscript -e "install.packages('extrafont');"
RUN Rscript -e "install.packages('reticulate');"
RUN Rscript -e "remotes::install_github('facebookexperimental/Robyn/R');"
RUN Rscript -e "install.packages('ggplot2');"
RUN Rscript -e "install.packages('data.table');"
RUN Rscript -e "install.packages('stringr');"
RUN Rscript -e "install.packages('bigrquery');"
RUN Rscript -e "install.packages('bursts');" 
RUN Rscript -e "install.packages('jsonlite');" 
RUN Rscript -e "install.packages('foreach');" 

We want to be sure you haven't changed anything on the latest working version, can you please check it?

**Comment by gufengzhou** [comment]
Hi, thanks for reporting this. I just pushed a fix and it worked on my side. would you please test and confirm.

**Comment by federicoSalaVv** [comment]
Hi, it looks like the issue is resolved, thank you!
