### ISSUE TITLE
Could not import matplotlib.pyplot, - Nevergrad Issue

### ISSUE THREAD

**Issue by Michaelmlewis** [facebookexperimental/Robyn#820]
I am trying to install nevergrad via pip 
using the following 
`library("reticulate")
virtualenv_create("r-reticulate")
use_virtualenv("r-reticulate", required = TRUE)
Sys.setenv(RETICULATE_PYTHON = "C:/Users/MIAT40093/Documents/.virtualenvs/r-reticulate/Scripts/python.exe")
py_install("numpy", pip = TRUE)
py_install("nevergrad", pip = TRUE)
`

when I run `py_module_available("nevergrad")` I get the following error
C:\Users\MIAT40~1\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\cma\s.py:13: UserWarning: Could not import matplotlib.pyplot, therefore ``cma.plot()`` etc. is not available
  _warnings.warn('Could not import matplotlib.pyplot, therefore'
[1] FALSE

Here is my 'py_config() '
python:         C:/Users/MIAT40093/Documents/.virtualenvs/r-reticulate/Scripts/python.exe
libpython:      C:/Users/MIAT40093/AppData/Local/Programs/Python/Python311/python311.dll
pythonhome:     C:/Users/MIAT40093/Documents/.virtualenvs/r-reticulate
version:        3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/MIAT40093/Documents/.virtualenvs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.26.0

NOTE: Python version was forced by RETICULATE_PYTHON

I tried alot of the mentioned solutions, with no luck :( 

Would you please advise

**Comment by gufengzhou** [comment]
Very tricky issue :( reticulate often fails to pick up the right python config by default. Below is my py_config(), as you see I'm using the python libs installed by miniconda. 

![image](https://github.com/facebookexperimental/Robyn/assets/14415136/babe61c8-d2a9-4940-9e53-9768b00e8ed5)

**Comment by gufengzhou** [comment]
Please reopen if necessary.
