### ISSUE TITLE
Warning message: In selectChildren(ac[!fin], -1) : error 'No child processes' in select

### ISSUE THREAD

**Issue by SeanRichterWalsh** [facebookexperimental/Robyn#822]
Hi,

After running robyn_run() I am getting the convergence stats but also the message in the title. I have not seen this before nor can I find much about it online. What does it imply? 

Thanks

**Comment by gufengzhou** [comment]
Haven't seen this before neither. Where are you running robyn? Looking at [this issue](https://github.com/ay-lab/FitHiChIP/issues/54) , it kind of indicates header issue

**Comment by SeanRichterWalsh** [comment]
I did find this quite old thread on the same issue I believe. https://github.com/facebookexperimental/Robyn/issues/41

I am running Robyn 3.10.4.9002 in R 4.2.3
