### ISSUE TITLE
Error when running the demo.R

### ISSUE THREAD

**Issue by SasithaGamage** [facebookexperimental/Robyn#825]
## Describe issue
When I run the demo.R example with test data, I'm getting the following error 

![Screenshot 2023-09-27 105106](https://github.com/facebookexperimental/Robyn/assets/66788920/565851ab-95ed-4dd6-b2ba-ee2010f98593)

I updated all the packages using "update.packages(checkBuilt=TRUE, ask=FALSE)".

## Environment & Robyn version
- Robyn version: 3.10.4.9008
- R version 4.3.1

**Comment by gufengzhou** [comment]
Looks like you haven't load the library as `library(Robyn)`

**Comment by SasithaGamage** [comment]
Yes, Just solved the issue. Thank you
