### ISSUE TITLE
Error calling library(Robyn)

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#832]
## Describe issue
I am working on a new PC, and in process of installing Robyn package.    I have successfully installed Nevergrad and Robyn.  When I call library(Robyn).   I get the following error

## Provide reproducible example
<img width="596" alt="image" src="https://github.com/facebookexperimental/Robyn/assets/69650410/87f8cc17-8e08-462b-93e4-a3a711091804">

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`:    **3.10.3**
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`):
                                   - **R version 4.3.1 (2023-06-16 ucrt)
                                     Platform: x86_64-w64-mingw32/x64 (64-bit)
                                     Running under: Windows 11 x64 (build 22621)**

**Comment by gufengzhou** [comment]
Have you tried installing h2o? Probably a secondary dependency

**Comment by tgtod002** [comment]
This worked!  Thanks.
