### ISSUE TITLE
Install nevergrad 

### ISSUE THREAD

**Issue by Armi19** [facebookexperimental/Robyn#836]
Hello,

I am trying to install nevergrad and connect R and Python. I get the following error message when I try to create the virtual environment : 

virtualenv_create("r-reticulate")

Error in python_config_impl(python) : 
  Error 1 occurred running /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12: 
In addition: Warning message:
In system2(command = python, args = shQuote(script), stdout = TRUE,  :
  running command ''/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12' '/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/config/config.py' 2>/dev/null' had status 1

-  `packageVersion("Robyn")` -- latest version, Version: 3.10.3
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`) - version 3.12

I would appreciate any suggestion to solve this.

Thanks

**Comment by gufengzhou** [comment]
Please check this first https://github.com/facebookexperimental/Robyn/blob/main/demo/install_nevergrad.R

**Comment by gufengzhou** [comment]
Please reopen if necessary.
