### ISSUE TITLE
Save InputCollect and OutputCollect

### ISSUE THREAD

**Issue by noob100000** [facebookexperimental/Robyn#837]
Hi. 
I am new to R and programming. 
I wanted to know if there is a way to save InputCollect and OutputCollect variables in file? so that I need not start from the beginning and just load the values.
I know that the model parameters are stored. But don't know if InputCollect and OutputCollect can be stored. 

Any help is appreciated. 

Thanks anyways!!
Awesome work guys.

**Comment by michellegrushkometa** [comment]
Hi @noob100000, welcome!

I suggest you check out some R resources, here is a great place to start: https://statisticsglobe.com/r-save-load-rdata-workspace-file

I also personally love referencing https://r4ds.had.co.nz/

**Comment by noob100000** [comment]
Thank you @michellegrushkometa.
