### ISSUE TITLE
Python version Release Date

### ISSUE THREAD

**Issue by waranyoghes** [facebookexperimental/Robyn#839]
Hi. Awesome work !!
In the facebook group somewhere it was written that a python version could be expected by end of this year. Just wanted to know, if there will be a python version ? And when could it be expected ? 
Apologies if the question is redundant. Did not find a recent update regarding this.

**Comment by gufengzhou** [comment]
thanks! we're currently working on an robyn API for python. but we can't commit to any deadline at the moment. will announce as soon as we can.

**Comment by waranyoghes** [comment]
Thanks for replying !!
