### ISSUE TITLE
Robyn v3.10.4 Hyperparameters appears on Pareto Front Top Perform Model

### ISSUE THREAD

**Issue by nikomataaa** [facebookexperimental/Robyn#840]
## Describe issue
Hyperparameters on each channels appears in the **pareto front cluster chart** under the `Top Peforming Model` section

attached image example
<img width="301" alt="Screenshot 2023-10-18 at 11 11 50" src="https://github.com/facebookexperimental/Robyn/assets/55773604/510e9a02-05ee-4e99-add2-f8d4a3053c7e">

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.

- the same script is used from `demo.R`
- all of the inputs are the same beside the `marketing channel`
- when I try to downgrade the Robyn to version `v3.10.3` the error was not appear anymore

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `v3.10.4`
- R version : `4.2.3`

**Comment by gufengzhou** [comment]
Hi, thanks for raising this. after a closer look, it's not a bug, but rather the result of our latest change of clustering parameters from the channel ROAS/CPA to channel hyperparameters. the latter is more sensitive and actually concludes the former. it means the plot is actually right, but it needs different/better labelling though. will add to our tickets.
