### ISSUE TITLE
Couldn't automatically create clusters:

### ISSUE THREAD

**Issue by Michaelmlewis** [facebookexperimental/Robyn#841]
## Describe issue
When trying to run robyn_run I am receiving the below error. Can you please assist?
```
OutputCollect <- robyn_outputs(
  InputCollect, OutputModels,
  pareto_fronts = "auto", # automatically pick how many pareto-fronts to fill min_candidates (100)
  min_candidates = 100, # top pareto models for clustering. Default to 100
  # calibration_constraint = 0.1, # range c(0.01, 0.1) & default at 0.1
  csv_out = "pareto", # "pareto", "all", or NULL (for none)
  clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
  export = create_files, # this will create files locally
  plot_folder = robyn_directory, # path for plots exports and files creation
  plot_pareto = create_files # Set to FALSE to deactivate plotting and saving model one-pagers
)
```
>>> Running Pareto calculations for 15000 models on auto fronts...
>> Automatically selected 4 Pareto-fronts to contain at least 100 pareto-optimal models (125)
>>> Calculating response curves for all models' media variables (875)...
>> Pareto-Front: 1 [34 models]
 00:00:09 [=====================================================================] 100% | 34                                                  
>> Pareto-Front: 2 [31 models]
 00:00:08 [=====================================================================] 100% | 31                                                  
>> Pareto-Front: 3 [33 models]
 00:00:09 [=====================================================================] 100% | 33                                                  
>> Pareto-Front: 4 [27 models]
 00:00:07 [=====================================================================] 100% | 27                                                  
>>> Calculating clusters for model selection using Pareto fronts...
Couldn't automatically create clusters: Error: empty cluster: try a better set of initial centers
Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "NULL"
Error in select(clusterCollect$data, .data$solID, .data$cluster, .data$top_sol) : 
  object 'clusterCollect' not found

## Environment & Robyn version

- Robyn version: 3.10.3
- R version: 4.2.2

**Comment by gufengzhou** [comment]
can you install the latest dev version and try? `remotes::install_github("facebookexperimental/Robyn/R")`

**Comment by gabiborges1** [comment]
Any news here? just got the same error :/

**Comment by gufengzhou** [comment]
this was rather related to older version of robyn
