### ISSUE TITLE
Pareto calculations : Error in serialize(data, node$con) : error writing to connection

### ISSUE THREAD

**Issue by LMiddles** [facebookexperimental/Robyn#845]
## Describe issue
Models have built, issue arises when running output collect. Ts validation, ROAS convergence, pareto matrix etc all produced in folder. error message when calculating pareto fronts 

>>> Running Pareto calculations for 25000 models on 5 fronts...
>>> Calculating response curves for all models' media variables (2510)...
Error in serialize(data, node$con) : error writing to connection

## Provide reproducible example
OutputCollect <- robyn_outputs(
+   InputCollect, OutputModels,
+   pareto_fronts = 5, # automatically pick how many pareto-fronts to fill min_candidates (100)
+   # min_candidates = 100, # top pareto models for clustering. Default to 100
+   # calibration_constraint = 0.1, # range c(0.01, 0.1) & default at 0.1
+   csv_out = "pareto", # "pareto", "all", or NULL (for none)
+   clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
+   export = create_files, # this will create files locally
+   plot_folder = robyn_directory, # path for plots exports and files creation
+   plot_pareto = create_files # Set to FALSE to deactivate plotting and saving model one-pagers
+ )
WARNING: Provided 'plot_folder' doesn't exist. Using current working directory: xxxxx/Documents
>>> Running Pareto calculations for 25000 models on 5 fronts...
>>> Calculating response curves for all models' media variables (2510)...
Error in serialize(data, node$con) : error writing to connection

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn 3.10.3’
- R 4.3.1

**Comment by LMiddles** [comment]
sessionInfo()$R.version
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$crt
[1] "ucrt"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "3.1"

$year
[1] "2023"

$month
[1] "06"

$day
[1] "16"

$`svn rev`
[1] "84548"

$language
[1] "R"

$version.string
[1] "R version 4.3.1 (2023-06-16 ucrt)"

$nickname
[1] "Beagle Scouts"

**Comment by gufengzhou** [comment]
I see you're still having this issue. It's very difficult to debug because I can't reproduce your error. Have you googled your error message? It seems like a OS specific problem with the parallel process.

**Comment by gufengzhou** [comment]
Please see the latest related issue https://github.com/facebookexperimental/Robyn/issues/964
