### ISSUE TITLE
Don't appear vec_collect build from xDecompVecImmCarr in v3.10.3

### ISSUE THREAD

**Issue by caarolinagil** [facebookexperimental/Robyn#848]
## Describe issue
Hi,

Recently, I have upgraded from version 3.9.0 to version 3.10.3 and have seen changes.

Until now, to separate the carryover vs immediate effects and to be able to represent them, I used the table coming from OutputModels$trial$resultCollect$xDecompVec, but in the results extracted from the model with version 3.10.3 I don't have this option and I don't know how to get this decomposition out.

## Provide reproducible example

I've tried this extracted to script pareto.R but I get a tibble 0x0:

**To recreate "xDecompVec", "xDecompVecImmediate", "xDecompVecCarryover" for each model**
temp <- OutputModels[names(OutputModels) %in% paste0("trial", 1:OutputModels$trials)]
xDecompVecImmCarr <- bind_rows(lapply(temp, function(x) x$resultCollect$xDecompVec))
if (!"solID" %in% colnames(xDecompVecImmCarr)) {
       xDecompVecImmCarr <- xDecompVecImmCarr %>%
         mutate(solID = paste(.data$trial, .data$iterNG, .data$iterPar, sep = "_")) %>%
         filter(.data$solID %in% uniqueSol)
     }
## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: 3.10.3
- R version: 4.2.1

**Comment by gufengzhou** [comment]
Hey, we've deprecated that table in the object because it's getting very large and causing many problem when users are having larger datasets and/or running more iterations. The new onepager actually provide the aggregated immediate vs carryover plot. is it sufficient for you?

**Comment by caarolinagil** [comment]
Thank you for your esponse.

Actually, my question is if it is necessary to visualize the immediate vs carryover by dates or better the aggregated data as we have it in the new one pager.
Also, I would like to know what adstock transformation would be best to use to reflect the impact of channels that focus on awareness campaigns?

**Comment by gufengzhou** [comment]
please reopen if necessary
