### ISSUE TITLE
Model run halted while calculating clusters for model selection

### ISSUE THREAD

**Issue by CJ2407** [facebookexperimental/Robyn#849]
Does anyone know how to fix this issue?

![image](https://github.com/facebookexperimental/Robyn/assets/91983160/43ad9132-dfd7-442e-ac63-4a011e9aa280)

**Comment by CJ2407** [comment]
@laresbernardo @gufengzhou I have tried running model with a few iterations and only 2 trials as well and I am getting the same "Error in geom_density_ridges_gradient". I tried keyword search in our Robyn github community and can't find if this error was reported/resolved earlier. Could you please suggest what should I do to fix it? I am stuck on this error from last one week.

**Comment by gufengzhou** [comment]
strange. can you try updating ggplot2 alone and test?

**Comment by gufengzhou** [comment]
please reopen if necessary
