### ISSUE TITLE
model one-pager does not display legend

### ISSUE THREAD

**Issue by ekdz** [facebookexperimental/Robyn#850]
## Describe issue
I'm using Robyn (newest version) on Databricks. After some workarounds everything runs smoothly except for model one-pagers. It does not display legends. Example below. What can be the issue? I've tried to download a default font but without success. Do you have any idea?

![image](https://github.com/facebookexperimental/Robyn/assets/44016232/96c946f5-f5d5-40aa-b10b-927c55a1b761)

**Comment by gufengzhou** [comment]
This is clearly a bug. Will check asap.

**Comment by michellegrushkometa** [comment]
Hey @ekdz, I am currently looking into the issue. As a workaround, can you please try running myOnePager[[select_model]]$patches$plots[[4]] for your selected model? This will show the plot with the legend

**Comment by ekdz** [comment]
@gufengzhou @michellegrushkometa thank you!
