### ISSUE TITLE
No numpy

### ISSUE THREAD

**Issue by taikis1991** [facebookexperimental/Robyn#851]
I proceeded with the installation.

> library(Robyn)
> library("reticulate")
> conda_create("r-reticulate")
`ERROR : Unable to find conda binary. Is Anaconda installed?`

This error was resolved as follows.

`use_condaenv("C:\\Users\\aaa\\.conda\\envs\\r-reticulate\\python.exe")`

I then proceeded.

` conda_create("r-reticulate")` 
+ "C:/ProgramData/miniconda3/condabin/conda.bat" "create" "--yes" "--name" "r-reticulate" "python=3.9" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

` ## Package Plan ##` 

  environment location: C:\Users\aaa\.conda\envs\r-reticulate

  added / updated specs:
    - python=3.9

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4 
  ca-certificates    conda-forge/win-64::ca-certificates-2023.7.22-h56e8100_0 
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5 
  libsqlite          conda-forge/win-64::libsqlite-3.43.2-hcfcfb64_0 
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_5 
  openssl            conda-forge/win-64::openssl-3.1.4-hcfcfb64_0 
  pip                conda-forge/noarch::pip-23.3.1-pyhd8ed1ab_0 
  python             conda-forge/win-64::python-3.9.18-h4de0772_0_cpython 
  setuptools         conda-forge/noarch::setuptools-68.2.2-pyhd8ed1ab_0 
  tk                 conda-forge/win-64::tk-8.6.13-hcfcfb64_0 
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0 
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 
  vc                 conda-forge/win-64::vc-14.3-h64f974e_17 
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.36.32532-hdcecf7f_17 
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.36.32532-h05e6639_17 
  wheel              conda-forge/noarch::wheel-0.41.3-pyhd8ed1ab_0 
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0 

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
[1] "C:\\Users\\aaa\\.conda\\envs\\r-reticulate/python.exe"

> Sys.setenv(RETICULATE_PYTHON = "C:/Users/aaa/.conda/envs/r-reticulate")

> py_config()

C:\Users\aaa\Documents>CALL "C:\ProgramData\miniconda3\condabin\activate.bat" "C:\Users\aaa\.conda\envs\r-reticulate" 

C:\Users\aaa\Documents>conda.bat activate "C:\Users\aaa\.conda\envs\r-reticulate" 

(r-reticulate) C:\Users\aaa\Documents>"C:/Users/aaa/.conda/envs/r-reticulate/python.exe" -m pip install --upgrade --no-user nevergrad 
Collecting nevergrad
  Using cached nevergrad-1.0.0-py3-none-any.whl.metadata (10 kB)
Collecting numpy>=1.24.0 (from nevergrad)
  Using cached numpy-1.26.1-cp39-cp39-win_amd64.whl.metadata (61 kB)
Collecting cma>=2.6.0 (from nevergrad)
  Using cached cma-3.3.0-py3-none-any.whl (260 kB)
Collecting bayesian-optimization>=1.2.0 (from nevergrad)
  Using cached bayesian_optimization-1.4.3-py3-none-any.whl (18 kB)
Collecting typing-extensions>=3.6.6 (from nevergrad)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting pandas (from nevergrad)
  Using cached pandas-2.1.2-cp39-cp39-win_amd64.whl.metadata (18 kB)
Collecting scipy>=1.0.0 (from bayesian-optimization>=1.2.0->nevergrad)
  Using cached scipy-1.11.3-cp39-cp39-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn>=0.18.0 (from bayesian-optimization>=1.2.0->nevergrad)
  Using cached scikit_learn-1.3.2-cp39-cp39-win_amd64.whl.metadata (11 kB)
Collecting colorama>=0.4.6 (from bayesian-optimization>=1.2.0->nevergrad)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting python-dateutil>=2.8.2 (from pandas->nevergrad)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas->nevergrad)
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas->nevergrad)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->nevergrad)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting joblib>=1.1.1 (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad)
  Using cached threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Using cached nevergrad-1.0.0-py3-none-any.whl (477 kB)
Using cached numpy-1.26.1-cp39-cp39-win_amd64.whl (15.8 MB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached pandas-2.1.2-cp39-cp39-win_amd64.whl (10.8 MB)
Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Using cached scikit_learn-1.3.2-cp39-cp39-win_amd64.whl (9.3 MB)
Using cached scipy-1.11.3-cp39-cp39-win_amd64.whl (44.3 MB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Installing collected packages: pytz, tzdata, typing-extensions, threadpoolctl, six, numpy, joblib, colorama, scipy, python-dateutil, cma, scikit-learn, pandas, bayesian-optimization, nevergrad
Successfully installed bayesian-optimization-1.4.3 cma-3.3.0 colorama-0.4.6 joblib-1.3.2 nevergrad-1.0.0 numpy-1.26.1 pandas-2.1.2 python-dateutil-2.8.2 pytz-2023.3.post1 scikit-learn-1.3.2 scipy-1.11.3 six-1.16.0 threadpoolctl-3.2.0 typing-extensions-4.8.0 tzdata-2023.3
Done!
python:         C:/Users/aaa/.conda/envs/r-reticulate/python.exe
libpython:      C:/Users/aaa/.conda/envs/r-reticulate/python39.dll
pythonhome:     C:/Users/aaa/.conda/envs/r-reticulate
version:        3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON

> conda_install("r-reticulate", "numpy", pip=TRUE)

C:\Users\aaa\Documents>CALL "C:\ProgramData\miniconda3\condabin\activate.bat" "r-reticulate" 

C:\Users\aaa\Documents>conda.bat activate "r-reticulate" 

(r-reticulate) C:\Users\aaa\Documents>"C:\Users\aaa\.conda\envs\r-reticulate/python.exe" -m pip install --upgrade --no-user numpy 
Requirement already satisfied: numpy in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (1.26.1)
[1] "numpy"
> conda_install("r-reticulate", "nevergrad", pip=TRUE)

C:\Users\aaa\Documents>CALL "C:\ProgramData\miniconda3\condabin\activate.bat" "r-reticulate" 

C:\Users\aaa\Documents>conda.bat activate "r-reticulate" 

(r-reticulate) C:\Users\aaa\Documents>"C:\Users\aaa\.conda\envs\r-reticulate/python.exe" -m pip install --upgrade --no-user nevergrad 
Requirement already satisfied: nevergrad in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (1.0.0)
Requirement already satisfied: numpy>=1.24.0 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from nevergrad) (1.26.1)
Requirement already satisfied: cma>=2.6.0 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from nevergrad) (3.3.0)
Requirement already satisfied: bayesian-optimization>=1.2.0 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from nevergrad) (1.4.3)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from nevergrad) (4.8.0)
Requirement already satisfied: pandas in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from nevergrad) (2.1.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from bayesian-optimization>=1.2.0->nevergrad) (1.11.3)
Requirement already satisfied: scikit-learn>=0.18.0 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from bayesian-optimization>=1.2.0->nevergrad) (1.3.2)
Requirement already satisfied: colorama>=0.4.6 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from bayesian-optimization>=1.2.0->nevergrad) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from pandas->nevergrad) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from pandas->nevergrad) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from pandas->nevergrad) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from python-dateutil>=2.8.2->pandas->nevergrad) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aaa\.conda\envs\r-reticulate\lib\site-packages (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad) (3.2.0)
[1] "nevergrad"
> py_config()
python:         C:/Users/aaa/.conda/envs/r-reticulate/python.exe
libpython:      C:/Users/aaa/.conda/envs/r-reticulate/python39.dll
pythonhome:     C:/Users/aaa/.conda/envs/r-reticulate
version:        3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON`

I completed the installation, but I ended up with numpy missing.
Please tell me how to deal with this.

**Comment by gufengzhou** [comment]
I'm seeing two diff paths, `c:\users\aaa.conda\envs\r-reticulate\)` and  `C:/Users/aaa/.conda/envs/r-reticulate`. looks like different envs?

**Comment by gufengzhou** [comment]
please reopen if necessary
