### ISSUE TITLE
Refresh Error - One or both dimensions exceed the maximum (50000px)

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#853]
Hi everyone, I wanted to run the refresh function for a client but I'm running into the following error. Has anyone encountered this before and knows how to fix it? Thanks in advance!

![image](https://github.com/facebookexperimental/Robyn/assets/118725564/0f5c13c1-058e-4339-a3b6-4ec9b522b2d2)

**Comment by gufengzhou** [comment]
the error message is quite clear. maybe you could try setting export = FALSE in refresh? you could still access the plots from the object `RobynRefresh$refresh$plots`

**Comment by bart-vanvlerken** [comment]
I was able to export using robyn_onepagers()
