### ISSUE TITLE
(reopen) robyn_allocator - What's the difference between expSpendUnitTot & optmSpendUnitTotal?

### ISSUE THREAD

**Issue by boschmonart** [facebookexperimental/Robyn#854]
Hi,
reopening [this issue](https://github.com/facebookexperimental/Robyn/issues/776)

thanks

**Comment by boschmonart** [comment]
Difference seems to come from the limit in channel constrains (200%). Would make sense to increase this to for example 1k%? or this 10x increase are outside of robyn scope?

**Comment by gufengzhou** [comment]
Sorry for the late reply. Please see the schema [here](https://github.com/facebookexperimental/Robyn/blob/main/demo/schema.R)

in general, it's risky to 10x the spend constraints. It's not very realistic to expect this kind of "prediction" to be very accurate.

**Comment by gufengzhou** [comment]
please reopen if necessary
