### ISSUE TITLE
Budget Allocator - Greater ROI with similar spend

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#861]
Hi everyone, hope you're doing well. A client that relies solely on performance marketing wanted to experiment with mid-funnel spend in order to build their brand. The MMM showed that this was effective, so that's great. Now we arrive at the budget allocator. Because most channels are affiliates, the client wanted to fix spending or decrease it to 0 (see the plot below). However, I'm getting a better ROI with the same spend for some channels, surely this can't be possible. Has any of you encountered this before? I'd appreciate your feedback!

![1_89_6_reallocated_best_roas](https://github.com/facebookexperimental/Robyn/assets/118725564/8bbb624b-2cfb-4c09-a83d-d50e024b75c6)

**Comment by gufengzhou** [comment]
There's been a fix on this, can you please update and retry? In general it's not impossible to have increasing ROAS, if you are at the beginning of an S-curve, mROAS and ROAS will both grow.

**Comment by bart-vanvlerken** [comment]
That's what I thought! We've since chosen a different way forward so unfortunately I cannot test and replicate, but it's good to know that there's been an update! I will re-open if the issue occurs again.
