### ISSUE TITLE
Budget Allocator ROAS does not match one-pager ROAS with weibull PDF adstock

### ISSUE THREAD

**Issue by iamlostcoast** [facebookexperimental/Robyn#866]
Hello, in my one pager, I am seeing substantially higher ROI numbers than the budget allocator suggests, across all channels.  I'm setting the budget allocator window to the entire model window.  For the `Initial` budget optimization result, I would expect ROI to match the ROIs from the one pager for each channel, but that's not the case.  I was previously experimenting with geometric adstock curves, and when I used those, the ROIs did match, so it seems to me there may be an issue with the way weibull adstocking is implemented in conjunction with the budget allocator.

## Environment & Robyn version
- Robyn version: `‘3.10.3’`
- R version: `R version 4.3.1 (2023-06-16)`

**Comment by iamlostcoast** [comment]
I believe this may be related to this issue: https://github.com/facebookexperimental/Robyn/issues/809

**Comment by iamlostcoast** [comment]
I'm going to close this given that this is related to an issue discussed in depth [here](https://github.com/facebookexperimental/Robyn/issues/734).  I do think it would be great if it were a bit more clear somewhere that essentially the simulator is biased towards channels where immediate spend > carryover, at least that's how I'm interpreting this!

**Comment by AdimDrewnik** [comment]
> I'm going to close this given that this is related to an issue discussed in depth [here](https://github.com/facebookexperimental/Robyn/issues/734). I do think it would be great if it were a bit more clear somewhere that essentially the simulator is biased towards channels where immediate spend > carryover, at least that's how I'm interpreting this!

Can you explain in what way simulator is biased against carryover (what causes that)? In my case the longer simulation time period I select the less carryover is marked on Hill curves.
