### ISSUE TITLE
Conversion for a particular channel given a Spend. 

### ISSUE THREAD

**Issue by noob100000** [facebookexperimental/Robyn#869]
Hi. Thanks for making this package. It's really cool. 

I am having weekly data which has media spend and conversions. 
I have inputted the data and run the robyn_outputs() to find good models. 

**Based on a selected model how to get the conversion for a particular channel for a given spend and considering last n weeks of adstock effect? Without adstock is also fine (In this case basically output of hill function for the input spend)** 

Example:  
There are 3 channels channel_A, channel_B and channel_C and conversions on weekly level.
After robyn_outputs(), I have selected a model. **For this model how to find the conversion for given spend=30K for the channel_A with or without adstock?**  

Thanks Anyways!!

**Comment by gufengzhou** [comment]
This is the exact use case of `robyn_response()` function. please check [this](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R#L509).
