### ISSUE TITLE
Technical paper/documentation

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#87]
# Contributing to FB NextGen MMM R script

# Issue

I wanted to hear, if there's a technical paper regarding Robyn like the Facebook Prophet [(here)](https://peerj.com/preprints/3190/)

What's the main model? How is it created? What are the parameters etc. etc

Or is the way simply to understand the modelling process to sit down, open the code, and run it through step by step?

I know there's the feature-tab about e.g [ridge-regression](https://facebookexperimental.github.io/Robyn/docs/ridge-regression), but I struggle to find anything of how each feature, transformation etc. work together to create the final Robyn model.

**Comment by gufengzhou** [comment]
Hi, we have to apologise that the documentation is not ideal for the moment. Please understand that Robyn is still quite new and only released since November.  Prophet is indeed our role model regarding documentation. We'll work on this in the second half of the year.

**Comment by Leonelsentana** [comment]
Hi Jakob,

Thanks so much for your interest. As Gufeng said, documentation is a work in progress. To your questions:

- Model: r=Ridge regression with hyperparameter optimization algorithm based on Nevergrad's oneplusone evolutionary algorithm. Whitepaper here: [[LINK](https://research.fb.com/wp-content/uploads/2020/07/Open-Source-Evolutionary-Structured-Optimization.pdf)]
- How is it created: We pretty much do variables transformation for adstocking and media saturation curves,  and run prophet on top of data. Then run a ridge regression with the hyperparameter optimization algorithm mentioned above using 2 objective functions for pareto optimality: NRMSE and the decomp.rssd (Decomp Root sum of squared distance, which is the square root of the difference between share of spend and share of effect squared). Note: we use a third for calibration, if ground-truth experiment calibration is desired. Minimizing distance too between ground-trouth values for a certain date period in the data series. We loop through different parallel trials and iterations for this hyperparameter optimization, where we explore on parameter values such as alphas and gammas for the hill function, thetas for the adstock geometric function, or shapes and scales for weibull, for each channel.  
- We then plot top pareto optimal model solutions plots in a folder, where you can choose the best model according to your business context. 
- Once you choose your preferred model, you may run a budget allocator to either maximize your current budget output or reallocate based on certain total budget increase.

Hope it helps to shade some light and thanks so much for your interest in Robyn :)
Best,
Leo

**Comment by Jakobhenningjensen** [comment]
@Leonelsentana Thanks a lot for that overview - that surely sheds some light of how Robyn is build.
