### ISSUE TITLE
Strange error with adobe-helvetica (?)

### ISSUE THREAD

**Issue by riccardorosalen** [facebookexperimental/Robyn#870]
## Project Robyn
Hello all, I'm trying to use the api but when I execute the demo code, but it returns a strange error. 

## Describe issue

_Error in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): Il carattere X11 -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, con faccia 1 e dimensione 15 non può essere caricato
Traceback:_

_1. lapply(InputCollect$modNLS$plots, plot)   # at line 271 of file <text>
2. FUN(X[[i]], ...)
3. plot.ggplot(X[[i]], ...)
4. ggplot_gtable(data)
5. ggplot_gtable.ggplot_built(data)
6. element_render(theme, "plot.title", plot$labels$title, margin_y = TRUE)
7. element_grob(el, ...)
8. element_grob.element_text(el, ...)
9. titleGrob(label, x, y, hjust = hj, vjust = vj, angle = angle, 
 .     gp = modify_list(element_gp, gp), margin = margin, margin_x = margin_x, 
 .     margin_y = margin_y, debug = element$debug, ...)
10. title_spec(label, x = x, y = y, hjust = hjust, vjust = vjust, 
  .     angle = angle, gp = gp, debug = debug, check.overlap = check.overlap)
11. font_descent(gp$fontfamily, gp$fontface, gp$fontsize, gp$cex)
12. convertHeight(grobDescent(textGrob(label = "gjpqyQ", gp = gpar(fontsize = size, 
  .     cex = cex, fontfamily = family, fontface = face))), "inches")
13. convertUnit(x, unitTo, "y", "dimension", "y", "dimension", valueOnly = valueOnly)
14. grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto), 
  .     valid.units(unitTo))
15. (function (x) 
  . {
  .     UseMethod("descentDetails", x)
  . })(structure(list(label = "gjpqyQ", x = structure(0.5, unit = 0L, class = c("simpleUnit", 
  . "unit", "unit_v2")), y = structure(0.5, unit = 0L, class = c("simpleUnit", 
  . "unit", "unit_v2")), just = "centre", hjust = NULL, vjust = NULL, 
  .     rot = 0, check.overlap = FALSE, name = "GRID.text.268", gp = structure(list(
  .         fontsize = 15), class = "gpar"), vp = NULL), class = c("text", 
  . "grob", "gDesc")))
16. descentDetails.text(structure(list(label = "gjpqyQ", x = structure(0.5, unit = 0L, class = c("simpleUnit", 
  . "unit", "unit_v2")), y = structure(0.5, unit = 0L, class = c("simpleUnit", 
  . "unit", "unit_v2")), just = "centre", hjust = NULL, vjust = NULL, 
  .     rot = 0, check.overlap = FALSE, name = "GRID.text.268", gp = structure(list(
  .         fontsize = 15), class = "gpar"), vp = NULL), class = c("text", 
  . "grob", "gDesc")))
17. grid.Call(C_stringMetric, as.graphicsAnnot(x$label))_

The code I'm trying to run is the demo.R file, not a single line changed.

## Environment & Robyn version
I'm on Ubuntu 22, with R version 4.3.2. Robyn version is 3.10.5.9005.

**Comment by gufengzhou** [comment]
hey, so this is not related to the API, but the R package? where are you running this? where does the code occur? please provide bit more info for debugging

**Comment by gufengzhou** [comment]
please reopen if necessary
