### ISSUE TITLE
Weibull adstock graph problem

### ISSUE THREAD

**Issue by AdimDrewnik** [facebookexperimental/Robyn#877]
When using Weibull adstock the graphical output is problematic and borderline useless. 
For example assume that someone uses few years of daily data and has 10-20 channels. In that case Weibull part of results is so compressed on the graph that nothing useful can be seen. Also why does x axis on this graphs span the range of the whole data set? If I analyse 3 years of daily data why do I need almost 1000 days on x axis?

Graphical results for Weibull adstock should be presented on a separate page. If there are many channels graphs need to be split across multiple pages, e.g. 10 channels per page. 

In case of Weibull pdf adstock showing half life probably makes no sense. Maybe indicating peak is more informative.

**Comment by gufengzhou** [comment]
"Borderline useless" is very passive aggressive language.

**Comment by AdimDrewnik** [comment]
Why this issue was closed? Was I incorrect in my description of the problem? Right now using Weibull pdf is a huge pain when it comes to interpretation of the results.
