### ISSUE TITLE
How to make Weibull plots more legible?

### ISSUE THREAD

**Issue by AdimDrewnik** [facebookexperimental/Robyn#878]
Hi 

Below is an example plot of Weibull pdf adstock. How do I make x-axis to be more reasonable? e.g. end at 60-90 days
My data set has 5 years of daily data. That probably is why x-axis is so long. But I hardly believe spend has more than few months of impact. I want to be able to see at which point in time each channel is peaking. 
Also, what does it mean when halflife line crosses the plot in two points?

![image](https://github.com/facebookexperimental/Robyn/assets/138211926/ce1f1688-8021-4e50-a761-eb52ebcb6da1)

**Comment by gufengzhou** [comment]
Hi, sorry for the late reply. It's definitely possible to set cutoffs, we don't have capacity to prioritize this at the moment tho. If you want to contribute, please feel free to create a PR:)

**Comment by gufengzhou** [comment]
Please reopen if necessary. half-life just means when the effect decays to half from peak.
