### ISSUE TITLE
Difference between immediate vs. carryover in OutputCollect and OutputModels

### ISSUE THREAD

**Issue by caarolinagil** [facebookexperimental/Robyn#879]
## Describe issue
Hi,

I noticed that by extracting the immediate vs carryover plot directly from the one pager, the result is one. However, checking the OutputModels$resultCollect$xDecompVec data and adding it all up to get the aggregate, the result is different.
Shouldn't it be the same on both sides?

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn 3.9.0
- R version: 4.2.1

**Comment by gufengzhou** [comment]
Robyn actually doesn't provide the immediate vs carryover breakout as time series because it's too chunky to store. In pareto_aggregated.csv, or OutputCollect$xDecompAgg, you can find column carryover_pct that's the same as the carryover vs immediate plot in onepager.

**Comment by caarolinagil** [comment]
Thanks for your answer.

One more doubt, the carryover_pct column in OutputCollect$xDecompAgg, from which version is it available? I can't find it in v.3.9.0. Is it in the next one?

Thanks again!

**Comment by gufengzhou** [comment]
I recommend you to update to the latest GitHub version.

**Comment by caarolinagil** [comment]
Perfect, I'll start working with the latest stable version of Github.

We can close the issue.

Thanks! Have a nice day.
