### ISSUE TITLE
Any way to avoid downloading Anaconda?

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#88]
# Contributing to FB NextGen MMM R script

# Issue
The lines
```R
conda_create("r-reticulate") #must run this line once only
conda_install("r-reticulate", "nevergrad", pip=TRUE) #must install nevergrad in conda before running Robyn
use_condaenv("r-reticulate")
```
require Anaconda to be installed. Since I'm using PIP and have multiple bad experiences by mixing pip and conda, is there a way to avoid using conda i.e using `use_python` instead? 

# Steps to Reproduce

# Expected Behavior

Being able to not mix pip/anaconda

# Actual Results

# Environment

R version: 4.1.0

**Comment by gufengzhou** [comment]
Hi, I'm sure it's possible to avoid conda. Please check reticulate's documentation about installing python package in pip environment https://rstudio.github.io/reticulate/articles/python_packages.html

**Comment by renzoluongoakiki** [comment]
I had the same question and solved it like this

virtualenv_create("r-reticulate")
virtualenv_install("r-reticulate", "nevergrad")
use_virtualenv("r-reticulate")
