### ISSUE TITLE
'500 Internal Server Error' while accessing 'robyn_outputs'  - robyn_api for python

### ISSUE THREAD

**Issue by apoorvabc** [facebookexperimental/Robyn#880]
Hello team,

I am working with the robyn api for python and facing issue accessing one of the functions 'robyn_outputs'.
https://github.com/facebookexperimental/Robyn/blob/main/robyn_api/robyn_python_notebook.ipynb

```
# Get response
OutputCollect = robyn_api('robyn_outputs',payload=payload)
```

I am encountering '500 Internal Server Error' despite having the payload in the correct format. Each component (InputCollect, OutputModels, outputsArgs) contains valid data in the right format.

**Comment by ebyjose** [comment]
Can you share the payload and sample dataset so that we can replicate the issue to check what might be happening

**Comment by apoorvabc** [comment]
There was an issue with the port since I had multiple sessions running which led to this error. This now stands resolved.

**Comment by apoorvabc** [comment]
Earlier it worked fine and I was able to run the allocator function and get the desired output. However, I am still having this issue at output collect {'error': '500 - Internal server error'}. Made sure there are no open ports running and the connections have been closed and retried. I am using the same dataset as shown in the example with no further changes done. Kindly assist.

**Comment by ebyjose** [comment]
Tried again with stimulate data but unable to replicate issue. 
Can you try changing the plot location to a smaller file path, sometimes it may help (a usual suspect on windows machine)

**Comment by apoorvabc** [comment]
It was indeed an issue with the path to the plot folder. I had overlooked it assuming it was an issue to the connection due to the error. Thank you for pointing me to this.
