### ISSUE TITLE
Inquiry About Sales Incremental Analysis with Budget Changes Using Robyn

### ISSUE THREAD

**Issue by jiyeoneom1** [facebookexperimental/Robyn#883]
## Project Robyn
Hey there,

I am using the Robyn model for MMM and am interested in understanding how to analyze the incremental impact on sales due to budget increases or decreases. My data is weekly and spans from 2022-03-29 to 2023-10-31. Could you guide me on how to approach this analysis within the Robyn framework? Specifically, what steps or functions should be used to accurately measure sales incrementality linked to budget variations? 

Additionally, after running OutputCollect, how can I generate the **Initial vs Optimized Budget Allocation graphs**? Is it necessary to perform a Model Refresh or Calibration for this purpose, and if so, could you provide guidance on these processes?

Thank you for your assistance.

Best regards,

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn version: 3.10.3
- R version: 4.1.2

**Comment by gufengzhou** [comment]
please go through demo.R. It's all there.
