### ISSUE TITLE
Robyn Python API - 

### ISSUE THREAD

**Issue by bortackers** [facebookexperimental/Robyn#886]
## Issue
Following the example notebook in this repo, robyn_api/robyn_python_notebook.ipynb, I receive the following error message when I attempt to run the Multi-Objective Optimisation plots:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16968\361802054.py in <module>
----> 1 plot_outputgraphs(OutputModels,graphtype='moo_distrb_plot',max_size=(1000, 1500),argumenttype='none')

~\MMM\Robyn\Robyn-main\robyn_api\python_helper.py in plot_outputgraphs(OutputJson, argumenttype, graphtype, max_size)
    126     """
    127     if(graphtype in ['moo_distrb_plot']):
--> 128         image_data = binascii.unhexlify("".join(OutputJson['convergence']['moo_distrb_plot']))
    129         image = Image.open(io.BytesIO(image_data))
    130         image.thumbnail(max_size, Image.Resampling.LANCZOS)

KeyError: 'convergence'
```
Checking the contents of `OutputModels` it returns `['error']`, which is due to `500 - Internal server error`.

## Offending Code
`plot_outputgraphs(OutputModels,graphtype='moo_distrb_plot',max_size=(1000, 1500),argumenttype='none')
`
## Environment & Robyn version
- Robyn version: `3.10.5.9009`
- R version: 4.3.1 (2023-06-16 ucrt)

**Comment by ebyjose** [comment]
Hi. Can I check if you ran code above this and have the object OutputModels computed? If so can you try printing the dictionary (OutputModels) and share its content. That will help us further debug

**Comment by bortackers** [comment]
hi @ebyjose, 
I ran every line up until then with no issue. When I ran the code below, it did not return an error, however, did not show the results of the response as seen in the sample workbook. I'm currently following it step-by-step to understand how it works and have made no changes at all to the code.

<img width="676" alt="image" src="https://github.com/facebookexperimental/Robyn/assets/154476435/0689aaf8-e4fc-40a7-aaf2-48d09e0ce80d">

**Comment by ebyjose** [comment]
Thanks for your patience @bortackers and sorry for delayed response on this. Christmas and NYE time off and all.
Would you be able top share the dataset or the payload used to reproduce this error?

**Comment by bortackers** [comment]
no problem! I'm using the sample data set included in the repo _dt_simulated_weekly_

**Comment by bortackers** [comment]
```
dt_simulated_weekly = pandas_builder(robyn_api('dt_simulated_weekly'))
dt_simulated_weekly.head()
```

**Comment by ebyjose** [comment]
Unable to replicate error. It seems like the issue resides with the payload. since the object OutputModels wasnt created.
Can you try sharing the payload for me to replicate the issue

**Comment by sujaykar** [comment]
I have installed all the R modules for Robyn and API and everything works until I am calling robyn_api to see robyn_version and call it for data loads. I was able to run the api service as detailed in the documentation. What might be the problem here?

**Comment by ebyjose** [comment]
@sujaykar Can you confirm which OS you are running this on? If on windows - can you share the log? If on others - can you share the exact error message you recieve?

**Comment by ranjanharman** [comment]
Hi @ebyjose @bortacers  .I am also getting the same error. Can you please tell which version of R, robyn_api and nevergard i shall use

**Comment by gufengzhou** [comment]
please reopen if necessary
