### ISSUE TITLE
Effect of trend,season and all the prophet decomposition is 0

### ISSUE THREAD

**Issue by roylist** [facebookexperimental/Robyn#889]
## Describe issue
The prophet decomposition factors are used to debias marketing channel effect. But due to the marketing channel itself follows DAU trend and seasonality or other unknown reasons, the coefficient of prophet decomposition factors is 0, which means the debias fails. How to change the coefficient distribution?

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.
![instance](https://github.com/facebookexperimental/Robyn/assets/42435138/2cd25e63-ad65-4048-bfc4-7cb0925bee4a)

**Comment by gufengzhou** [comment]
A variable can have 0% decomp, but explains a lot of variance of the dep_var. Season is typical, it has values centered at 0, thus when summed, it's always (close to) 0, but if your data has strong seasonality, it will be explained by the season var. Same for weekday. It's the reference point problem for variables with relative scale. 

Holiday/trend are not centered around 0 and thus it depends, they might be reduced to 0 by regularisation.
