### ISSUE TITLE
Logic behind Average Adstock decay rate

### ISSUE THREAD

**Issue by xaviangles** [facebookexperimental/Robyn#89]
Hi, 

thanks for the work you guys have done with Robyn. Really amazing!

I do have one question regarding how you calculate the decay rate. I struggle to understand how x value that equates `sum(decay_rate) -  1/(1-x)-1` to 0 is equivalent to the average adstock decay rate.

For reference, that can be found lines 1746 to 1758 on `fb_robyn.func.R`.

Thanks in advance!

Xavi & Leo

**Comment by gufengzhou** [comment]
Thanks! The purpose here is actually to show a simple "decay rate" when using weibull adstock. For geometric, a fixed decay rate of for example 80% is easy to understand and visualise. But Weibull has changing decay rate, for example 80% for day1, 78% day2, 75% day3 etc. For the decay rate plot in model onepager, we want to also show a simple "decay rate" for Weibull for better interpretation. So the idea is just to compare Weibull with Geometric: what is the Geometric equivalent fixed decay rate for a Weibull decay Serie of 0.8, 0.78, 0.75... i do this by comparing the infinite sum of Weibull and Geometric. For geometric, the formula for infinite sum is 1/(1-r), where the r is the fixed decay rate. You can see this in the "Sum" session of this Wiki Page https://en.wikipedia.org/wiki/Geometric_series

**Comment by xaviangles** [comment]
Genius, now it all makes sense. Thank you again!
