### ISSUE TITLE
How to active MAPE calculation

### ISSUE THREAD

**Issue by DongHarry-Kang** [facebookexperimental/Robyn#893]
Hi all -

I am running several data analysis, however everytime I run, it seems that MAPE is not calculated. Could somebody let me know how we can calculate MAPE?

![image](https://github.com/facebookexperimental/Robyn/assets/146807827/54ca001c-ba54-4385-913e-9e86c840b4d8)

**Comment by gufengzhou** [comment]
MAPE is only calculated for calibrated models. Check nrmse or adjusted r2 for "normal" model

**Comment by DongHarry-Kang** [comment]
THank you very much!
