### ISSUE TITLE
Budget Allocator

### ISSUE THREAD

**Issue by DongHarry-Kang** [facebookexperimental/Robyn#894]
https://github.com/facebookexperimental/Robyn/blob/4300767cd11e4058f8f41d664b041659599c2f42/demo/demo.R#L374

Hi all -

I have one question, currently BudgetAllocator by defaults uses the last month for budget allocation exercise. How do I change to the entire period of time?

**Comment by gufengzhou** [comment]
date_range = "all"

Please check the documentation ?robyn_allocator

**Comment by DongHarry-Kang** [comment]
Thank you very much!
