### ISSUE TITLE
Unable to get decent R2 in Test due to new collection launch for the brand which resulted in step increase in the daily sales

### ISSUE THREAD

**Issue by CJ2407** [facebookexperimental/Robyn#898]
## Describe issue
My brand has launched a new collection in Mar 2023 which has resulted in a step increase in the average daily sales. I am using 972 days of data in this modeling (Feb 2021 - Sep 2023). To account for this change, I have added context variable called "BrandMoment" which I have set to 1 from 3/4/2023 onwards. I tried numerical values as well in this variable trying to give gradual increase in the impact of this brand moment. I have also given interaction context var = having a product of trend variable with simply categorical brand moment variable. But none of these way I am getting this new trend captured in the prediction.

Could you please assist on how to proceed with this to get better R2 in the Test and better NRMSE for test? So, far I have not tuned any hyperparameters for any channel and they are set to recommended values. The channel that was promoting this launch is also generating 0 coefficient.

![image](https://github.com/facebookexperimental/Robyn/assets/91983160/40f7c6d0-e3b2-4148-99f7-80d05492595c)

![image](https://github.com/facebookexperimental/Robyn/assets/91983160/78fb099b-2f84-47c9-b017-81bccf48c23c)

Attaching files to recreate this example on your side - 
[Daily_Data_M2_v1 - github.csv](https://github.com/facebookexperimental/Robyn/files/13896614/Daily_Data_M2_v1.-.github.csv)
[CodeforGithub.txt](https://github.com/facebookexperimental/Robyn/files/13896616/CodeforGithub.txt)

**Comment by CJ2407** [comment]
@laresbernardo @gufengzhou Sorry for tagging you guys specifically, but I could really use your inputs here! Thank you so much in advance :)

**Comment by gufengzhou** [comment]
I suggest you to turn off ts_validation. Because you're not really forecasting and thus test stats noch really necessary. 

In general it's very difficult to get good test R2 because of the step change that's completely outside of the training data. The model has no chance to "learn" about the effect so to say.

**Comment by CJ2407** [comment]
Thanks @gufengzhou. Your input is very helpful. A few more things to clarify on the same note - 

1. Since we don't yet have forecasting capabilities within Robyn, should we always turn off ts_validation?
2. If yes for above, then how do we know that model is not biased or overfitting?
3. Is there an ETA on the forecasting capabilities?
4. As you can see we have huge impact on our KPI due to holidays and promotions around that time, is there an easy way to bake that in the model? Currently, I keep adding PROMO dummy flags in the model and it's quite a manual step.

**Comment by gufengzhou** [comment]
I'd say it's ok to disable ts validation without forecasting. MMM's main purpose is inference.
Robyn already use ridge regression to reduce overfitting, also the second objective function decomp.rssd prevents the optimisation from overfitting to the training set. 

For your promotion, if you spend extra on these periods, it should be reflected as media spend. If could also flag the holiday data frame to include some of these effects into holiday if you don't want them separately.

**Comment by gufengzhou** [comment]
please reopen if necessary
