### ISSUE TITLE
Please tell me the definition of the column of de_simulated_data.csv

### ISSUE THREAD

**Issue by watanta** [facebookexperimental/Robyn#9]
This is a question, not an issue. I'm sorry if I shouldn't ask a question here. Please tell me in the right place.

# background
I want to know what data is needed for an analysis like quick start.

# question
Please tell me the definition of the column of de_simulated_data.csv.
I think the following, is it correct?

|  column_name  |  description  |
| ---- | ---- |
|  DATE  |  The day the row was observed  |
|  revenue  |  revenue of the day  |
|  tv_S|  Investment in that channel  |
|  ooh_S|  Investment in that channel  |
|  print_S  | Investment in that channel  |
|  facebook_I  | Investment in that channel  |
|  search_clicks_P  | what is this? |
|  competitor_sales_B| what is this?  |
|  facebook_S　| what is this? |

I would like to do this analysis on the data of the company I belong to. :)

**Comment by Leonelsentana** [comment]
Hi @watanta! Thanks so much for your feedback and questions:
column_name | description
-- | --
DATE | The day the row was observed
revenue | revenue of the day
tv_S | Investment (Spend) in that channel
ooh_S | Investment (Spend) in that channel
print_S | Investment (Spend) in that channel
facebook_I | Impressions in that channel
search_clicks_P | The number of clicks in google search ads (Not necessary, you could just use search investment instead)
competitor_sales_B | This is the sales that competitors had for very similar products. (Not necessary to build the model but it usually helps as a control variable)
facebook_S | Investment (Spend) in that channel

You may use spend and/or impressions for any channel without a problem with our code there is not a strict requirement there.

Hope it helps!
Happy coding 👍

**Comment by wenyanyy** [comment]
@Leonelsentana Could you please explain why we may use spend and impression together without problem? because spend is about money and non-spending is about impression, Can I use both of them together in the model?
