### ISSUE TITLE
wrong notebook links in robyn_python_notebook.ipynb

### ISSUE THREAD

**Issue by iuiu34** [facebookexperimental/Robyn#902]
Hi,
links in the index of `robyn_api/robyn_python_notebook.ipynb` don't point to each section. All point to the root folder.

thanks

**Comment by yu-ya-tanaka** [comment]
Hi
Can you download the notebook and check the index on your local device? Github looks not supporting the internal linking function in a notebook.
But I found some minor bugs in index, will fix it soon.

**Comment by yu-ya-tanaka** [comment]
Hi @iuiu34, I fixed index of notebook. Please use the latest version on your local env.
