### ISSUE TITLE
hierarchical MMM 

### ISSUE THREAD

**Issue by noamanemobidata** [facebookexperimental/Robyn#909]
Hello! Appreciate the package you've provided! 

I'm interested to know if there are any plans to incorporate sub-national data. We believe that incorporating this approach could yield more accurate results due to the utilization of a greater number of data points, potentially aiding in addressing multicollinearity issues.

**Comment by gufengzhou** [comment]
Hi! Yes we're aware of this and will try to prioritize, but we cannot share any timeline due to resource constraints. thanks for your understanding.
