### ISSUE TITLE
error writing to connection

### ISSUE THREAD

**Issue by DongHarry-Kang** [facebookexperimental/Robyn#911]
## Describe issue
Describe your issue and provide warnings and error messages.

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)
Hi, when I do a simulation with a lot of iterations, I keep getting the below message when running robyn_outputs(). is there anything to solve this? what if I dont have to output onepagers?

>> Plotting 15 selected models on 11 cores...
  |==================================================                                                                                                                                           |  27%Failed exporting results, but returned model results anyways:
 Error in serialize(data, node$con): error writing to connection

**Comment by gufengzhou** [comment]
This seems to be OS-related, as in previous issues [here](https://github.com/facebookexperimental/Robyn/issues/652) and [here](https://github.com/facebookexperimental/Robyn/issues/845). Please try the latest Robyn github version first. If not, a workaround would be setting `robyn_outputs(export = FALSE)`, then you can manually create loop the onepagers using `robyn_onepagers`

**Comment by DongHarry-Kang** [comment]
Thank you very much. Now I can out the figures. :)
