### ISSUE TITLE
Robyn future budget allocation feature status

### ISSUE THREAD

**Issue by ekladiousm** [facebookexperimental/Robyn#914]
Hello all,
Great work on the project!
I was wondering what is the expected release date for the future allocation feature. I have been looking forward for this for quiet some time and would really appreciate it if there is hope for the near future 😁
Thanks

**Comment by apoorvabc** [comment]
Hello Team!

I would like to know about this feature too. Just wondering if there's any news on when we can expect the **Budget allocation for the future time period** feature to be available? If not, are there any workarounds we could explore in the meantime?

**Comment by gufengzhou** [comment]
Hi all, I apologize for the delay because of our internal resource uncertainty. Unfortunately I can't provide further timeline. What I can promise is that I'll do my best to ship these features as soon as our capacity allows.
