### ISSUE TITLE
Issue creating one  pagers either through robyn_outputs or onepager()

### ISSUE THREAD

**Issue by zivzach** [facebookexperimental/Robyn#921]
## Describe issue
I'm able to follow the demo.r script up until the point where you use the robyn_outputs function to produce one pagers. It writes every file except the one pagers. Even if I ignore this function in the demo and try to spit out a one-pager using the onepager() function, my Rstudio instance continues to run for hours with no end in sight until I interrupt the session and it crashes. At first, I was able to get it to run by installing the rngtools and foreach libraries, but now it is spinning out again. Is it possible that robyn has additional library requirements that are not mentioned in the requirements?

## Provide reproducible example
This section of code is where I get stuck. My dataset is different with many zeroes throughout.

## Environment & Robyn version
Robyn Version 3.10.3
R Versions 4.3.2

**Comment by ebyjose** [comment]
Ideally, if you are able to run the outputs. The package requirements should have been met. Can you please share the OS you are using. If using windows, can you also take a look at the log file which is generated and stored on your HDD.

**Comment by zivzach** [comment]
Repeating the above with more memory allocation stopped the above error
