### ISSUE TITLE
Spend and Effect Share definition

### ISSUE THREAD

**Issue by xaviangles** [facebookexperimental/Robyn#95]
Hi there, 

Have been working on understanding the code, and got a question when I tried to understand both effect and spend share. 

My assumption was that both effects were to represent the following:

- For spend share, the proportion of spend I invest in each channel over a given period of time. 

- For effect share, the proportion of signups that can be attributed to each marketing channel. 

Based on that assumption, I took for granted that they were calculated as the sum of the costs and the sum of the regression contributions per marketing channel but in the code the mean is used instead. 

However, using the mean makes the shares susceptible to change depending on how the campaigns are distributed. Here’s an example to clarify based on spend share (please assume that if there is a cost > 0 on a given day is because there is a campaign running with its proportionate volume):

|     | Case 1            |                            |     |                                      Case 2 ||
--- | --- |---|--- | ---|---|
|     |Channel 1 cost | Channel 2 cost |       | Channel 1 cost | Channel 2 cost |
| Day 1 | 0 | 20 | | 15 | 20 |
| Day 2 | 20 | 0 | | 0 | 0 |
| Day 3 | 0 | 0 | | 15 | 0 | 
| Day 4 | 30 | 30 | | 10 | 30 |
| Day 5 | 0 | 0 | | 10 | 0 |
| | |  | | | |
| Mean (exc 0) | 25 | 25 | | 12.5 | 25 | 
| Spend Share | 0.5 | 0.5 || 0.33 | 0.67 |
| | | | | | |
| Sum | 50 | 50 | | 50 | 50 | 
| Spend Share | 0.5 | 0.5 | | 0.5 | 0.5 |

As you can see, using the means the spend share is susceptible to change depending on the campaign distribution whereas if you use the sum instead, the spend share remains constant regardless of the campaign distribution. 

That would have a direct impact on the decomp.rssd, thus impacting the pareto front and the models that robyn dumps into the png and the csv files. 

Would it be possible to understand why the spend and effect shares are calculated on the basis of the mean and not on the basis of the sum? And to get an understanding of why the sum is not a good option? 

Thanks in advance!

**Comment by gufengzhou** [comment]
Hi, glad that you're digging this deep already:) indeed, it's our intention to use mean of non-zero periods as share of spend instead of sum or mean of all periods (which is the same as sum when calculating share). Assuming a scenario with 100 weeks of data, one channel is new and has been spending for only 10 weeks. Let's say the total spend for this channel is 1mio. What is the mean spend? Is it 1mio/100 or 1mio/10? We believe it's more accurate/realistic to only look at active periods in order to better represent active marketing decisions. But of course you can always make an argument for the other option. This is what makes more sense to us. Hope it's helpful?

**Comment by xaviangles** [comment]
Hi there, 

It does make total sense to use the non-0 periods to calculate the means, but I guess that my point might have gotten lost here. 

What I am struggling to understand is the selection of the mean instead of the sum.

Say that for a channel X, over the period of 100 weeks and accepting that only the non-0 periods are counted, using the sum will ensure that regardless of how that budget is distributed, the share will always be 80%. However, the mean will not ensure that the share will be 80% as it will be dependent on how this budget is distributed. In fact, if you use the mean what you are actually calculating is the proportion of average spend per active period per marketing channel. And that to me sounds more like the average spend per time unit share.

So I guess that my question could be reframed as follows:

Why is the spend/effect share defined as the proportion of the average over active time unit instead as the overall spend/effect proportion? 

Thanks!

**Comment by gufengzhou** [comment]
I think your case 2 above is a very good example to show the difference between share of non-zero spend mean and share of spend sum. Channel 2 only spends in 2 weeks, while channel 1 spreads its money over 4 weeks. We believe marketing managers make active decision on when to spend money and we want to reflect that using non-zero spend mean. But as I said, you could always make an argument for the other option. It's just our choice.

**Comment by xaviangles** [comment]
I see your point, and it is super interesting because I think that the selection of sum _vs._ avg would be dependant on the situation. 

Thanks you for your feedback! Very useful as usual!
