### ISSUE TITLE
Loading Robyn issue

### ISSUE THREAD

**Issue by ychen2024** [facebookexperimental/Robyn#951]
## Describe issue
Packages Robyn, numpy, and nevergrad are all installed. When loading Robyn, library(Robyn), error message "R session Aborted." Tried many times, same issue.  

## Environment & Robyn version
- Robyn version:  3.10.3
- R version: 4.3.2
- Windows OS

**Comment by gufengzhou** [comment]
sorry this is very hard for us to debug. can you try another laptop?

**Comment by ychen2024** [comment]
I was able to download and install later on. I don't know what I specifically did, though.
