### ISSUE TITLE
Error in check_datevar

### ISSUE THREAD

**Issue by kevinSTS** [facebookexperimental/Robyn#957]
## Project Robyn

This is the error output when running InputCollect:

_Error in check_datevar(dt_input, date_var) : 
  You must provide only 1 correct date variable name for 'date_var'_

There are no errors up to InputCollect.

Here is date column of the CSV file being imported. Date column of type date, and the others of type general.

<img width="100" alt="Capture" src="https://github.com/facebookexperimental/Robyn/assets/58270576/f095450a-58c6-4fce-8e4f-73b99bdc5ccd">

```
InputCollect <- robyn_inputs(
  dt_input = dt_input_file,  (name of file from import
  dt_holidays = dt_prophet_holidays,
  date_var = "Date", 
```

## Environment & Robyn version

- Robyn version: 3.10.3`
- R version 4.3.3 (2024-02-29 ucrt)

**Comment by gufengzhou** [comment]
Please check your dataframe dt_input_file within R first, not just in Excel

**Comment by kevinSTS** [comment]
Thanks gufengzhou. 
Encoding during the csv import changed the first column name from Date to i..Date. 
Adding encoding to the read line fixed this.  `read.csv('<fileName>.csv', fileEncoding = 'UTF-8-BOM')`
