### ISSUE TITLE
Issue when I run the model with 12 to 14 variables in dev (3.10.6001 )

### ISSUE THREAD

**Issue by amanrai2508** [facebookexperimental/Robyn#967]
## Describe issue
Currently I am using version 3.10.6001 (dev) of Robyn. When I use 2 to 4 variables, the model runs successfully. However, when I run the model with 12 to 14 variables, the following error occurs: "Error in png_dev(..., res = dpi, units = "in")  "err_trace": "Traceback (most recent call last):\n  File \"/app/src/robyn/python/robyn_train.py\" Can someone help me with this, Is this the problem of robyn ?

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- R version (3.10.6001 (dev))

**Comment by yu-ya-tanaka** [comment]
Hi @amanrai2508 , How are you using Robyn, is it API for Python? Is robyn_train.py a program you created?
Also, please share the following
- OS
- Source code where the error occurred
- Full text of the error message

Thanks,

**Comment by yu-ya-tanaka** [comment]
Thanks, Can you share the code where the error is happening? Also can you try R version Robyn (not API) to test whether the same error happen or not?

**Comment by amanrai2508** [comment]
It got solved in the latest version.
