### ISSUE TITLE
Error running f.robyn() -- hyperparameters out of range

### ISSUE THREAD

**Issue by lbarta** [facebookexperimental/Robyn#97]
# Contributing to FB NextGen MMM R script

# Issue

I've installed all packages/ Nevergrad and updated my data to match the format/data types of the simulated data, but when I try to run f.robyn, I receive the following error:

 ```
Error in { : 
  task 1 failed - "hyperparameters out of range. theta range: 0-1 (excl.1), shape range: 0-5 (excl.0), alpha range: 0-5 (excl.0),  gamma range: 0-1 (excl.0)" 
6.
stop(simpleError(msg, call = expr)) 
5.
e$fun(obj, substitute(ex), parent.frame(), e$data) 
4.
foreach(i = 1:iterPar, .export = c("f.adstockGeometric", "f.adstockWeibull", 
    "f.transformation", "f.rsq", "f.decomp", "f.calibrateLift", 
    "f.lambdaRidge", "f.refit"), .packages = c("glmnet", "stringr", 
    "data.table")) %dopar% { ... at fb_robyn.func.R#1026
3.
system.time({
    for (lng in 1:iterNG) {
        nevergrad_hp <- list()
        nevergrad_hp_val <- list() ... at fb_robyn.func.R#976
2.
f.mmm(set_hyperBoundLocal, set_iter = set_iter, set_cores = set_cores, 
    optimizer_name = optmz) at fb_robyn.func.R#1433
1.
f.robyn(set_hyperBoundLocal = set_hyperBoundLocal, optimizer_name = set_hyperOptimAlgo, 
    set_trial = set_trial, set_cores = set_cores, plot_folder = "C:/Users/[plot path]/plot_folder") 
```

While my data has more input variables than the simulated data, I've updated the naming and followed all guidelines for hyperparameter setting (set_hyperBoundLocal list exactly matches local_name, using geometric distribution, alpha = (0.5,3), gamma = (0.3,1), theta = (0,0.3) or (0.1,0.4) or (0.3,0.8)) i.e. they should all be in range, so I'm not sure what's producing this error. I've also tried restarting the session and running with only 1 core, but I get the same error

# Environment

R version 4.1.0, Python version 3.9.5

**Comment by Leonelsentana** [comment]
Hi lbarta,

Hope you are well and thanks for your interest in Robyn. Would you be so kind to share your .exec script with us and maybe just an example screenshot with your data table coming from the .csv you updloaded? I think it will be easier to debug that way in the case bounds are not actually the problem.

Thanks so much,
Best,
Leo

**Comment by lbarta** [comment]
Yes definitely -- attached is the exec script I've updated (in a .txt) and a sample of my input data. Let me know if you need anything else from my end, and thank you!
[fb_robyn_DK.exec.txt](https://github.com/facebookexperimental/Robyn/files/6734983/fb_robyn_DK.exec.txt)
![dt_input sample](https://user-images.githubusercontent.com/86615014/123834803-d0581800-d8d5-11eb-9ad3-3ecdb5f44a03.PNG)

**Comment by Leonelsentana** [comment]
Hi lbarta,

I was looking into the baseline variable names and it looks like you are calling competitor_sales_B but I can't see it in your example data .CSV:
set_baseVarName <- c("competitor_sales_B")
**Could you try either removing that variable and creating an empty object or adding the actual data for competitor_sales_B?**

I can see you are using spend across both var and spend names. remember we tend to recommend using other variables more related to user ad exposure and not pricing such as impressions, clicks, GRPs, etc. within set_mediaVarName. Said that, both objects look OK:
set_mediaVarName <- c("audio_S", "nonCPA_S", "offline_S", "other_S", "partnerships_S", "search_S", "social_S", "tv_S")
set_mediaSpendName <- c("audio_S", "nonCPA_S", "offline_S", "other_S", "partnerships_S", "search_S", "social_S", "tv_S")

Alphas, thetas and gammas all look OK and match the names in your set_mediaVarName variable:
 audio_S_alphas = c(0.5, 3) # example bounds for alpha
  ,audio_S_gammas = c(0.3, 1) # example bounds for gamma
  ,audio_S_thetas = c(0.1, 0.4) # example bounds for theta
  #,audio_S_scales = c(0, 0.1) # example bounds for scale
  #,audio_S_shapes = c(0.0001, 2) # example bounds for shape
  
  ,nonCPA_S_alphas = c(0.5, 3)
  ,nonCPA_S_gammas = c(0.3, 1)
  ,nonCPA_S_thetas = c(0, 0.3)
  #,nonCPA_S_scales = c(0, 0.1)
  #,nonCPA_S_shapes = c(0.0001, 2)
  
  ,offline_S_alphas = c(0.5, 3)
  ,offline_S_gammas = c(0.3, 1)
  ,offline_S_thetas = c(0.1, 0.4)
  #,offline_S_scales = c(0, 0.1)
  #,offline_S_shapes = c(0.0001, 2)
  
  ,other_S_alphas = c(0.5, 3)
  ,other_S_gammas = c(0.3, 1)
  ,other_S_thetas = c(0, 0.3)
  #,other_S_scales = c(0, 0.1)
  #,other_S_shapes = c(0.0001, 2)
  
  ,partnerships_S_alphas = c(0.5, 3)
  ,partnerships_S_gammas = c(0.3, 1)
  ,partnerships_S_thetas = c(0, 0.3)
  #,partnerships_S_scales = c(0, 0.1)
  #,partnerships_S_shapes = c(0.0001, 2)
  
  ,search_S_alphas = c(0.5, 3)
  ,search_S_gammas = c(0.3, 1)
  ,search_S_thetas = c(0, 0.3)
  #,search_S_scales = c(0, 0.1)
  #,search_S_shapes = c(0.0001, 2)
  
  ,social_S_alphas = c(0.5, 3)
  ,social_S_gammas = c(0.3, 1)
  ,social_S_thetas = c(0, 0.3)
  #,social_S_scales = c(0, 0.1)
  #,social_S_shapes = c(0.0001, 2)
  
  ,tv_S_alphas = c(0.5, 3)
  ,tv_S_gammas = c(0.3, 1)
  ,tv_S_thetas = c(0.3, 0.8)
  #,tv_S_scales= c(0, 0.1)
  #,tv_S_shapes = c(0.0001, 2)

**Comment by lbarta** [comment]
I planned on adding non-spend variables in the future, but haven't pulled that data yet/ wanted to trial run with only spend, so I'll get to work on adding that in to see if it helps. 

Also, I just double checked, and I don't have baseline variables activated (I think you were looking at a line that was commented out):

```
activate_baseline <- F
#set_baseVarName <- c("competitor_sales_B") # typically competitors, price & promotion, temperature,  unemployment rate etc
#set_baseVarSign <- c("negative") # c("default", "positive", and "negative"), control the signs of coefficients for baseline variables
```
I was reading through some past issues that had been reported, and saw some people were getting errors from poorly set training size, but it looks like the training size parameter calibration/ setting has been removed in this version - do you think that could be causing it? I'm not sure what else to look at at this point, as the hyperparameters are clearly in bound

**Comment by gufengzhou** [comment]
Hi, this issue is sometimes caused by very sparse data. looking at your screenshot, the offline_S looks like mostly 0. How sparse is this one? Can you try removing this and run everything again? This is also how you can debug, just by removing skeptical input variables one by one and see if it runs

**Comment by lbarta** [comment]
Removed offline as well as TV and that seemed to work! 

Ideally, I would like to include these variables, and the sparsity is primarily in the early period of my data - is there a known workaround for this other than excluding the variable? or do you have any methodologies you would recommend for correcting this? Thanks!

**Comment by gufengzhou** [comment]
Actually we haven't been seeing this error for a while (I thought we solved it already...). I assume you're using the latest code version, right? If yes, would it be possible to send me the data set, so that I can debug it? Of course you can change the scale of the data to protect privacy. That'd be the easiest way for me to find out why

**Comment by lbarta** [comment]
Yes, I'm using the most recent version of the code (pushed April 15 for exec/ April 29 for func). The data set, holiday calendar, and exec script that is throwing the error are attached below (wouldn't allow me to upload csv for some reason, so data and holidays are Excel workbooks, and the exec script as a txt). Thanks for helping look into this! 
[fb_robyn_DK.exec.txt](https://github.com/facebookexperimental/Robyn/files/6785726/fb_robyn_DK.exec.txt)
[holidays.xlsx](https://github.com/facebookexperimental/Robyn/files/6785738/holidays.xlsx)
[inputdata_adjusted.xlsx](https://github.com/facebookexperimental/Robyn/files/6785739/inputdata_adjusted.xlsx)

**Comment by gufengzhou** [comment]
Hey, I found out that your tv_S has an negative value on date 2021-04-16. After turning it to positive the whole script runs on my side, including all variables. I can't see any error with your offline var. Please try again after correcting that. I've also integrated a negative value check now for the future. thanks for sharing the data and raising the issue.

**Comment by gufengzhou** [comment]
two more things 
- you're using daily data, so it's recommended to also use "weekday" in prophet to capture weekday pattern. 
- Also, if there's more than 1 channel within your social var, it's highly recommended to break them out
