### ISSUE TITLE
Input Data: Quarterly Data 

### ISSUE THREAD

**Issue by wenyanyy** [facebookexperimental/Robyn#972]
## Describe issue

I only have quarterly data available, and our awareness metrics can also only be collected on a quarterly basis. How should I handle this situation? In which file can I modify the code to smoothly handle quarterly data?

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: 3.10.6.9003
- R version (Please, check and share: R version 4.3.2 (2023-10-31 ucrt)

**Comment by gufengzhou** [comment]
I'm afraid Robyn doesn't support quarterly data. Monthly, weekly and daily are the time grains we support.
