### ISSUE TITLE
CRAN package version outdated (still at 3.10.3 instead of 3.10.5)

### ISSUE THREAD

**Issue by NumesSanguis** [facebookexperimental/Robyn#976]
## Describe issue
Installed Robyn through `install.packages("Robyn")` in a Conda environment in JupyterLab, but noticed `packageVersion("Robyn")` shows "3.10.3".

Checking the CRAN website, the package version indeed seems to be outdated compared to version released on GitHub: https://cran.rstudio.com/web/packages/Robyn/index.html

### 1 - Remotes package
```R
install.packages("remotes")
remotes::install_github("facebookexperimental/Robyn@v3.10.5")
```

However, this gives the error:
```R
> remotes::install_github("facebookexperimental/Robyn@v3.10.5")
Downloading GitHub repo facebookexperimental/Robyn@v3.10.5
Error: Failed to install 'Robyn' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
```

### 2 - ZIP file
1. I downloaded v3.10.5 from the Release page
2. After activating R in terminal, executed command: `install.packages("data/Robyn-3.10.5.zip", repos = NULL, type = "source")`

However, this gives the error:
```
> install.packages("data/Robyn-3.10.5.zip", repos = NULL, type = "source")
Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\xf0\001KW\0\0\0\0\0\0\0\0\0\0\0\0\r\0\t\0Robyn-3.10.5/UT\005\0\001\x95K&ePK\003\004\n\0\0\0\b\0\xf0\001KW\xf3\xf1\001\x8fZ\0\0\0b\0\0\0\032\0\t\0Robyn-3.10.5/.dock'
Warning message:
In install.packages("data/Robyn-3.10.5.zip", repos = NULL, type = "source") :
  installation of package ‘data/Robyn-3.10.5.zip’ had non-zero exit status
```

**Comment by gufengzhou** [comment]
You should do `remotes::install_github("facebookexperimental/Robyn/R@v3.10.5")`, you missed the /R

**Comment by laresbernardo** [comment]
Expect a CRAN version updated by the end of this week @NumesSanguis
