### ISSUE TITLE
No function named v2t 

### ISSUE THREAD

**Issue by ritviksaras** [facebookexperimental/Robyn#977]
when I tried to run the code of robyn_allocator present in one of the folder in this repository. Got the below issue
![image](https://github.com/facebookexperimental/Robyn/assets/158150931/cbcafb33-6024-44a3-9225-d13db027f6ba)
Tried searching the function in other folders , but did not get the function yet that function is used in defining other functions.
Please comment the code of the function v2t.

Thanks in advance

**Comment by gufengzhou** [comment]
the function v2t is in the package lares. strange that this is not installed when you installed Robyn. Can you just do install.packages("lares"), then it should be ok
