### ISSUE TITLE
Budget allocator for future dates

### ISSUE THREAD

**Issue by stdp95** [facebookexperimental/Robyn#979]
## Describe issue
I have used the Robyn package for marketing mix modeling and budget allocation based on historical data. However, I am facing challenges when attempting to extend this capability to predict and allocate budgets for future dates. The Robyn package primarily supports past dates, and I want to understand how to correctly implement future date allocations. Below are the details of the issue I am encountering:

### Current Setup:
Historical data includes variables like media spend, date, and other predictors.
Successfully ran the model and used the robyn_allocator method for historical data.

#### Extending Input Data:

To predict future media spend and allocate budgets, I generated future dates and filled them with estimated or average spend values. However, I am unsure if this approach is correct and if the model will handle these future dates appropriately.

## Need for Guidance:

Please guide me on correctly implementing budget allocation for future dates using Robyn. Specifically:
How to properly extend the input data to include future dates.
Best practices for capturing seasonality and trends in future predictions.
Correctly specifying the date_range parameter for future dates to avoid warnings.

**Comment by gufengzhou** [comment]
Unfortunatly robyn doesn't support forecast at the moment. For now, using historical performance to allocate budget is the next best thing you can do. And to be honest, the forecast would be also just "guessing" in the new period that is not so entirely different.
