### ISSUE TITLE
Clarify robyn_allocator date_range default doc

### ISSUE THREAD

**Issue by louisjanin** [facebookexperimental/Robyn#991]
## Describe issue
demo not up-to-date what default is for date_range in robyn_allocator
demo says last month but function's doc says "all"
I think it's all indeed.

Thanks for the clarification!

## Provide reproducible example
![image](https://github.com/facebookexperimental/Robyn/assets/16646642/039e7874-9293-4689-a5e3-ca16a0244653)

from RStudio, w/ the command
> ?robyn_allocator
![image](https://github.com/facebookexperimental/Robyn/assets/16646642/d95b47d9-7e49-4183-83de-3f2e03b2ff60)

## Environment & Robyn version
![image](https://github.com/facebookexperimental/Robyn/assets/16646642/aad7f95c-84b6-4385-a418-a7b4a3c41dfd)

**Comment by laresbernardo** [comment]
Fixed, thanks for reporting it
