### ISSUE TITLE
NumPy 2.0 Incompatibility Issue

### ISSUE THREAD

**Issue by stdp95** [facebookexperimental/Robyn#998]
## Issue
Robyn is currently not compatible with NumPy 2.0. I encountered this issue while trying to run Robyn, and I had to downgrade NumPy to an older version to get it working.

**Comment by anhdanggit** [comment]
Same problem to me. This is the new code I replaced in `install_nevergrad.R` to make it work!
```
conda_create(envname = "r-reticulate", packages = "python=3.9")
use_condaenv("r-reticulate")
conda_install("r-reticulate", "numpy==1.26.4", pip = TRUE)
conda_install("r-reticulate", "nevergrad", pip = TRUE)
```
To make it more sustainable in env conflicts, probably we could keep the version of python libraries in `requirements.txt`, and using `conda/pip` on CLI to install it into the `r-reticulate` conda env

**Comment by stdp95** [comment]
This approach would definitely help to mitigate conflicts in the future.

Additionally, I wanted to share that a fix has been deployed to the main branch of Reticulate. We can pull the latest changes from the main branch or wait until a new version is released. This should resolve the compatibility issue with NumPy 2.0.
